---@meta _
-- Generated by scripts\gameindex.py from the index of the game's classes. Changes here are lost on the next run.

---@class BP_Back_Condensed_Exotic_C : BP_Back_Item_Base_C
---@field StaticMesh StaticMeshComponent

---@class BP_Back_DroneCompanion_C : BP_Back_Item_Base_C
---@field StaticMesh StaticMeshComponent
---@field ReceiveBeginPlay fun(self: BP_Back_DroneCompanion_C)
---@field ReceiveEndPlay fun(self: BP_Back_DroneCompanion_C, EndPlayReason: EEndPlayReason)

---@class BP_Back_Item_Base_C : StaticItem

---@class BP_Back_Item_Water_Can_T3_C : BP_Back_Item_Base_C
---@field StaticMesh StaticMeshComponent

---@class BP_Back_Mission_Hoverframe_C : BP_Back_Item_Base_C
---@field StaticMesh StaticMeshComponent

---@class BP_Back_Mission_Navigation_C : BP_Back_Item_Base_C
---@field StaticMesh StaticMeshComponent

---@class BP_Back_Portable_StasisBag_C : BP_Back_Item_Base_C
---@field SkeletalMesh SkeletalMeshComponent

---@class BP_Back_Portable_Tank_Biofuel_C : BP_Back_Item_Base_C
---@field StaticMesh StaticMeshComponent

---@class BP_Back_Portable_Tank_Oil_C : BP_Back_Item_Base_C
---@field StaticMesh StaticMeshComponent

---@class BP_Back_Portable_Tank_Water_C : BP_Back_Item_Base_C
---@field StaticMesh StaticMeshComponent
---@field IcarusBeginPlay fun(self: BP_Back_Portable_Tank_Water_C)
---@field ReceiveTick fun(self: BP_Back_Portable_Tank_Water_C, DeltaSeconds: number)

---@class BP_Back_Seismic_Probe_C : BP_Back_Item_Base_C

---@class BP_Back_SlugLauncher_C : BP_Back_Item_Base_C
---@field Backpack StaticMeshComponent
---@field Core SkeletalMeshComponent
---@field Guard StaticMeshComponent
---@field GunVisible boolean
---@field Loader StaticMeshComponent
---@field Muzzle StaticMeshComponent
---@field SkeletalMesh SkeletalMeshComponent
---@field UpgradeSlots StaticMeshComponent[]
---@field FocusedItemUpdated fun(self: BP_Back_SlugLauncher_C)
---@field IcarusBeginPlay fun(self: BP_Back_SlugLauncher_C)
---@field OnRep_GunVisible fun(self: BP_Back_SlugLauncher_C)
---@field UpdateGunVisbility fun(self: BP_Back_SlugLauncher_C)

---@class BP_Back_Vesper_Cage_C : BP_Back_Item_Base_C
---@field StaticMesh StaticMeshComponent
