---@meta _
-- Generated by scripts\gameindex.py from the index of the game's classes. Changes here are lost on the next run.

---@class BP_Prop_Bear_Trap_C : BP_DeployableBase_C

---@class BP_Prop_Bear_Trap_Hanging_C : BP_DeployableBase_C

---@class BP_Prop_Boardgame_A_C : BP_DeployableContainerBase_C

---@class BP_Prop_Boardgame_B_C : BP_DeployableContainerBase_C

---@class BP_Prop_BookStack_A_C : BP_DeployableBase_C

---@class BP_Prop_BookStack_B_C : BP_DeployableBase_C

---@class BP_Prop_Book_A_C : BP_DeployableBase_C

---@class BP_Prop_Book_B_C : BP_DeployableBase_C

---@class BP_Prop_Book_C_C : BP_DeployableBase_C

---@class BP_Prop_Book_D_C : BP_DeployableBase_C

---@class BP_Prop_Book_E_C : BP_DeployableBase_C

---@class BP_Prop_Book_F_C : BP_DeployableBase_C

---@class BP_Prop_Book_G_C : BP_DeployableBase_C

---@class BP_Prop_Camera_C : BP_DeployableBase_C
---@field CameraMovement TimelineComponent
---@field CameraMovement_NewTrack_0_7D380A1541038BB3B61B2BB11EC92ED9 number
---@field CameraMovement__Direction_7D380A1541038BB3B61B2BB11EC92ED9 ETimelineDirection
---@field DeployableSM1 StaticMeshComponent
---@field CameraMovement__FinishedFunc fun(self: BP_Prop_Camera_C)
---@field CameraMovement__UpdateFunc fun(self: BP_Prop_Camera_C)
---@field IcarusBeginPlay fun(self: BP_Prop_Camera_C)

---@class BP_Prop_Cards_A_C : BP_DeployableContainerBase_C

---@class BP_Prop_Cards_B_C : BP_DeployableContainerBase_C

---@class BP_Prop_Centrifuge_C : BP_DeployableContainerBase_C
---@field Deployable_Interact fun(self: BP_Prop_Centrifuge_C, Interactor: Actor?)

---@class BP_Prop_Clipboard_A_C : BP_DeployableBase_C

---@class BP_Prop_Clipboard_B_C : BP_DeployableBase_C

---@class BP_Prop_Clipboard_C_C : BP_DeployableBase_C

---@class BP_Prop_Clipboard_D_C : BP_DeployableBase_C

---@class BP_Prop_Clipboard_E_C : BP_DeployableBase_C

---@class BP_Prop_Clipboard_F_C : BP_DeployableBase_C

---@class BP_Prop_Clipboard_G_C : BP_DeployableBase_C

---@class BP_Prop_Clipboard_H_C : BP_DeployableBase_C

---@class BP_Prop_Colony_Poster_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Colony_Poster_C)

---@class BP_Prop_Colony_Sign_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Colony_Sign_C)

---@class BP_Prop_Cone_C : BP_DeployableBase_C
---@field Scene SceneComponent

---@class BP_Prop_Corkboard_Large_A_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Corkboard_Large_A_C)

---@class BP_Prop_Corkboard_Large_B_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Corkboard_Large_B_C)

---@class BP_Prop_Corkboard_Large_C_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Corkboard_Large_C_C)

---@class BP_Prop_Corkboard_Large_D_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Corkboard_Large_D_C)

---@class BP_Prop_Corkboard_Large_E_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Corkboard_Large_E_C)

---@class BP_Prop_Corkboard_Large_F_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Corkboard_Large_F_C)

---@class BP_Prop_Corkboard_Large_G_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Corkboard_Large_G_C)

---@class BP_Prop_Corkboard_Large_H_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Corkboard_Large_H_C)

---@class BP_Prop_Corkboard_Small_A_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Corkboard_Small_A_C)

---@class BP_Prop_Crate_Plastic_A_C : BP_DeployableContainerBase_C

---@class BP_Prop_Crate_Plastic_B_C : BP_DeployableContainerBase_C

---@class BP_Prop_Crate_Plastic_C_C : BP_DeployableContainerBase_C

---@class BP_Prop_Crate_Plastic_D_C : BP_DeployableContainerBase_C

---@class BP_Prop_Crate_Plastic_E_C : BP_DeployableContainerBase_C

---@class BP_Prop_Cryogenic_Sample_Storage_C : BP_DeployableBase_C

---@class BP_Prop_Damaged_Generator_C : BP_DeployableBase_C

---@class BP_Prop_Dissected_Roach_C : BP_DeployableBase_C

---@class BP_Prop_Dropship_C : BP_DeployableBase_C

---@class BP_Prop_Enzyme_PropagationUnit_C : BP_DeployableBase_C

---@class BP_Prop_Enzyme_Vat_C : BP_DeployableBase_C
---@field FMODAudio FMODAudioComponent
---@field NS_AquariumBubblesLarge NiagaraComponent
---@field NS_AquariumBubblesLarge1 NiagaraComponent
---@field NS_AquariumBubblesLarge2 NiagaraComponent

---@class BP_Prop_Enzyme_Vat_Empty_C : BP_DeployableBase_C
---@field Scene SceneComponent

---@class BP_Prop_Filing_Cabinet_C : BP_DeployableBase_C

---@class BP_Prop_Flask_A_C : BP_DeployableBase_C

---@class BP_Prop_Flask_B_C : BP_DeployableBase_C

---@class BP_Prop_Flask_C_C : BP_DeployableBase_C

---@class BP_Prop_Flask_D_C : BP_DeployableBase_C

---@class BP_Prop_Flask_E_C : BP_DeployableBase_C

---@class BP_Prop_Flask_F_C : BP_DeployableBase_C

---@class BP_Prop_Glass_Display_CabinetWall_C : BP_DeployableBase_C
---@field StaticMesh StaticMeshComponent

---@class BP_Prop_Glass_Display_Cabinet_C : BP_DeployableBase_C
---@field StaticMesh StaticMeshComponent

---@class BP_Prop_GrainSack_A_Open_C : BP_DeployableContainerBase_C

---@class BP_Prop_GrainSack_B_Open_C : BP_DeployableContainerBase_C

---@class BP_Prop_GrainSack_Horizontal_C : BP_DeployableContainerBase_C

---@class BP_Prop_GrainSack_Vertical_C : BP_DeployableContainerBase_C

---@class BP_Prop_Industrial_Sign_Diamond_A_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Industrial_Sign_Diamond_A_C)

---@class BP_Prop_Industrial_Sign_Diamond_B_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Industrial_Sign_Diamond_B_C)

---@class BP_Prop_Industrial_Sign_Diamond_C_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Industrial_Sign_Diamond_C_C)

---@class BP_Prop_Industrial_Sign_Diamond_D_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Industrial_Sign_Diamond_D_C)

---@class BP_Prop_Industrial_Sign_Diamond_E_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Industrial_Sign_Diamond_E_C)

---@class BP_Prop_Industrial_Sign_Diamond_F_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Industrial_Sign_Diamond_F_C)

---@class BP_Prop_Industrial_Sign_Diamond_G_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Industrial_Sign_Diamond_G_C)

---@class BP_Prop_Industrial_Sign_Diamond_H_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Industrial_Sign_Diamond_H_C)

---@class BP_Prop_Industrial_Sign_Square_A_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Industrial_Sign_Square_A_C)

---@class BP_Prop_Industrial_Sign_Square_B_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Industrial_Sign_Square_B_C)

---@class BP_Prop_Industrial_Sign_Square_C_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Industrial_Sign_Square_C_C)

---@class BP_Prop_Industrial_Sign_Square_D_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Industrial_Sign_Square_D_C)

---@class BP_Prop_Industrial_Sign_Square_E_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Industrial_Sign_Square_E_C)

---@class BP_Prop_Industrial_Sign_Square_F_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Industrial_Sign_Square_F_C)

---@class BP_Prop_Industrial_Sign_Triangle_A_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Industrial_Sign_Triangle_A_C)

---@class BP_Prop_Industrial_Sign_Triangle_B_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Industrial_Sign_Triangle_B_C)

---@class BP_Prop_Industrial_Sign_Triangle_C_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Industrial_Sign_Triangle_C_C)

---@class BP_Prop_Industrial_Sign_Triangle_D_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Industrial_Sign_Triangle_D_C)

---@class BP_Prop_Industrial_Sign_Triangle_E_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Industrial_Sign_Triangle_E_C)

---@class BP_Prop_Industrial_Sign_Triangle_F_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Industrial_Sign_Triangle_F_C)

---@class BP_Prop_Keyboard_C : BP_DeployableBase_C
---@field Scene SceneComponent

---@class BP_Prop_LabTable_LRG_C : BP_DeployableBase_C
---@field Cube StaticMeshComponent
---@field ReceiveBeginPlay fun(self: BP_Prop_LabTable_LRG_C)

---@class BP_Prop_LabTable_SML_C : BP_DeployableBase_C

---@class BP_Prop_Lab_Poster_A_C : BP_DeployableBase_C
---@field Widget WidgetComponent
---@field ReceiveBeginPlay fun(self: BP_Prop_Lab_Poster_A_C)

---@class BP_Prop_Lab_Poster_B_C : BP_DeployableBase_C
---@field Widget WidgetComponent
---@field ReceiveBeginPlay fun(self: BP_Prop_Lab_Poster_B_C)

---@class BP_Prop_Lab_Poster_C_C : BP_DeployableBase_C
---@field Widget WidgetComponent
---@field ReceiveBeginPlay fun(self: BP_Prop_Lab_Poster_C_C)

---@class BP_Prop_Lab_Stand_B_C : BP_DeployableContainerBase_C

---@class BP_Prop_Lab_Stand_C : BP_DeployableContainerBase_C

---@class BP_Prop_Laboratory_Stirrer_C : BP_DeployableContainerBase_C
---@field Deployable_Interact fun(self: BP_Prop_Laboratory_Stirrer_C, Interactor: Actor?)

---@class BP_Prop_LandingPad_C : BP_DeployableContainerBase_C
---@field Plane StaticMeshComponent

---@class BP_Prop_Laptop_A_C : BP_DeployableBase_C
---@field FMODAudio FMODAudioComponent

---@class BP_Prop_Laptop_B_C : BP_DeployableBase_C

---@class BP_Prop_Laptop_C_C : BP_DeployableBase_C

---@class BP_Prop_Laptop_D_C : BP_DeployableBase_C

---@class BP_Prop_Laptop_E_C : BP_DeployableBase_C

---@class BP_Prop_Laptop_F_C : BP_DeployableBase_C

---@class BP_Prop_Laptop_G_C : BP_DeployableBase_C

---@class BP_Prop_Laptop_H_C : BP_DeployableBase_C

---@class BP_Prop_LaserControls_C : BP_DeployableContainerBase_C

---@class BP_Prop_Magazine_A_C : BP_DeployableBase_C

---@class BP_Prop_Magazine_B_C : BP_DeployableBase_C

---@class BP_Prop_Magazine_C_C : BP_DeployableBase_C

---@class BP_Prop_Magazine_D_C : BP_DeployableBase_C

---@class BP_Prop_Magazine_E_C : BP_DeployableBase_C

---@class BP_Prop_Magazine_Eden_A_C : BP_DeployableBase_C

---@class BP_Prop_Magazine_Eden_B_C : BP_DeployableBase_C

---@class BP_Prop_Magazine_Eden_C_C : BP_DeployableBase_C

---@class BP_Prop_Magazine_Eden_D_C : BP_DeployableBase_C

---@class BP_Prop_Magazine_Eden_E_C : BP_DeployableBase_C

---@class BP_Prop_Magazine_Eden_F_C : BP_DeployableBase_C

---@class BP_Prop_Magazine_Eden_G_C : BP_DeployableBase_C

---@class BP_Prop_Magazine_Eden_H_C : BP_DeployableBase_C

---@class BP_Prop_Magazine_F_C : BP_DeployableBase_C

---@class BP_Prop_Magazine_G_C : BP_DeployableBase_C

---@class BP_Prop_Magazine_H_C : BP_DeployableBase_C

---@class BP_Prop_Magazine_I_C : BP_DeployableBase_C

---@class BP_Prop_Magazine_J_C : BP_DeployableBase_C

---@class BP_Prop_Magazine_K_C : BP_DeployableBase_C

---@class BP_Prop_Magazine_L_C : BP_DeployableBase_C

---@class BP_Prop_Magazine_M_C : BP_DeployableBase_C

---@class BP_Prop_Medical_Trolly_A_C : BP_DeployableBase_C

---@class BP_Prop_Medical_Trolly_B_C : BP_DeployableBase_C

---@class BP_Prop_Medical_Trolly_C_C : BP_DeployableBase_C

---@class BP_Prop_Medical_Trolly_D_C : BP_DeployableBase_C

---@class BP_Prop_Microscope_B_C : BP_Prop_Microscope_C

---@class BP_Prop_Microscope_C : BP_DeployableContainerBase_C
---@field Deployable_Interact fun(self: BP_Prop_Microscope_C, Interactor: Actor?)

---@class BP_Prop_MilkCan_C : BP_DeployableBase_C

---@class BP_Prop_Mining_Cart_A_C : BP_DeployableBase_C

---@class BP_Prop_Mining_Cart_B_C : BP_DeployableBase_C

---@class BP_Prop_Mining_Cart_C_C : BP_DeployableBase_C

---@class BP_Prop_Mining_Equipment_A_C : BP_DeployableBase_C

---@class BP_Prop_Mining_Equipment_B_C : BP_DeployableBase_C

---@class BP_Prop_Mining_Equipment_C_C : BP_DeployableBase_C

---@class BP_Prop_Mining_Equipment_D_C : BP_DeployableBase_C

---@class BP_Prop_Mining_Equipment_E_C : BP_DeployableBase_C

---@class BP_Prop_Mining_Rail_A_C : BP_DeployableBase_C

---@class BP_Prop_Mining_Rail_B_C : BP_DeployableBase_C

---@class BP_Prop_Mining_Rail_C_C : BP_DeployableBase_C

---@class BP_Prop_Mining_Rail_D_C : BP_DeployableBase_C

---@class BP_Prop_Mining_Rail_E_C : BP_DeployableBase_C

---@class BP_Prop_Mining_Rail_F_C : BP_DeployableBase_C

---@class BP_Prop_MoistureAnalyzer_C : BP_DeployableContainerBase_C
---@field Deployable_Interact fun(self: BP_Prop_MoistureAnalyzer_C, Interactor: Actor?)

---@class BP_Prop_Monitor_C : BP_Painting_Base_C
---@field OnLoaded_D39979FE4B8D29917F0665AB8124AB69 fun(self: BP_Prop_Monitor_C, Loaded: Object?)
---@field TriggerPaintingUpdate fun(self: BP_Prop_Monitor_C)
---@field UpdatePaintingDisplay fun(self: BP_Prop_Monitor_C)

---@class BP_Prop_Monitor_Wall_C : BP_Prop_Monitor_C

---@class BP_Prop_MortarPestle_C : BP_MortarAndPestle_C

---@class BP_Prop_Mouse_C : BP_DeployableBase_C
---@field Scene SceneComponent

---@class BP_Prop_Mug_A_C : BP_DeployableBase_C

---@class BP_Prop_Mug_B_C : BP_DeployableBase_C

---@class BP_Prop_Mug_C_C : BP_DeployableBase_C

---@class BP_Prop_Mug_D_C : BP_DeployableBase_C

---@class BP_Prop_Mug_E_C : BP_DeployableBase_C

---@class BP_Prop_Mug_F_C : BP_DeployableBase_C

---@class BP_Prop_Mug_G_C : BP_DeployableBase_C

---@class BP_Prop_Mug_H_C : BP_DeployableBase_C

---@class BP_Prop_Mug_I_C : BP_DeployableBase_C

---@class BP_Prop_Mug_J_C : BP_DeployableBase_C

---@class BP_Prop_Mug_K_C : BP_DeployableBase_C

---@class BP_Prop_Mug_L_C : BP_DeployableBase_C

---@class BP_Prop_Mug_M_C : BP_DeployableBase_C

---@class BP_Prop_Mug_N_C : BP_DeployableBase_C

---@class BP_Prop_NPC_File_A_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_NPC_File_A_C)

---@class BP_Prop_NPC_File_B_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_NPC_File_B_C)

---@class BP_Prop_NPC_File_C_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_NPC_File_C_C)

---@class BP_Prop_Pamphlet_A_C : BP_DeployableBase_C

---@class BP_Prop_Pamphlet_B_C : BP_DeployableBase_C

---@class BP_Prop_Pamphlet_C_C : BP_DeployableBase_C

---@class BP_Prop_Photo_A_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Photo_A_C)

---@class BP_Prop_Photo_B_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Photo_B_C)

---@class BP_Prop_Photo_C_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Photo_C_C)

---@class BP_Prop_Photo_D_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Photo_D_C)

---@class BP_Prop_PlasticBarrel_C : BP_DeployableBase_C

---@class BP_Prop_Poster_A_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Poster_A_C)

---@class BP_Prop_Poster_B_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Poster_B_C)

---@class BP_Prop_Poster_C_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Poster_C_C)

---@class BP_Prop_Poster_Fish_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Poster_Fish_C)

---@class BP_Prop_Poster_Sandworm_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Poster_Sandworm_C)

---@class BP_Prop_Rad_Book_A_C : BP_DeployableBase_C

---@class BP_Prop_Rad_Book_B_C : BP_DeployableBase_C

---@class BP_Prop_Rad_Metal_Sign_A_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Rad_Metal_Sign_A_C)

---@class BP_Prop_Rad_Metal_Sign_B_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Rad_Metal_Sign_B_C)

---@class BP_Prop_Rad_Metal_Sign_C_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Rad_Metal_Sign_C_C)

---@class BP_Prop_Rad_Metal_Sign_D_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Rad_Metal_Sign_D_C)

---@class BP_Prop_Rad_Metal_Sign_E_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Rad_Metal_Sign_E_C)

---@class BP_Prop_Rad_Paper_Poster_A_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Rad_Paper_Poster_A_C)

---@class BP_Prop_Rad_Paper_Poster_B_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Rad_Paper_Poster_B_C)

---@class BP_Prop_Rad_Paper_Poster_C_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Rad_Paper_Poster_C_C)

---@class BP_Prop_Rad_Paper_Poster_D_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Rad_Paper_Poster_D_C)

---@class BP_Prop_Rad_Paper_Poster_E_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Rad_Paper_Poster_E_C)

---@class BP_Prop_Rad_Polaroid_A_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Rad_Polaroid_A_C)

---@class BP_Prop_Rad_Polaroid_B_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Rad_Polaroid_B_C)

---@class BP_Prop_Rad_Polaroid_C_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Rad_Polaroid_C_C)

---@class BP_Prop_Rad_Polaroid_D_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Rad_Polaroid_D_C)

---@class BP_Prop_Rad_Polaroid_E_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Rad_Polaroid_E_C)

---@class BP_Prop_Rad_Polaroid_F_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Rad_Polaroid_F_C)

---@class BP_Prop_Rad_Polaroid_G_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Rad_Polaroid_G_C)

---@class BP_Prop_Radio_C : BP_DeployableBase_C

---@class BP_Prop_Record_A_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Record_A_C)

---@class BP_Prop_Record_B_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Record_B_C)

---@class BP_Prop_Record_C_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Record_C_C)

---@class BP_Prop_Record_D_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Record_D_C)

---@class BP_Prop_Record_E_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Record_E_C)

---@class BP_Prop_Record_F_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Record_F_C)

---@class BP_Prop_Record_G_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Record_G_C)

---@class BP_Prop_Record_H_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Record_H_C)

---@class BP_Prop_Record_I_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Record_I_C)

---@class BP_Prop_Record_J_C : BP_DeployableBase_C
---@field ReceiveBeginPlay fun(self: BP_Prop_Record_J_C)

---@class BP_Prop_Record_Player_C : BP_DeployableBase_C

---@class BP_Prop_SaddleBag_A_C : BP_DeployableContainerBase_C

---@class BP_Prop_SaddleBag_B_C : BP_DeployableContainerBase_C

---@class BP_Prop_SaddlePouch_A_C : BP_DeployableContainerBase_C

---@class BP_Prop_Scales_B_C : BP_Prop_Scales_C

---@class BP_Prop_Scales_C : BP_DeployableContainerBase_C
---@field Deployable_Interact fun(self: BP_Prop_Scales_C, Interactor: Actor?)

---@class BP_Prop_Sled_C : BP_DeployableContainerBase_C

---@class BP_Prop_Sled_Hanging_C : BP_DeployableContainerBase_C

---@class BP_Prop_Specimen_C : BP_DeployableBase_C
---@field FMODAudio FMODAudioComponent
---@field MeshMapping table<integer, SceneComponent>
---@field NS_AquariumBubblesLarge NiagaraComponent
---@field NS_AquariumBubblesLarge1 NiagaraComponent
---@field Radiation_Growths StaticMeshComponent
---@field Scene SceneComponent
---@field Specimen_Dragonfly StaticMeshComponent
---@field Specimen_Striker StaticMeshComponent

---@class BP_Prop_Specimen_Dragonfly_C : BP_DeployableBase_C
---@field FMODAudio FMODAudioComponent
---@field MeshMapping table<integer, SceneComponent>
---@field NS_AquariumBubblesLarge NiagaraComponent
---@field NS_AquariumBubblesLarge1 NiagaraComponent
---@field Scene SceneComponent
---@field Specimen_Dragonfly StaticMeshComponent

---@class BP_Prop_Specimen_Growth_C : BP_DeployableBase_C
---@field FMODAudio FMODAudioComponent
---@field MeshMapping table<integer, SceneComponent>
---@field NS_AquariumBubblesLarge NiagaraComponent
---@field NS_AquariumBubblesLarge1 NiagaraComponent
---@field Radiation_Growths StaticMeshComponent
---@field Scene SceneComponent

---@class BP_Prop_Specimen_Large_C : BP_DeployableBase_C
---@field FMODAudio FMODAudioComponent
---@field NS_AquariumBubblesLarge NiagaraComponent
---@field NS_AquariumBubblesLarge1 NiagaraComponent
---@field NS_AquariumBubblesLarge2 NiagaraComponent
---@field Scene SceneComponent
---@field Specimen_Raptor StaticMeshComponent

---@class BP_Prop_Specimen_Large_Raptor_C : BP_DeployableBase_C
---@field FMODAudio FMODAudioComponent
---@field NS_AquariumBubblesLarge NiagaraComponent
---@field NS_AquariumBubblesLarge1 NiagaraComponent
---@field NS_AquariumBubblesLarge2 NiagaraComponent
---@field Scene SceneComponent
---@field Specimen_Raptor StaticMeshComponent

---@class BP_Prop_Specimen_Small_C : BP_DeployableBase_C
---@field FMODAudio FMODAudioComponent
---@field NS_AquariumBubblesLarge NiagaraComponent
---@field NS_AquariumBubblesLarge1 NiagaraComponent
---@field Scene SceneComponent

---@class BP_Prop_Specimen_Striker_C : BP_DeployableBase_C
---@field FMODAudio FMODAudioComponent
---@field MeshMapping table<integer, SceneComponent>
---@field NS_AquariumBubblesLarge NiagaraComponent
---@field NS_AquariumBubblesLarge1 NiagaraComponent
---@field Scene SceneComponent
---@field Specimen_Striker StaticMeshComponent

---@class BP_Prop_Stool_C : BP_ChairBase_C

---@class BP_Prop_Surgical_Set_C : BP_DeployableContainerBase_C
---@field IcarusBeginPlay fun(self: BP_Prop_Surgical_Set_C)

---@class BP_Prop_TestTube_Rack_C : BP_DeployableContainerBase_C

---@class BP_Prop_Whiteboard_Alien_C : BP_DeployableBase_C
---@field Scene SceneComponent

---@class BP_SurgicalMask_A_C : BP_DeployableBase_C

---@class BP_SurgicalMask_B_C : BP_DeployableBase_C

---@class BP_SurgicalMasks_Box_C : BP_DeployableBase_C

---@class BP_Surgical_Clamps_A_C : BP_DeployableBase_C

---@class BP_Surgical_Clamps_B_C : BP_DeployableBase_C

---@class BP_Surgical_Pincers_A_C : BP_DeployableBase_C

---@class BP_Surgical_Pincers_B_C : BP_DeployableBase_C

---@class BP_Surgical_Scalpel_A_C : BP_DeployableBase_C

---@class BP_Surgical_Tweezers_A_C : BP_DeployableBase_C

---@class BP_Surgical_Tweezers_B_C : BP_DeployableBase_C

---@class Prop_Chemicals_A_C : BP_DeployableBase_C
---@field Deployable_Interact fun(self: Prop_Chemicals_A_C, Interactor: Actor?)

---@class Prop_Chemicals_B_C : BP_DeployableBase_C
---@field Deployable_Interact fun(self: Prop_Chemicals_B_C, Interactor: Actor?)

---@class Prop_CleaningSupplies_A_C : BP_DeployableBase_C

---@class Prop_CleaningSupplies_B_C : BP_DeployableBase_C

---@class Prop_CleaningSupplies_C_C : BP_DeployableBase_C

---@class Prop_CleaningSupplies_D_C : BP_DeployableBase_C

---@class Prop_EyeWashStation_C : BP_DeployableBase_C

---@class Prop_Goggles_A_C : BP_DeployableBase_C

---@class Prop_Goggles_B_C : BP_DeployableBase_C

---@class Prop_Goggles_C_C : BP_DeployableBase_C

---@class Prop_Labcoats_C : BP_DeployableBase_C

---@class Prop_LargeFlask_A_C : BP_DeployableBase_C

---@class Prop_LargeFlask_B_C : BP_DeployableBase_C

---@class Prop_LargeFlask_C_C : BP_DeployableBase_C

---@class Prop_Molecules_A_C : BP_DeployableBase_C

---@class Prop_Molecules_B_C : BP_DeployableBase_C

---@class Prop_Molecules_C_C : BP_DeployableBase_C

---@class Prop_Paper_Towls_A_C : BP_DeployableBase_C

---@class Prop_Pipe2_A_C : BP_DeployableBase_C

---@class Prop_Pipe2_B_C : BP_DeployableBase_C

---@class Prop_Pipe2_C_C : BP_DeployableBase_C

---@class Prop_Pipe2_D_C : BP_DeployableBase_C

---@class Prop_Pipe2_E_C : BP_DeployableBase_C

---@class Prop_Pipe2_F_C : BP_DeployableBase_C

---@class Prop_Pipe_A_C : BP_DeployableBase_C

---@class Prop_Pipe_B_C : BP_DeployableBase_C

---@class Prop_Pipe_C_C : BP_DeployableBase_C

---@class Prop_Pipe_D_C : BP_DeployableBase_C

---@class Prop_Pipe_E_C : BP_DeployableBase_C

---@class Prop_Science_Tray_A_C : BP_DeployableBase_C

---@class Prop_Science_Tray_B_C : BP_DeployableBase_C

---@class Prop_Skeleton_C : BP_DeployableBase_C

---@class Prop_Soap_C : BP_DeployableBase_C
