---@meta _
-- Generated by scripts\gameindex.py from the index of the game's classes. Changes here are lost on the next run.

---@class BP_IcarusJumpLink_C : IcarusNavLink
---@field JumpFinished fun(self: BP_IcarusJumpLink_C)
---@field LaunchAgent fun(self: BP_IcarusJumpLink_C, Agent: Character?, Destination: Vector|{})
---@field ReceiveSmartLinkReached fun(self: BP_IcarusJumpLink_C, Agent: Actor?, Destination: Vector|{})
