---@meta _
-- Generated by scripts\gameindex.py from the index of the game's classes. Changes here are lost on the next run.

---@class BP_Exotic_Harvester_C : BP_Extractor_C

---@class BP_Exotic_Uranium_Collector_C : BP_Extractor_C
---@field BPQC_WeightedAnimalSwarm BPQC_WeightedAnimalSwarm_C
---@field CurrentSlotFilled integer
---@field Decal DecalComponent
---@field Mat_Liquid MaterialInstanceDynamic
---@field MaxPlayerActiveDistance number
---@field SM_DEP_Uranium_Collection_Device_Liquid StaticMeshComponent
---@field ActiveStateUpdated fun(self: BP_Exotic_Uranium_Collector_C)
---@field CanStartDrill fun(self: BP_Exotic_Uranium_Collector_C, CanStart: boolean)
---@field DistanceCheck fun(self: BP_Exotic_Uranium_Collector_C)
---@field IcarusBeginPlay fun(self: BP_Exotic_Uranium_Collector_C)
---@field OnInventoryModified fun(self: BP_Exotic_Uranium_Collector_C, Inventory: Inventory?, Location: integer)
---@field OnRep_CurrentSlotFilled fun(self: BP_Exotic_Uranium_Collector_C)
---@field PlayerDistanceCheck fun(self: BP_Exotic_Uranium_Collector_C, InRange: boolean)
---@field ReceiveBeginPlay fun(self: BP_Exotic_Uranium_Collector_C)
---@field UpdateSpawning fun(self: BP_Exotic_Uranium_Collector_C, Spawning: boolean)

---@class BP_Extractor_Biofuel_C : BP_Extractor_C

---@class BP_Extractor_C : BP_Drill_Base_C
---@field AIPerceptionStimuliSource AIPerceptionStimuliSourceComponent
---@field BP_IcarusSpotLight BP_IcarusSpotLight_C
---@field GenericAITarget GenericAITargetComponent
---@field NS_Extractor_baseFX NiagaraComponent
---@field NS_Extractor_engineFX NiagaraComponent
---@field NS_Extractor_ventFX NiagaraComponent
---@field NS_Extractor_ventFX1 NiagaraComponent
---@field ActiveStateUpdated fun(self: BP_Extractor_C)
---@field GetCriticalHitBones fun(self: BP_Extractor_C): CriticalHitLocation[]
---@field GetRelationshipData fun(self: BP_Extractor_C): AIRelationshipsRowHandle
---@field GetTargetAlertness fun(self: BP_Extractor_C): integer
---@field GetTargetLocation fun(self: BP_Extractor_C): Vector
---@field IsActorAlive fun(self: BP_Extractor_C): boolean
---@field IsCriticalHitDisabled fun(self: BP_Extractor_C): boolean
---@field IsHidden fun(self: BP_Extractor_C): boolean
---@field IsStealthBonusDamageDisabled fun(self: BP_Extractor_C): boolean
---@field ShouldOverrideTargetNeutrality fun(self: BP_Extractor_C, TargetActor: Actor?, OutRelationshipType: ERelationshipType): boolean

---@class BP_Extractor_Electric_C : BP_Extractor_C

---@class BP_Extractor_Meta_C : BP_Extractor_C
