---@meta _
-- Generated by scripts\gameindex.py from the index of the game's classes. Changes here are lost on the next run.

---@class UMG_DeployableRotationIndicator_C : UserWidget
---@field DrawSize number
---@field Grow WidgetAnimation
---@field Image_AngleSnap Image
---@field Image_Rotator Image
---@field Rotate WidgetAnimation
---@field Construct fun(self: UMG_DeployableRotationIndicator_C)
---@field Hide fun(self: UMG_DeployableRotationIndicator_C)
---@field Show fun(self: UMG_DeployableRotationIndicator_C, DesiredSize: number, ShowAngleSnap: boolean)

---@class UMG_ReviveInstruction_C : UserWidget
