---@meta _
-- Generated by scripts\gameindex.py from the index of the game's classes. Changes here are lost on the next run.

---@class BP_Alpha_Desert_Wolf_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Alpha_Desert_Wolf_Corpse_C)

---@class BP_Alpha_Snow_Wolf_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Alpha_Snow_Wolf_Corpse_C)

---@class BP_Alpha_Wolf_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Alpha_Wolf_Corpse_C)

---@class BP_Ape_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent

---@class BP_Ape_Juvenile_Corpse_C : BP_GOAP_Corpse_C

---@class BP_Arctic_Moa_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Arctic_Moa_Corpse_C)

---@class BP_Arctic_Moa_Mount_Corpse_C : BP_GOAP_Corpse_Mount_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Arctic_Moa_Mount_Corpse_C)

---@class BP_Axolotl_Corpse_C : BP_GOAP_Corpse_C

---@class BP_BabyDeer_Corpse_C : BP_GOAP_Corpse_C

---@class BP_BatDog_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_BatDog_Corpse_C)

---@class BP_BearCub_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_BearCub_Corpse_C)

---@class BP_Bear_Contaminated_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field Niagara NiagaraComponent
---@field OnSkinnedStateUpdated fun(self: BP_Bear_Contaminated_C)

---@class BP_Bear_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Bear_Corpse_C)

---@class BP_Beaver_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Beaver_Corpse_C)

---@class BP_BlueBack_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_BlueBack_Corpse_C)

---@class BP_BlueBack_Lava_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_BlueBack_Lava_Corpse_C)

---@class BP_BlueBack_Lava_Mount_Corpse_C : BP_GOAP_Corpse_Mount_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_BlueBack_Lava_Mount_Corpse_C)
---@field ReceiveBeginPlay fun(self: BP_BlueBack_Lava_Mount_Corpse_C)

---@class BP_BlueBack_Mount_Corpse_C : BP_GOAP_Corpse_Mount_C
---@field GFur GFurComponent

---@class BP_Boar_Juvenile_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Boar_Juvenile_Corpse_C)

---@class BP_Bounder_Desert_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Bounder_Desert_Corpse_C)

---@class BP_BroodlingWorldSpawn_Corpse_C : BP_GOAP_Corpse_C
---@field OnSkinnedStateUpdated fun(self: BP_BroodlingWorldSpawn_Corpse_C)

---@class BP_Buffalo_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Buffalo_Corpse_C)

---@class BP_Buffalo_Juvenile_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Buffalo_Juvenile_Corpse_C)

---@class BP_Buffalo_Mount_Corpse_C : BP_GOAP_Corpse_Mount_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Buffalo_Mount_Corpse_C)

---@class BP_Bull_Corpse_C : BP_GOAP_Corpse_Mount_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Bull_Corpse_C)

---@class BP_Calf_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Calf_Corpse_C)

---@class BP_Centipede_Corpse_C : BP_GOAP_Corpse_C
---@field OnSkinnedStateUpdated fun(self: BP_Centipede_Corpse_C)

---@class BP_Chamois_M_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Chamois_M_Corpse_C)

---@class BP_Chamois_Var_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field IsSkeletonUpdated fun(self: BP_Chamois_Var_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Chamois_Var_Corpse_C)

---@class BP_Chew_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Chew_Corpse_C)

---@class BP_Chew_Juvenile_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Chew_Juvenile_Corpse_C)
---@field UpdateSkeletalMeshCarryPhysics fun(self: BP_Chew_Juvenile_Corpse_C, SkeletalMeshComponent: SkeletalMeshComponent?)

---@class BP_Chick_Corpse_C : BP_GOAP_Corpse_C
---@field ChickenColourIndex integer
---@field GFur GFurComponent
---@field IsSkeletonUpdated fun(self: BP_Chick_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Chick_Corpse_C)

---@class BP_Chicken_Corpse_C : BP_GOAP_Corpse_C
---@field ChickenColourIndex integer
---@field IsSkeletonUpdated fun(self: BP_Chicken_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Chicken_Corpse_C)
---@field UpdateCosmeticMaterials fun(self: BP_Chicken_Corpse_C)

---@class BP_Conifer_Wolf_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Conifer_Wolf_Corpse_C)

---@class BP_Conifer_Wolf_Juvenile_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Conifer_Wolf_Juvenile_Corpse_C)

---@class BP_Conifer_Wolf_Tame_Corpse_C : BP_GOAP_Corpse_Mount_C
---@field GFur GFurComponent

---@class BP_Cougar_Alpha_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Cougar_Alpha_Corpse_C)

---@class BP_Cow_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Cow_Corpse_C)

---@class BP_Crab_Coastal_Corpse_C : BP_GOAP_Corpse_C
---@field IsSkeletonUpdated fun(self: BP_Crab_Coastal_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Crab_Coastal_Corpse_C)
---@field UpdateSkeletalMeshCarryPhysics fun(self: BP_Crab_Coastal_Corpse_C, SkeletalMeshComponent: SkeletalMeshComponent?)

---@class BP_Crab_Coastal_Parent_Corpse_C : BP_GOAP_Corpse_C
---@field IsSkeletonUpdated fun(self: BP_Crab_Coastal_Parent_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Crab_Coastal_Parent_Corpse_C)
---@field UpdateSkeletalMeshCarryPhysics fun(self: BP_Crab_Coastal_Parent_Corpse_C, SkeletalMeshComponent: SkeletalMeshComponent?)

---@class BP_Crawler_Corpse_C : BP_GOAP_Corpse_C
---@field OnSkinnedStateUpdated fun(self: BP_Crawler_Corpse_C)

---@class BP_Crocodile_Corpse_C : BP_GOAP_Corpse_C

---@class BP_DeerDesertLarge_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_DeerDesertLarge_Corpse_C)

---@class BP_DeerDesert_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_DeerDesert_Corpse_C)

---@class BP_DeerLarge_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_DeerLarge_Corpse_C)

---@class BP_Deer_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Deer_Corpse_C)

---@class BP_Deer_Var_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Deer_Var_Corpse_C)

---@class BP_Deployable_AITargetDummy_C : BP_DeployableBase_C
---@field GenericAITarget GenericAITargetComponent
---@field IsMoving boolean
---@field TargetLocation Vector_NetQuantize10
---@field ChooseNewMoveTarget fun(self: BP_Deployable_AITargetDummy_C)
---@field DeployableTick fun(self: BP_Deployable_AITargetDummy_C, DeltaSeconds: number)
---@field GetCriticalHitBones fun(self: BP_Deployable_AITargetDummy_C): CriticalHitLocation[]
---@field GetIsMoving fun(self: BP_Deployable_AITargetDummy_C, IsMoving: boolean)
---@field GetRelationshipData fun(self: BP_Deployable_AITargetDummy_C): AIRelationshipsRowHandle
---@field GetTargetAlertness fun(self: BP_Deployable_AITargetDummy_C): integer
---@field GetTargetLocation fun(self: BP_Deployable_AITargetDummy_C): Vector
---@field IcarusBeginPlay fun(self: BP_Deployable_AITargetDummy_C)
---@field IsActorAlive fun(self: BP_Deployable_AITargetDummy_C): boolean
---@field IsCriticalHitDisabled fun(self: BP_Deployable_AITargetDummy_C): boolean
---@field IsHidden fun(self: BP_Deployable_AITargetDummy_C): boolean
---@field IsStealthBonusDamageDisabled fun(self: BP_Deployable_AITargetDummy_C): boolean
---@field ShouldOverrideTargetNeutrality fun(self: BP_Deployable_AITargetDummy_C, TargetActor: Actor?, OutRelationshipType: ERelationshipType): boolean
---@field ToggleMovement fun(self: BP_Deployable_AITargetDummy_C)

---@class BP_Deployable_Ape_Attractor_C : BP_Deployable_SpawnBlocker_C
---@field Activatedfmodaudio FMODAudioComponent
---@field BP_UIProjectionLocation BP_UIProjectionLocation_C
---@field NS_SoundWave NiagaraComponent
---@field NS_SoundWave1 NiagaraComponent
---@field NS_SoundWave2 NiagaraComponent
---@field NS_SoundWave3 NiagaraComponent
---@field RadarMaterial MaterialInstanceDynamic
---@field CanSupportNewTetheredAI fun(self: BP_Deployable_Ape_Attractor_C, CanSupport: boolean)
---@field GeneratorStateUpdate fun(self: BP_Deployable_Ape_Attractor_C, Active: boolean)
---@field GetSpawnAttractorEffectiveRadius fun(self: BP_Deployable_Ape_Attractor_C): integer
---@field GetSpawnBlockerEffectiveRadius fun(self: BP_Deployable_Ape_Attractor_C): integer
---@field OnDeviceOnStateChanged fun(self: BP_Deployable_Ape_Attractor_C, bIsOn: boolean)
---@field ReceiveBeginPlay fun(self: BP_Deployable_Ape_Attractor_C)
---@field UpdateSpawnBlockerEffects fun(self: BP_Deployable_Ape_Attractor_C)

---@class BP_Deployable_SpawnBlocker_C : BP_DeployableBase_C
---@field BPQC_SearchArea BPQC_SearchArea_C
---@field DefaultRadiusOverride integer
---@field SpawnBlockerActive boolean
---@field SpawnBlockerRadius integer
---@field DeployableTick fun(self: BP_Deployable_SpawnBlocker_C, DeltaSeconds: number)
---@field GetSpawnAttractorEffectiveRadius fun(self: BP_Deployable_SpawnBlocker_C): integer
---@field GetSpawnBlockerEffectiveRadius fun(self: BP_Deployable_SpawnBlocker_C): integer
---@field GetWidgetClass fun(self: BP_Deployable_SpawnBlocker_C, Widget: Class?)
---@field IcarusBeginPlay fun(self: BP_Deployable_SpawnBlocker_C)
---@field OnRep_SpawnBlockerActive fun(self: BP_Deployable_SpawnBlocker_C)
---@field OnRep_SpawnBlockerRadius fun(self: BP_Deployable_SpawnBlocker_C)
---@field ReceiveBeginPlay fun(self: BP_Deployable_SpawnBlocker_C)
---@field UpdateRadius fun(self: BP_Deployable_SpawnBlocker_C, SpawnRadius: integer)
---@field UpdateSpawnBlockerEffects fun(self: BP_Deployable_SpawnBlocker_C)

---@class BP_Deployable_SpawnBlocker_Scarecrow_C : BP_Deployable_SpawnBlocker_C
---@field Camera CameraComponent
---@field AddFuelAudio fun(self: BP_Deployable_SpawnBlocker_Scarecrow_C)
---@field CheckBlockerActive fun(self: BP_Deployable_SpawnBlocker_Scarecrow_C)
---@field Deployable_Interact fun(self: BP_Deployable_SpawnBlocker_Scarecrow_C, Interactor: Actor?)
---@field GeneratorStateUpdate fun(self: BP_Deployable_SpawnBlocker_Scarecrow_C, Active: boolean)
---@field IcarusBeginPlay fun(self: BP_Deployable_SpawnBlocker_Scarecrow_C)
---@field ItemAdded fun(self: BP_Deployable_SpawnBlocker_Scarecrow_C, Inventory: Inventory?, Location: integer)
---@field OnDeviceOnStateChanged fun(self: BP_Deployable_SpawnBlocker_Scarecrow_C, bIsOn: boolean)
---@field OnFuelInventoryUpdated fun(self: BP_Deployable_SpawnBlocker_Scarecrow_C, Inventory: Inventory?, Location: integer)
---@field OutOfFuelCheck fun(self: BP_Deployable_SpawnBlocker_Scarecrow_C)

---@class BP_Deployable_SpawnBlocker_T2_C : BP_Deployable_SpawnBlocker_C
---@field BP_UIProjectionLocation BP_UIProjectionLocation_C
---@field Camera CameraComponent
---@field NS_Smelly NiagaraComponent
---@field CheckBlockerActive fun(self: BP_Deployable_SpawnBlocker_T2_C)
---@field Deployable_Interact fun(self: BP_Deployable_SpawnBlocker_T2_C, Interactor: Actor?)
---@field GeneratorStateUpdate fun(self: BP_Deployable_SpawnBlocker_T2_C, Active: boolean)
---@field IcarusBeginPlay fun(self: BP_Deployable_SpawnBlocker_T2_C)
---@field OnDeviceOnStateChanged fun(self: BP_Deployable_SpawnBlocker_T2_C, bIsOn: boolean)
---@field OnFuelInventoryUpdated fun(self: BP_Deployable_SpawnBlocker_T2_C, Inventory: Inventory?, Location: integer)
---@field OutOfFuelCheck fun(self: BP_Deployable_SpawnBlocker_T2_C)
---@field UpdateSpawnBlockerEffects fun(self: BP_Deployable_SpawnBlocker_T2_C)

---@class BP_Deployable_SpawnBlocker_T3_C : BP_Deployable_SpawnBlocker_C
---@field Camera CameraComponent
---@field NS_Spray NiagaraComponent
---@field NS_Spray1 NiagaraComponent
---@field NS_Spray2 NiagaraComponent
---@field NS_Spray3 NiagaraComponent
---@field PoweredAudioLoop FMODAudioComponent
---@field SM_DEP_SpawnBlocker_T3 StaticMeshComponent
---@field CheckBlockerActive fun(self: BP_Deployable_SpawnBlocker_T3_C)
---@field Deployable_Interact fun(self: BP_Deployable_SpawnBlocker_T3_C, Interactor: Actor?)
---@field GeneratorStateUpdate fun(self: BP_Deployable_SpawnBlocker_T3_C, Active: boolean)
---@field IcarusBeginPlay fun(self: BP_Deployable_SpawnBlocker_T3_C)
---@field OnDeviceOnStateChanged fun(self: BP_Deployable_SpawnBlocker_T3_C, bIsOn: boolean)
---@field OnFuelInventoryUpdated fun(self: BP_Deployable_SpawnBlocker_T3_C, Inventory: Inventory?, Location: integer)
---@field OutOfFuelCheck fun(self: BP_Deployable_SpawnBlocker_T3_C)
---@field UpdateSpawnBlockerEffects fun(self: BP_Deployable_SpawnBlocker_T3_C)

---@class BP_Deployable_SpawnBlocker_T4_C : BP_Deployable_SpawnBlocker_C
---@field BP_IcarusPointLight BP_IcarusPointLight_C
---@field NS_SoundWave NiagaraComponent
---@field CalculateIsDeviceRunning fun(self: BP_Deployable_SpawnBlocker_T4_C, IsRunning: boolean)
---@field OnDeviceOnStateChanged fun(self: BP_Deployable_SpawnBlocker_T4_C, bIsOn: boolean)
---@field ReceiveBeginPlay fun(self: BP_Deployable_SpawnBlocker_T4_C)
---@field UpdateSpawnBlockerEffects fun(self: BP_Deployable_SpawnBlocker_T4_C)

---@class BP_Desert_Striker_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field IsSkeletonUpdated fun(self: BP_Desert_Striker_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Desert_Striker_Corpse_C)

---@class BP_Dino_Large_Corpse_C : BP_GOAP_Corpse_C

---@class BP_DragonFly_Corpse_C : BP_GOAP_Corpse_C

---@class BP_Eagle_Corpse_C : BP_GOAP_Corpse_C
---@field ReceiveBeginPlay fun(self: BP_Eagle_Corpse_C)

---@class BP_Elegant_Horse_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field IsSkeletonUpdated fun(self: BP_Elegant_Horse_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Elegant_Horse_Corpse_C)
---@field UpdateCorpseMaterials fun(self: BP_Elegant_Horse_Corpse_C)
---@field UpdateCosmeticMaterials fun(self: BP_Elegant_Horse_Corpse_C)

---@class BP_Elephant_Corpse_C : BP_GOAP_Corpse_C

---@class BP_Flightless_Tank_Corpse_C : BP_GOAP_Corpse_C

---@class BP_Flying_Tank_Corpse_C : BP_GOAP_Corpse_C

---@class BP_GOAP_Corpse_C : IcarusGOAPCorpseBase
---@field AddDecayingCorpseModifier boolean
---@field AttachProjectilesTimer TimerHandle
---@field BackPositionOffset Vector
---@field BackRotationOffset Rotator
---@field BlackmarketRewards ItemRewardsRowHandle
---@field BonesMesh SkeletalMesh
---@field CarcassGfurMatOverride MaterialInstance
---@field CarcassMesh SkeletalMesh
---@field CorpseItem ItemsStaticRowHandle
---@field CosmeticSkinIndex integer
---@field CurrentlyBeingHarvested boolean
---@field EmptyCorpseWhenFinishedEating boolean
---@field ExoticParticleSystem NiagaraComponent
---@field FPCarryPhysicsAsset PhysicsAsset
---@field HackyFixForClients Vector
---@field HarvestBonesSound FMODEvent
---@field HasBeenSkinned boolean
---@field HittableRewards ItemData[]
---@field Inventory InventoryComponent
---@field IsBabyAnimal boolean
---@field IsSkeleton boolean
---@field LastInteractPlayer IcarusPlayerCharacter
---@field MaxCorpseSettleTime number
---@field MaxCount integer[]
---@field NetworkedPose PoseSnapshot
---@field Niagara_Flies NiagaraComponent
---@field OnBackSimulateBelowBone string
---@field PopulatedContents boolean
---@field Projectiles ItemData[]
---@field RagdollPose PoseSnapshot
---@field RewardCount integer[]
---@field SettleTickTimer TimerHandle
---@field SettleTimer TimerHandle
---@field SlotableTransformRelativeOffset Transform
---@field TPCarryAnim_CHA AnimSequence
---@field TPCarryPhysicsAsset PhysicsAsset
---@field AddSessionFlagItems fun(self: BP_GOAP_Corpse_C, Items: ItemData[]) Wax refuses this call from Lua.
---@field ApplyRottingModifier fun(self: BP_GOAP_Corpse_C)
---@field AttachActorToSelf fun(self: BP_GOAP_Corpse_C, AttachedActor: Actor?): boolean
---@field AttachedActorPickedUp fun(self: BP_GOAP_Corpse_C, Item: IcarusItem?)
---@field BeginDelayedSettle fun(self: BP_GOAP_Corpse_C)
---@field ["ConvertBones&LeatherToCarbonPaste"] fun(self: BP_GOAP_Corpse_C, Items: ItemData[], Output: ItemData[]) Wax refuses this call from Lua.
---@field EmptyCorpse fun(self: BP_GOAP_Corpse_C)
---@field ForceSettle fun(self: BP_GOAP_Corpse_C)
---@field GenerateItem fun(self: BP_GOAP_Corpse_C, Item: ItemTemplateRowHandle|{}, Amount: integer, OutputItem: ItemData|{}) Do not call from Lua: it needs 528 bytes and the call buffer holds 512.
---@field GetNextUID fun(self: BP_GOAP_Corpse_C): integer
---@field GetRagdollPose fun(self: BP_GOAP_Corpse_C): PoseSnapshot
---@field GetSpawnTransformOffset fun(self: BP_GOAP_Corpse_C, OutTransformOffset: Transform|{})
---@field GetWidgetClass fun(self: BP_GOAP_Corpse_C, Widget: Class?)
---@field HarvestBones fun(self: BP_GOAP_Corpse_C, PlayerController: IcarusPlayerController?, DamagePercent: number) Wax refuses this call from Lua.
---@field HideInstigator fun(self: BP_GOAP_Corpse_C)
---@field IcarusBeginPlay fun(self: BP_GOAP_Corpse_C)
---@field InitialiseAttachedActors fun(self: BP_GOAP_Corpse_C)
---@field IsSkeletonUpdated fun(self: BP_GOAP_Corpse_C)
---@field MULTI_PlayPickupFX fun(self: BP_GOAP_Corpse_C, PickingUpPlayer: IcarusPlayerCharacter?)
---@field OnCorpseFocused fun(self: BP_GOAP_Corpse_C, IsThirdPerson: boolean)
---@field OnDamaged fun(self: BP_GOAP_Corpse_C, ActorState: ActorState?, DamageTaken: integer, DamageEvent: DamageEvent|{}, Instigator: Controller?, DamageCauser: Actor?)
---@field OnInstigatorEndPlay fun(self: BP_GOAP_Corpse_C, Actor: Actor?, EndPlayReason: EEndPlayReason)
---@field OnItemRemovedVerbose fun(self: BP_GOAP_Corpse_C, Inventory: Inventory?, Location: integer, Item: ItemData|{})
---@field OnRep_CosmeticSkinIndex fun(self: BP_GOAP_Corpse_C)
---@field OnRep_HackyFixForClients fun(self: BP_GOAP_Corpse_C)
---@field OnRep_HasBeenSkinned fun(self: BP_GOAP_Corpse_C)
---@field OnRep_IsSkeleton fun(self: BP_GOAP_Corpse_C)
---@field OnRep_NetworkedPose fun(self: BP_GOAP_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_GOAP_Corpse_C)
---@field PickupCorpse fun(self: BP_GOAP_Corpse_C, TargetPlayer: BP_IcarusPlayerCharacterSurvival_C?) Wax refuses this call from Lua.
---@field PlayBonesFullyHarvestedSound fun(self: BP_GOAP_Corpse_C)
---@field PlayHarvestBonesEffects fun(self: BP_GOAP_Corpse_C)
---@field PlayPickedUpSound fun(self: BP_GOAP_Corpse_C, PickingUpPlayer: IcarusPlayerCharacter?) Wax refuses this call from Lua.
---@field ["Populate Contents"] fun(self: BP_GOAP_Corpse_C, Multiplier: number, Player: IcarusPlayerCharacter?, ForcePopulateCorpse: boolean)
---@field ReceiveBeginPlay fun(self: BP_GOAP_Corpse_C)
---@field ReceiveEndPlay fun(self: BP_GOAP_Corpse_C, EndPlayReason: EEndPlayReason)
---@field SettleTick fun(self: BP_GOAP_Corpse_C)
---@field SetupCorpseSettleTime fun(self: BP_GOAP_Corpse_C, NewMaxCorpseSettleTime: number)
---@field TryGenerateChilledAlteration fun(self: BP_GOAP_Corpse_C, StatContainer: IcarusStatContainer?, ReturnValue1: ItemData|{}, ItemData: ItemData|{}) Do not call from Lua: it needs 1000 bytes and the call buffer holds 512.
---@field TryInitExoticFX fun(self: BP_GOAP_Corpse_C)
---@field UpdateCosmeticMaterials fun(self: BP_GOAP_Corpse_C) Wax refuses this call from Lua.
---@field UpdateSkeletalMeshCarryPhysics fun(self: BP_GOAP_Corpse_C, SkeletalMeshComponent: SkeletalMeshComponent?)

---@class BP_GOAP_Corpse_Mount_C : BP_GOAP_Corpse_C
---@field IcarusMapIcon IcarusMapIconComponent
---@field MountName string
---@field IcarusBeginPlay fun(self: BP_GOAP_Corpse_Mount_C)
---@field Multi_Unstuck fun(self: BP_GOAP_Corpse_Mount_C, NewLocation: Vector|{})
---@field OnInventoryItemRemoved fun(self: BP_GOAP_Corpse_Mount_C, Inventory: Inventory?, Location: integer)
---@field OnItemRemovedVerbose fun(self: BP_GOAP_Corpse_Mount_C, Inventory: Inventory?, Location: integer, Item: ItemData|{})
---@field SetupMountCorpse fun(self: BP_GOAP_Corpse_Mount_C) Wax refuses this call from Lua.

---@class BP_GeothermalSpider_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field IsSkeletonUpdated fun(self: BP_GeothermalSpider_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_GeothermalSpider_Corpse_C)
---@field UpdateSkeletalMeshCarryPhysics fun(self: BP_GeothermalSpider_Corpse_C, SkeletalMeshComponent: SkeletalMeshComponent?)

---@class BP_Ghost_Crocodile_Corpse_C : BP_GOAP_Corpse_C

---@class BP_Giant_Beetle_Corpse_C : BP_GOAP_Corpse_C

---@class BP_Giant_Roach_Corpse_C : BP_GOAP_Corpse_C

---@class BP_Giant_Turtle_Corpse_C : BP_GOAP_Corpse_C

---@class BP_Ground_Dragon_Corpse_C : BP_GOAP_Corpse_C

---@class BP_Hammerhead_Slug_Corpse_C : BP_GOAP_Corpse_C
---@field OnSkinnedStateUpdated fun(self: BP_Hammerhead_Slug_Corpse_C)

---@class BP_HitchingPost_C : BP_DeployableBase_C
---@field Attach SceneComponent
---@field AttachPoint Vector
---@field BP_UIProjectionLocation BP_UIProjectionLocation_C
---@field DynamicCableComponentMap table<CableComponent, Character>
---@field ["Element Index"] integer
---@field LastTrappedCharacters Character[]
---@field TrapRange number
---@field TrappedCharacters Character[]
---@field CleanupTrappedCharacter fun(self: BP_HitchingPost_C, TrappedCharacter: Character?)
---@field GetBaitLocation fun(self: BP_HitchingPost_C): Vector
---@field GetCableComponentForCharacter fun(self: BP_HitchingPost_C, Character: Character?, Output: CableComponent?)
---@field GetCurrentlyTrappedCharacter fun(self: BP_HitchingPost_C): Character
---@field GetCurrentlyTrappedCharacters fun(self: BP_HitchingPost_C): Character[]
---@field GetTrapOrigin fun(self: BP_HitchingPost_C): Vector
---@field GetTrapRadius fun(self: BP_HitchingPost_C): number
---@field InitialiseTrappedCharacter fun(self: BP_HitchingPost_C, TrappedCharacter: Character?)
---@field NotifyDynamicCharacterSpawned fun(self: BP_HitchingPost_C)
---@field OnRep_TrappedCharacter fun(self: BP_HitchingPost_C)
---@field OnTrappedCharacterEndPlay fun(self: BP_HitchingPost_C, Actor: Actor?, EndPlayReason: EEndPlayReason)
---@field ReceiveBeginPlay fun(self: BP_HitchingPost_C)
---@field ReleaseCharacter fun(self: BP_HitchingPost_C, Character: Character?)
---@field RemoveTrappedCharacter fun(self: BP_HitchingPost_C, Character: Character?)
---@field SetCurrentlyTrappedCharacter fun(self: BP_HitchingPost_C, Character: Character?)
---@field TrapCharacter fun(self: BP_HitchingPost_C, TrappedCharacter: Character?)
---@field UpdateRopeVisibility fun(self: BP_HitchingPost_C)
---@field WantsDynamicSpawn fun(self: BP_HitchingPost_C): boolean

---@class BP_HitchingPost_Wall_C : BP_HitchingPost_C

---@class BP_Hopping_Creature_Corpse_C : BP_GOAP_Corpse_C
---@field IsSkeletonUpdated fun(self: BP_Hopping_Creature_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Hopping_Creature_Corpse_C)
---@field ["Populate Contents"] fun(self: BP_Hopping_Creature_Corpse_C, Multiplier: number, Player: IcarusPlayerCharacter?, ForcePopulateCorpse: boolean)
---@field UpdateCosmeticMaterials fun(self: BP_Hopping_Creature_Corpse_C)

---@class BP_Hopping_Creature_Swamp_Corpse_C : BP_GOAP_Corpse_C
---@field IsSkeletonUpdated fun(self: BP_Hopping_Creature_Swamp_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Hopping_Creature_Swamp_Corpse_C)
---@field ["Populate Contents"] fun(self: BP_Hopping_Creature_Swamp_Corpse_C, Multiplier: number, Player: IcarusPlayerCharacter?, ForcePopulateCorpse: boolean)
---@field UpdateCosmeticMaterials fun(self: BP_Hopping_Creature_Swamp_Corpse_C)

---@class BP_Horse_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field IsSkeletonUpdated fun(self: BP_Horse_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Horse_Corpse_C)
---@field UpdateCorpseMaterials fun(self: BP_Horse_Corpse_C)
---@field UpdateCosmeticMaterials fun(self: BP_Horse_Corpse_C)

---@class BP_Horse_Mount_Corpse_C : BP_GOAP_Corpse_Mount_C
---@field GFur GFurComponent
---@field IsSkeletonUpdated fun(self: BP_Horse_Mount_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Horse_Mount_Corpse_C)
---@field UpdateCorpseMaterials fun(self: BP_Horse_Mount_Corpse_C)
---@field UpdateCosmeticMaterials fun(self: BP_Horse_Mount_Corpse_C)

---@class BP_Ice_Mammoth_Corpse_C : BP_GOAP_Corpse_C
---@field IsSkeletonUpdated fun(self: BP_Ice_Mammoth_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Ice_Mammoth_Corpse_C)

---@class BP_Irradiated_Abomination_Corpse_C : BP_GOAP_Corpse_C
---@field IsSkeletonUpdated fun(self: BP_Irradiated_Abomination_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Irradiated_Abomination_Corpse_C)
---@field ["Populate Contents"] fun(self: BP_Irradiated_Abomination_Corpse_C, Multiplier: number, Player: IcarusPlayerCharacter?, ForcePopulateCorpse: boolean)
---@field UpdateCosmeticMaterials fun(self: BP_Irradiated_Abomination_Corpse_C)

---@class BP_Irradiated_Mutation_Corpse_C : BP_GOAP_Corpse_C
---@field BP_IcarusPointLight_Hi1 BP_IcarusPointLight_C
---@field BP_IcarusPointLight_Hi2 BP_IcarusPointLight_C
---@field BP_IcarusPointLight_Hi3 BP_IcarusPointLight_C
---@field BP_IcarusPointLight_Hi4 BP_IcarusPointLight_C
---@field BP_IcarusPointLight_Hi5 BP_IcarusPointLight_C
---@field BP_IcarusPointLight_Hi6 BP_IcarusPointLight_C
---@field BP_IcarusPointLight_Lo1 BP_IcarusPointLight_C
---@field FadeLight TimelineComponent
---@field FadeLight_Alpha_8AF483DB47937431B8A6A19F60CAD2B8 number
---@field FadeLight__Direction_8AF483DB47937431B8A6A19F60CAD2B8 ETimelineDirection
---@field MatID0 MaterialInstanceDynamic
---@field MatID1 MaterialInstanceDynamic
---@field FadeLight__FinishedFunc fun(self: BP_Irradiated_Mutation_Corpse_C)
---@field FadeLight__UpdateFunc fun(self: BP_Irradiated_Mutation_Corpse_C)
---@field ReceiveBeginPlay fun(self: BP_Irradiated_Mutation_Corpse_C)

---@class BP_Irradiated_Prospector_Corpse_C : BP_GOAP_Corpse_C
---@field BP_IcarusPointLight_Hi1 BP_IcarusPointLight_C
---@field BP_IcarusPointLight_Hi2 BP_IcarusPointLight_C
---@field BP_IcarusPointLight_Hi3 BP_IcarusPointLight_C
---@field BP_IcarusPointLight_Hi4 BP_IcarusPointLight_C
---@field BP_IcarusPointLight_Lo1 BP_IcarusPointLight_C
---@field FadeLight TimelineComponent
---@field FadeLight_Alpha_29193A864A0320384B896492622325AE number
---@field FadeLight__Direction_29193A864A0320384B896492622325AE ETimelineDirection
---@field MatID1 MaterialInstanceDynamic
---@field FadeLight__FinishedFunc fun(self: BP_Irradiated_Prospector_Corpse_C)
---@field FadeLight__UpdateFunc fun(self: BP_Irradiated_Prospector_Corpse_C)
---@field IsSkeletonUpdated fun(self: BP_Irradiated_Prospector_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Irradiated_Prospector_Corpse_C)
---@field ["Populate Contents"] fun(self: BP_Irradiated_Prospector_Corpse_C, Multiplier: number, Player: IcarusPlayerCharacter?, ForcePopulateCorpse: boolean)
---@field ReceiveBeginPlay fun(self: BP_Irradiated_Prospector_Corpse_C)
---@field UpdateCosmeticMaterials fun(self: BP_Irradiated_Prospector_Corpse_C)

---@class BP_Jaguar_Black_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Jaguar_Black_Corpse_C)

---@class BP_Jaguar_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Jaguar_Corpse_C)

---@class BP_Jungle_Hunter_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Jungle_Hunter_Corpse_C)

---@class BP_Juvenile_Wooly_Zebra_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Juvenile_Wooly_Zebra_Corpse_C)

---@class BP_Juvie_Horse_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field IsSkeletonUpdated fun(self: BP_Juvie_Horse_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Juvie_Horse_Corpse_C)
---@field UpdateSkeletalMeshCarryPhysics fun(self: BP_Juvie_Horse_Corpse_C, SkeletalMeshComponent: SkeletalMeshComponent?)

---@class BP_Kea_Corpse_C : BP_GOAP_Corpse_C
---@field ReceiveBeginPlay fun(self: BP_Kea_Corpse_C)

---@class BP_Kiwi_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Kiwi_Corpse_C)

---@class BP_Komodo_Corpse_C : BP_GOAP_Corpse_C

---@class BP_Komodo_Lava_Corpse_C : BP_GOAP_Corpse_C

---@class BP_LavaBomber_Corpse_C : BP_GOAP_Corpse_C
---@field IsSkeletonUpdated fun(self: BP_LavaBomber_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_LavaBomber_Corpse_C)
---@field UpdateSkeletalMeshCarryPhysics fun(self: BP_LavaBomber_Corpse_C, SkeletalMeshComponent: SkeletalMeshComponent?)

---@class BP_Lava_Slug_Corpse_C : BP_GOAP_Corpse_C
---@field OnSkinnedStateUpdated fun(self: BP_Lava_Slug_Corpse_C)

---@class BP_Lion_F_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Lion_F_Corpse_C)

---@class BP_MammothDesert_Corpse_C : BP_GOAP_Corpse_C
---@field BP_UIProjectionLocation BP_UIProjectionLocation_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_MammothDesert_Corpse_C)

---@class BP_Mammoth_Corpse_C : BP_GOAP_Corpse_C
---@field BP_UIProjectionLocation BP_UIProjectionLocation_C
---@field GFur GFurComponent
---@field GFurLong GFurComponent
---@field IsSkeletonUpdated fun(self: BP_Mammoth_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Mammoth_Corpse_C)

---@class BP_Mammoth_Corpse_Icy_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field GFurLong GFurComponent
---@field IceArmour1 SkeletalMeshComponent
---@field IceArmour2 SkeletalMeshComponent
---@field IceArmour3 SkeletalMeshComponent
---@field IceArmour4 SkeletalMeshComponent
---@field IceArmour5 SkeletalMeshComponent
---@field IsSkeletonUpdated fun(self: BP_Mammoth_Corpse_Icy_C)
---@field OnSkinnedStateUpdated fun(self: BP_Mammoth_Corpse_Icy_C)

---@class BP_Mammoth_Mount_Corpse_C : BP_GOAP_Corpse_Mount_C
---@field BP_UIProjectionLocation BP_UIProjectionLocation_C
---@field GFur GFurComponent
---@field GFurLong GFurComponent
---@field IsSkeletonUpdated fun(self: BP_Mammoth_Mount_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Mammoth_Mount_Corpse_C)

---@class BP_Mange_Wolf_Alpha_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Mange_Wolf_Alpha_Corpse_C)

---@class BP_Mange_Wolf_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Mange_Wolf_Corpse_C)

---@class BP_MiniHippo_Corpse_C : BP_GOAP_Corpse_C
---@field IsSkeletonUpdated fun(self: BP_MiniHippo_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_MiniHippo_Corpse_C)
---@field UpdateCosmeticMaterials fun(self: BP_MiniHippo_Corpse_C)

---@class BP_MissionSpawnBlocker_Cave_C : BP_MissionSpawnBlocker_C
---@field IcarusBeginPlay fun(self: BP_MissionSpawnBlocker_Cave_C)

---@class BP_Moa_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Moa_Corpse_C)

---@class BP_Moa_Juvenile_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Moa_Juvenile_Corpse_C)
---@field UpdateSkeletalMeshCarryPhysics fun(self: BP_Moa_Juvenile_Corpse_C, SkeletalMeshComponent: SkeletalMeshComponent?)

---@class BP_Moa_Mount_Corpse_C : BP_GOAP_Corpse_Mount_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Moa_Mount_Corpse_C)

---@class BP_Mount_Chew_Corpse_C : BP_GOAP_Corpse_Mount_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Mount_Chew_Corpse_C)

---@class BP_Mount_Horse_Standard_Corpse_C : BP_GOAP_Corpse_Mount_C
---@field IsSkeletonUpdated fun(self: BP_Mount_Horse_Standard_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Mount_Horse_Standard_Corpse_C)
---@field UpdateCosmeticMaterials fun(self: BP_Mount_Horse_Standard_Corpse_C)
---@field UpdateSkeletalMeshCarryPhysics fun(self: BP_Mount_Horse_Standard_Corpse_C, SkeletalMeshComponent: SkeletalMeshComponent?)

---@class BP_Mount_Zebra_Corpse_C : BP_GOAP_Corpse_Mount_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Mount_Zebra_Corpse_C)

---@class BP_Needler_Corpse_C : BP_GOAP_Corpse_C

---@class BP_Needler_Fire_Corpse_C : BP_GOAP_Corpse_C

---@class BP_Orka_Arctic_Corpse_C : BP_GOAP_Corpse_C

---@class BP_Orka_Juvenile_Corpse_C : BP_GOAP_Corpse_C
---@field ReceiveBeginPlay fun(self: BP_Orka_Juvenile_Corpse_C)

---@class BP_Orka_Mount_Corpse_C : BP_GOAP_Corpse_Mount_C

---@class BP_Pig_Corpse_C : BP_GOAP_Corpse_C
---@field OnSkinnedStateUpdated fun(self: BP_Pig_Corpse_C)

---@class BP_Piglet_Corpse_C : BP_GOAP_Corpse_C
---@field HasWool boolean

---@class BP_PlantBoss_Elite_Corpse_C : BP_GOAP_Corpse_C

---@class BP_PolarBearCub_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_PolarBearCub_Corpse_C)

---@class BP_PolarBear_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_PolarBear_Corpse_C)

---@class BP_PredatorBird_Corpse_C : BP_GOAP_Corpse_C
---@field ReceiveBeginPlay fun(self: BP_PredatorBird_Corpse_C)

---@class BP_Pronghorn_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Pronghorn_Corpse_C)

---@class BP_Rabbit_Arctic_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Rabbit_Arctic_Corpse_C)

---@class BP_Rabbit_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Rabbit_Corpse_C)

---@class BP_Rabbit_Variant_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Rabbit_Variant_Corpse_C)

---@class BP_Rabbit_Variant_Snow_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Rabbit_Variant_Snow_Corpse_C)

---@class BP_Raccoon_Corpse_C : BP_GOAP_Corpse_C

---@class BP_Rad_Broodling_Corpse_C : BP_GOAP_Corpse_C
---@field OnSkinnedStateUpdated fun(self: BP_Rad_Broodling_Corpse_C)

---@class BP_Ram_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field HasWool boolean
---@field IsSkeletonUpdated fun(self: BP_Ram_Corpse_C)
---@field OnRep_HasWool fun(self: BP_Ram_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Ram_Corpse_C)
---@field ReceiveBeginPlay fun(self: BP_Ram_Corpse_C)
---@field UpdateCorpseMaterials fun(self: BP_Ram_Corpse_C)

---@class BP_Raptor_Corpse_C : BP_GOAP_Corpse_C

---@class BP_Raptor_Desert_Corpse_C : BP_GOAP_Corpse_C

---@class BP_Raptor_Desert_Juvenile_Corpse_C : BP_GOAP_Corpse_C
---@field UpdateSkeletalMeshCarryPhysics fun(self: BP_Raptor_Desert_Juvenile_Corpse_C, SkeletalMeshComponent: SkeletalMeshComponent?)

---@class BP_Raptor_Desert_Mount_Corpse_C : BP_Raptor_Mount_Corpse_C

---@class BP_Raptor_Juvenile_Corpse_C : BP_GOAP_Corpse_C
---@field UpdateSkeletalMeshCarryPhysics fun(self: BP_Raptor_Juvenile_Corpse_C, SkeletalMeshComponent: SkeletalMeshComponent?)

---@class BP_Raptor_Mount_Corpse_C : BP_GOAP_Corpse_Mount_C

---@class BP_Reaver_Corpse_C : BP_GOAP_Corpse_C

---@class BP_Roat_Corpse_C : BP_GOAP_Corpse_C

---@class BP_Roat_Lava_Corpse_C : BP_GOAP_Corpse_C

---@class BP_Roat_Swamp_Corpse_C : BP_GOAP_Corpse_C

---@class BP_RockDog_Corpse_C : BP_GOAP_Corpse_C

---@class BP_RockGolem_Juvie_Corpse_Arctic_C : BP_RockGolem_Juvie_Corpse_C
---@field IsSkeletonUpdated fun(self: BP_RockGolem_Juvie_Corpse_Arctic_C)
---@field OnSkinnedStateUpdated fun(self: BP_RockGolem_Juvie_Corpse_Arctic_C)

---@class BP_RockGolem_Juvie_Corpse_C : BP_GOAP_Corpse_C
---@field IsSkeletonUpdated fun(self: BP_RockGolem_Juvie_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_RockGolem_Juvie_Corpse_C)
---@field ["Populate Contents"] fun(self: BP_RockGolem_Juvie_Corpse_C, Multiplier: number, Player: IcarusPlayerCharacter?, ForcePopulateCorpse: boolean)
---@field UpdateCosmeticMaterials fun(self: BP_RockGolem_Juvie_Corpse_C)

---@class BP_Rooster_Corpse_C : BP_GOAP_Corpse_C
---@field ChickenColourIndex integer
---@field IsSkeletonUpdated fun(self: BP_Rooster_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Rooster_Corpse_C)

---@class BP_SandScuttle_Corpse_C : BP_GOAP_Corpse_C
---@field UpdateSkeletalMeshCarryPhysics fun(self: BP_SandScuttle_Corpse_C, SkeletalMeshComponent: SkeletalMeshComponent?)

---@class BP_Sandwyrm_Queen_Corpse_C : BP_GOAP_Corpse_C

---@class BP_Scorpion_Arctic_Corpse_C : BP_GOAP_Corpse_C
---@field UpdateSkeletalMeshCarryPhysics fun(self: BP_Scorpion_Arctic_Corpse_C, SkeletalMeshComponent: SkeletalMeshComponent?)

---@class BP_Scorpion_Corpse_C : BP_GOAP_Corpse_C
---@field UpdateSkeletalMeshCarryPhysics fun(self: BP_Scorpion_Corpse_C, SkeletalMeshComponent: SkeletalMeshComponent?)

---@class BP_Sheep_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field HasWool boolean
---@field IsSkeletonUpdated fun(self: BP_Sheep_Corpse_C)
---@field OnRep_HasWool fun(self: BP_Sheep_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Sheep_Corpse_C)
---@field ReceiveBeginPlay fun(self: BP_Sheep_Corpse_C)
---@field UpdateCorpseMaterials fun(self: BP_Sheep_Corpse_C)

---@class BP_Slinker_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Slinker_Corpse_C)

---@class BP_Slinker_Jungle_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Slinker_Jungle_Corpse_C)

---@class BP_Slinker_Juvenile_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Slinker_Juvenile_Corpse_C)
---@field UpdateSkeletalMeshCarryPhysics fun(self: BP_Slinker_Juvenile_Corpse_C, SkeletalMeshComponent: SkeletalMeshComponent?)

---@class BP_Slinker_Mount_Corpse_C : BP_GOAP_Corpse_Mount_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Slinker_Mount_Corpse_C)

---@class BP_SnareTrap_C : BP_DeployableBase_C
---@field AnimTimeline_Reset TimelineComponent
---@field AnimTimeline_Reset_StickAngle_F9E6348249E647B8410AF695672B4BC0 number
---@field AnimTimeline_Reset__Direction_F9E6348249E647B8410AF695672B4BC0 ETimelineDirection
---@field AnimTimeline_Trap TimelineComponent
---@field AnimTimeline_Trap_StickAngle_6A7C2757411096865DFAB2A47CB8DE49 number
---@field AnimTimeline_Trap__Direction_6A7C2757411096865DFAB2A47CB8DE49 ETimelineDirection
---@field BP_UIProjectionLocation BP_UIProjectionLocation_C
---@field BaitLocation SceneComponent
---@field BaitedTameRows TamesRowHandle[]
---@field Cable CableComponent
---@field CableEndPoint SceneComponent
---@field DoesWantDynamicSpawn boolean
---@field DynamicSpawnTimer TimerHandle
---@field IsBaited boolean
---@field IsDynamicSpawnBlocked boolean
---@field LastTrappedCharacter Character
---@field SM_Bait StaticMeshComponent
---@field SM_Sticks StaticMeshComponent
---@field StatsToApplyWhileTrapped table<StatsEnum, integer>
---@field StickAnimOffset number
---@field TrapRange number
---@field TrappedCharacter Character
---@field TriggerCollider SphereComponent
---@field AnimTimeline_Reset__FinishedFunc fun(self: BP_SnareTrap_C)
---@field AnimTimeline_Reset__UpdateFunc fun(self: BP_SnareTrap_C)
---@field AnimTimeline_Trap__FinishedFunc fun(self: BP_SnareTrap_C)
---@field AnimTimeline_Trap__UpdateFunc fun(self: BP_SnareTrap_C)
---@field CleanupTrappedCharacter fun(self: BP_SnareTrap_C, TrappedCharacter: Character?)
---@field ClearDynamicSpawnCooldown fun(self: BP_SnareTrap_C)
---@field DelayedRevealSnareRope fun(self: BP_SnareTrap_C)
---@field GetBaitItem fun(self: BP_SnareTrap_C, BaitItem: ItemData|{})
---@field GetBaitLocation fun(self: BP_SnareTrap_C): Vector
---@field GetBestBoneToAttachTo fun(self: BP_SnareTrap_C, Character: Character?, BestBoneOrSocket: string)
---@field GetCurrentlyTrappedCharacter fun(self: BP_SnareTrap_C): Character
---@field GetCurrentlyTrappedCharacters fun(self: BP_SnareTrap_C): Character[]
---@field GetTrapOrigin fun(self: BP_SnareTrap_C): Vector
---@field GetTrapRadius fun(self: BP_SnareTrap_C): number
---@field InitialiseTrappedCharacter fun(self: BP_SnareTrap_C, TrappedCharacter: Character?)
---@field NotifyDynamicCharacterSpawned fun(self: BP_SnareTrap_C)
---@field OnInventoryItemChanged fun(self: BP_SnareTrap_C, Inventory: Inventory?, Location: integer)
---@field OnRep_IsBaited fun(self: BP_SnareTrap_C)
---@field OnRep_TrappedCharacter fun(self: BP_SnareTrap_C)
---@field ReceiveBeginPlay fun(self: BP_SnareTrap_C)
---@field RemoveTrappedCharacter fun(self: BP_SnareTrap_C, Character: Character?)
---@field RequestDynamicSpawn fun(self: BP_SnareTrap_C)
---@field SetCurrentlyBaited fun(self: BP_SnareTrap_C, CurrentlyBaited: boolean)
---@field SetCurrentlyTrappedCharacter fun(self: BP_SnareTrap_C, Character: Character?)
---@field StartStopAnimTimeline fun(self: BP_SnareTrap_C, Start: boolean)
---@field TrapCharacter fun(self: BP_SnareTrap_C, TrappedCharacter: Character?)
---@field WantsDynamicSpawn fun(self: BP_SnareTrap_C): boolean

---@class BP_SnowLeopard_Alpha_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnCorpseFocused fun(self: BP_SnowLeopard_Alpha_Corpse_C, IsThirdPerson: boolean)
---@field OnSkinnedStateUpdated fun(self: BP_SnowLeopard_Alpha_Corpse_C)

---@class BP_SnowLeopard_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnCorpseFocused fun(self: BP_SnowLeopard_Corpse_C, IsThirdPerson: boolean)
---@field OnSkinnedStateUpdated fun(self: BP_SnowLeopard_Corpse_C)

---@class BP_Snow_Striker_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Snow_Striker_Corpse_C)

---@class BP_Snow_Striker_Mount_Corpse_C : BP_GOAP_Corpse_Mount_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Snow_Striker_Mount_Corpse_C)

---@class BP_Snow_Wolf_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field IsSkeletonUpdated fun(self: BP_Snow_Wolf_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Snow_Wolf_Corpse_C)

---@class BP_Snow_Wolf_Juvenile_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Snow_Wolf_Juvenile_Corpse_C)

---@class BP_SpeederBike_Corpse_C : BP_GOAP_Corpse_Mount_C
---@field Niagara_BrokenFX NiagaraComponent
---@field StaticMesh StaticMeshComponent
---@field SetupMountCorpse fun(self: BP_SpeederBike_Corpse_C)

---@class BP_Spider_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent

---@class BP_Stomper_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Stomper_Corpse_C)

---@class BP_Stomper_Matriarch_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Stomper_Matriarch_Corpse_C)

---@class BP_Storca_Corpse_C : BP_GOAP_Corpse_C
---@field OnSkinnedStateUpdated fun(self: BP_Storca_Corpse_C)

---@class BP_Storca_Jungle_Corpse_C : BP_GOAP_Corpse_C
---@field OnSkinnedStateUpdated fun(self: BP_Storca_Jungle_Corpse_C)

---@class BP_SwampBird_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_SwampBird_Corpse_C)

---@class BP_SwampBird_Juvenile_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_SwampBird_Juvenile_Corpse_C)
---@field UpdateSkeletalMeshCarryPhysics fun(self: BP_SwampBird_Juvenile_Corpse_C, SkeletalMeshComponent: SkeletalMeshComponent?)

---@class BP_SwampBird_Mount_Corpse_C : BP_GOAP_Corpse_Mount_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_SwampBird_Mount_Corpse_C)

---@class BP_Swamp_Quadruped_Corpse_C : BP_GOAP_Corpse_C
---@field ReceiveBeginPlay fun(self: BP_Swamp_Quadruped_Corpse_C)

---@class BP_Swamp_Quadruped_Mount_Corpse_C : BP_GOAP_Corpse_Mount_C
---@field ReceiveBeginPlay fun(self: BP_Swamp_Quadruped_Mount_Corpse_C)

---@class BP_Swamp_Slug_Corpse_C : BP_GOAP_Corpse_C
---@field ReceiveBeginPlay fun(self: BP_Swamp_Slug_Corpse_C)

---@class BP_Swamp_Slug_Corpse_Enzyme_C : BP_GOAP_Corpse_C
---@field ReceiveBeginPlay fun(self: BP_Swamp_Slug_Corpse_Enzyme_C)

---@class BP_Tame_Cat_A_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field IsSkeletonUpdated fun(self: BP_Tame_Cat_A_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Tame_Cat_A_Corpse_C)
---@field UpdateCosmeticMaterials fun(self: BP_Tame_Cat_A_Corpse_C)

---@class BP_Tame_Cat_B_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field IsSkeletonUpdated fun(self: BP_Tame_Cat_B_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Tame_Cat_B_Corpse_C)
---@field UpdateCosmeticMaterials fun(self: BP_Tame_Cat_B_Corpse_C)

---@class BP_Tame_Cat_C_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field IsSkeletonUpdated fun(self: BP_Tame_Cat_C_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Tame_Cat_C_Corpse_C)
---@field UpdateCosmeticMaterials fun(self: BP_Tame_Cat_C_Corpse_C)

---@class BP_Tame_Dog_A_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field SkinVariationStat StatsEnum
---@field OnSkinnedStateUpdated fun(self: BP_Tame_Dog_A_Corpse_C)
---@field UpdateCosmeticMaterials fun(self: BP_Tame_Dog_A_Corpse_C)

---@class BP_Tame_Dog_B_Corpse_C : BP_Tame_Dog_A_Corpse_C
---@field OnSkinnedStateUpdated fun(self: BP_Tame_Dog_B_Corpse_C)
---@field UpdateCosmeticMaterials fun(self: BP_Tame_Dog_B_Corpse_C)

---@class BP_Tame_Dog_C2_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Tame_Dog_C2_Corpse_C)

---@class BP_Tame_Dog_C_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Tame_Dog_C_Corpse_C)

---@class BP_Tame_Dog_D_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field IsSkeletonUpdated fun(self: BP_Tame_Dog_D_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Tame_Dog_D_Corpse_C)
---@field UpdateCosmeticMaterials fun(self: BP_Tame_Dog_D_Corpse_C)
---@field UpdateSkeletalMeshCarryPhysics fun(self: BP_Tame_Dog_D_Corpse_C, SkeletalMeshComponent: SkeletalMeshComponent?)

---@class BP_Tame_Dog_E_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field IsSkeletonUpdated fun(self: BP_Tame_Dog_E_Corpse_C)
---@field OnSkinnedStateUpdated fun(self: BP_Tame_Dog_E_Corpse_C)
---@field UpdateCosmeticMaterials fun(self: BP_Tame_Dog_E_Corpse_C)
---@field UpdateSkeletalMeshCarryPhysics fun(self: BP_Tame_Dog_E_Corpse_C, SkeletalMeshComponent: SkeletalMeshComponent?)

---@class BP_Tropical_Bird_Corpse_C : BP_GOAP_Corpse_C
---@field ReceiveBeginPlay fun(self: BP_Tropical_Bird_Corpse_C)

---@class BP_TundraDeer_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field GFur_Long GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_TundraDeer_Corpse_C)

---@class BP_Tundra_Monkey_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Tundra_Monkey_Corpse_C)

---@class BP_Tundra_Monkey_Juvenile_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Tundra_Monkey_Juvenile_Corpse_C)

---@class BP_Turtle_Duck_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Turtle_Duck_Corpse_C)

---@class BP_Turtle_Fish_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Turtle_Fish_Corpse_C)

---@class BP_Tusker_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Tusker_Corpse_C)

---@class BP_Tusker_Juvenile_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Tusker_Juvenile_Corpse_C)

---@class BP_Tusker_Mount_Corpse_C : BP_GOAP_Corpse_Mount_C
---@field GFur GFurComponent

---@class BP_WildBoar_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_WildBoar_Corpse_C)

---@class BP_WildBoar_Mount_Corpse_C : BP_GOAP_Corpse_Mount_C
---@field GFur GFurComponent

---@class BP_WolfDesert_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_WolfDesert_Corpse_C)

---@class BP_WoollyMammoth_Juvenile_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_WoollyMammoth_Juvenile_Corpse_C)

---@class BP_Wooly_Zebra_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Wooly_Zebra_Corpse_C)

---@class BP_Wooly_Zebra_Mount_Corpse_C : BP_GOAP_Corpse_Mount_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Wooly_Zebra_Mount_Corpse_C)

---@class BP_Yeti_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Yeti_Corpse_C)

---@class BP_Zebra_Corpse_C : BP_GOAP_Corpse_C
---@field GFur GFurComponent
---@field OnSkinnedStateUpdated fun(self: BP_Zebra_Corpse_C)
