---@meta _
-- Generated by scripts\gameindex.py from the index of the game's classes. Changes here are lost on the next run.

---@class BP_IcarusNPCController_Soldier_C : IcarusNPCController
---@field OnProcessedNoise fun(self: BP_IcarusNPCController_Soldier_C, PerceivedActor: Actor?, EventStimulus: AIStimulus|{}): boolean
---@field ReceivePossess fun(self: BP_IcarusNPCController_Soldier_C, PossessedPawn: Pawn?)

---@class BP_NPC_Soldier_C : BP_IcarusNPCGOAPCharacter_C
---@field Armour_Arms SkeletalMeshComponent
---@field Armour_Chest SkeletalMeshComponent
---@field Armour_Feet SkeletalMeshComponent
---@field Armour_Head SkeletalMeshComponent
---@field Armour_Legs SkeletalMeshComponent
---@field BP_IcarusSpotLight BP_IcarusSpotLight_C
---@field BP_UIProjectionLocation BP_UIProjectionLocation_C
---@field DeathMontageSection string
---@field FollowTargetActorKey_0 string
---@field HasGeneratedRewards boolean
---@field Interactable InteractableComponent
---@field Inventory InventoryComponent
---@field IsADS boolean
---@field IsADSKey string
---@field LastKnownTargetLocation Vector_NetQuantize
---@field LastKnownTargetLocationKey string
---@field NS_DroneFlare NiagaraComponent
---@field SK_ITM_Flashlight_SML SkeletalMeshComponent
---@field SkeletalMesh_Item SkeletalMeshComponent
---@field GetAlertWidgetLocation fun(self: BP_NPC_Soldier_C, Location: Vector|{})
---@field GetCurrentAnimationTarget fun(self: BP_NPC_Soldier_C): Actor
---@field GetOverrideMoveSpeedMappingMultiplier fun(self: BP_NPC_Soldier_C, OutMultiplier: number): boolean
---@field GetStealthAwarenessLevel fun(self: BP_NPC_Soldier_C): EStealthAttackType
---@field IcarusBeginPlay fun(self: BP_NPC_Soldier_C)
---@field Interact fun(self: BP_NPC_Soldier_C, InstigatingActor: Actor?)
---@field Multicast_ActorDeath fun(self: BP_NPC_Soldier_C)
---@field OnHighlightChanged fun(self: BP_NPC_Soldier_C, Highlightable: HighlightableComponent?, Component: PrimitiveComponent?, bHighlighted: boolean)
---@field ReceiveBeginPlay fun(self: BP_NPC_Soldier_C)
---@field ReceiveTick fun(self: BP_NPC_Soldier_C, DeltaSeconds: number)
---@field ReplicateBlackboardVariables fun(self: BP_NPC_Soldier_C)
---@field UserConstructionScript fun(self: BP_NPC_Soldier_C)

---@class BTD_CheckRemainingMoveDistance_C : BTDecorator_BlueprintBase
---@field DistanceThreshold number
---@field PerformConditionCheckAI fun(self: BTD_CheckRemainingMoveDistance_C, OwnerController: AIController?, ControlledPawn: Pawn?): boolean

---@class BTD_CheckSoldierCombatMode_C : BTDecorator_BlueprintBase
---@field CombatModeKey BlackboardKeySelector
---@field DesiredCombatMode SoldierCombatMode
---@field PerformConditionCheck fun(self: BTD_CheckSoldierCombatMode_C, OwnerActor: Actor?): boolean

---@class BTD_IsCrouched_C : BTDecorator_BlueprintBase
---@field PerformConditionCheckAI fun(self: BTD_IsCrouched_C, OwnerController: AIController?, ControlledPawn: Pawn?): boolean

---@class BTS_CopyActorToLocationKey_C : BTService_BlueprintBase
---@field SourceActorKey BlackboardKeySelector
---@field TargetLocationKey BlackboardKeySelector
---@field ReceiveTickAI fun(self: BTS_CopyActorToLocationKey_C, OwnerController: AIController?, ControlledPawn: Pawn?, DeltaSeconds: number)

---@class BTS_Sprint_C : BTService_BlueprintBase
---@field WantsSprint boolean
---@field ReceiveActivationAI fun(self: BTS_Sprint_C, OwnerController: AIController?, ControlledPawn: Pawn?)
---@field ReceiveDeactivationAI fun(self: BTS_Sprint_C, OwnerController: AIController?, ControlledPawn: Pawn?)

---@class BTS_UpdateAudioState_C : BTService_BlueprintBase
---@field DesiredEntryState EAIAudioState
---@field DesiredExitState EAIAudioState
---@field SetStateOnExit boolean
---@field ReceiveActivationAI fun(self: BTS_UpdateAudioState_C, OwnerController: AIController?, ControlledPawn: Pawn?)
---@field ReceiveDeactivationAI fun(self: BTS_UpdateAudioState_C, OwnerController: AIController?, ControlledPawn: Pawn?)

---@class BTS_UpdateCrouch_C : BTService_BlueprintBase
---@field CrouchChance number
---@field ToggleCrouchOnSuccessfullRoll boolean
---@field ReceiveDeactivationAI fun(self: BTS_UpdateCrouch_C, OwnerController: AIController?, ControlledPawn: Pawn?)
---@field ReceiveTickAI fun(self: BTS_UpdateCrouch_C, OwnerController: AIController?, ControlledPawn: Pawn?, DeltaSeconds: number)

---@class BTT_SetCombatMode_C : BTTask_BlueprintBase
---@field CombatModeKey BlackboardKeySelector
---@field DesiredCombatMode SoldierCombatMode
---@field ReceiveExecute fun(self: BTT_SetCombatMode_C, OwnerActor: Actor?)

---@alias SoldierCombatMode
---| 0 # NewEnumerator0
---| 1 # NewEnumerator1
---| integer

---@alias SoldierMovementState
---| 0 # NewEnumerator8
---| 1 # NewEnumerator4
---| 2 # NewEnumerator5
---| 3 # NewEnumerator6
---| 4 # NewEnumerator7
---| integer
