---@meta _
-- Generated by scripts\gameindex.py from the game's object dump. Changes here are lost on the next run.

---@class UMG_StealthHitIndicator_C : UserWidget
---@field Pulse WidgetAnimation
---@field StealthDamageText TextBlock
---@field StealthType EStealthAttackType
---@field Construct fun(self: UMG_StealthHitIndicator_C)
---@field OnAnimComplete fun(self: UMG_StealthHitIndicator_C)
