---@meta _
-- Generated by scripts\gameindex.py from the index of the game's classes. Changes here are lost on the next run.

---@class BP_StaticItem_CondensedExotic_C : StaticItem
---@field IcarusMapIcon IcarusMapIconComponent

---@class BP_StaticItem_Egg_C : StaticItem
---@field ReceiveBeginPlay fun(self: BP_StaticItem_Egg_C)

---@class BP_StaticItem_HitchingRope_C : StaticItem
---@field CableComponent CableComponent
---@field InitialMovementState EMountMovementBehaviourState
---@field LinkedCharacter Character
---@field LinkedHitchingPost Actor
---@field AddCableComponent fun(self: BP_StaticItem_HitchingRope_C)
---@field GetLinkedCharacter fun(self: BP_StaticItem_HitchingRope_C, LinkedCharacter: Character?)
---@field GetLinkedHitchingPost fun(self: BP_StaticItem_HitchingRope_C, LinkedHitchingPost: Actor?)
---@field OnRep_LinkedCharacter fun(self: BP_StaticItem_HitchingRope_C)
---@field OnRep_LinkedHitchingPost fun(self: BP_StaticItem_HitchingRope_C)
---@field ReceiveEndPlay fun(self: BP_StaticItem_HitchingRope_C, EndPlayReason: EEndPlayReason)
---@field ReceiveTick fun(self: BP_StaticItem_HitchingRope_C, DeltaSeconds: number)
---@field ResetRope fun(self: BP_StaticItem_HitchingRope_C)
---@field SetLinkedCharacter fun(self: BP_StaticItem_HitchingRope_C, LinkedCharacter: Character?)
---@field SetLinkedHitchingPost fun(self: BP_StaticItem_HitchingRope_C, LinkedHitchingPost: Actor?)

---@class BP_StaticItem_RawUranium_C : StaticItem
---@field ReceiveBeginPlay fun(self: BP_StaticItem_RawUranium_C)
---@field ReceiveEndPlay fun(self: BP_StaticItem_RawUranium_C, EndPlayReason: EEndPlayReason)
