---@meta _
-- Generated by scripts\gameindex.py from the game's object dump. Changes here are lost on the next run.

---@class ActorArrayStruct
---@field ActorArray_3_5CDA33E84FAB094882AB2880391F8A0A Actor[]

---@class BP_AccountFlagFunctionLibrary_C : BlueprintFunctionLibrary
---@field AccountFlagAppend fun(self: BP_AccountFlagFunctionLibrary_C, Base: string, New: string, __WorldContext: Object?, Text: string)
---@field AccountFlagGetAllRewards fun(self: BP_AccountFlagFunctionLibrary_C, RowHandle: AccountFlagsRowHandle|{}, __WorldContext: Object?, BuiltText: string)
---@field AccountFlag_GetRequiredMissionText fun(self: BP_AccountFlagFunctionLibrary_C, RowHandle: AccountFlagsRowHandle|{}, __WorldContext: Object?, Text: string) Do not call from Lua: it needs 2432 bytes and the call buffer holds 512.
---@field AccountFlag_GetTalentModifierText fun(self: BP_AccountFlagFunctionLibrary_C, RowHandle: AccountFlagsRowHandle|{}, __WorldContext: Object?, Text: string)
---@field AccountFlag_GetUnlockedBlueprintsText fun(self: BP_AccountFlagFunctionLibrary_C, RowHandle: AccountFlagsRowHandle|{}, __WorldContext: Object?, Text: string) Do not call from Lua: it needs 1112 bytes and the call buffer holds 512.
---@field AccountFlag_GetWorkshopUnlockText fun(self: BP_AccountFlagFunctionLibrary_C, RowHandle: AccountFlagsRowHandle|{}, __WorldContext: Object?, Text: string) Do not call from Lua: it needs 1216 bytes and the call buffer holds 512.

---@class BP_AudioFunctionLibrary_C : BlueprintFunctionLibrary
---@field GetDamageTypeFMODParam fun(self: BP_AudioFunctionLibrary_C, DamageType: EIcarusDamageType, __WorldContext: Object?, FMODParamValue: EDamageTypeFMODParam)
---@field GetPlayerTypeFMODParam fun(self: BP_AudioFunctionLibrary_C, Player: IcarusPlayerCharacter?, __WorldContext: Object?, PlayerTypeFMODParam: EPlayerTypeFMODParam)
---@field GetSurfaceFMODParam fun(self: BP_AudioFunctionLibrary_C, Surface: EPhysicalSurface, __WorldContext: Object?, SurfaceFMODParam: ESurfaceFMODParam)
---@field IsPlayerInAudioPerspective fun(self: BP_AudioFunctionLibrary_C, Player: IcarusPlayerCharacter?, Perspective: EAudioPlayerPerspective, __WorldContext: Object?, Result: boolean)
---@field SetFMODAudioComponentEvent fun(self: BP_AudioFunctionLibrary_C, AudioComponent: FMODAudioComponent?, Event: FMODEvent?, SetPlayStatePlaying: boolean, __WorldContext: Object?)
---@field SetPlayerTypeParameter fun(self: BP_AudioFunctionLibrary_C, EventInstance: FMODEventInstance|{}, Player: IcarusPlayerCharacter?, __WorldContext: Object?)
---@field SetPlayerTypeParameterAttached fun(self: BP_AudioFunctionLibrary_C, AudioComponent: FMODAudioComponent?, Player: IcarusPlayerCharacter?, __WorldContext: Object?)
---@field ShouldHitAudioBeSuppressedByCritZone fun(self: BP_AudioFunctionLibrary_C, Hit: HitResult|{}, DamageTypes: EIcarusDamageType[], __WorldContext: Object?, Result: boolean) Do not call from Lua: it needs 586 bytes and the call buffer holds 512.

---@class BP_BallisticFunctionLibrary_C : BlueprintFunctionLibrary
---@field CreateCriticalHitResult fun(self: BP_BallisticFunctionLibrary_C, InPredictedHit: HitResult|{}, CriticalHitBone: string, __WorldContext: Object?, OutCriticalHit: HitResult|{}) Do not call from Lua: it needs 720 bytes and the call buffer holds 512.
---@field GetBallisticPoolManager fun(self: BP_BallisticFunctionLibrary_C, __WorldContext: Object?): BallisticPoolManager
---@field GetClosestBoneAlongProjectilePrediction fun(self: BP_BallisticFunctionLibrary_C, InPredictionData: PredictProjectilePathResult|{}, InActor: Actor?, __WorldContext: Object?, HitBone: string, HitComponent: PrimitiveComponent?) Do not call from Lua: it needs 1837 bytes and the call buffer holds 512.
---@field PredictProjectileDamage fun(self: BP_BallisticFunctionLibrary_C, Weapon: Actor?, Defender: Actor?, ProjectileHit: HitResult|{}, Killcam: boolean, __WorldContext: Object?, OutDamage: number)

---@class BP_DeployableFunctionLibrary_C : BlueprintFunctionLibrary
---@field GetDeployableVariationClass fun(self: BP_DeployableFunctionLibrary_C, Item: ItemData|{}, Variation: integer, __WorldContext: Object?, AsIcarus_Item: Class?) Do not call from Lua: it needs 1153 bytes and the call buffer holds 512.
---@field SpawnDeployable fun(self: BP_DeployableFunctionLibrary_C, Item: ItemData|{}, Transform: Transform|{}, __WorldContext: Object?, Deployable: BP_DeployableBase_C?) Do not call from Lua: it needs 1330 bytes and the call buffer holds 512.
---@field SpawnDeployablePersistent fun(self: BP_DeployableFunctionLibrary_C, Item: ItemData|{}, Name: string, Location: QuestQueriesRowHandle|{}, __WorldContext: Object?, Deployable: BP_DeployableBase_C?) Do not call from Lua: it needs 808 bytes and the call buffer holds 512.

---@class BP_MapFunctionLibrary_C : BlueprintFunctionLibrary
---@field FromUV fun(self: BP_MapFunctionLibrary_C, UV: Vector2D|{}, __WorldContext: Object?, Fractional: Vector2D|{})
---@field GetAlphabet fun(self: BP_MapFunctionLibrary_C, __WorldContext: Object?, Alphabet: string[])
---@field GetGridSize fun(self: BP_MapFunctionLibrary_C, __WorldContext: Object?, GridSize: number)
---@field GetLowestGroundHeightAtLocation fun(self: BP_MapFunctionLibrary_C, GridLocation: Vector|{}, TraceForLandscapeOnly: boolean, __WorldContext: Object?, Location: Vector|{}, Success: boolean)
---@field GetSurfaceHeightAtLocation fun(self: BP_MapFunctionLibrary_C, GridLocation: Vector|{}, IncludeActorSurfaces: boolean, __WorldContext: Object?, Location: Vector|{}, Success: boolean) Do not call from Lua: it needs 770 bytes and the call buffer holds 512.
---@field GetUV fun(self: BP_MapFunctionLibrary_C, Fractional: Vector2D|{}, __WorldContext: Object?, UV: Vector2D|{})
---@field GetZeroIndex fun(self: BP_MapFunctionLibrary_C, __WorldContext: Object?, Index: integer)
---@field GridToIndex fun(self: BP_MapFunctionLibrary_C, Grid: string, __WorldContext: Object?, Index: IntPoint|{})
---@field GridToLocation fun(self: BP_MapFunctionLibrary_C, Grid: string, UV: Vector2D|{}, __WorldContext: Object?, Location: Vector2D|{})
---@field IndexToGrid fun(self: BP_MapFunctionLibrary_C, Index: IntPoint|{}, __WorldContext: Object?, Grid: string)
---@field IndexToLocation fun(self: BP_MapFunctionLibrary_C, Index: IntPoint|{}, __WorldContext: Object?, Location: Vector2D|{})
---@field IsPointBelowLevel fun(self: BP_MapFunctionLibrary_C, WorldLocation: Vector|{}, TraceForLandscapeOnly: boolean, __WorldContext: Object?, BelowLevel: boolean)
---@field IsPointOutsideOfLevel fun(self: BP_MapFunctionLibrary_C, WorldLocation: Vector|{}, __WorldContext: Object?, IsOutside: boolean)
---@field LocationToGrid fun(self: BP_MapFunctionLibrary_C, Location: Vector2D|{}, __WorldContext: Object?, Grid: string, UV: Vector2D|{})
---@field LocationToIndex fun(self: BP_MapFunctionLibrary_C, Location: Vector2D|{}, __WorldContext: Object?, Index: IntPoint|{})

---@class BP_PaniniFunctionLibrary_C : BlueprintFunctionLibrary
---@field SetPaniniEnabledForPrimitive fun(self: BP_PaniniFunctionLibrary_C, Primitive: PrimitiveComponent?, Enabled: boolean, __WorldContext: Object?)
---@field UpdateActorPanini fun(self: BP_PaniniFunctionLibrary_C, Target: Actor?, Enabled: boolean, __WorldContext: Object?)

---@class BP_PauseFunctionLibrary_C : BlueprintFunctionLibrary
---@field SetAudioPaused fun(self: BP_PauseFunctionLibrary_C, bPaused: boolean, __WorldContext: Object?)

---@class BP_PlayerCosmeticsFunctionLibrary_C : BlueprintFunctionLibrary
---@field ApplyCosmeticsToPrimitive fun(self: BP_PlayerCosmeticsFunctionLibrary_C, PrimitiveComponent: PrimitiveComponent?, CosmeticData: CharacterCosmetics|{}, __WorldContext: Object?) Do not call from Lua: it needs 5777 bytes and the call buffer holds 512.
---@field ClearCosmeticMaterialOverride fun(self: BP_PlayerCosmeticsFunctionLibrary_C, InPrimitive: PrimitiveComponent?, __WorldContext: Object?)
---@field GetMasterMaterial fun(self: BP_PlayerCosmeticsFunctionLibrary_C, Material: MaterialInterface?, __WorldContext: Object?, Parent: Material?)
---@field MakeCharacterCreationDataArray fun(self: BP_PlayerCosmeticsFunctionLibrary_C, CharacterCosmetics: CharacterCosmetics|{}, __WorldContext: Object?, OutData: CharacterCreationDataRowHandle[])
---@field UpdateSkinTone fun(self: BP_PlayerCosmeticsFunctionLibrary_C, Tone: number, Tint: number, Saturation: number, MatHead: MaterialInstanceDynamic?, __WorldContext: Object?)

---@class BP_PlayerProgressionFunctionLibrary_C : BlueprintFunctionLibrary
---@field CalculatePlayerLevelFromExp fun(self: BP_PlayerProgressionFunctionLibrary_C, Experience: integer, __WorldContext: Object?, Level: integer, RemainingXP: integer, PercentageToNextLevel: number)

---@class BP_SentryFunctionLibrary_C : BlueprintFunctionLibrary
---@field CaptureCustomSentryReport fun(self: BP_SentryFunctionLibrary_C, UserDescription: string, Level: ESentryLevel, CustomTags: table<string, string>, __WorldContext: Object?)

---@class BP_Weight_C : WeightComponent
---@field OnTopOf table<ShapeComponent, ActorArrayStruct>
---@field SpreadWeightToBuildingNeighbors boolean
---@field BoundColliderBeginOverlap fun(self: BP_Weight_C, OverlappedComponent: PrimitiveComponent?, OtherActor: Actor?, OtherComp: PrimitiveComponent?, OtherBodyIndex: integer, bFromSweep: boolean, SweepResult: HitResult|{})
---@field BoundColliderEndOverlap fun(self: BP_Weight_C, OverlappedComponent: PrimitiveComponent?, OtherActor: Actor?, OtherComp: PrimitiveComponent?, OtherBodyIndex: integer)
---@field GetWeight fun(self: BP_Weight_C, Shape: ShapeComponent?): number
---@field Init fun(self: BP_Weight_C)
---@field RemoveWeightFromBuilding fun(self: BP_Weight_C, Building: Actor?, Shape: ShapeComponent?)
---@field SendWeightToBuilding fun(self: BP_Weight_C, Building: Actor?, Shape: ShapeComponent?)

---@class FProspectServerInfo
---@field DedicatedServer_29_F52309C7414817A00450F39BBD398484 boolean
---@field FromServer_25_F9C528E64F20AFA8C84ED7AA1326ED9A boolean
---@field Locked_27_6AF042504E9CF0860185D5954A081152 boolean
---@field ProspectInfo_23_6124B8864E499D95C9280FB64D71F169 ProspectInfo
---@field Session_13_24CBF6094F819F915C2AF59365EDF438 BlueprintSessionResult

---@class HighlightableCustomiserInterface_C : Interface
---@field GetDescription fun(self: HighlightableCustomiserInterface_C, Description: string)
---@field GetDisplayName fun(self: HighlightableCustomiserInterface_C, Name: string)

---@class IcarusFunctionLibrary_C : BlueprintFunctionLibrary
---@field AddReverseLinesToVectorPairArray fun(self: IcarusFunctionLibrary_C, VectorPairs: VectorPair__Building[], __WorldContext: Object?, PairsWithReversed: VectorPair__Building[])
---@field FilterActorListBySoftClasses fun(self: IcarusFunctionLibrary_C, InActors: Actor[], InClassFilter: Class[], __WorldContext: Object?, OutActors: Actor[])
---@field FormatRawSecondsToTimeLength fun(self: IcarusFunctionLibrary_C, SecondsInput: integer, __WorldContext: Object?, Formatted: string)
---@field FormatRawSecondsToTimeLengthDigital fun(self: IcarusFunctionLibrary_C, SecondsInput: integer, __WorldContext: Object?, Time: string[])
---@field FormatTimeLength fun(self: IcarusFunctionLibrary_C, SecondsInput: integer, __WorldContext: Object?, Formatted: string)
---@field FormatTimeLengthDigital fun(self: IcarusFunctionLibrary_C, SecondsInput: integer, __WorldContext: Object?, Time: string[])
---@field ["Get Custom Item Icon"] fun(self: IcarusFunctionLibrary_C, ItemData: ItemData|{}, __WorldContext: Object?, Icon: Texture2D?, AlphaOverride: Texture2D?) Do not call from Lua: it needs 1464 bytes and the call buffer holds 512.
---@field ["Get Icon or Missing"] fun(self: IcarusFunctionLibrary_C, Icon: Texture2D?, __WorldContext: Object?, Output: Texture2D?)
---@field GetCollectableNoteRow fun(self: IcarusFunctionLibrary_C, Item: ItemData|{}, WorldContextObject: Object?, __WorldContext: Object?, NoteRow: CollectableNotesRowHandle|{}) Do not call from Lua: it needs 569 bytes and the call buffer holds 512.
---@field GetIcarusController fun(self: IcarusFunctionLibrary_C, Index: integer, __WorldContext: Object?, Valid: boolean): IcarusPlayerController
---@field GetInteractionsSupportingMountedState fun(self: IcarusFunctionLibrary_C, Interactable: InteractableComponent?, __WorldContext: Object?, HasAny: boolean, WorldPressInteractions: InteractionsRowHandle[], WorldHoldInteractions: InteractionsRowHandle[], WorldAltPressInteractions: InteractionsRowHandle[], WorldAltHoldInteractions: InteractionsRowHandle[]) Do not call from Lua: it needs 1068 bytes and the call buffer holds 512.
---@field GetItemIcon fun(self: IcarusFunctionLibrary_C, ItemData: ItemData|{}, __WorldContext: Object?, Icon: Texture2D?) Do not call from Lua: it needs 2888 bytes and the call buffer holds 512.
---@field GetItemIcon_Static fun(self: IcarusFunctionLibrary_C, ItemStatic: ItemStaticData|{}, __WorldContext: Object?, Icon: Texture2D?) Do not call from Lua: it needs 1504 bytes and the call buffer holds 512.
---@field GetItemName fun(self: IcarusFunctionLibrary_C, ItemData: ItemData|{}, __WorldContext: Object?, Name: string) Do not call from Lua: it needs 2746 bytes and the call buffer holds 512.
---@field GetItemName_Static fun(self: IcarusFunctionLibrary_C, ItemStatic: ItemStaticData|{}, __WorldContext: Object?, Name: string) Do not call from Lua: it needs 1442 bytes and the call buffer holds 512.
---@field GetLocalSelectedChrSlot fun(self: IcarusFunctionLibrary_C, __WorldContext: Object?, ChrSlot: integer)
---@field GetPlayerIdentityData fun(self: IcarusFunctionLibrary_C, Index: integer, __WorldContext: Object?, PlayerIdentity: PlayerIdentityData|{})
---@field GetResourceColour fun(self: IcarusFunctionLibrary_C, Type: IcarusResourcesEnum|{}, __WorldContext: Object?, Color: Color|{})
---@field GetResourceContainer fun(self: IcarusFunctionLibrary_C, Type: IcarusResourcesEnum|{}, __WorldContext: Object?, Container_Icon: MaterialInstance?)
---@field GetResourceImage fun(self: IcarusFunctionLibrary_C, Type: IcarusResourcesEnum|{}, __WorldContext: Object?): Texture2D
---@field GetResourceName fun(self: IcarusFunctionLibrary_C, Type: IcarusResourcesEnum|{}, __WorldContext: Object?): string
---@field GetResourceUnit fun(self: IcarusFunctionLibrary_C, Type: IcarusResourcesEnum|{}, __WorldContext: Object?, Unit: string)
---@field ["Is Actor Required To Be Outside"] fun(self: IcarusFunctionLibrary_C, Actor: Actor?, __WorldContext: Object?, MustBeOutside: boolean)
---@field IsActorAffectedByShelter fun(self: IcarusFunctionLibrary_C, Actor: Actor?, __WorldContext: Object?, IsAffected: boolean)
---@field IsItemAffectedByShelter fun(self: IcarusFunctionLibrary_C, Actor: ItemData|{}, __WorldContext: Object?, IsAffected: boolean) Do not call from Lua: it needs 1964 bytes and the call buffer holds 512.
---@field MakeItem fun(self: IcarusFunctionLibrary_C, MetaItem: MetaItem|{}, __WorldContext: Object?, Item: ItemData|{}) Do not call from Lua: it needs 537 bytes and the call buffer holds 512.
---@field PrintDebug fun(self: IcarusFunctionLibrary_C, Category: string, Log: string, __WorldContext: Object?)
---@field ResolveSoftClassReferenceArray fun(self: IcarusFunctionLibrary_C, InSoftReferences: Class[], __WorldContext: Object?, OutClasses: Class[])
---@field RoundVector fun(self: IcarusFunctionLibrary_C, Vector: Vector|{}, __WorldContext: Object?, Rounded: Vector|{})
---@field SetAllLightsHiddenInGame fun(self: IcarusFunctionLibrary_C, HiddenInGame: boolean, ActorIgnoreList: Actor[], ComponentIgnoreList: LightComponent[], __WorldContext: Object?)
---@field ShouldItemBePlacedOutside fun(self: IcarusFunctionLibrary_C, Item: ItemData|{}, __WorldContext: Object?, PlaceOutside: boolean) Do not call from Lua: it needs 1850 bytes and the call buffer holds 512.
---@field UpdatePlayerComfortLevel fun(self: IcarusFunctionLibrary_C, __WorldContext: Object?, Comfort: integer, SleepDuration: integer, SleepEffectiveness: integer)

---@class IcarusSurvivalFunctionLibrary_C : BlueprintFunctionLibrary
---@field GetBestSafeTeleportLocationForPlayer fun(self: IcarusSurvivalFunctionLibrary_C, PlayerCharacter: IcarusPlayerCharacter?, __WorldContext: Object?, OutLocation: Vector|{}) Do not call from Lua: it needs 1100 bytes and the call buffer holds 512.
---@field GetIcarusPlayerCharacterSurvivalBP fun(self: IcarusSurvivalFunctionLibrary_C, PlayerIndex: integer, __WorldContext: Object?, Valid: boolean): BP_IcarusPlayerCharacterSurvival_C
---@field GetIcarusPlayerControllerSurvivalBP fun(self: IcarusSurvivalFunctionLibrary_C, PlayerIndex: integer, __WorldContext: Object?, Valid: boolean): BP_IcarusPlayerControllerSurvival_C

---@class MissionFunctionLibrary_C : BlueprintFunctionLibrary
---@field GetHistoryForMission fun(self: MissionFunctionLibrary_C, MissionRow: FactionMissionsRowHandle|{}, __WorldContext: Object?, Mission_State: EMissionState, Mission_End_Time: integer, FoundHistory: boolean)
---@field IsMissionInProgress fun(self: MissionFunctionLibrary_C, Mission: FactionMissionsRowHandle|{}, WorldContextObject: Object?, __WorldContext: Object?, IsValid: boolean)
---@field IsOperationCompleteOnOpenWorld fun(self: MissionFunctionLibrary_C, WorldContextObject: Object?, Operation: FactionMissionsRowHandle|{}, __WorldContext: Object?, bComplete: boolean)

---@class UIControllerInterface_C : Interface
---@field GetUserInterface fun(self: UIControllerInterface_C, UserInterface: UMG_UserInterface_Base_C?)
