---@meta _
-- Generated by scripts\gameindex.py from the index of the game's classes. Changes here are lost on the next run.

---@class BP_Animal_Trap_Base_C : BP_DeployableBase_C
---@field AttractionRadius number
---@field BP_UIProjectionLocation BP_UIProjectionLocation_C
---@field CaptureZone BoxComponent
---@field Creature AISetupRowHandle
---@field InventoryRef Inventory
---@field Level integer
---@field Scene SceneComponent
---@field ValidCaptureList AISetupRowHandle[]
---@field bTrapActive boolean
---@field CanCaptureAnimal fun(self: BP_Animal_Trap_Base_C, Creature: Object?, CanCapture: boolean)
---@field CaptureAnimal fun(self: BP_Animal_Trap_Base_C, Object: Object?)
---@field Deployable_Interact fun(self: BP_Animal_Trap_Base_C, Interactor: Actor?)
---@field GetWidgetClass fun(self: BP_Animal_Trap_Base_C, Widget: Class?)
---@field IcarusBeginPlay fun(self: BP_Animal_Trap_Base_C)
---@field OnRep_bActive fun(self: BP_Animal_Trap_Base_C)
---@field ReleaseCreature fun(self: BP_Animal_Trap_Base_C)
---@field ToggleTrapActive fun(self: BP_Animal_Trap_Base_C)

---@class BP_Animal_Trap_Medium_C : BP_Animal_Trap_Base_C
---@field SM_DEP_Trap_Large_Bear StaticMeshComponent
---@field ReceiveBeginPlay fun(self: BP_Animal_Trap_Medium_C)

---@class BP_Animal_Trap_Small_C : BP_Animal_Trap_Base_C
---@field SM_DEP_Trap_Small_T2 StaticMeshComponent
---@field ReceiveBeginPlay fun(self: BP_Animal_Trap_Small_C)

---@class BP_Animal_Trap_Small_T4_C : BP_Animal_Trap_Base_C
---@field SM_DEP_Trap_Small_T4 StaticMeshComponent
---@field ReceiveBeginPlay fun(self: BP_Animal_Trap_Small_T4_C)

---@class BP_Bait_C : BP_DeployableBase_C
---@field FlyAudio FMODAudioComponent
---@field NS_Flies1 NiagaraComponent

---@class BP_Bait_Poisoned_C : BP_DeployableBase_C
---@field FlyAudio FMODAudioComponent
---@field NS_Flies1 NiagaraComponent
---@field P_Smoke_Poison ParticleSystemComponent
---@field GetModifierToApplyOnConsume fun(self: BP_Bait_Poisoned_C, Modifier: ModifierStatesRowHandle|{}, Lifetime: number)
