---@meta _
-- Generated by scripts\gameindex.py from the index of the game's classes. Changes here are lost on the next run.

---@class BP_Brick_Sign_Angle_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Brick_Sign_Angle_C)

---@class BP_Brick_Sign_Angle_Small_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Brick_Sign_Angle_Small_C)

---@class BP_Brick_Sign_Small_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Brick_Sign_Small_C)

---@class BP_Brick_Wall_Sign_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Brick_Wall_Sign_C)

---@class BP_Composite_Sign_Angle_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Composite_Sign_Angle_C)

---@class BP_Composite_Sign_Angle_Small_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Composite_Sign_Angle_Small_C)

---@class BP_Composite_Sign_Small_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Composite_Sign_Small_C)

---@class BP_Composite_Wall_Sign_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Composite_Wall_Sign_C)

---@class BP_Concrete_Sign_Angle_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Concrete_Sign_Angle_C)

---@class BP_Concrete_Sign_Angle_Small_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Concrete_Sign_Angle_Small_C)

---@class BP_Concrete_Sign_Small_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Concrete_Sign_Small_C)

---@class BP_Concrete_Wall_Sign_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Concrete_Wall_Sign_C)

---@class BP_Gold_Wall_Sign_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Gold_Wall_Sign_C)

---@class BP_Iron_Sign_Angle_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Iron_Sign_Angle_C)

---@class BP_Iron_Sign_Angle_Small_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Iron_Sign_Angle_Small_C)

---@class BP_Iron_Sign_Small_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Iron_Sign_Small_C)

---@class BP_Iron_Wall_Sign_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Iron_Wall_Sign_C)

---@class BP_Propaganda_Sign_A_C : BP_Sign_Base_C
---@field Widget_SignDisplay1 WidgetComponent
---@field GetMaxCharacters fun(self: BP_Propaganda_Sign_A_C, MaxCharacters: integer[])
---@field GetSignWidgets fun(self: BP_Propaganda_Sign_A_C, Widgets: UMG_Sign_Text_Display_C[])
---@field ReceiveBeginPlay fun(self: BP_Propaganda_Sign_A_C)
---@field UserConstructionScript fun(self: BP_Propaganda_Sign_A_C)

---@class BP_Propaganda_Sign_B_C : BP_Sign_Base_C
---@field Widget_SignDisplay1 WidgetComponent
---@field GetMaxCharacters fun(self: BP_Propaganda_Sign_B_C, MaxCharacters: integer[])
---@field GetSignWidgets fun(self: BP_Propaganda_Sign_B_C, Widgets: UMG_Sign_Text_Display_C[])
---@field ReceiveBeginPlay fun(self: BP_Propaganda_Sign_B_C)
---@field UserConstructionScript fun(self: BP_Propaganda_Sign_B_C)

---@class BP_Propaganda_Sign_C_C : BP_Sign_Base_C
---@field Widget_SignDisplay1 WidgetComponent
---@field GetMaxCharacters fun(self: BP_Propaganda_Sign_C_C, MaxCharacters: integer[])
---@field GetSignWidgets fun(self: BP_Propaganda_Sign_C_C, Widgets: UMG_Sign_Text_Display_C[])
---@field ReceiveBeginPlay fun(self: BP_Propaganda_Sign_C_C)
---@field UserConstructionScript fun(self: BP_Propaganda_Sign_C_C)

---@class BP_Propaganda_Sign_D_C : BP_Sign_Base_C
---@field Widget_SignDisplay1 WidgetComponent
---@field GetMaxCharacters fun(self: BP_Propaganda_Sign_D_C, MaxCharacters: integer[])
---@field GetSignWidgets fun(self: BP_Propaganda_Sign_D_C, Widgets: UMG_Sign_Text_Display_C[])
---@field ReceiveBeginPlay fun(self: BP_Propaganda_Sign_D_C)
---@field UserConstructionScript fun(self: BP_Propaganda_Sign_D_C)

---@class BP_Propaganda_Sign_E_C : BP_Sign_Base_C
---@field Widget_SignDisplay1 WidgetComponent
---@field GetMaxCharacters fun(self: BP_Propaganda_Sign_E_C, MaxCharacters: integer[])
---@field GetSignWidgets fun(self: BP_Propaganda_Sign_E_C, Widgets: UMG_Sign_Text_Display_C[])
---@field ReceiveBeginPlay fun(self: BP_Propaganda_Sign_E_C)
---@field UserConstructionScript fun(self: BP_Propaganda_Sign_E_C)

---@class BP_Propaganda_Sign_F_C : BP_Sign_Base_C
---@field Widget_SignDisplay1 WidgetComponent
---@field GetMaxCharacters fun(self: BP_Propaganda_Sign_F_C, MaxCharacters: integer[])
---@field GetSignWidgets fun(self: BP_Propaganda_Sign_F_C, Widgets: UMG_Sign_Text_Display_C[])
---@field ReceiveBeginPlay fun(self: BP_Propaganda_Sign_F_C)
---@field UserConstructionScript fun(self: BP_Propaganda_Sign_F_C)

---@class BP_Propaganda_Sign_G_C : BP_Sign_Base_C
---@field Widget_SignDisplay1 WidgetComponent
---@field GetMaxCharacters fun(self: BP_Propaganda_Sign_G_C, MaxCharacters: integer[])
---@field GetSignWidgets fun(self: BP_Propaganda_Sign_G_C, Widgets: UMG_Sign_Text_Display_C[])
---@field ReceiveBeginPlay fun(self: BP_Propaganda_Sign_G_C)
---@field UserConstructionScript fun(self: BP_Propaganda_Sign_G_C)

---@class BP_Propaganda_Sign_H_C : BP_Sign_Base_C
---@field Widget_SignDisplay1 WidgetComponent
---@field GetMaxCharacters fun(self: BP_Propaganda_Sign_H_C, MaxCharacters: integer[])
---@field GetSignWidgets fun(self: BP_Propaganda_Sign_H_C, Widgets: UMG_Sign_Text_Display_C[])
---@field ReceiveBeginPlay fun(self: BP_Propaganda_Sign_H_C)
---@field UserConstructionScript fun(self: BP_Propaganda_Sign_H_C)

---@class BP_Ranch_Gate_Sign_C : BP_Sign_Base_C
---@field BP_UIProjectionLocation BP_UIProjectionLocation_C
---@field SM_DCO_Giant_Ranch_Sign_Gate_Door01 StaticMeshComponent
---@field SM_DCO_Giant_Ranch_Sign_Gate_Door02 StaticMeshComponent
---@field bOpen boolean
---@field Deployable_Interact fun(self: BP_Ranch_Gate_Sign_C, Interactor: Actor?)
---@field DisableForcedAnimUpdates fun(self: BP_Ranch_Gate_Sign_C)
---@field IcarusBeginPlay fun(self: BP_Ranch_Gate_Sign_C)
---@field OnRep_bOpen fun(self: BP_Ranch_Gate_Sign_C)
---@field ReceiveBeginPlay fun(self: BP_Ranch_Gate_Sign_C)
---@field TemporarilyForceAnimUpdates fun(self: BP_Ranch_Gate_Sign_C)
---@field UpdateSign fun(self: BP_Ranch_Gate_Sign_C, Interactor: Actor?)
---@field UpdateSignWidgetText fun(self: BP_Ranch_Gate_Sign_C)

---@class BP_Ranch_Sign_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Ranch_Sign_C)
---@field UpdateSignWidgetText fun(self: BP_Ranch_Sign_C)

---@class BP_Raw_Wood_Sign_Ground_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Raw_Wood_Sign_Ground_C)

---@class BP_Raw_Wood_Sign_Ground_Trunk_A_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Raw_Wood_Sign_Ground_Trunk_A_C)

---@class BP_Raw_Wood_Sign_Ground_Trunk_B_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Raw_Wood_Sign_Ground_Trunk_B_C)

---@class BP_Raw_Wood_Wall_Sign_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Raw_Wood_Wall_Sign_C)

---@class BP_Raw_Wood_Wall_Sign_Trunk_A_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Raw_Wood_Wall_Sign_Trunk_A_C)

---@class BP_Raw_Wood_Wall_Sign_Trunk_B_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Raw_Wood_Wall_Sign_Trunk_B_C)

---@class BP_ScoriaBrick_Sign_Angle_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_ScoriaBrick_Sign_Angle_C)

---@class BP_ScoriaBrick_Sign_Angle_Small_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_ScoriaBrick_Sign_Angle_Small_C)

---@class BP_ScoriaBrick_Sign_Small_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_ScoriaBrick_Sign_Small_C)

---@class BP_ScoriaBrick_Wall_Sign_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_ScoriaBrick_Wall_Sign_C)

---@class BP_Sign_Base_C : BP_DeployableBase_C
---@field Camera CameraComponent
---@field FontColor LinearColor
---@field IconRow ItemableRowHandle
---@field MaxCharacters integer
---@field SupportedColourOverrides LinearColor[]
---@field SupportsIcons boolean
---@field Text string
---@field TextJustification ETextJustify
---@field Widget_SignDisplay WidgetComponent
---@field Deployable_Interact fun(self: BP_Sign_Base_C, Interactor: Actor?)
---@field EditorDebugIcon fun(self: BP_Sign_Base_C)
---@field GetMaxCharacters fun(self: BP_Sign_Base_C, MaxCharacters: integer[])
---@field GetSignColor fun(self: BP_Sign_Base_C): LinearColor
---@field GetSignIconRow fun(self: BP_Sign_Base_C): ItemableRowHandle
---@field GetSignText fun(self: BP_Sign_Base_C): string
---@field GetSignWidgets fun(self: BP_Sign_Base_C, Widgets: UMG_Sign_Text_Display_C[])
---@field OnRep_FontColor fun(self: BP_Sign_Base_C)
---@field OnRep_IconRow fun(self: BP_Sign_Base_C)
---@field OnRep_Text fun(self: BP_Sign_Base_C)
---@field ReceiveBeginPlay fun(self: BP_Sign_Base_C)
---@field SetSignIcon fun(self: BP_Sign_Base_C, IconRow: ItemableRowHandle|{})
---@field SetSignText fun(self: BP_Sign_Base_C, Text: string, Color: LinearColor|{})
---@field UpdateIcon fun(self: BP_Sign_Base_C, IconRow: ItemableRowHandle|{})
---@field UpdateSignWidgetText fun(self: BP_Sign_Base_C)
---@field UpdateTextRender fun(self: BP_Sign_Base_C, Text: string, Color: LinearColor|{})

---@class BP_StoneBrick_Sign_Angle_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_StoneBrick_Sign_Angle_C)

---@class BP_StoneBrick_Sign_Angle_Small_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_StoneBrick_Sign_Angle_Small_C)

---@class BP_StoneBrick_Sign_Small_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_StoneBrick_Sign_Small_C)

---@class BP_StoneBrick_Wall_Sign_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_StoneBrick_Wall_Sign_C)

---@class BP_Stone_Sign_Angle_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Stone_Sign_Angle_C)

---@class BP_Stone_Sign_Angle_Small_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Stone_Sign_Angle_Small_C)

---@class BP_Stone_Wall_Sign_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Stone_Wall_Sign_C)

---@class BP_UDA_Sign_A_C : BP_Sign_Base_C
---@field GetMaxCharacters fun(self: BP_UDA_Sign_A_C, MaxCharacters: integer[])
---@field GetSignWidgets fun(self: BP_UDA_Sign_A_C, Widgets: UMG_Sign_Text_Display_C[])
---@field ReceiveBeginPlay fun(self: BP_UDA_Sign_A_C)
---@field UserConstructionScript fun(self: BP_UDA_Sign_A_C)

---@class BP_UDA_Sign_B_C : BP_Sign_Base_C
---@field GetMaxCharacters fun(self: BP_UDA_Sign_B_C, MaxCharacters: integer[])
---@field GetSignWidgets fun(self: BP_UDA_Sign_B_C, Widgets: UMG_Sign_Text_Display_C[])
---@field ReceiveBeginPlay fun(self: BP_UDA_Sign_B_C)
---@field UserConstructionScript fun(self: BP_UDA_Sign_B_C)

---@class BP_UDA_Sign_C_C : BP_Sign_Base_C
---@field GetMaxCharacters fun(self: BP_UDA_Sign_C_C, MaxCharacters: integer[])
---@field GetSignWidgets fun(self: BP_UDA_Sign_C_C, Widgets: UMG_Sign_Text_Display_C[])
---@field ReceiveBeginPlay fun(self: BP_UDA_Sign_C_C)
---@field UserConstructionScript fun(self: BP_UDA_Sign_C_C)

---@class BP_UDA_Sign_D_C : BP_Sign_Base_C
---@field GetMaxCharacters fun(self: BP_UDA_Sign_D_C, MaxCharacters: integer[])
---@field GetSignWidgets fun(self: BP_UDA_Sign_D_C, Widgets: UMG_Sign_Text_Display_C[])
---@field ReceiveBeginPlay fun(self: BP_UDA_Sign_D_C)
---@field UserConstructionScript fun(self: BP_UDA_Sign_D_C)

---@class BP_UDA_Sign_E_C : BP_Sign_Base_C
---@field Widget_SignDisplay1 WidgetComponent
---@field GetMaxCharacters fun(self: BP_UDA_Sign_E_C, MaxCharacters: integer[])
---@field GetSignWidgets fun(self: BP_UDA_Sign_E_C, Widgets: UMG_Sign_Text_Display_C[])
---@field ReceiveBeginPlay fun(self: BP_UDA_Sign_E_C)
---@field UserConstructionScript fun(self: BP_UDA_Sign_E_C)

---@class BP_UDA_Sign_F_C : BP_Sign_Base_C
---@field Widget_SignDisplay1 WidgetComponent
---@field GetMaxCharacters fun(self: BP_UDA_Sign_F_C, MaxCharacters: integer[])
---@field GetSignWidgets fun(self: BP_UDA_Sign_F_C, Widgets: UMG_Sign_Text_Display_C[])
---@field ReceiveBeginPlay fun(self: BP_UDA_Sign_F_C)
---@field UserConstructionScript fun(self: BP_UDA_Sign_F_C)

---@class BP_UDA_Sign_G_C : BP_Sign_Base_C
---@field Widget_SignDisplay1 WidgetComponent
---@field GetMaxCharacters fun(self: BP_UDA_Sign_G_C, MaxCharacters: integer[])
---@field GetSignWidgets fun(self: BP_UDA_Sign_G_C, Widgets: UMG_Sign_Text_Display_C[])
---@field ReceiveBeginPlay fun(self: BP_UDA_Sign_G_C)
---@field UserConstructionScript fun(self: BP_UDA_Sign_G_C)

---@class BP_UDA_Sign_H_C : BP_Sign_Base_C
---@field Widget_SignDisplay1 WidgetComponent
---@field GetMaxCharacters fun(self: BP_UDA_Sign_H_C, MaxCharacters: integer[])
---@field GetSignWidgets fun(self: BP_UDA_Sign_H_C, Widgets: UMG_Sign_Text_Display_C[])
---@field ReceiveBeginPlay fun(self: BP_UDA_Sign_H_C)
---@field UserConstructionScript fun(self: BP_UDA_Sign_H_C)

---@class BP_Wood_Sign_Small_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Wood_Sign_Small_C)

---@class BP_Wood_Wall_Sign_C : BP_Sign_Base_C
---@field ReceiveBeginPlay fun(self: BP_Wood_Wall_Sign_C)

---@class UMG_Lab_Poster_B_C : UserWidget
---@field Image Image
---@field Image_1 Image
---@field Image_10 Image
---@field Image_11 Image
---@field Image_12 Image
---@field Image_13 Image
---@field Image_14 Image
---@field Image_15 Image
---@field Image_16 Image
---@field Image_17 Image
---@field Image_18 Image
---@field Image_191 Image
---@field Image_2 Image
---@field Image_3 Image
---@field Image_4 Image
---@field Image_5 Image
---@field Image_6 Image
---@field Image_7 Image
---@field Image_8 Image
---@field Image_9 Image

---@class UMG_Lab_Poster_C : UserWidget
---@field Image Image
---@field Image_1 Image
---@field Image_10 Image
---@field Image_11 Image
---@field Image_12 Image
---@field Image_13 Image
---@field Image_14 Image
---@field Image_15 Image
---@field Image_16 Image
---@field Image_17 Image
---@field Image_18 Image
---@field Image_2 Image
---@field Image_3 Image
---@field Image_4 Image
---@field Image_5 Image
---@field Image_6 Image
---@field Image_7 Image
---@field Image_8 Image
---@field Image_82 Image
---@field Image_9 Image

---@class UMG_Lab_Poster_C_C : UserWidget
---@field Image Image
---@field Image_1 Image
---@field Image_10 Image
---@field Image_11 Image
---@field Image_12 Image
---@field Image_15 Image
---@field Image_16 Image
---@field Image_17 Image
---@field Image_18 Image
---@field Image_191 Image
---@field Image_2 Image
---@field Image_3 Image
---@field Image_7 Image
---@field Image_8 Image
---@field Image_9 Image

---@class UMG_Sign_IconListEntry_C : UserWidget
---@field Image_HoverIcon Image
---@field Image_ItemIcon Image
---@field BP_OnEntryReleased fun(self: UMG_Sign_IconListEntry_C)
---@field BP_OnItemExpansionChanged fun(self: UMG_Sign_IconListEntry_C, bIsExpanded: boolean)
---@field BP_OnItemSelectionChanged fun(self: UMG_Sign_IconListEntry_C, bIsSelected: boolean)
---@field Construct fun(self: UMG_Sign_IconListEntry_C)
---@field Get_Image_HoverIcon_Brush_0 fun(self: UMG_Sign_IconListEntry_C): SlateBrush
---@field OnListItemObjectSet fun(self: UMG_Sign_IconListEntry_C, ListItemObject: Object?)
---@field SetVisuallySelected fun(self: UMG_Sign_IconListEntry_C, IsSelected: boolean)

---@class UMG_Sign_Text_DisplayRanch_C : UserWidget
---@field CurrentIconRow ItemableRowHandle
---@field Image_Icon Image
---@field TextBlock_SignText TextBlock
---@field UpdateSignDisplayIcon fun(self: UMG_Sign_Text_DisplayRanch_C, Itemable: ItemableRowHandle|{})
---@field UpdateSignDisplayText fun(self: UMG_Sign_Text_DisplayRanch_C, Text: string)

---@class UMG_Sign_Text_Display_C : UserWidget
---@field CurrentIconRow ItemableRowHandle
---@field Image_Icon Image
---@field SizeBox_Main SizeBox
---@field TextBlock_SignText TextBlock
---@field InitialiseWidget fun(self: UMG_Sign_Text_Display_C, Size: Vector2D|{}, WrapText: boolean, Justification: ETextJustify)
---@field UpdateSignDisplayIcon fun(self: UMG_Sign_Text_Display_C, Itemable: ItemableRowHandle|{})
---@field UpdateSignDisplayText fun(self: UMG_Sign_Text_Display_C, Text: string)

---@class UMG_Sign_Text_Window_C : UMG_IcarusLinkedActorPanel_C
---@field ButtonIcon UMG_ToggleButton_MenuHeader_C
---@field ButtonText UMG_ToggleButton_MenuHeader_C
---@field ColorSelectionPanel UniformGridPanel
---@field ConfirmButton UMG_IconTextButton_C
---@field EditableTextBox1 EditableTextBox
---@field EditableTextBox2 EditableTextBox
---@field EditableTextBox3 EditableTextBox
---@field EditableTextBox4 EditableTextBox
---@field EditableTextBox_IconSearch EditableTextBox
---@field FontColor LinearColor
---@field FontColorChanged GameDelegate
---@field HorizontalBox_Tabs HorizontalBox
---@field IconListItems SignIconListItem[]
---@field ListView_ItemIcons ListView
---@field MaxCharacters integer[]
---@field SignReference BP_Sign_Base_C
---@field SizeBox_Text1 SizeBox
---@field SizeBox_Text2 SizeBox
---@field SizeBox_Text3 SizeBox
---@field SizeBox_Text4 SizeBox
---@field SupportedColors LinearColor[]
---@field TempString string
---@field VerticalBox_Input VerticalBox
---@field WidgetSwitcher_SignType WidgetSwitcher
---@field divider Image
---@field Construct fun(self: UMG_Sign_Text_Window_C)
---@field GenerateItemList fun(self: UMG_Sign_Text_Window_C, ValidItemables: ItemableRowHandle[]) Wax refuses this call from Lua.
---@field GetAppendedText fun(self: UMG_Sign_Text_Window_C, OutText: string)
---@field OnColorSelected fun(self: UMG_Sign_Text_Window_C, Button: UMG_ButtonBase_C?)
---@field ParseText fun(self: UMG_Sign_Text_Window_C, InText: string, Row1: string, Row2: string, Row3: string, Row4: string)
---@field PreConstruct fun(self: UMG_Sign_Text_Window_C, IsDesignTime: boolean)
---@field ProxyUpdateIcon fun(self: UMG_Sign_Text_Window_C, IconRow: ItemableRowHandle|{})
---@field ProxyUpdateText fun(self: UMG_Sign_Text_Window_C, Text: string)
---@field SetFontColor fun(self: UMG_Sign_Text_Window_C, Color: LinearColor|{})
---@field UpdateIconList fun(self: UMG_Sign_Text_Window_C, Items: Object[])
