---@meta _
-- Generated by scripts\gameindex.py from the index of the game's classes. Changes here are lost on the next run.

---@class BPQ_BW6_Survey_Travel_C : BPQ_Travel_C
---@field Setup fun(self: BPQ_BW6_Survey_Travel_C, bFirstTime: boolean)

---@class BP_BW3_CollectTusk_C : Quest
---@field Collected boolean
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW3_CollectTusk_C): boolean
---@field RunOperations fun(self: BP_BW3_CollectTusk_C, DeltaSeconds: number)

---@class BP_BW3_KillMammoth_C : Quest
---@field BossSpawner BP_ManualAISpawnPoint_C
---@field DefaultSceneRoot SceneComponent
---@field IcarusMapIcon IcarusMapIconComponent
---@field Check fun(self: BP_BW3_KillMammoth_C): boolean
---@field Cleanup fun(self: BP_BW3_KillMammoth_C)
---@field OnCreatureKilledNotify_Event_0 fun(self: BP_BW3_KillMammoth_C, Player: IcarusPlayerCharacter?, Causer: IcarusActor?, Creature: Actor?, KillingBlowFromPawn: Pawn?)
---@field Setup fun(self: BP_BW3_KillMammoth_C, bFirstTime: boolean)

---@class BP_BW3_Mammoth_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW3_Mammoth_C): boolean
---@field RunFlow fun(self: BP_BW3_Mammoth_C)

---@class BP_BW4_Activate_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW4_Activate_C): boolean
---@field OnInteract fun(self: BP_BW4_Activate_C)
---@field Setup fun(self: BP_BW4_Activate_C, bFirstTime: boolean)
---@field TriggerActivateDialogue fun(self: BP_BW4_Activate_C)

---@class BP_BW4_Collect_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW4_Collect_C): boolean
---@field Setup fun(self: BP_BW4_Collect_C, bFirstTime: boolean)
---@field TriggerCollectDialogue fun(self: BP_BW4_Collect_C)

---@class BP_BW4_Progress_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field ["Delta Seconds"] number
---@field ["Enemy Spawn"] Vector
---@field EpicCreature EpicCreaturesRowHandle
---@field HostileTargetLocationKey string
---@field InRange boolean
---@field MaxScanTime number
---@field Target Actor
---@field Check fun(self: BP_BW4_Progress_C): boolean
---@field GetDescription fun(self: BP_BW4_Progress_C, InDescription: string, OutDescription: string, bOutComplete: boolean)
---@field RunOperations fun(self: BP_BW4_Progress_C, DeltaSeconds: number)
---@field Setup fun(self: BP_BW4_Progress_C, bFirstTime: boolean)
---@field TriggerAIEvent fun(self: BP_BW4_Progress_C)
---@field TriggerBossDeathDialogue fun(self: BP_BW4_Progress_C, ActorState: ActorState?)
---@field TriggerBossSpawnDialogue fun(self: BP_BW4_Progress_C)
---@field TriggerEndDialogue fun(self: BP_BW4_Progress_C)

---@class BP_BW4_Satellite_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW4_Satellite_C): boolean
---@field ["Get Satellites Finished"] fun(self: BP_BW4_Satellite_C, Count: integer)
---@field RunFlow fun(self: BP_BW4_Satellite_C)
---@field Setup fun(self: BP_BW4_Satellite_C, bFirstTime: boolean)

---@class BP_BW4_Satellite_Object_C : BP_WorldObject_C
---@field BP_UIProjectionComponent BP_UIProjectionComponent_C
---@field BP_UIProjectionLocation BP_UIProjectionLocation_C
---@field ["Core Material"] MaterialInstanceDynamic
---@field Cylinder StaticMeshComponent
---@field Cylinder1 StaticMeshComponent
---@field DefenceAudioComponent FMODAudioComponent
---@field DefendComplete boolean
---@field EnterAudioTrigger SphereComponent
---@field FMODEvent_ArmInteraction FMODEvent
---@field FMODEvent_DefenseTimerEnded FMODEvent
---@field FMODEvent_NeedleRemoved FMODEvent
---@field FlickerTimeline TimelineComponent
---@field FlickerTimeline_NewTrack_0_5897F4764DDE427A04175AB479BDCF16 number
---@field FlickerTimeline__Direction_5897F4764DDE427A04175AB479BDCF16 ETimelineDirection
---@field IcarusMapIcon IcarusMapIconComponent
---@field IcarusNavigationDirtier IcarusNavigationDirtier
---@field Inventory InventoryComponent
---@field IsArmed boolean
---@field LastInteractedPlayer IcarusPlayerCharacter
---@field Material1 MaterialInstanceDynamic
---@field Material2 MaterialInstanceDynamic
---@field NS_FactionSatellite_FX NiagaraComponent
---@field NS_FactionSatellite_V2_FX NiagaraComponent
---@field NS_FactionSatellite_V2_FX1 NiagaraComponent
---@field PointLight PointLightComponent
---@field PointLight1 PointLightComponent
---@field PointLight2 PointLightComponent
---@field PointLight3 PointLightComponent
---@field PointLight4 PointLightComponent
---@field PointLight5 PointLightComponent
---@field SM_DPS_Satellite_INARIS_Crashed_CF_Chute StaticMeshComponent
---@field SM_DPS_Satellite_INARIS_Crashed_CF_Chute2 StaticMeshComponent
---@field SM_DPS_Satellite_INARIS_Crashed_CF_CoreInt SkeletalMeshComponent
---@field SM_DPS_Satellite_INARIS_Crashed_CF_Ground StaticMeshComponent
---@field SM_ROCK_CF_SML_01 StaticMeshComponent
---@field SM_ROCK_CF_SML_010 StaticMeshComponent
---@field SM_ROCK_CF_SML_011 StaticMeshComponent
---@field SM_ROCK_CF_SML_012 StaticMeshComponent
---@field SM_ROCK_CF_SML_02 StaticMeshComponent
---@field SM_ROCK_CF_SML_03 StaticMeshComponent
---@field SM_ROCK_CF_SML_04 StaticMeshComponent
---@field SM_ROCK_CF_SML_05 StaticMeshComponent
---@field SM_ROCK_CF_SML_06 StaticMeshComponent
---@field SM_ROCK_CF_SML_07 StaticMeshComponent
---@field SM_ROCK_CF_SML_08 StaticMeshComponent
---@field SM_ROCK_CF_SML_09 StaticMeshComponent
---@field SM_ROCK_CF_Stone_01 StaticMeshComponent
---@field StatUID integer
---@field StaticMesh StaticMeshComponent
---@field ActivatedStateUpdated fun(self: BP_BW4_Satellite_Object_C, Activated: boolean, Defending: boolean)
---@field FlickerTimeline__FinishedFunc fun(self: BP_BW4_Satellite_Object_C)
---@field FlickerTimeline__UpdateFunc fun(self: BP_BW4_Satellite_Object_C)
---@field IsFunctional fun(self: BP_BW4_Satellite_Object_C, bFunctional: boolean)
---@field MULTI_PlayWarheadRemovedFX fun(self: BP_BW4_Satellite_Object_C)
---@field OnInventoryItemRemoved fun(self: BP_BW4_Satellite_Object_C, Inventory: Inventory?, Location: integer, Item: ItemData|{})
---@field OnRep_DefendComplete fun(self: BP_BW4_Satellite_Object_C)
---@field OnRep_IsArmed fun(self: BP_BW4_Satellite_Object_C)
---@field PlaySFX fun(self: BP_BW4_Satellite_Object_C, FMODEvent: FMODEvent?)
---@field ReceiveBeginPlay fun(self: BP_BW4_Satellite_Object_C)
---@field UpdateState fun(self: BP_BW4_Satellite_Object_C)
---@field WorldObject_Interact fun(self: BP_BW4_Satellite_Object_C, Instigator: Actor?)

---@class BP_BW4_Satellites_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW4_Satellites_C): boolean
---@field ["Get Satellites Finished"] fun(self: BP_BW4_Satellites_C, NumberActive: integer)
---@field ReceiveQuestEnded fun(self: BP_BW4_Satellites_C, bWasAbandoned: boolean)
---@field RunFlow fun(self: BP_BW4_Satellites_C)

---@class BP_BW4_Travel_Satellite_C : BP_Quest_TravelLarge_C
---@field Setup fun(self: BP_BW4_Travel_Satellite_C, bFirstTime: boolean)
---@field TriggerReachedDialogue fun(self: BP_BW4_Travel_Satellite_C)

---@class BP_BW5_ActivateDrill_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Drill IcarusActor
---@field Check fun(self: BP_BW5_ActivateDrill_C): boolean

---@class BP_BW5_ActivateRadar_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Drill IcarusActor
---@field Check fun(self: BP_BW5_ActivateRadar_C): boolean

---@class BP_BW5_Blocker_C : Quest
---@field CaveBlocker BP_Faction_Mission_Blocker_C
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW5_Blocker_C): boolean
---@field RunFlow fun(self: BP_BW5_Blocker_C)
---@field Setup fun(self: BP_BW5_Blocker_C, bFirstTime: boolean)

---@class BP_BW5_Boss_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field IcarusMapIcon IcarusMapIconComponent
---@field Check fun(self: BP_BW5_Boss_C): boolean
---@field OnActorDeath fun(self: BP_BW5_Boss_C, ActorState: ActorState?)
---@field OnDamaged fun(self: BP_BW5_Boss_C, ActorState: ActorState?, DamageTaken: integer, DamageEvent: DamageEvent|{}, Instigator: Controller?, DamageCauser: Actor?)
---@field Setup fun(self: BP_BW5_Boss_C, bFirstTime: boolean)

---@class BP_BW5_CollectSamples_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW5_CollectSamples_C): boolean

---@class BP_BW5_CraftBiofuel_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW5_CraftBiofuel_C): boolean

---@class BP_BW5_CraftBossItem_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW5_CraftBossItem_C): boolean

---@class BP_BW5_CraftDrill_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW5_CraftDrill_C): boolean

---@class BP_BW5_CraftRadar_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW5_CraftRadar_C): boolean

---@class BP_BW5_DefendRadar_C : Quest
---@field BreakTime number
---@field BreakTimeMax number
---@field DefaultSceneRoot SceneComponent
---@field ScanTime number
---@field ScanTimeMax number
---@field Check fun(self: BP_BW5_DefendRadar_C): boolean
---@field GetDescription fun(self: BP_BW5_DefendRadar_C, InDescription: string, OutDescription: string, bOutComplete: boolean)
---@field QuestEnded fun(self: BP_BW5_DefendRadar_C)
---@field RadarStopped fun(self: BP_BW5_DefendRadar_C)
---@field RunOperations fun(self: BP_BW5_DefendRadar_C, DeltaSeconds: number)
---@field Setup fun(self: BP_BW5_DefendRadar_C, bFirstTime: boolean)

---@class BP_BW5_DeployDrill_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW5_DeployDrill_C): boolean
---@field DeployableDeployed fun(self: BP_BW5_DeployDrill_C, Player: IcarusPlayerCharacter?, Deployable: IcarusActor?)
---@field Setup fun(self: BP_BW5_DeployDrill_C, bFirstTime: boolean)

---@class BP_BW5_DeployRadar_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW5_DeployRadar_C): boolean
---@field DeployableDeployed fun(self: BP_BW5_DeployRadar_C, Player: IcarusPlayerCharacter?, Deployable: IcarusActor?)
---@field Setup fun(self: BP_BW5_DeployRadar_C, bFirstTime: boolean)

---@class BP_BW5_Quest_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW5_Quest_C): boolean
---@field RunFlow fun(self: BP_BW5_Quest_C)
---@field Setup fun(self: BP_BW5_Quest_C, bFirstTime: boolean)

---@class BP_BW5_Removeblocker_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field GetDescription fun(self: BP_BW5_Removeblocker_C, InDescription: string, OutDescription: string, bOutComplete: boolean)

---@class BP_BW5_Scan_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW5_Scan_C): boolean
---@field RunFlow fun(self: BP_BW5_Scan_C)

---@class BP_BW5_TravelDesert_C : BP_BW5_Travel_C
---@field Setup fun(self: BP_BW5_TravelDesert_C, bFirstTime: boolean)

---@class BP_BW5_TravelScan_C : BP_BW5_Travel_C
---@field Complete_0 boolean
---@field Setup fun(self: BP_BW5_TravelScan_C, bFirstTime: boolean)

---@class BP_BW5_Travel_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Location StaticMeshComponent
---@field Sphere SphereComponent
---@field Check fun(self: BP_BW5_Travel_C): boolean

---@class BP_BW6_Explore_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Explore_C): boolean
---@field Custom fun(self: BP_BW6_Explore_C, Player: IcarusPlayerCharacter?, DropShip: IcarusRocket?)
---@field RunFlow fun(self: BP_BW6_Explore_C)
---@field Setup fun(self: BP_BW6_Explore_C, bFirstTime: boolean)

---@class BP_BW6_Extermination_Boss_C : Quest
---@field BossScaling CurveFloat
---@field BossSpawn SceneComponent
---@field BossSpawner BP_ManualAISpawnPoint_C
---@field DefaultSceneRoot SceneComponent
---@field IcarusMapIcon IcarusMapIconComponent
---@field BossKilled fun(self: BP_BW6_Extermination_Boss_C)
---@field Check fun(self: BP_BW6_Extermination_Boss_C): boolean
---@field Setup fun(self: BP_BW6_Extermination_Boss_C, bFirstTime: boolean)

---@class BP_BW6_Extermination_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Extermination_C): boolean
---@field ReceiveQuestEnded fun(self: BP_BW6_Extermination_C, bWasAbandoned: boolean)
---@field RunFlow fun(self: BP_BW6_Extermination_C)
---@field Setup fun(self: BP_BW6_Extermination_C, bFirstTime: boolean)

---@class BP_BW6_Extermination_Clue1_C : Quest
---@field BPQC_SearchArea BPQC_SearchArea_C
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Extermination_Clue1_C): boolean
---@field RunFlow fun(self: BP_BW6_Extermination_Clue1_C)
---@field Setup fun(self: BP_BW6_Extermination_Clue1_C, bFirstTime: boolean)

---@class BP_BW6_Extermination_Clue2_C : Quest
---@field BPQC_SearchArea BPQC_SearchArea_C
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Extermination_Clue2_C): boolean
---@field RunFlow fun(self: BP_BW6_Extermination_Clue2_C)
---@field Setup fun(self: BP_BW6_Extermination_Clue2_C, bFirstTime: boolean)

---@class BP_BW6_Extermination_Clue3_C : Quest
---@field BPQC_SearchArea BPQC_SearchArea_C
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Extermination_Clue3_C): boolean
---@field RunFlow fun(self: BP_BW6_Extermination_Clue3_C)
---@field Setup fun(self: BP_BW6_Extermination_Clue3_C, bFirstTime: boolean)

---@class BP_BW6_Extermination_Interact_2_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Extermination_Interact_2_C): boolean
---@field OnInteract fun(self: BP_BW6_Extermination_Interact_2_C)
---@field Setup fun(self: BP_BW6_Extermination_Interact_2_C, bFirstTime: boolean)

---@class BP_BW6_Extermination_Interact_3_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Extermination_Interact_3_C): boolean
---@field OnInteract fun(self: BP_BW6_Extermination_Interact_3_C)
---@field Setup fun(self: BP_BW6_Extermination_Interact_3_C, bFirstTime: boolean)

---@class BP_BW6_Extermination_Interact_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Extermination_Interact_C): boolean
---@field OnInteract fun(self: BP_BW6_Extermination_Interact_C)
---@field Setup fun(self: BP_BW6_Extermination_Interact_C, bFirstTime: boolean)

---@class BP_BW6_Extermination_LocateDen_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Extermination_LocateDen_C): boolean
---@field RunFlow fun(self: BP_BW6_Extermination_LocateDen_C)

---@class BP_BW6_Extermination_Nightfall_C : Quest
---@field BPQC_SearchArea BPQC_SearchArea_C
---@field DefaultSceneRoot SceneComponent
---@field ["Delta Seconds"] number
---@field IsNightTime boolean
---@field MaxPlacementDistance number
---@field NightfallFMODEvent FMODEvent
---@field Sphere SphereComponent
---@field UpdateTime number
---@field Check fun(self: BP_BW6_Extermination_Nightfall_C): boolean
---@field DeployableDeployed fun(self: BP_BW6_Extermination_Nightfall_C, Player: IcarusPlayerCharacter?, Deployable: IcarusActor?)
---@field HandleQuestEnded fun(self: BP_BW6_Extermination_Nightfall_C)
---@field MULTI_PlayNightfallSFX fun(self: BP_BW6_Extermination_Nightfall_C)
---@field PlayNightfallSFX fun(self: BP_BW6_Extermination_Nightfall_C)
---@field ReceiveQuestEnded fun(self: BP_BW6_Extermination_Nightfall_C, bWasAbandoned: boolean)
---@field RunOperations fun(self: BP_BW6_Extermination_Nightfall_C, DeltaSeconds: number)
---@field Setup fun(self: BP_BW6_Extermination_Nightfall_C, bFirstTime: boolean)

---@class BP_BW6_Extermination_Travel_C : BP_BW5_Travel_C
---@field ReceiveQuestEnded fun(self: BP_BW6_Extermination_Travel_C, bWasAbandoned: boolean)
---@field Setup fun(self: BP_BW6_Extermination_Travel_C, bFirstTime: boolean)

---@class BP_BW6_Level10_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field UpdateTime number
---@field Check fun(self: BP_BW6_Level10_C): boolean
---@field RunOperations fun(self: BP_BW6_Level10_C, DeltaSeconds: number)

---@class BP_BW6_Recon_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Recon_C): boolean
---@field CompleteAudio fun(self: BP_BW6_Recon_C)
---@field Custom fun(self: BP_BW6_Recon_C, Player: IcarusPlayerCharacter?, DropShip: IcarusRocket?)
---@field MissionComplete fun(self: BP_BW6_Recon_C)
---@field RunFlow fun(self: BP_BW6_Recon_C)
---@field Setup fun(self: BP_BW6_Recon_C, bFirstTime: boolean)

---@class BP_BW6_Recovery_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Recovery_C): boolean
---@field RunFlow fun(self: BP_BW6_Recovery_C)

---@class BP_BW6_Recovery_Collect_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Recovery_Collect_C): boolean

---@class BP_BW6_Recovery_Location1_C : BP_BW6_Recovery_Location_C

---@class BP_BW6_Recovery_Location2_C : BP_BW6_Recovery_Location_C

---@class BP_BW6_Recovery_Location3_C : BP_BW6_Recovery_Location_C

---@class BP_BW6_Recovery_Location_C : Quest
---@field BPQC_SearchArea BPQC_SearchArea_C
---@field ["Container Class"] Class
---@field DefaultSceneRoot SceneComponent
---@field ["Recovered Item"] ItemsStaticRowHandle
---@field SearchAreaRow QuestQueriesRowHandle
---@field Transform Transform
---@field Check fun(self: BP_BW6_Recovery_Location_C): boolean
---@field ReceiveQuestEnded fun(self: BP_BW6_Recovery_Location_C, bWasAbandoned: boolean)
---@field RunFlow fun(self: BP_BW6_Recovery_Location_C)
---@field Setup fun(self: BP_BW6_Recovery_Location_C, bFirstTime: boolean)

---@class BP_BW6_Recovery_Recombine_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Recovery_Recombine_C): boolean
---@field Setup fun(self: BP_BW6_Recovery_Recombine_C, bFirstTime: boolean)

---@class BP_BW6_Recovery_Test_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Recovery_Test_C): boolean
---@field Complete fun(self: BP_BW6_Recovery_Test_C)
---@field Setup fun(self: BP_BW6_Recovery_Test_C, bFirstTime: boolean)

---@class BP_BW6_ScanLocation1_C : BP_BW6_Scan_ScanLocation_C

---@class BP_BW6_ScanLocation2_C : BP_BW6_Scan_ScanLocation_C

---@class BP_BW6_ScanLocation3_C : BP_BW6_Scan_ScanLocation_C

---@class BP_BW6_Scan_ActivateRadar_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Scan_ActivateRadar_C): boolean

---@class BP_BW6_Scan_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field LocationComplete GameDelegate
---@field Check fun(self: BP_BW6_Scan_C): boolean
---@field RunFlow fun(self: BP_BW6_Scan_C)

---@class BP_BW6_Scan_CollectRadar_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Scan_CollectRadar_C): boolean
---@field RunFlow fun(self: BP_BW6_Scan_CollectRadar_C)

---@class BP_BW6_Scan_DeployRadar_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Scan_DeployRadar_C): boolean
---@field OnDeploy fun(self: BP_BW6_Scan_DeployRadar_C, Player: IcarusPlayerCharacter?, Deployable: IcarusActor?)
---@field Setup fun(self: BP_BW6_Scan_DeployRadar_C, bFirstTime: boolean)

---@class BP_BW6_Scan_ProgressScan_C : Quest
---@field AISetup AISetupRowHandle
---@field ["Ai Count"] integer
---@field BreakMaxTime number
---@field BreakTime number
---@field DefaultSceneRoot SceneComponent
---@field ["Delta Seconds"] number
---@field ["Enemy Spawn"] Vector
---@field EventTime number
---@field HostileTargetLocationKey string
---@field MaxEventTime number
---@field MaxScanTime number
---@field ["Snap Actor Suffix"] string
---@field Target Actor
---@field TriggeredEvent boolean
---@field AnimalEventAudio fun(self: BP_BW6_Scan_ProgressScan_C)
---@field Check fun(self: BP_BW6_Scan_ProgressScan_C): boolean
---@field GetDescription fun(self: BP_BW6_Scan_ProgressScan_C, InDescription: string, OutDescription: string, bOutComplete: boolean)
---@field RunOperations fun(self: BP_BW6_Scan_ProgressScan_C, DeltaSeconds: number)
---@field ScanningStoppedAudio fun(self: BP_BW6_Scan_ProgressScan_C)
---@field Setup fun(self: BP_BW6_Scan_ProgressScan_C, bFirstTime: boolean)
---@field TriggerAIEvent fun(self: BP_BW6_Scan_ProgressScan_C)
---@field TriggerBreak fun(self: BP_BW6_Scan_ProgressScan_C)
---@field TriggerWeatherEvent fun(self: BP_BW6_Scan_ProgressScan_C)
---@field WeatherEventAudio fun(self: BP_BW6_Scan_ProgressScan_C)

---@class BP_BW6_Scan_RecoverEquipment_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field AddRadarToInventory fun(self: BP_BW6_Scan_RecoverEquipment_C, Actor: Actor?)
---@field Check fun(self: BP_BW6_Scan_RecoverEquipment_C): boolean
---@field RunFlow fun(self: BP_BW6_Scan_RecoverEquipment_C)
---@field Setup fun(self: BP_BW6_Scan_RecoverEquipment_C, bFirstTime: boolean)

---@class BP_BW6_Scan_RetreiveRadar_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Scan_RetreiveRadar_C): boolean
---@field RunFlow fun(self: BP_BW6_Scan_RetreiveRadar_C)
---@field Setup fun(self: BP_BW6_Scan_RetreiveRadar_C, bFirstTime: boolean)

---@class BP_BW6_Scan_ScanLocation_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field SnapActorSuffix string
---@field Check fun(self: BP_BW6_Scan_ScanLocation_C): boolean
---@field OnBoolVariableUpdated fun(self: BP_BW6_Scan_ScanLocation_C, Name: string, bValue: boolean)
---@field RunFlow fun(self: BP_BW6_Scan_ScanLocation_C)
---@field RunOperations fun(self: BP_BW6_Scan_ScanLocation_C, DeltaSeconds: number)
---@field ScanCompleteAudio fun(self: BP_BW6_Scan_ScanLocation_C)
---@field Setup fun(self: BP_BW6_Scan_ScanLocation_C, bFirstTime: boolean)

---@class BP_BW6_Survey_ActivateRadar1_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Survey_ActivateRadar1_C): boolean

---@class BP_BW6_Survey_ActivateRadar2_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Survey_ActivateRadar2_C): boolean

---@class BP_BW6_Survey_ActivateRadar3_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Survey_ActivateRadar3_C): boolean

---@class BP_BW6_Survey_ActivateTransmitter_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Survey_ActivateTransmitter_C): boolean

---@class BP_BW6_Survey_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Survey_C): boolean
---@field ReceiveQuestEnded fun(self: BP_BW6_Survey_C, bWasAbandoned: boolean)
---@field RunFlow fun(self: BP_BW6_Survey_C)

---@class BP_BW6_Survey_CollectRadar_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Survey_CollectRadar_C): boolean

---@class BP_BW6_Survey_CollectTransmitter_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Survey_CollectTransmitter_C): boolean

---@class BP_BW6_Survey_DefendTransmitter_C : Quest
---@field AbleToTransmit boolean
---@field BPQC_Boss BPQC_AnimalSwarm_C
---@field BPQC_Minons BPQC_AnimalSwarm_C
---@field BPQC_Minons2 BPQC_AnimalSwarm_C
---@field DefaultSceneRoot SceneComponent
---@field SurveyTransmitter BP_SurveyTransmitter_C
---@field Check fun(self: BP_BW6_Survey_DefendTransmitter_C): boolean
---@field ReceiveQuestEnded fun(self: BP_BW6_Survey_DefendTransmitter_C, bWasAbandoned: boolean)
---@field RunFlow fun(self: BP_BW6_Survey_DefendTransmitter_C)
---@field RunOperations fun(self: BP_BW6_Survey_DefendTransmitter_C, DeltaSeconds: number)
---@field Setup fun(self: BP_BW6_Survey_DefendTransmitter_C, bFirstTime: boolean)

---@class BP_BW6_Survey_DeployRadar1_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Survey_DeployRadar1_C): boolean
---@field OnDeployNotify fun(self: BP_BW6_Survey_DeployRadar1_C, Player: IcarusPlayerCharacter?, Deployable: IcarusActor?)
---@field Setup fun(self: BP_BW6_Survey_DeployRadar1_C, bFirstTime: boolean)

---@class BP_BW6_Survey_DeployRadar2_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Survey_DeployRadar2_C): boolean
---@field OnDeployNotify fun(self: BP_BW6_Survey_DeployRadar2_C, Player: IcarusPlayerCharacter?, Deployable: IcarusActor?)
---@field Setup fun(self: BP_BW6_Survey_DeployRadar2_C, bFirstTime: boolean)

---@class BP_BW6_Survey_DeployRadar3_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Survey_DeployRadar3_C): boolean
---@field OnDeployNotify fun(self: BP_BW6_Survey_DeployRadar3_C, Player: IcarusPlayerCharacter?, Deployable: IcarusActor?)
---@field Setup fun(self: BP_BW6_Survey_DeployRadar3_C, bFirstTime: boolean)

---@class BP_BW6_Survey_DeployTransmitter_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Survey_DeployTransmitter_C): boolean
---@field OnDeployNotify fun(self: BP_BW6_Survey_DeployTransmitter_C, Player: IcarusPlayerCharacter?, Deployable: IcarusActor?)
---@field RunOperations fun(self: BP_BW6_Survey_DeployTransmitter_C, DeltaSeconds: number)
---@field Setup fun(self: BP_BW6_Survey_DeployTransmitter_C, bFirstTime: boolean)

---@class BP_BW6_Survey_SetupRadar1_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field IcarusMapIcon IcarusMapIconComponent
---@field SpawnPoint BP_ManualAISpawnPoint_C
---@field Check fun(self: BP_BW6_Survey_SetupRadar1_C): boolean
---@field ReceiveQuestEnded fun(self: BP_BW6_Survey_SetupRadar1_C, bWasAbandoned: boolean)
---@field RunFlow fun(self: BP_BW6_Survey_SetupRadar1_C)
---@field Setup fun(self: BP_BW6_Survey_SetupRadar1_C, bFirstTime: boolean)

---@class BP_BW6_Survey_SetupRadar2_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field IcarusMapIcon IcarusMapIconComponent
---@field SpawnPoint BP_ManualAISpawnPoint_C
---@field Check fun(self: BP_BW6_Survey_SetupRadar2_C): boolean
---@field ReceiveQuestEnded fun(self: BP_BW6_Survey_SetupRadar2_C, bWasAbandoned: boolean)
---@field RunFlow fun(self: BP_BW6_Survey_SetupRadar2_C)
---@field Setup fun(self: BP_BW6_Survey_SetupRadar2_C, bFirstTime: boolean)

---@class BP_BW6_Survey_SetupRadar3_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field IcarusMapIcon IcarusMapIconComponent
---@field SpawnPoint BP_ManualAISpawnPoint_C
---@field Check fun(self: BP_BW6_Survey_SetupRadar3_C): boolean
---@field ReceiveQuestEnded fun(self: BP_BW6_Survey_SetupRadar3_C, bWasAbandoned: boolean)
---@field RunFlow fun(self: BP_BW6_Survey_SetupRadar3_C)
---@field Setup fun(self: BP_BW6_Survey_SetupRadar3_C, bFirstTime: boolean)

---@class BP_BW6_Survey_SetupRadars_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_BW6_Survey_SetupRadars_C): boolean
---@field PlaySetupAudio fun(self: BP_BW6_Survey_SetupRadars_C)
---@field RunFlow fun(self: BP_BW6_Survey_SetupRadars_C)

---@class BP_BW6_Survey_SetupTransmitter_C : BPQ_Retrieve_Item_And_Spawn_Crate_C
---@field Check fun(self: BP_BW6_Survey_SetupTransmitter_C): boolean
---@field CleanupPod fun(self: BP_BW6_Survey_SetupTransmitter_C)
---@field ReceiveQuestEnded fun(self: BP_BW6_Survey_SetupTransmitter_C, bWasAbandoned: boolean)
---@field RunFlow fun(self: BP_BW6_Survey_SetupTransmitter_C)
---@field Setup fun(self: BP_BW6_Survey_SetupTransmitter_C, bFirstTime: boolean)

---@class BP_BW6_Survive_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field UpdateTime number
---@field Check fun(self: BP_BW6_Survive_C): boolean

---@class BP_InteractWithDropship_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_InteractWithDropship_C): boolean
---@field InteractWithShip fun(self: BP_InteractWithDropship_C, Player: IcarusPlayerCharacter?, DropShip: IcarusRocket?)
---@field Setup fun(self: BP_InteractWithDropship_C, bFirstTime: boolean)

---@class BP_Quest_Bw6_Research_AnimalCorpse_1_C : Quest
---@field BPQC_SearchArea BPQC_SearchArea_C
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_Quest_Bw6_Research_AnimalCorpse_1_C): boolean
---@field OnPickedUp fun(self: BP_Quest_Bw6_Research_AnimalCorpse_1_C)
---@field ReceiveQuestEnded fun(self: BP_Quest_Bw6_Research_AnimalCorpse_1_C, bWasAbandoned: boolean)
---@field Setup fun(self: BP_Quest_Bw6_Research_AnimalCorpse_1_C, bFirstTime: boolean)

---@class BP_Quest_Bw6_Research_C : Quest
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_Quest_Bw6_Research_C): boolean
---@field RunFlow fun(self: BP_Quest_Bw6_Research_C)
---@field RunOperations fun(self: BP_Quest_Bw6_Research_C, DeltaSeconds: number)
---@field Setup fun(self: BP_Quest_Bw6_Research_C, bFirstTime: boolean)

---@class BP_Quest_Bw6_Research_Flower_1_C : Quest
---@field BPQC_SearchArea BPQC_SearchArea_C
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_Quest_Bw6_Research_Flower_1_C): boolean
---@field OnPickedUp fun(self: BP_Quest_Bw6_Research_Flower_1_C)
---@field ReceiveQuestEnded fun(self: BP_Quest_Bw6_Research_Flower_1_C, bWasAbandoned: boolean)
---@field Setup fun(self: BP_Quest_Bw6_Research_Flower_1_C, bFirstTime: boolean)

---@class BP_Quest_Bw6_Research_Flower_2_C : Quest
---@field BPQC_SearchArea BPQC_SearchArea_C
---@field DefaultSceneRoot SceneComponent
---@field Check fun(self: BP_Quest_Bw6_Research_Flower_2_C): boolean
---@field OnPickedUp fun(self: BP_Quest_Bw6_Research_Flower_2_C)
---@field ReceiveQuestEnded fun(self: BP_Quest_Bw6_Research_Flower_2_C, bWasAbandoned: boolean)
---@field Setup fun(self: BP_Quest_Bw6_Research_Flower_2_C, bFirstTime: boolean)

---@class BP_Quest_TravelLarge_C : BPQ_Travel_C
