---@meta _
-- Generated by scripts\gameindex.py from the index of the game's classes. Changes here are lost on the next run.

---@class BP_DialogueManager_C : DialogueManager
---@field GetDialogueWidget fun(self: BP_DialogueManager_C, DialogueWidget: UMG_Dialogue_C?)
---@field OnDialogueCleared fun(self: BP_DialogueManager_C)
---@field OnDialoguePlayed fun(self: BP_DialogueManager_C, Dialogue: DialogueRowHandle|{})
