---@meta _
-- Generated by scripts\gameindex.py from the index of the game's classes. Changes here are lost on the next run.

---@class BP_Exotic_Processor_C : BP_ResourceNetworkProcessor_C
---@field BP_IcarusPointLight BP_IcarusPointLight_C
---@field BP_IcarusSpotLight_Red BP_IcarusSpotLight_C
---@field FMODAudio_StartProcessor FMODAudioComponent
---@field IsPlayingAnim boolean
---@field Niagara NiagaraComponent
---@field Scene_Lights SceneComponent
---@field UpdateEffects fun(self: BP_Exotic_Processor_C, EnergyFlowChanged: boolean, ProcessorActiveChanged: boolean)

---@class BP_T3_Cleaning_Device_C : BP_ResourceNetworkProcessor_C
---@field FMODAudio_StartProcessor FMODAudioComponent
---@field Niagara NiagaraComponent
---@field ProcessorStateUpdate fun(self: BP_T3_Cleaning_Device_C, Active: boolean)
---@field UpdateEffects fun(self: BP_T3_Cleaning_Device_C, EnergyFlowChanged: boolean, ProcessorActiveChanged: boolean)
