---@meta _
-- Generated by scripts\gameindex.py from the index of the game's classes. Changes here are lost on the next run.

---@class BPI_LinkedActorInventoryRedirector_C : Interface
---@field GetRedirectedInventoryComponent fun(self: BPI_LinkedActorInventoryRedirector_C, InventoryComponent: InventoryComponent?)
