-- Offline tests for data.journal: layers in mod order, values and functions, leaving, conflicts, what a core restart keeps.
-- Run from the workspace root:  tools\lua\lua54\lua.exe wax\tests\offline\journal_test.lua

local t = dofile("wax/tests/offline/harness.lua")
local Wax = t.new_wax()
local journal = Wax.import("data.journal")
journal.clear()

local function copy(value)
    if type(value) ~= "table" then return value end
    local out = {}
    for key, item in pairs(value) do out[key] = copy(item) end
    return out
end

local function same(a, b)
    if type(a) ~= "table" or type(b) ~= "table" then return a == b end
    for key, item in pairs(a) do
        if not same(item, b[key]) then return false end
    end
    for key in pairs(b) do
        if a[key] == nil then return false end
    end
    return true
end

-- Runs a function step as it is, and counts the calls.
local runs = 0
local function run(_, step, value)
    runs = runs + 1
    return step.change(copy(value))
end

local function result(entry) return journal.result(entry, copy, run, same) end

local RANKS = { A = 1, B = 2, C = 3 }
local function rank(owner) return RANKS[owner] or 100 end

local function owners(entry)
    local out = {}
    for index, layer in ipairs(entry.layers) do out[index] = layer.owner .. (layer.leaving and "?" or "") end
    return table.concat(out, ",")
end

local function fresh(key, original)
    return (journal.open(key, "recipes", { table = "Recipes", row = "Axe", field = key }, original))
end

t.test("an entry keeps the original it was opened with, and is found again by its key", function()
    local entry, made = journal.open("work", "recipes", { field = "Work" }, 2500)
    t.eq(made, true)
    t.eq(entry.original, 2500)
    local again, second = journal.open("work", "recipes", { field = "Work" }, 99)
    t.eq(again, entry, "the same entry")
    t.eq(second, false)
    t.eq(entry.original, 2500, "the original is the first one")
    t.eq(journal.find("work"), entry)
    t.eq(journal.find("nothing"), nil)
    t.eq(result(entry), 2500, "no layer: the original")
    journal.close(entry)
    t.eq(journal.find("work"), nil)
    t.eq(journal.stats().entries, 0)
end)

t.test("a Set is a value, a Change a function of the value below, and they run bottom to top", function()
    local entry = fresh("count", 10)
    journal.push(entry, "A", { set = 4 }, rank)
    t.eq(result(entry), 4)
    journal.push(entry, "B", { change = function(value) return value * 2 end }, rank)
    t.eq(result(entry), 8, "B's function gets A's value")
    journal.push(entry, "A", { set = 5 }, rank)
    t.eq(result(entry), 10, "A set again in its own place, and B's function ran on the new value")
    t.eq(owners(entry), "A,B")
    journal.close(entry)
end)

t.test("one mod's steps pile up in its layer: a Set starts it again, a Change is added", function()
    local entry = fresh("list", { 1 })
    local function add(n) return function(list) list[#list + 1] = n return list end end
    journal.push(entry, "A", { change = add(2) }, rank)
    journal.push(entry, "A", { change = add(3) }, rank)
    t.eq(table.concat(result(entry), ","), "1,2,3")
    t.eq(#entry.layers, 1, "still one layer")
    journal.push(entry, "A", { set = { 9 } }, rank)
    t.eq(table.concat(result(entry), ","), "9", "the Set dropped the two changes before it")
    journal.push(entry, "A", { change = add(8) }, rank)
    t.eq(table.concat(result(entry), ","), "9,8", "a Change after the Set builds on it")
    t.eq(table.concat(entry.original, ","), "1", "the original was never touched")
    journal.close(entry)
end)

t.test("a layer goes where its mod stands in the order, whenever it arrives", function()
    local entry = fresh("order", 0)
    journal.push(entry, "C", { set = 3 }, rank)
    journal.push(entry, "A", { set = 1 }, rank)
    t.eq(owners(entry), "A,C")
    journal.push(entry, "B", { set = 2 }, rank)
    t.eq(owners(entry), "A,B,C")
    t.eq(result(entry), 3, "the last in the order is on top")
    journal.push(entry, "X", { set = 7 }, rank)
    journal.push(entry, "Y", { set = 8 }, rank)
    t.eq(owners(entry), "A,B,C,X,Y", "mods of one rank stay in the order they came")
    journal.push(entry, "Z", { set = 9 })
    t.eq(owners(entry), "A,B,C,X,Y,Z", "no rank given: on top")
    journal.close(entry)
end)

t.test("when the order of the mods changes, the layers of an entry are put in the new order, and equal ranks stay as they stood", function()
    local entry = fresh("moved", 0)
    journal.push(entry, "A", { set = 1 }, rank)
    journal.push(entry, "B", { set = 2 }, rank)
    journal.push(entry, "X", { set = 7 }, rank)
    journal.push(entry, "Y", { set = 8 }, rank)
    t.eq(journal.rank(entry, rank), false, "the same order: nothing moves")
    t.eq(owners(entry), "A,B,X,Y")
    local swapped = { A = 2, B = 1 }
    t.eq(journal.rank(entry, function(owner) return swapped[owner] or 100 end), true)
    t.eq(owners(entry), "B,A,X,Y", "B loads first now, and the two the order does not know stay as they came")
    t.eq(result(entry), 8)
    journal.remove(entry, "X")
    journal.remove(entry, "Y")
    t.eq(result(entry), 1, "A is on top")
    -- a mod that comes in later finds the others at the places they have now, not at the ones they were given once
    local later = { B = 1, C = 2, A = 3 }
    local function now_rank(owner) return later[owner] or 100 end
    journal.rank(entry, now_rank)
    journal.push(entry, "C", { set = 3 }, now_rank)
    t.eq(owners(entry), "B,C,A")
    -- the rank is asked for before the layers are looked at, because the answer may come with a new order for them
    local asked_with = nil
    journal.push(entry, "D", { set = 4 }, function(owner)
        asked_with = owners(entry)
        return 0
    end)
    t.eq(asked_with, "B,C,A", "D was not in yet")
    t.eq(owners(entry), "D,B,C,A")
    journal.close(entry)
end)

t.test("a layer that was taken off can be put back where it stood", function()
    local entry = fresh("back", 1)
    journal.push(entry, "A", { set = 2 }, rank)
    journal.push(entry, "B", { set = 3 }, rank)
    journal.push(entry, "C", { set = 4 }, rank)
    local removed, taken = journal.remove(entry, "B")
    t.eq(removed, true)
    t.eq(owners(entry), "A,C")
    t.eq(#journal.leave("B"), 0, "B is not listed for the key")
    journal.put_back(entry, taken)
    t.eq(owners(entry), "A,B,C")
    t.eq(#journal.leave("B"), 1, "and is again")
    t.eq(owners(entry), "A,B?,C")
    journal.leave("A")
    local dropped
    dropped, taken = journal.drop_leaving(entry)
    t.eq(dropped, 2)
    t.eq(owners(entry), "C")
    journal.put_back(entry, taken)
    t.eq(owners(entry), "A?,B?,C", "both, at their places")
    journal.put_back(entry, taken)
    t.eq(owners(entry), "A?,B?,C", "a layer that is there is not put in twice")
    -- some leaving layers may be kept: those of a mod that is loading again
    dropped, taken = journal.drop_leaving(entry, function(owner) return owner == "A" end)
    t.eq(dropped, 1)
    t.eq(owners(entry), "A?,C")
    t.eq(taken[1].layer.owner, "B")
    journal.close(entry)
    journal.put_back(entry, taken)
    t.eq(#entry.layers, 0, "nothing is put back on an entry that was closed")
    t.eq(journal.stats().owners, 0)
end)

t.test("a mod that leaves and says the same again keeps its place, and its old steps are gone", function()
    local entry = fresh("reload", 1)
    journal.push(entry, "A", { set = 10 }, rank)
    journal.push(entry, "A", { change = function(value) return value + 1 end }, rank)
    journal.push(entry, "B", { change = function(value) return value * 2 end }, rank)
    t.eq(result(entry), 22)
    local keys = journal.leave("A")
    t.eq(#keys, 1)
    t.eq(keys[1], "reload")
    t.eq(owners(entry), "A?,B")
    t.eq(result(entry), 22, "a leaving layer still counts until it is dropped")
    journal.push(entry, "A", { set = 10 }, rank)
    t.eq(owners(entry), "A,B", "back, in the same place")
    t.eq(result(entry), 20, "the change from before the reload is not there any more")
    journal.push(entry, "A", { change = function(value) return value + 1 end }, rank)
    t.eq(result(entry), 22)
    t.eq(journal.drop_leaving(entry), 0, "nothing is leaving")
    journal.close(entry)
end)

t.test("a layer that is still leaving is dropped, and the rest gives the value", function()
    local entry = fresh("gone", 1)
    journal.push(entry, "A", { set = 10 }, rank)
    journal.push(entry, "B", { change = function(value) return value * 2 end }, rank)
    journal.leave("A")
    t.eq(journal.drop_leaving(entry), 1)
    t.eq(owners(entry), "B")
    t.eq(result(entry), 2, "B's function now gets the original")
    journal.leave("B")
    t.eq(journal.drop_leaving(entry), 1)
    t.eq(result(entry), 1)
    t.eq(#entry.layers, 0)
    journal.close(entry)
end)

t.test("leave marks every key of one mod and nobody else's, sorted", function()
    local first, second, third = fresh("b-key", 1), fresh("a-key", 1), fresh("c-key", 1)
    journal.push(first, "A", { set = 2 }, rank)
    journal.push(second, "A", { set = 2 }, rank)
    journal.push(third, "B", { set = 2 }, rank)
    local keys = journal.leave("A")
    t.eq(table.concat(keys, ","), "a-key,b-key")
    t.eq(owners(third), "B")
    t.eq(#journal.leave("Nobody"), 0)
    t.eq(journal.remove(first, "A"), true)
    t.eq(journal.remove(first, "A"), false, "it is gone")
    t.eq(#journal.leave("A"), 1, "only the key it is still on")
    for _, entry in ipairs({ first, second, third }) do journal.close(entry) end
    t.eq(journal.stats().owners, 0, "closing takes the owners' index with it")
end)

t.test("a push can be taken back: a new layer goes, a changed one gets its steps and its leaving back", function()
    local entry = fresh("undo", 1)
    local token = journal.push(entry, "A", { set = 5 }, rank)
    journal.restore(token)
    t.eq(#entry.layers, 0)
    t.eq(#journal.leave("A"), 0, "and the mod is not listed for the key")
    journal.push(entry, "A", { set = 5 }, rank)
    token = journal.push(entry, "A", { change = function(value) return value + 1 end }, rank)
    t.eq(result(entry), 6)
    journal.restore(token)
    t.eq(result(entry), 5)
    journal.leave("A")
    token = journal.push(entry, "A", { set = 9 }, rank)
    t.eq(owners(entry), "A")
    journal.restore(token)
    t.eq(owners(entry), "A?", "leaving again")
    t.eq(result(entry), 5, "with the steps it had")
    journal.close(entry)
end)

t.test("a mod may not pile changes on one field without end", function()
    local entry = fresh("many", 0)
    for _ = 1, journal.MAX_STEPS do
        t.ok(journal.push(entry, "A", { change = function(value) return value + 1 end }, rank))
    end
    local token, why = journal.push(entry, "A", { change = function(value) return value + 1 end }, rank)
    t.eq(token, nil)
    t.eq(why, "full")
    t.eq(result(entry), journal.MAX_STEPS)
    t.ok(journal.push(entry, "A", { set = 1 }, rank), "a Set starts the layer again")
    t.eq(result(entry), 1)
    journal.close(entry)
end)

t.test("a Set over another mod's different result is a conflict, and names who is used and who is covered", function()
    local entry = fresh("conflict", { 1 })
    journal.push(entry, "A", { set = { 2 } }, rank)
    local _, conflict = result(entry)
    t.eq(conflict, nil, "one mod alone")
    journal.push(entry, "B", { set = { 3 } }, rank)
    local value
    value, conflict = result(entry)
    t.eq(value[1], 3)
    t.eq(conflict.used, "B")
    t.eq(table.concat(conflict.covered, ","), "A")
    journal.push(entry, "C", { set = { 4 } }, rank)
    value, conflict = result(entry)
    t.eq(value[1], 4)
    t.eq(conflict.used, "C")
    t.eq(table.concat(conflict.covered, ","), "A,B", "everyone below is covered")
    journal.close(entry)
end)

t.test("the same value twice, and a Change on top of a Set, are no conflict", function()
    local entry = fresh("agree", { 1 })
    journal.push(entry, "A", { set = { 2 } }, rank)
    journal.push(entry, "B", { set = { 2 } }, rank)
    local _, conflict = result(entry)
    t.eq(conflict, nil, "two mods that set the same")
    journal.push(entry, "C", { change = function(list) list[2] = 5 return list end }, rank)
    local value
    value, conflict = result(entry)
    t.eq(conflict, nil, "a change builds on what is there")
    t.eq(table.concat(value, ","), "2,5")
    journal.close(entry)
    entry = fresh("build", 1)
    journal.push(entry, "A", { change = function(value) return value + 1 end }, rank)
    journal.push(entry, "B", { set = 9 }, rank)
    _, conflict = result(entry)
    t.eq(conflict.used, "B", "a Set over another mod's change hides it")
    t.eq(conflict.covered[1], "A")
    journal.close(entry)
end)

t.test("a leaving layer and a quiet one are in no conflict", function()
    local entry = fresh("quiet", 1)
    journal.push(entry, "A", { set = 2 }, rank)
    journal.push(entry, "B", { set = 3 }, rank)
    journal.leave("A")
    local value, conflict = result(entry)
    t.eq(value, 3)
    t.eq(conflict, nil, "A is on its way out")
    journal.drop_leaving(entry)
    local token = journal.push(entry, "(off)", { set = 0 })
    token.layer.quiet = true
    value, conflict = result(entry)
    t.eq(value, 0, "the quiet layer is on top")
    t.eq(conflict, nil, "and hides B without a conflict")
    journal.close(entry)
end)

t.test("a function that returns nothing leaves the value as it is, and functions are run each time", function()
    local entry = fresh("skip", 5)
    journal.push(entry, "A", { change = function() return nil end }, rank)
    journal.push(entry, "B", { change = function(value) return value + 1 end }, rank)
    local before = runs
    t.eq(result(entry), 6)
    t.eq(runs, before + 2)
    t.eq(result(entry), 6)
    t.eq(runs, before + 4, "nothing is kept between two asks")
    journal.close(entry)
end)

t.test("entries are listed by table, sorted, and the tables that have any are named", function()
    local first = journal.open("z", "recipes", {}, 1)
    local second = journal.open("a", "recipes", {}, 1)
    local third = journal.open("m", "items", {}, 1)
    local list = journal.entries("recipes")
    t.eq(#list, 2)
    t.eq(list[1], second)
    t.eq(list[2], first)
    t.eq(#journal.entries("items"), 1)
    t.eq(#journal.entries("nothing"), 0)
    t.eq(#journal.entries(), 3)
    t.eq(table.concat(journal.groups(), ","), "items,recipes")
    journal.close(third)
    t.eq(table.concat(journal.groups(), ","), "recipes")
    journal.close(first)
    journal.close(second)
end)

t.test("rows mods added are kept by key, listed by table, and leave with their mod", function()
    local row = journal.add_row("recipes\0a_axe", { group = "recipes", table = "Recipes", row = "A_Axe", owner = "A" })
    journal.add_row("items\0b_plank", { group = "items", table = "Items", row = "B_Plank", owner = "B" })
    t.eq(journal.row("recipes\0a_axe"), row)
    t.eq(row.key, "recipes\0a_axe")
    t.eq(#journal.rows(), 2)
    t.eq(#journal.rows("recipes"), 1)
    t.eq(journal.rows()[1].row, "B_Plank", "sorted by key")
    local _, rows = journal.leave("A")
    t.eq(#rows, 1)
    t.eq(row.leaving, true)
    row.leaving, row.retired = false, true
    _, rows = journal.leave("A")
    t.eq(#rows, 0, "a row that is switched off already is not leaving again")
    journal.remove_row("recipes\0a_axe")
    journal.remove_row("items\0b_plank")
    t.eq(#journal.rows(), 0)
end)

t.test("a table's change count only goes up, and a thing is said once", function()
    t.eq(journal.count("recipes"), 0)
    t.eq(journal.bump("recipes"), 1)
    t.eq(journal.bump("recipes"), 2)
    t.eq(journal.count("recipes"), 2)
    t.eq(journal.count("items"), 0)
    t.eq(journal.first("A and B on Axe"), true)
    t.eq(journal.first("A and B on Axe"), false)
    t.eq(journal.first("something else"), true)
end)

t.test("the entries of one row are found by the start of their keys, and what is on its way out or owed is listed", function()
    local first = journal.open("recipes\0axe\0Inputs", "recipes", {}, 1)
    local second = journal.open("recipes\0axe\0Work", "recipes", {}, 1)
    local third = journal.open("recipes\0axe_long\0Work", "recipes", {}, 1)
    local other = journal.open("items\0axe\0Work", "items", {}, 1)
    local found = journal.under("recipes", "recipes\0axe\0")
    t.eq(#found, 2, "the two fields of Axe, and not those of a row whose name begins the same")
    t.ok((found[1] == first and found[2] == second) or (found[1] == second and found[2] == first))
    t.eq(#journal.under("nothing", "recipes\0axe\0"), 0)
    journal.push(first, "A", { set = 2 }, rank)
    journal.push(second, "A", { set = 2 }, rank)
    journal.push(third, "B", { set = 2 }, rank)
    t.eq(#journal.pending(), 0, "nothing is leaving")
    journal.leave("B")
    other.owed = true
    t.eq(table.concat(journal.pending(), ","), "items\0axe\0Work,recipes\0axe_long\0Work", "sorted: a leaving layer, and a put-back that is owed")
    t.eq(table.concat(journal.owners(), ","), "A,B")
    local row = journal.add_row("recipes\0c_axe", { group = "recipes", table = "Recipes", row = "C_Axe", owner = "C" })
    t.eq(table.concat(journal.owners(), ","), "A,B,C", "a mod that only added a row has something standing too")
    row.retired = true
    t.eq(table.concat(journal.owners(), ","), "A,B", "but not once the row is switched off")
    journal.remove_row("recipes\0c_axe")
    for _, entry in ipairs({ first, second, third, other }) do journal.close(entry) end
end)

t.test("the names of enums are kept where the journal is, so another core finds them", function()
    local enums = journal.enums()
    t.eq(journal.enums(), enums, "one table")
    enums["/Script/Icarus.Recipe:Mode"] = { names = { "Slow" } }
    local other = t.new_wax().import("data.journal")
    t.eq(other.enums()["/Script/Icarus.Recipe:Mode"].names[1], "Slow")
    enums["/Script/Icarus.Recipe:Mode"] = nil
end)

t.test("the journal outlives the core: another core finds it, and what mods changed in it is leaving", function()
    local entry = fresh("kept", 1)
    journal.push(entry, "A", { set = 2 }, rank)
    journal.push(entry, "B", { set = 3 }, rank)
    -- a row that was switched off: the layer that does it belongs to no mod
    local off = fresh("off", false)
    journal.push(off, "(off)", { set = true }).layer.quiet = true
    off.applied = true
    local row = journal.add_row("recipes\0a_axe", { group = "recipes", table = "Recipes", row = "A_Axe", owner = "A" })
    local keys = journal.adopt(Wax)
    t.eq(#keys, 0, "the first core to come takes it as it is")
    t.eq(owners(entry), "A,B")
    t.eq(#(journal.adopt(Wax)), 0, "the same core again: nothing happens")
    local second = t.new_wax()
    local again = second.import("data.journal")
    t.ok(again ~= journal, "another module in another core")
    t.eq(again.find("kept"), entry, "with the same entries")
    t.eq(again.count("recipes"), 2, "and the same counts")
    local rows
    keys, rows = again.adopt(second)
    t.eq(table.concat(keys, ","), "kept,off", "every key is looked at")
    t.eq(#rows, 1)
    t.eq(owners(entry), "A?,B?", "the mods of the core before are gone")
    t.eq(owners(off), "(off)", "the layer that switches a row off is not leaving")
    t.eq(off.applied, nil, "and its field is read from the game again, in case the game no longer holds it")
    t.eq(result(off), true)
    t.eq(row.leaving, true)
    again.push(entry, "A", { set = 2 }, rank)
    t.eq(owners(entry), "A,B?", "a mod that loads again in the new core takes its place back")
    again.remove_row("recipes\0a_axe")
    again.close(entry)
    again.close(off)
end)

t.test("clear forgets everything but the names of enums, which hold while the game runs", function()
    local entry = fresh("temp", 1)
    journal.push(entry, "A", { set = 2 }, rank)
    journal.enums()["/Script/Icarus.Recipe:Mode"] = { names = { "Slow" } }
    journal.clear()
    t.eq(journal.enums()["/Script/Icarus.Recipe:Mode"].names[1], "Slow")
    journal.enums()["/Script/Icarus.Recipe:Mode"] = nil
    t.eq(journal.find("temp"), nil)
    local stats = journal.stats()
    t.eq(stats.entries + stats.layers + stats.rows + stats.owners + stats.tables, 0)
    t.eq(journal.count("recipes"), 0)
    t.eq(journal.first("A and B on Axe"), true, "what was said is forgotten too")
end)

t.finish("journal")
