#!/usr/bin/env node
// Editor setup for writing Wax mods: node wax/cli/editor.mjs
// Writes a .luarc.json into every mod folder (so each mod is checked on its own, seeing only the mods it depends on),
// Wax.code-workspace (open that in VS Code for per-mod checking), and wax/types/lua_basic.lua (Lua's built-ins
// without print and require, which mean something else inside a mod).
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { ROOT } from './bridge.mjs';
import { scanMods } from './mods.mjs';
// Shared with the VS Code extension, which writes the same file on a player's machine.
import luarc from '../vscode/lib/luarc.js';

const TYPES = path.join(ROOT, 'wax', 'types');
const PLUGIN = path.join(ROOT, 'wax', 'lsp', 'plugin.lua');
const SERVER = path.join(ROOT, 'tools', 'lua', 'lua-language-server', 'bin', 'lua-language-server.exe');

const relative = (from, to) => path.relative(from, to).split(path.sep).join('/');

// Lua's own definitions as the installed server generates them, minus the two functions Wax replaces.
function writeBasics() {
  if (!fs.existsSync(SERVER)) return 'skipped (language server not installed; run scripts\\Get-Tools.ps1)';
  const scratch = fs.mkdtempSync(path.join(os.tmpdir(), 'wax-editor-'));
  const empty = path.join(scratch, 'empty');
  fs.mkdirSync(empty);
  try {
    execFileSync(SERVER, ['--check', empty, '--metapath', path.join(scratch, 'meta'), '--logpath', path.join(scratch, 'log')], { stdio: 'ignore' });
  } catch {}
  const folder = fs.readdirSync(path.join(scratch, 'meta')).find((name) => name.startsWith('Lua 5.4'));
  if (!folder) return 'skipped (the server did not write its definitions)';
  const lines = fs.readFileSync(path.join(scratch, 'meta', folder, 'basic.lua'), 'utf8').split(/\r?\n/);
  const kept = [];
  for (const line of lines) {
    if (/^function (print|require)\(/.test(line)) {
      // drop the function and the comment block above it
      while (kept.length && kept[kept.length - 1].startsWith('---')) kept.pop();
      continue;
    }
    kept.push(line);
  }
  const header = '-- Generated by wax/cli/editor.mjs from the language server\'s own definitions; print and require are in mod.lua.\n';
  fs.writeFileSync(path.join(TYPES, 'lua_basic.lua'), header + kept.join('\n').replace(/\n{3,}/g, '\n\n'));
  fs.rmSync(scratch, { recursive: true, force: true });
  return `written (${kept.length} lines)`;
}

const { mods } = scanMods();
const folders = new Map(mods.map((mod) => [mod.id, mod.dir]));
for (const mod of mods) {
  luarc.write(mod.dir, luarc.settingsFor({ dir: mod.dir, types: TYPES, plugin: PLUGIN, mods: folders }));
  luarc.writeFiles(mod.dir, mod.files);
}

// Mod folders first: the server gives a file to the first folder that contains it.
const workspace = {
  folders: [...mods.map((mod) => ({ name: `mod: ${mod.id}`, path: relative(ROOT, mod.dir) })), { name: 'IcarusModding', path: '.' }],
  settings: {},
};
fs.writeFileSync(path.join(ROOT, 'Wax.code-workspace'), JSON.stringify(workspace, null, 2) + '\n');

console.log(`lua_basic.lua: ${writeBasics()}`);
console.log(`${mods.length} mod folder(s) given a .luarc.json: ${mods.map((mod) => mod.id).join(', ') || 'none'}`);
console.log('Wax.code-workspace written. Open it in VS Code to have each mod checked on its own.');
