---@meta _
-- Generated by scripts\gameindex.py from the game's object dump. Changes here are lost on the next run.

---@class AdvancedExternalUILibrary : BlueprintFunctionLibrary
---@field CloseWebURLUI fun(self: AdvancedExternalUILibrary)
---@field ShowAccountUpgradeUI fun(self: AdvancedExternalUILibrary, PlayerRequestingAccountUpgradeUI: BPUniqueNetId|{}, Result: EBlueprintResultSwitch)
---@field ShowFriendsUI fun(self: AdvancedExternalUILibrary, PlayerController: PlayerController?, Result: EBlueprintResultSwitch)
---@field ShowInviteUI fun(self: AdvancedExternalUILibrary, PlayerController: PlayerController?, Result: EBlueprintResultSwitch)
---@field ShowLeaderBoardUI fun(self: AdvancedExternalUILibrary, LeaderboardName: string, Result: EBlueprintResultSwitch)
---@field ShowProfileUI fun(self: AdvancedExternalUILibrary, PlayerViewingProfile: BPUniqueNetId|{}, PlayerToViewProfileOf: BPUniqueNetId|{}, Result: EBlueprintResultSwitch)
---@field ShowWebURLUI fun(self: AdvancedExternalUILibrary, URLToShow: string, Result: EBlueprintResultSwitch, AllowedDomains: string[], bEmbedded: boolean, bShowBackground: boolean, bShowCloseButton: boolean, OffsetX: integer, OffsetY: integer, SizeX: integer, SizeY: integer)

---@class AdvancedFriendsLibrary : BlueprintFunctionLibrary
---@field GetFriend fun(self: AdvancedFriendsLibrary, PlayerController: PlayerController?, FriendUniqueNetId: BPUniqueNetId|{}, Friend: BPFriendInfo|{})
---@field GetStoredFriendsList fun(self: AdvancedFriendsLibrary, PlayerController: PlayerController?, FriendsList: BPFriendInfo[])
---@field GetStoredRecentPlayersList fun(self: AdvancedFriendsLibrary, UniqueNetId: BPUniqueNetId|{}, PlayersList: BPOnlineRecentPlayer[])
---@field IsAFriend fun(self: AdvancedFriendsLibrary, PlayerController: PlayerController?, UniqueNetId: BPUniqueNetId|{}, IsFriend: boolean)
---@field SendSessionInviteToFriend fun(self: AdvancedFriendsLibrary, PlayerController: PlayerController?, FriendUniqueNetId: BPUniqueNetId|{}, Result: EBlueprintResultSwitch)
---@field SendSessionInviteToFriends fun(self: AdvancedFriendsLibrary, PlayerController: PlayerController?, Friends: BPUniqueNetId[], Result: EBlueprintResultSwitch)

---@class AdvancedIdentityLibrary : BlueprintFunctionLibrary
---@field GetAllUserAccounts fun(self: AdvancedIdentityLibrary, AccountInfos: BPUserOnlineAccount[], Result: EBlueprintResultSwitch)
---@field GetLoginStatus fun(self: AdvancedIdentityLibrary, UniqueNetId: BPUniqueNetId|{}, LoginStatus: EBPLoginStatus, Result: EBlueprintResultSwitch)
---@field GetPlayerAuthToken fun(self: AdvancedIdentityLibrary, PlayerController: PlayerController?, AuthToken: string, Result: EBlueprintResultSwitch)
---@field GetPlayerNickname fun(self: AdvancedIdentityLibrary, UniqueNetId: BPUniqueNetId|{}, PlayerNickname: string)
---@field GetUserAccount fun(self: AdvancedIdentityLibrary, UniqueNetId: BPUniqueNetId|{}, AccountInfo: BPUserOnlineAccount|{}, Result: EBlueprintResultSwitch)
---@field GetUserAccountAccessToken fun(self: AdvancedIdentityLibrary, AccountInfo: BPUserOnlineAccount|{}, AccessToken: string)
---@field GetUserAccountAttribute fun(self: AdvancedIdentityLibrary, AccountInfo: BPUserOnlineAccount|{}, AttributeName: string, AttributeValue: string, Result: EBlueprintResultSwitch)
---@field GetUserAccountAuthAttribute fun(self: AdvancedIdentityLibrary, AccountInfo: BPUserOnlineAccount|{}, AttributeName: string, AuthAttribute: string, Result: EBlueprintResultSwitch)
---@field GetUserAccountDisplayName fun(self: AdvancedIdentityLibrary, AccountInfo: BPUserOnlineAccount|{}, DisplayName: string)
---@field GetUserAccountRealName fun(self: AdvancedIdentityLibrary, AccountInfo: BPUserOnlineAccount|{}, UserName: string)
---@field GetUserID fun(self: AdvancedIdentityLibrary, AccountInfo: BPUserOnlineAccount|{}, UniqueNetId: BPUniqueNetId|{})
---@field SetUserAccountAttribute fun(self: AdvancedIdentityLibrary, AccountInfo: BPUserOnlineAccount|{}, AttributeName: string, NewAttributeValue: string, Result: EBlueprintResultSwitch)

---@class AdvancedSessionsLibrary : BlueprintFunctionLibrary
---@field AddOrModifyExtraSettings fun(self: AdvancedSessionsLibrary, SettingsArray: SessionPropertyKeyPair[], NewOrChangedSettings: SessionPropertyKeyPair[], ModifiedSettingsArray: SessionPropertyKeyPair[])
---@field BanPlayer fun(self: AdvancedSessionsLibrary, WorldContextObject: Object?, PlayerToBan: PlayerController?, BanReason: string): boolean
---@field EqualEqual_UNetIDUnetID fun(self: AdvancedSessionsLibrary, A: BPUniqueNetId|{}, B: BPUniqueNetId|{}): boolean
---@field FindSessionPropertyByName fun(self: AdvancedSessionsLibrary, ExtraSettings: SessionPropertyKeyPair[], SettingsName: string, Result: EBlueprintResultSwitch, OutProperty: SessionPropertyKeyPair|{})
---@field FindSessionPropertyIndexByName fun(self: AdvancedSessionsLibrary, ExtraSettings: SessionPropertyKeyPair[], SettingName: string, Result: EBlueprintResultSwitch, OutIndex: integer)
---@field GetCurrentSessionID_AsString fun(self: AdvancedSessionsLibrary, WorldContextObject: Object?, SessionId: string)
---@field GetCurrentUniqueBuildID fun(self: AdvancedSessionsLibrary, UniqueBuildId: integer)
---@field GetExtraSettings fun(self: AdvancedSessionsLibrary, SessionResult: BlueprintSessionResult|{}, ExtraSettings: SessionPropertyKeyPair[])
---@field GetNetPlayerIndex fun(self: AdvancedSessionsLibrary, PlayerController: PlayerController?, NetPlayerIndex: integer)
---@field GetNumberOfNetworkPlayers fun(self: AdvancedSessionsLibrary, WorldContextObject: Object?, NumNetPlayers: integer)
---@field GetPlayerName fun(self: AdvancedSessionsLibrary, PlayerController: PlayerController?, PlayerName: string)
---@field GetSessionID_AsString fun(self: AdvancedSessionsLibrary, SessionResult: BlueprintSessionResult|{}, SessionId: string)
---@field GetSessionPropertyBool fun(self: AdvancedSessionsLibrary, ExtraSettings: SessionPropertyKeyPair[], SettingName: string, SearchResult: ESessionSettingSearchResult, SettingValue: boolean)
---@field GetSessionPropertyByte fun(self: AdvancedSessionsLibrary, ExtraSettings: SessionPropertyKeyPair[], SettingName: string, SearchResult: ESessionSettingSearchResult, SettingValue: integer)
---@field GetSessionPropertyFloat fun(self: AdvancedSessionsLibrary, ExtraSettings: SessionPropertyKeyPair[], SettingName: string, SearchResult: ESessionSettingSearchResult, SettingValue: number)
---@field GetSessionPropertyInt fun(self: AdvancedSessionsLibrary, ExtraSettings: SessionPropertyKeyPair[], SettingName: string, SearchResult: ESessionSettingSearchResult, SettingValue: integer)
---@field GetSessionPropertyKey fun(self: AdvancedSessionsLibrary, SessionProperty: SessionPropertyKeyPair|{}): string
---@field GetSessionPropertyString fun(self: AdvancedSessionsLibrary, ExtraSettings: SessionPropertyKeyPair[], SettingName: string, SearchResult: ESessionSettingSearchResult, SettingValue: string)
---@field GetSessionSettings fun(self: AdvancedSessionsLibrary, WorldContextObject: Object?, NumConnections: integer, NumPrivateConnections: integer, bIsLAN: boolean, bIsDedicated: boolean, bAllowInvites: boolean, bAllowJoinInProgress: boolean, bIsAnticheatEnabled: boolean, BuildUniqueID: integer, ExtraSettings: SessionPropertyKeyPair[], Result: EBlueprintResultSwitch)
---@field GetSessionState fun(self: AdvancedSessionsLibrary, WorldContextObject: Object?, SessionState: EBPOnlineSessionState)
---@field GetUniqueBuildID fun(self: AdvancedSessionsLibrary, SessionResult: BlueprintSessionResult|{}, UniqueBuildId: integer)
---@field GetUniqueNetID fun(self: AdvancedSessionsLibrary, PlayerController: PlayerController?, UniqueNetId: BPUniqueNetId|{})
---@field GetUniqueNetIDFromPlayerState fun(self: AdvancedSessionsLibrary, PlayerState: PlayerState?, UniqueNetId: BPUniqueNetId|{})
---@field HasOnlineSubsystem fun(self: AdvancedSessionsLibrary, SubSystemName: string): boolean
---@field IsPlayerInSession fun(self: AdvancedSessionsLibrary, WorldContextObject: Object?, PlayerToCheck: BPUniqueNetId|{}, bIsInSession: boolean)
---@field IsValidSession fun(self: AdvancedSessionsLibrary, SessionResult: BlueprintSessionResult|{}): boolean
---@field IsValidUniqueNetID fun(self: AdvancedSessionsLibrary, UniqueNetId: BPUniqueNetId|{}): boolean
---@field KickPlayer fun(self: AdvancedSessionsLibrary, WorldContextObject: Object?, PlayerToKick: PlayerController?, KickReason: string): boolean
---@field MakeLiteralSessionPropertyBool fun(self: AdvancedSessionsLibrary, Key: string, Value: boolean, Type: EOnlineAdvertisementType): SessionPropertyKeyPair
---@field MakeLiteralSessionPropertyByte fun(self: AdvancedSessionsLibrary, Key: string, Value: integer, Type: EOnlineAdvertisementType): SessionPropertyKeyPair
---@field MakeLiteralSessionPropertyFloat fun(self: AdvancedSessionsLibrary, Key: string, Value: number, Type: EOnlineAdvertisementType): SessionPropertyKeyPair
---@field MakeLiteralSessionPropertyInt fun(self: AdvancedSessionsLibrary, Key: string, Value: integer, Type: EOnlineAdvertisementType): SessionPropertyKeyPair
---@field MakeLiteralSessionPropertyString fun(self: AdvancedSessionsLibrary, Key: string, Value: string, Type: EOnlineAdvertisementType): SessionPropertyKeyPair
---@field MakeLiteralSessionSearchProperty fun(self: AdvancedSessionsLibrary, SessionSearchProperty: SessionPropertyKeyPair|{}, ComparisonOp: EOnlineComparisonOpRedux): SessionsSearchSetting
---@field SetPlayerName fun(self: AdvancedSessionsLibrary, PlayerController: PlayerController?, PlayerName: string)
---@field UniqueNetIdToString fun(self: AdvancedSessionsLibrary, UniqueNetId: BPUniqueNetId|{}, String: string)

---@class AdvancedVoiceLibrary : BlueprintFunctionLibrary
---@field GetNumLocalTalkers fun(self: AdvancedVoiceLibrary, NumLocalTalkers: integer)
---@field IsHeadsetPresent fun(self: AdvancedVoiceLibrary, bHasHeadset: boolean, LocalPlayerNum: integer)
---@field IsLocalPlayerTalking fun(self: AdvancedVoiceLibrary, LocalPlayerNum: integer): boolean
---@field IsPlayerMuted fun(self: AdvancedVoiceLibrary, LocalUserNumChecking: integer, UniqueNetId: BPUniqueNetId|{}): boolean
---@field IsRemotePlayerTalking fun(self: AdvancedVoiceLibrary, UniqueNetId: BPUniqueNetId|{}): boolean
---@field MuteRemoteTalker fun(self: AdvancedVoiceLibrary, LocalUserNum: integer, UniqueNetId: BPUniqueNetId|{}, bIsSystemWide: boolean): boolean
---@field RegisterAllLocalTalkers fun(self: AdvancedVoiceLibrary)
---@field RegisterLocalTalker fun(self: AdvancedVoiceLibrary, LocalPlayerNum: integer): boolean
---@field RegisterRemoteTalker fun(self: AdvancedVoiceLibrary, UniqueNetId: BPUniqueNetId|{}): boolean
---@field RemoveAllRemoteTalkers fun(self: AdvancedVoiceLibrary)
---@field StartNetworkedVoice fun(self: AdvancedVoiceLibrary, LocalPlayerNum: integer)
---@field StopNetworkedVoice fun(self: AdvancedVoiceLibrary, LocalPlayerNum: integer)
---@field UnMuteRemoteTalker fun(self: AdvancedVoiceLibrary, LocalUserNum: integer, UniqueNetId: BPUniqueNetId|{}, bIsSystemWide: boolean): boolean
---@field UnRegisterAllLocalTalkers fun(self: AdvancedVoiceLibrary)
---@field UnRegisterLocalTalker fun(self: AdvancedVoiceLibrary, LocalPlayerNum: integer)
---@field UnRegisterRemoteTalker fun(self: AdvancedVoiceLibrary, UniqueNetId: BPUniqueNetId|{}): boolean

---@class BPFriendInfo
---@field DisplayName string
---@field OnlineState EBPOnlinePresenceState
---@field PresenceInfo BPFriendPresenceInfo
---@field RealName string
---@field UniqueNetId BPUniqueNetId
---@field bIsPlayingSameGame boolean

---@class BPFriendPresenceInfo
---@field PresenceState EBPOnlinePresenceState
---@field StatusString string
---@field bHasVoiceSupport boolean
---@field bIsJoinable boolean
---@field bIsOnline boolean
---@field bIsPlaying boolean
---@field bIsPlayingThisGame boolean

---@class BPOnlineRecentPlayer : BPOnlineUser
---@field LastSeen string

---@class BPOnlineUser
---@field DisplayName string
---@field RealName string
---@field UniqueNetId BPUniqueNetId

---@class BPUniqueNetId

---@class BPUserOnlineAccount

---@class CancelFindSessionsCallbackProxy : OnlineBlueprintCallProxyBase
---@field OnFailure GameDelegate
---@field OnSuccess GameDelegate
---@field CancelFindSessions fun(self: CancelFindSessionsCallbackProxy, WorldContextObject: Object?, PlayerController: PlayerController?): CancelFindSessionsCallbackProxy

---@class CreateSessionCallbackProxyAdvanced : OnlineBlueprintCallProxyBase
---@field OnFailure GameDelegate
---@field OnSuccess GameDelegate
---@field CreateAdvancedSession fun(self: CreateSessionCallbackProxyAdvanced, WorldContextObject: Object?, ExtraSettings: SessionPropertyKeyPair[], PlayerController: PlayerController?, PublicConnections: integer, PrivateConnections: integer, bUseLAN: boolean, bAllowInvites: boolean, bIsDedicatedServer: boolean, bUsePresence: boolean, bUseLobbiesIfAvailable: boolean, bAllowJoinViaPresence: boolean, bAllowJoinViaPresenceFriendsOnly: boolean, bAntiCheatProtected: boolean, bUsesStats: boolean, bShouldAdvertise: boolean, bUseLobbiesVoiceChatIfAvailable: boolean): CreateSessionCallbackProxyAdvanced

---@alias EBPLoginStatus
---| 0 # NotLoggedIn
---| 1 # UsingLocalProfile
---| 2 # LoggedIn
---| integer

---@alias EBPOnlinePresenceState
---| 0 # Online
---| 1 # Offline
---| 2 # Away
---| 3 # ExtendedAway
---| 4 # DoNotDisturb
---| 5 # Chat
---| integer

---@alias EBPOnlineSessionState
---| 0 # NoSession
---| 1 # Creating
---| 2 # Pending
---| 3 # Starting
---| 4 # InProgress
---| 5 # Ending
---| 6 # Ended
---| 7 # Destroying
---| integer

---@alias EBPServerPresenceSearchType
---| 0 # AllServers
---| 1 # ClientServersOnly
---| 2 # DedicatedServersOnly
---| integer

---@alias EBlueprintAsyncResultSwitch
---| 0 # OnSuccess
---| 1 # AsyncLoading
---| 2 # OnFailure
---| integer

---@alias EBlueprintResultSwitch
---| 0 # OnSuccess
---| 1 # OnFailure
---| integer

---@alias EOnlineAdvertisementType
---| 0 # DontAdvertise
---| 1 # ViaPingOnly
---| 2 # ViaOnlineService
---| 3 # ViaOnlineServiceAndPing
---| integer

---@alias EOnlineComparisonOpRedux
---| 0 # Equals
---| 1 # NotEquals
---| 2 # GreaterThan
---| 3 # GreaterThanEquals
---| 4 # LessThan
---| 5 # LessThanEquals
---| integer

---@alias ESessionSettingSearchResult
---| 0 # Found
---| 1 # NotFound
---| 2 # WrongType
---| integer

---@class FindFriendSessionCallbackProxy : OnlineBlueprintCallProxyBase
---@field OnFailure GameDelegate
---@field OnSuccess GameDelegate
---@field FindFriendSession fun(self: FindFriendSessionCallbackProxy, WorldContextObject: Object?, PlayerController: PlayerController?, FriendUniqueNetId: BPUniqueNetId|{}): FindFriendSessionCallbackProxy

---@class FindSessionsCallbackProxyAdvanced : OnlineBlueprintCallProxyBase
---@field OnFailure GameDelegate
---@field OnResultReturned GameDelegate
---@field OnSuccess GameDelegate
---@field FilterSessionResults fun(self: FindSessionsCallbackProxyAdvanced, SessionResults: BlueprintSessionResult[], Filters: SessionsSearchSetting[], FilteredResults: BlueprintSessionResult[])
---@field FindSessionsAdvanced fun(self: FindSessionsCallbackProxyAdvanced, WorldContextObject: Object?, PlayerController: PlayerController?, MaxResults: integer, bUseLAN: boolean, ServerTypeToSearch: EBPServerPresenceSearchType, Filters: SessionsSearchSetting[], bEmptyServersOnly: boolean, bNonEmptyServersOnly: boolean, bSecureServersOnly: boolean, bSearchLobbies: boolean, MinSlotsAvailable: integer): FindSessionsCallbackProxyAdvanced
---@field SessionTick fun(self: FindSessionsCallbackProxyAdvanced, DeltaSeconds: number): boolean

---@class GetFriendsCallbackProxy : OnlineBlueprintCallProxyBase
---@field OnFailure GameDelegate
---@field OnSuccess GameDelegate
---@field GetAndStoreFriendsList fun(self: GetFriendsCallbackProxy, WorldContextObject: Object?, PlayerController: PlayerController?): GetFriendsCallbackProxy

---@class SessionPropertyKeyPair

---@class SessionsSearchSetting

---@class UpdateSessionCallbackProxyAdvanced : OnlineBlueprintCallProxyBase
---@field OnFailure GameDelegate
---@field OnSuccess GameDelegate
---@field UpdateSession fun(self: UpdateSessionCallbackProxyAdvanced, WorldContextObject: Object?, ExtraSettings: SessionPropertyKeyPair[], PublicConnections: integer, PrivateConnections: integer, bUseLAN: boolean, bAllowInvites: boolean, bAllowJoinInProgress: boolean, bRefreshOnlineData: boolean, bIsDedicatedServer: boolean): UpdateSessionCallbackProxyAdvanced
