---@meta _
-- Generated by scripts\gameindex.py from the game's object dump. Changes here are lost on the next run.

---@class OcclusionPluginSourceSettingsBase : Object

---@class ReverbPluginSourceSettingsBase : Object

---@class SoundModulatorBase : Object

---@class SoundfieldEncodingSettingsBase : Object

---@class SpatializationPluginSourceSettingsBase : Object
