---@meta _
-- Generated by scripts\gameindex.py from the game's object dump. Changes here are lost on the next run.

---@class CameraFilmbackSettings
---@field SensorAspectRatio number
---@field SensorHeight number
---@field SensorWidth number

---@class CameraFocusSettings
---@field DebugFocusPlaneColor Color
---@field FocusMethod ECameraFocusMethod
---@field FocusOffset number
---@field FocusSmoothingInterpSpeed number
---@field ManualFocusDistance number
---@field TrackingFocusSettings CameraTrackingFocusSettings
---@field bDrawDebugFocusPlane boolean
---@field bSmoothFocusChanges boolean

---@class CameraLensSettings
---@field DiaphragmBladeCount integer
---@field MaxFStop number
---@field MaxFocalLength number
---@field MinFStop number
---@field MinFocalLength number
---@field MinimumFocusDistance number

---@class CameraRig_Rail : Actor
---@field CurrentPositionOnRail number
---@field RailCameraMount SceneComponent
---@field RailSplineComponent SplineComponent
---@field TransformComponent SceneComponent
---@field bLockOrientationToRail boolean
---@field GetRailSplineComponent fun(self: CameraRig_Rail): SplineComponent

---@class CameraTrackingFocusSettings
---@field ActorToTrack Actor
---@field RelativeOffset Vector
---@field bDrawDebugTrackingFocusPoint boolean

---@alias ECameraFocusMethod
---| 0 # DoNotOverride
---| 1 # Manual
---| 2 # Tracking
---| 3 # Disable
---| 4 # MAX
---| integer
