---@meta _
-- Generated by scripts\gameindex.py from the index of the game's classes. Changes here are lost on the next run.

---@class ClothingAssetBase : Object
---@field AssetGuid Guid
---@field ImportedFilePath string

---@class ClothingInteractor : Object

---@class ClothingSimulationFactory : Object

---@class ClothingSimulationInteractor : Object
---@field ClothingInteractors table<string, ClothingInteractor>
---@field ClothConfigUpdated fun(self: ClothingSimulationInteractor)
---@field DisableGravityOverride fun(self: ClothingSimulationInteractor)
---@field EnableGravityOverride fun(self: ClothingSimulationInteractor, InVector: Vector|{})
---@field GetClothingInteractor fun(self: ClothingSimulationInteractor, ClothingAssetName: string): ClothingInteractor
---@field GetNumCloths fun(self: ClothingSimulationInteractor): integer
---@field GetNumDynamicParticles fun(self: ClothingSimulationInteractor): integer
---@field GetNumIterations fun(self: ClothingSimulationInteractor): integer
---@field GetNumKinematicParticles fun(self: ClothingSimulationInteractor): integer
---@field GetNumSubsteps fun(self: ClothingSimulationInteractor): integer
---@field GetSimulationTime fun(self: ClothingSimulationInteractor): number
---@field PhysicsAssetUpdated fun(self: ClothingSimulationInteractor)
---@field SetAnimDriveSpringStiffness fun(self: ClothingSimulationInteractor, InStiffness: number)
---@field SetNumIterations fun(self: ClothingSimulationInteractor, NumIterations: integer)
---@field SetNumSubsteps fun(self: ClothingSimulationInteractor, NumSubsteps: integer)
