---@meta _
-- Generated by scripts\gameindex.py from the game's object dump. Changes here are lost on the next run.

---@class Box
---@field IsValid integer
---@field Max Vector
---@field Min Vector

---@class Box2D
---@field Max Vector2D
---@field Min Vector2D
---@field bIsValid integer

---@class BoxSphereBounds
---@field BoxExtent Vector
---@field Origin Vector
---@field SphereRadius number

---@class Class : Struct

---@class Color
---@field A integer
---@field B integer
---@field G integer
---@field R integer

---@class DateTime

---@alias EAxis
---| 0 # None
---| 1 # X
---| 2 # Y
---| 3 # Z
---| integer

---@alias EInterpCurveMode
---| 0 # CIM_Linear
---| 1 # CIM_CurveAuto
---| 2 # CIM_Constant
---| 3 # CIM_CurveUser
---| 4 # CIM_CurveBreak
---| 5 # CIM_CurveAutoClamped
---| integer

---@alias ELocalizedTextSourceCategory
---| 0 # Game
---| 1 # Engine
---| 2 # Editor
---| integer

---@alias EMouseCursor
---| 0 # None
---| 1 # Default
---| 2 # TextEditBeam
---| 3 # ResizeLeftRight
---| 4 # ResizeUpDown
---| 5 # ResizeSouthEast
---| 6 # ResizeSouthWest
---| 7 # CardinalCross
---| 8 # Crosshairs
---| 9 # Hand
---| 10 # GrabHand
---| 11 # GrabHandClosed
---| 12 # SlashedCircle
---| 13 # EyeDropper
---| integer

---@alias EPixelFormat
---| 0 # PF_Unknown
---| 1 # PF_A32B32G32R32F
---| 2 # PF_B8G8R8A8
---| 3 # PF_G8
---| 4 # PF_G16
---| 5 # PF_DXT1
---| 6 # PF_DXT3
---| 7 # PF_DXT5
---| 8 # PF_UYVY
---| 9 # PF_FloatRGB
---| 10 # PF_FloatRGBA
---| 11 # PF_DepthStencil
---| 12 # PF_ShadowDepth
---| 13 # PF_R32_FLOAT
---| 14 # PF_G16R16
---| 15 # PF_G16R16F
---| 16 # PF_G16R16F_FILTER
---| 17 # PF_G32R32F
---| 18 # PF_A2B10G10R10
---| 19 # PF_A16B16G16R16
---| 20 # PF_D24
---| 21 # PF_R16F
---| 22 # PF_R16F_FILTER
---| 23 # PF_BC5
---| 24 # PF_V8U8
---| 25 # PF_A1
---| 26 # PF_FloatR11G11B10
---| 27 # PF_A8
---| 28 # PF_R32_UINT
---| 29 # PF_R32_SINT
---| 30 # PF_PVRTC2
---| 31 # PF_PVRTC4
---| 32 # PF_R16_UINT
---| 33 # PF_R16_SINT
---| 34 # PF_R16G16B16A16_UINT
---| 35 # PF_R16G16B16A16_SINT
---| 36 # PF_R5G6B5_UNORM
---| 37 # PF_R8G8B8A8
---| 38 # PF_A8R8G8B8
---| 39 # PF_BC4
---| 40 # PF_R8G8
---| 41 # PF_ATC_RGB
---| 42 # PF_ATC_RGBA_E
---| 43 # PF_ATC_RGBA_I
---| 44 # PF_X24_G8
---| 45 # PF_ETC1
---| 46 # PF_ETC2_RGB
---| 47 # PF_ETC2_RGBA
---| 48 # PF_R32G32B32A32_UINT
---| 49 # PF_R16G16_UINT
---| 50 # PF_ASTC_4x4
---| 51 # PF_ASTC_6x6
---| 52 # PF_ASTC_8x8
---| 53 # PF_ASTC_10x10
---| 54 # PF_ASTC_12x12
---| 55 # PF_BC6H
---| 56 # PF_BC7
---| 57 # PF_R8_UINT
---| 58 # PF_L8
---| 59 # PF_XGXR8
---| 60 # PF_R8G8B8A8_UINT
---| 61 # PF_R8G8B8A8_SNORM
---| 62 # PF_R16G16B16A16_UNORM
---| 63 # PF_R16G16B16A16_SNORM
---| 64 # PF_PLATFORM_HDR_0
---| 65 # PF_PLATFORM_HDR_1
---| 66 # PF_PLATFORM_HDR_2
---| 67 # PF_NV12
---| 68 # PF_R32G32_UINT
---| 69 # PF_ETC2_R11_EAC
---| 70 # PF_ETC2_RG11_EAC
---| integer

---@alias ERangeBoundTypes
---| 0 # Exclusive
---| 1 # Inclusive
---| 2 # Open
---| integer

---@alias ESearchCase
---| 0 # CaseSensitive
---| 1 # IgnoreCase
---| integer

---@alias ESearchDir
---| 0 # FromStart
---| 1 # FromEnd
---| integer

---@class Enum : Field

---@class Field : Object

---@class FloatInterval
---@field Max number
---@field Min number

---@class FloatRange
---@field LowerBound FloatRangeBound
---@field UpperBound FloatRangeBound

---@class FloatRangeBound
---@field Type ERangeBoundTypes
---@field Value number

---@class FrameNumber
---@field Value integer

---@class FrameNumberRange
---@field LowerBound FrameNumberRangeBound
---@field UpperBound FrameNumberRangeBound

---@class FrameNumberRangeBound
---@field Type ERangeBoundTypes
---@field Value FrameNumber

---@class FrameRate
---@field Denominator integer
---@field Numerator integer

---@class FrameTime
---@field FrameNumber FrameNumber
---@field SubFrame number

---@class Function : Struct

---@class Guid
---@field A integer
---@field B integer
---@field C integer
---@field D integer

---@class Int32Interval
---@field Max integer
---@field Min integer

---@class Int32Range
---@field LowerBound Int32RangeBound
---@field UpperBound Int32RangeBound

---@class Int32RangeBound
---@field Type ERangeBoundTypes
---@field Value integer

---@class IntPoint
---@field X integer
---@field Y integer

---@class IntVector
---@field X integer
---@field Y integer
---@field Z integer

---@class Interface : Object

---@class InterpCurveFloat
---@field LoopKeyOffset number
---@field Points InterpCurvePointFloat[]
---@field bIsLooped boolean

---@class InterpCurvePointFloat
---@field ArriveTangent number
---@field InVal number
---@field InterpMode EInterpCurveMode
---@field LeaveTangent number
---@field OutVal number

---@class InterpCurvePointQuat
---@field ArriveTangent Quat
---@field InVal number
---@field InterpMode EInterpCurveMode
---@field LeaveTangent Quat
---@field OutVal Quat

---@class InterpCurvePointVector
---@field ArriveTangent Vector
---@field InVal number
---@field InterpMode EInterpCurveMode
---@field LeaveTangent Vector
---@field OutVal Vector

---@class InterpCurveQuat
---@field LoopKeyOffset number
---@field Points InterpCurvePointQuat[]
---@field bIsLooped boolean

---@class InterpCurveVector
---@field LoopKeyOffset number
---@field Points InterpCurvePointVector[]
---@field bIsLooped boolean

---@class LinearColor
---@field A number
---@field B number
---@field G number
---@field R number

---@class Matrix
---@field WPlane Plane
---@field XPlane Plane
---@field YPlane Plane
---@field ZPlane Plane

---@class Object : WaxInstance

---@class Package : Object

---@class PackageMap : Object

---@class Plane : Vector
---@field W number

---@class PolyglotTextData
---@field CachedText string
---@field Category ELocalizedTextSourceCategory
---@field Key string
---@field LocalizedStrings table<string, string>
---@field Namespace string
---@field NativeCulture string
---@field NativeString string
---@field bIsMinimalPatch boolean

---@class PrimaryAssetId
---@field PrimaryAssetName string
---@field PrimaryAssetType PrimaryAssetType

---@class PrimaryAssetType
---@field Name string

---@class QualifiedFrameTime
---@field Rate FrameRate
---@field Time FrameTime

---@class Quat
---@field W number
---@field X number
---@field Y number
---@field Z number

---@class RandomStream
---@field InitialSeed integer
---@field Seed integer

---@class Rotator
---@field Pitch number
---@field Roll number
---@field Yaw number

---@class ScriptStruct : Struct

---@class SoftClassPath : SoftObjectPath

---@class SoftObjectPath
---@field AssetPathName string
---@field SubPathString string

---@class Struct : Field

---@class Timecode
---@field Frames integer
---@field Hours integer
---@field Minutes integer
---@field Seconds integer
---@field bDropFrameFormat boolean

---@class Timespan

---@class Transform
---@field Rotation Quat
---@field Scale3D Vector
---@field Translation Vector

---@class UniqueNetIdWrapper

---@class Vector
---@field X number
---@field Y number
---@field Z number

---@class Vector2D
---@field X number
---@field Y number

---@class Vector4
---@field W number
---@field X number
---@field Y number
---@field Z number
