---@meta _
-- Generated by scripts\gameindex.py from the game's object dump. Changes here are lost on the next run.

---@alias EGameplayTaskRunResult
---| 0 # Error
---| 1 # Failed
---| 2 # Success_Paused
---| 3 # Success_Active
---| 4 # Success_Finished
---| integer

---@alias ETaskResourceOverlapPolicy
---| 0 # StartOnTop
---| 1 # StartAtEnd
---| integer

---@class GameplayResourceSet

---@class GameplayTask : Object
---@field ChildTask GameplayTask
---@field InstanceName string
---@field ResourceOverlapPolicy ETaskResourceOverlapPolicy
---@field EndTask fun(self: GameplayTask)
---@field ReadyForActivation fun(self: GameplayTask)

---@class GameplayTaskOwnerInterface : Interface

---@class GameplayTaskResource : Object
---@field AutoResourceID integer
---@field ManualResourceID integer
---@field bManuallySetID boolean

---@class GameplayTasksComponent : ActorComponent
---@field KnownTasks GameplayTask[]
---@field OnClaimedResourcesChange GameDelegate
---@field SimulatedTasks GameplayTask[]
---@field TaskPriorityQueue GameplayTask[]
---@field TickingTasks GameplayTask[]
---@field bIsNetDirty boolean
---@field K2_RunGameplayTask fun(self: GameplayTasksComponent, TaskOwner: GameplayTaskOwnerInterface?, Task: GameplayTask?, Priority: integer, AdditionalRequiredResources: Class[], AdditionalClaimedResources: Class[]): EGameplayTaskRunResult
---@field OnRep_SimulatedTasks fun(self: GameplayTasksComponent)
