---@meta _
-- Generated by scripts\gameindex.py from the game's object dump. Changes here are lost on the next run.

---@alias EAIAudioState
---| 0 # Undefined
---| 1 # Idle
---| 2 # Fleeing
---| 3 # Attacking
---| 4 # Dead
---| 5 # Relaxing
---| 6 # Mounted
---| 7 # Stalking
---| integer

---@alias EAIEventRequestResponse
---| 0 # Invalid
---| 1 # FailedToStart
---| 2 # EventStarted
---| 3 # PendingLoad
---| integer

---@alias EAIVocalisationType
---| 0 # Attack
---| 1 # Flinch
---| 2 # Death
---| integer

---@alias EActionRangeCheckBehaviour
---| 0 # ValidMove
---| 1 # CustomFunction
---| 2 # Both
---| integer

---@alias EActionableEventType
---| 0 # Undefined
---| 1 # Primary
---| 2 # Secondary
---| 3 # Tertiary
---| 4 # Reload
---| 5 # MAX_VALUE
---| integer

---@alias EActionableTrigger
---| 0 # ActionPressed
---| 1 # ActionReleased
---| 2 # ActionHeld
---| integer

---@alias EAliveState
---| 0 # Alive
---| 1 # Dead
---| integer

---@alias EAnimOverlayState
---| 0 # Default
---| 1 # OneHanded
---| 2 # Bow
---| 3 # TwoHandedRifle
---| 4 # Driving
---| 5 # Spear
---| 6 # Carrying
---| 7 # Firearm
---| 8 # Fishing
---| integer

---@alias EAnimStateFMODParam
---| 0 # NotAnimating
---| 1 # Animating
---| integer

---@alias EAntiAliasingSetting
---| 0 # Low
---| 1 # Medium
---| 2 # High
---| 3 # Epic
---| 4 # Cinematic
---| 5 # NumSettings
---| 255 # Custom
---| integer

---@alias EArcadeMachineRankingType
---| 0 # LowerIsBetter
---| 1 # GreaterIsBetter
---| integer

---@alias EArmourType
---| 0 # Undefined
---| 1 # Head
---| 2 # Chest
---| 3 # Hands
---| 4 # Legs
---| 5 # Feet
---| 6 # Undersuit
---| 7 # Skin_Head
---| 8 # Undersuit_Helmet
---| 9 # Skin_Head_Hair
---| 10 # Backpack
---| 11 # Gauntlet
---| integer

---@alias EAssetType
---| 0 # Object
---| 1 # Class
---| integer

---@alias EAudioShelterState
---| 0 # Low
---| 1 # Medium
---| 2 # High
---| integer

---@alias EAuthorityType
---| 0 # ClientOnly
---| 1 # ServerOnly
---| 2 # Both
---| integer

---@alias EBestiaryUnlockPopup
---| 0 # Creature
---| 1 # Stat1
---| 2 # Stat2
---| 3 # Lore1
---| 4 # Lore2
---| 5 # Lore3
---| 6 # Weaknesses
---| 7 # Loot
---| integer

---@alias EBiomeImageType
---| 0 # None
---| 1 # Small
---| 2 # Medium
---| 3 # Large
---| integer

---@alias EBuildingDestroyReason
---| 0 # Stability
---| 1 # Player
---| 2 # Damaged
---| 3 # Replaced
---| integer

---@alias EBuildingMeshType
---| 0 # Invalid
---| 1 # BaseMesh
---| 2 # FrameMesh
---| integer

---@alias EBuildingOpenFMODParam
---| 0 # Closed
---| 1 # Open
---| integer

---@alias EBuildingPieceType
---| 0 # Floor
---| 1 # Wall
---| 2 # Frame
---| 3 # Ramp
---| integer

---@alias EBuildingUnzipFMODParam
---| 0 # Normal
---| 1 # Unzipping
---| integer

---@alias ECameraPathMode
---| 0 # Idle
---| 1 # Recording
---| 2 # Playing
---| integer

---@alias ECanHitResult
---| 0 # CantHit
---| 1 # Miss
---| 2 # Hit
---| integer

---@alias ECanRepair
---| 0 # HaveIngredients
---| 1 # RequiresIngredients
---| 2 # NeedsPower
---| 3 # ToResolve
---| integer

---@alias ECanUseItemResult
---| 0 # VisibleAndEnabled
---| 1 # VisibleAndDisabled
---| 2 # Hidden
---| integer

---@alias ECaveContextFMODParam
---| 0 # None
---| 1 # ListenerOutSourceOut
---| 2 # ListenerOutSourceInCave
---| 3 # ListenerInCaveSourceOut
---| 4 # ListenerInCaveSourceInCave
---| integer

---@alias ECaveLightType
---| 0 # Spot
---| 1 # Rect
---| integer

---@alias EChallengeTypes
---| 0 # KillCreature
---| 1 # CriticalHit
---| 2 # StealthAttack
---| 3 # SkinCreature
---| 4 # HarvestCreatureItem
---| 5 # HarvestPlant
---| 6 # FellTree
---| 7 # CollectTreeItem
---| 8 # FullyMineVoxel
---| 9 # MineResource
---| integer

---@alias ECharacterBodyType
---| 0 # Masculine
---| 1 # Feminine
---| 2 # Neutral
---| integer

---@alias ECharacterCustomisationContext
---| 0 # Undefined
---| 1 # CharacterCreation
---| 2 # HABCustomisation
---| integer

---@alias ECharacterOptionCategory
---| 0 # Head
---| 1 # Body
---| 2 # BodyColor
---| 3 # HairStyle
---| 4 # HairColor
---| 5 # Head_Tattoo
---| 6 # Head_Scar
---| 7 # Head_FacialHair
---| 8 # SkinTone
---| 9 # Color
---| 10 # EyeColor
---| 11 # Decal
---| 12 # Piercing
---| 13 # Eyebrows
---| 14 # Complexion
---| 15 # Rebreather
---| 16 # HairV2
---| 17 # BeardV2
---| 18 # EyeColorV2
---| 19 # HairColorV2
---| 20 # ScarV2
---| 21 # HeadV2
---| 22 # AgeV2
---| 23 # Hood
---| 24 # Helmet
---| integer

---@alias ECheatsEnabled
---| 0 # Enabled
---| 1 # NotEnabled
---| integer

---@alias EClassRepPolicy
---| 0 # NotRouted
---| 1 # ManuallyRouted
---| 2 # RelevantAllConnections
---| 3 # Spatialize_Static
---| 4 # Spatialize_Dynamic
---| 5 # Spatialize_Dormancy
---| integer

---@alias EComparisonType
---| 0 # Equals
---| 1 # NotEquals
---| 2 # LessThan
---| 3 # LessThanOrEqual
---| 4 # GreaterThan
---| 5 # GreaterThanOrEqual
---| integer

---@alias EControllerIconSet
---| 0 # None
---| 1 # Xbox
---| 2 # Playstation
---| 3 # NintendoSwitch
---| integer

---@alias EControllerIconsSetting
---| 0 # Xbox
---| 1 # Playstation
---| 2 # Switch
---| 3 # NumSettings
---| 255 # Custom
---| integer

---@alias ECraftingContainerType
---| 0 # Recipes
---| 1 # RecipeSets
---| 2 # Query
---| integer

---@alias ECreatureAudioThreatTargetType
---| 0 # Invalid
---| 1 # OtherPlayer
---| 2 # LocalPlayer
---| 3 # OtherCreature
---| 4 # Stimulus
---| integer

---@alias ECreatureFoliageFMODParam
---| 0 # NotInFoliage
---| 1 # InFoliage
---| integer

---@alias ECreatureFootstepTypeFMODParam
---| 0 # FrontFoot
---| 1 # RearFoot
---| 2 # Jump
---| 3 # JumpLand
---| integer

---@alias ECreatureSex
---| 0 # Unknown
---| 1 # Female
---| 2 # Male
---| integer

---@alias ECropMeshRotationType
---| 0 # NoRotation
---| 1 # Random90
---| 2 # FullyRandom
---| integer

---@alias ECrosshairColorSetting
---| 0 # White
---| 1 # Red
---| 2 # Green
---| 3 # Blue
---| 4 # Yellow
---| 5 # Pink
---| 6 # Cyan
---| 7 # Black
---| 8 # NumSettings
---| 255 # Custom
---| integer

---@alias ECrosshairStyleSetting
---| 0 # Dot
---| 1 # Chevron
---| 2 # Circle
---| 3 # Cross
---| 4 # Plus
---| 5 # Diamond
---| 6 # Notched
---| 7 # Scope
---| 8 # Bullseye
---| 9 # Spread
---| 10 # Target
---| 11 # NumSettings
---| 255 # Custom
---| integer

---@alias ECustomGameStatCategory
---| 0 # Player
---| 1 # Weather
---| 2 # Creatures
---| 3 # Misc
---| integer

---@alias ECustomGameStatChangeability
---| 0 # OnProspectCreation
---| 1 # OnProspectLoad
---| 2 # Anytime
---| integer

---@alias ECustomGameStatType
---| 0 # Bool
---| 1 # Int
---| 2 # DropDown
---| integer

---@alias EDamageTypeFMODParam
---| 0 # Undefined
---| 1 # Pure
---| 2 # Physical
---| 3 # Melee
---| 4 # Ranged
---| 5 # Fire
---| 6 # FallDamage
---| 7 # Collision
---| 8 # Poison
---| 9 # Wind
---| integer

---@alias EDataValid
---| 0 # DataValid
---| 1 # DataInvalid
---| integer

---@alias EDataValidity
---| 0 # Valid
---| 1 # Invalid
---| integer

---@alias EDeployableSnapBehaviour
---| 0 # WorldPlacementOnly
---| 1 # SnapPlacementOnly
---| 2 # WorldAndSnap
---| integer

---@alias EDestroyPattern
---| 0 # RadialOutward
---| 1 # RadialInward
---| 2 # Random
---| integer

---@alias EDeviceState
---| 0 # On
---| 1 # Idle
---| 2 # Off
---| integer

---@alias EDialogueEvents
---| 0 # None
---| 1 # QuestStart
---| 2 # QuestEnd
---| integer

---@alias EDialogueRedirectCondition
---| 0 # None
---| 1 # IsOpenWorldProspect
---| 2 # IsMissionProspect
---| integer

---@alias EDirtierMode
---| 0 # OwningActor
---| 1 # AffectedObjectsList
---| integer

---@alias EDisplayTemperatureSetting
---| 0 # Celsius
---| 1 # Fahrenheit
---| 2 # NumSettings
---| 255 # Custom
---| integer

---@alias EDropAbundance
---| 0 # Low
---| 1 # Medium
---| 2 # High
---| integer

---@alias EDropTemperature
---| 0 # Cold
---| 1 # Normal
---| 2 # Hot
---| integer

---@alias EDropshipDescentStateFMODParam
---| 0 # MainEngines
---| 1 # Booster
---| 2 # Freefall
---| 3 # Landed
---| 4 # EnterSeat
---| 5 # CrashBegin
---| 6 # CrashEnd
---| integer

---@alias EDynamicItemProperties
---| 0 # AssociatedItemInventoryId
---| 1 # AssociatedItemInventorySlot
---| 2 # DynamicState
---| 3 # GunCurrentMagSize
---| 4 # CurrentAmmoType
---| 5 # BuildingVariation
---| 6 # Durability
---| 7 # ItemableStack
---| 8 # MillijoulesRemaining
---| 9 # TransmutableUnits
---| 10 # Fillable_StoredUnits
---| 11 # Fillable_Type
---| 12 # Decayable_CurrentSpoilTime
---| 13 # InventoryContainer_LinkedInventoryId
---| 14 # MaxDynamicItemProperties
---| integer

---@alias EDynamicQuestDifficulty
---| 0 # None
---| 1 # Easy
---| 2 # Medium
---| 3 # Hard
---| integer

---@alias EEffectsSetting
---| 0 # Low
---| 1 # Medium
---| 2 # High
---| 3 # Epic
---| 4 # Cinematic
---| 5 # NumSettings
---| 255 # Custom
---| integer

---@alias EEndProspectSessionContext
---| 0 # Undefined
---| 1 # HostLeavingSession
---| 2 # ExpiredProspect
---| 3 # Error_InvalidHost
---| 4 # Error_FailedToHostSession
---| integer

---@alias EEnvironmentLightningTargetFMODParam
---| 0 # Random
---| 1 # Player
---| 2 # Tree
---| 3 # Building
---| integer

---@alias EErrorAction
---| 0 # Immediate
---| 1 # Kick
---| 2 # Queue
---| 3 # AppClose
---| integer

---@alias EErrorTarget
---| 0 # Log
---| 1 # Widget
---| 2 # Dialog
---| integer

---@alias EEventEndReason
---| 0 # InvalidReason
---| 1 # Completed
---| 2 # Timeout
---| 3 # Aborted
---| integer

---@alias EExperienceSource
---| 0 # XP_None
---| 1 # XP_OnAction
---| 2 # XP_OnInteract
---| 3 # XP_OnHit
---| 4 # XP_OnDamaged
---| 5 # XP_OnDeath
---| 6 # XP_OnCraft
---| 7 # XP_OnAchievement
---| 8 # XP_Misc
---| integer

---@alias EFLODActorState
---| 0 # Undefined
---| 2 # Revealing
---| 4 # Revealed
---| 8 # Concealing
---| 16 # Concealed
---| integer

---@alias EFLODLevelInfluenceType
---| 0 # None
---| 1 # ViewTrace
---| 2 # Distance
---| integer

---@alias EFSRModeSetting
---| 0 # Off
---| 1 # Performance
---| 2 # Balanced
---| 3 # Quality
---| 4 # Ultra_Quality
---| 5 # NumSettings
---| 255 # Custom
---| integer

---@alias EFeatureLevelCheckResult
---| 0 # Unchecked
---| 1 # Fail_FeatureLevel
---| 2 # Fail_Flag
---| 3 # Unknown_CouldNotCheckFlag
---| 4 # Pass
---| integer

---@alias EFieldGuideItemHotToObtain
---| 0 # Unobtainium
---| 1 # Harvest
---| 2 # Craft
---| 4 # Kill
---| 8 # Fishing
---| 16 # PickAxe
---| 32 # SledgeHammer
---| 64 # DrillOrExtract
---| 128 # Buy_At_Workshop
---| integer

---@alias EFireExtinguishResult
---| 0 # Failed
---| 1 # ExtinguishedCombustion
---| 2 # ExtinguishedPyrolysis
---| integer

---@alias EFireMode
---| 0 # Semiauto
---| 1 # Burst
---| 2 # Auto
---| integer

---@alias EFireStateFMODParam
---| 0 # NotOnFire
---| 1 # OnFire
---| integer

---@alias EFirearmAttachType
---| 0 # Weapon
---| 1 # Player
---| integer

---@alias EFishRarity
---| 0 # None
---| 1 # Common
---| 2 # Uncommon
---| 3 # Rare
---| 4 # Unique
---| integer

---@alias EFishType
---| 0 # None
---| 1 # Saltwater
---| 2 # Freshwater
---| integer

---@alias EFishUnlockPopup
---| 0 # None
---| 1 # FishCaught
---| 2 # Quality
---| 4 # Weight
---| 8 # Length
---| 255 # All
---| integer

---@alias EFlagsTableType
---| 0 # D_CharacterFlags
---| 1 # D_SessionFlags
---| 2 # D_AccountFlags
---| 3 # D_DLCPackageData
---| 255 # None
---| integer

---@alias EFlammableAudioLocationType
---| 0 # ActorLocation
---| 1 # BoundsOrigin
---| 2 # BoundsBase
---| integer

---@alias EFlammablePropagationType
---| 0 # None
---| 1 # Self
---| 2 # FireInstance
---| integer

---@alias EFlammableState
---| 0 # None
---| 1 # Detached
---| 2 # Pyrolysis
---| 3 # Combusting
---| 4 # Combusted
---| 5 # Destroyed
---| integer

---@alias EFloatRoundingMode
---| 0 # Round
---| 1 # Floor
---| 2 # Ceiling
---| integer

---@alias EFoliageSetting
---| 0 # Low
---| 1 # Medium
---| 2 # High
---| 3 # Epic
---| 4 # Cinematic
---| 5 # NumSettings
---| 255 # Custom
---| integer

---@alias EForceRemovePlayerReason
---| 0 # Initialisation_NotApproved
---| 1 # KickedByHostingPlayer
---| integer

---@alias EFunctionOutcome
---| 0 # Success
---| 1 # Failure
---| integer

---@alias EGOAPCharacterStance
---| 0 # Standing
---| 1 # Sitting
---| 2 # Lying
---| integer

---@alias EGOAPControllerState
---| 0 # Idle
---| 1 # GetNewAction
---| 2 # MoveToAction
---| 3 # PerformAction
---| integer

---@alias EGOAPFactSource
---| 0 # VisionPerception
---| 1 # SoundPerception
---| 2 # DamagePerception
---| 3 # ProtectiveMotivation
---| integer

---@alias EGOAPObjectType
---| 0 # Food
---| 1 # Water
---| 2 # Enemy
---| 3 # MaxObjectTypes
---| integer

---@alias EGOAPProperty
---| 0 # Hungry
---| 1 # Thirsty
---| 2 # HasFood
---| 3 # HasWater
---| 4 # FoundFood
---| 5 # FoundWater
---| 6 # Wander
---| 7 # Scared
---| 8 # RunForSafety
---| 9 # MaxProperties
---| integer

---@alias EGlobalDropStateFMODParam
---| 0 # Hab
---| 1 # Dropship
---| 2 # Prospect
---| 3 # LoadingProspect
---| integer

---@alias EGlobalEnvironmentBiomeFMODParam
---| 0 # None
---| 1 # Conifer
---| 2 # Arctic
---| 3 # Desert
---| 4 # Lava
---| 5 # Wetlands
---| 6 # Grasslands
---| integer

---@alias EGlobalEnvironmentTerrainZoneFMODParam
---| 0 # Default
---| 1 # Canyon_Narrow
---| 2 # Canyon_Med
---| 3 # Canyon_Wide
---| integer

---@alias EGlobalLoadingScreenStateFMODParam
---| 0 # LoadingScreen_Inactive
---| 1 # LoadingScreen_Active
---| integer

---@alias EGlobalPlayerCharacterVoiceFMODParam
---| 0 # None
---| 1 # VoiceA
---| 2 # VoiceB
---| integer

---@alias EGraphicsCardVendor
---| 0 # Invalid
---| 1 # Unknown
---| 2 # Nvidia
---| 3 # AMD
---| 4 # Intel
---| integer

---@alias EGreatHuntMissionType
---| 0 # None
---| 1 # Standard
---| 2 # Choice
---| 3 # Optional
---| 4 # Final
---| integer

---@alias EHandedness
---| 0 # Right
---| 1 # Left
---| 2 # Both
---| integer

---@alias EHuntingClueType
---| 0 # Footprint
---| 1 # BloodTrail
---| integer

---@alias EIcarusActorDestroyReason
---| 0 # Other
---| 1 # Pickup
---| 2 # Durability
---| integer

---@alias EIcarusClaimLaunchConfirmationStep
---| 0 # ClaimingProspect
---| 1 # LoadingProspect
---| integer

---@alias EIcarusDamageType
---| 0 # Undefined
---| 1 # Pure
---| 2 # Melee
---| 3 # Projectile
---| 4 # Fire
---| 5 # FallDamage
---| 6 # Collision
---| 7 # Poison
---| 8 # Wind
---| 9 # Shield
---| 10 # Returned
---| 11 # Frost
---| 12 # Electric
---| 13 # Explosive
---| 14 # Shatter
---| 15 # Felling
---| 16 # Laser
---| integer

---@alias EIcarusGameVersionFlags
---| 0 # None
---| 1 # Major
---| 2 # Minor
---| 4 # Patch
---| 8 # Changelist
---| 15 # Numbers
---| 16 # BuildType
---| 32 # FeatureLevel
---| 63 # All
---| integer

---@alias EIcarusItemContext
---| 0 # None
---| 1 # World
---| 2 # EquipHand
---| 3 # EquipBack
---| 4 # Vehicle
---| 5 # Deployable
---| 6 # Slotable
---| 7 # Buildable
---| 8 # DropshipPart
---| 9 # Gravestone
---| 10 # Light
---| integer

---@alias EIcarusJoinConfirmationStep
---| 0 # FindingSession
---| 1 # JoiningProspect
---| 2 # LoadingProspect
---| integer

---@alias EIcarusProspectDifficulty
---| 0 # Easy
---| 1 # Normal
---| 2 # Hard
---| 3 # Extreme
---| integer

---@alias EIcarusResourceType
---| 0 # None
---| 1 # Energy
---| 2 # Water
---| 3 # Fuel
---| 4 # Oxygen
---| 5 # Hydrazine
---| 6 # Crude_Oil
---| 7 # Refined_Oil
---| 8 # Chute
---| 9 # MaxResourceTypes
---| integer

---@alias EIcarusResumeConfirmationStep
---| 0 # ResumeRequest
---| 1 # ConfirmationHost
---| 2 # ConfirmationJoin
---| 3 # LoadingProspectHost
---| 4 # FindingSessionJoin
---| 5 # LoadingProspectJoin
---| 6 # Mismatch
---| integer

---@alias EIcarusWeatherDifficulty
---| 0 # Light
---| 1 # Medium
---| 2 # Heavy
---| 3 # Extreme
---| integer

---@alias EInputContext
---| 0 # Both
---| 1 # KeyboardOnly
---| 2 # ControllerOnly
---| integer

---@alias EInputTypeSetting
---| 0 # Keyboard
---| 1 # Controller
---| 2 # NumSettings
---| 255 # Custom
---| integer

---@alias EInstancedLevelPickType
---| 0 # FirstItem
---| integer

---@alias EInteractType
---| 0 # Undefined
---| 1 # WorldPress
---| 2 # WorldHold
---| 3 # WorldAltPress
---| 4 # WorldAltHold
---| integer

---@alias EInteractableHitLookupType
---| 0 # None
---| 1 # FLOD_Instance
---| integer

---@alias EInventoryContainerType
---| 0 # Items
---| 1 # RecipeSets
---| 2 # Query
---| integer

---@alias EInventorySortType
---| 0 # ByTag
---| 1 # ByWeight
---| 2 # ByStackCount
---| 3 # ByAlphaNumeric
---| integer

---@alias EItemCraftingTypeFMODParam
---| 0 # Player
---| 1 # World
---| integer

---@alias EItemDestructionContext
---| 0 # Decayed
---| 1 # Dismantled
---| 2 # FellOutOfWorld
---| integer

---@alias EKeybindVisibility
---| 0 # VisibleRemap
---| 1 # VisibleNoRemap
---| 2 # Invisible
---| integer

---@alias ELastProspectHostType
---| 0 # LocalHost
---| 1 # SteamP2P
---| 2 # DedicatedServer
---| integer

---@alias ELeaveProspectSessionType
---| 0 # None
---| 1 # Quit
---| 2 # ReturnToCharacterSelect
---| 3 # LeaveByDropship
---| 4 # ReturnToTitlescreen
---| 5 # Disconnected
---| integer

---@alias ELevel
---| 0 # NoLogging
---| 1 # Error
---| 2 # Warning
---| 3 # Info
---| integer

---@alias ELineDrawMethod
---| 0 # Unspecified
---| 1 # NoLine
---| 2 # ShortestDistance
---| 3 # XThenY
---| 4 # YThenX
---| integer

---@alias ELobbyPrivacy
---| 0 # Unknown
---| 1 # FriendsOnly
---| 2 # Private
---| integer

---@alias ELookAtType
---| 0 # PitchAndYaw
---| 1 # VectorLocation
---| 2 # AbsoluteLocation
---| integer

---@alias EMapTileRadarFlag
---| 0 # NotScanned
---| 1 # NoResource
---| 2 # FoundResource
---| 3 # Scanning
---| 4 # FogOfWar
---| integer

---@alias EMetaHashResult
---| 0 # None
---| 1 # FilesNotFound
---| 2 # BadFileSize
---| 4 # ExtraFilesFound
---| 8 # ModFilesFound
---| 255 # All
---| integer

---@alias EMigrationStep
---| 0 # Start
---| 1 # CreatePlayerDataFolder
---| 2 # MigrateMetaInventoryFormat
---| 3 # OnlineGetUserProfile
---| 4 # OnlineGetCharacterData
---| 5 # OnlineGetCharacterLoadouts
---| 6 # OnlineGetMetaInventory
---| 7 # SwitchToOffline
---| 8 # CacheOfflineManagers
---| 9 # OfflineGetUserProfile
---| 10 # OfflineGetCharacterData
---| 11 # OfflineGetCharacterLoadouts
---| 12 # OfflineGetMetaInventory
---| 13 # MergeProfileData
---| 14 # MergeCharacterData
---| 15 # MergeLoadoutData
---| 16 # MergeMetaInventories
---| 17 # MergeOutpostFiles
---| 18 # UpdateLoadoutData
---| 19 # MigrateSaveFormat
---| 20 # DeletingOldFiles
---| 21 # FinaliseMigration
---| integer

---@alias EMissionState
---| 0 # InProgress
---| 1 # Completed
---| 2 # Abandoned
---| 3 # Failed
---| 4 # MAX
---| integer

---@alias EModifierMergeType
---| 0 # Stack
---| 1 # LongestDuration
---| 2 # Replace
---| 3 # Count
---| integer

---@alias EModifierType
---| 0 # Buff
---| 1 # Debuff
---| 2 # Biome
---| 3 # Aura_Positive
---| 4 # Aura_Negative
---| 5 # Radiation
---| 6 # Item
---| integer

---@alias EMountAction
---| 0 # Invalid
---| 1 # Eating
---| 2 # Drinking
---| 3 # Sleeping
---| 4 # Attacking
---| 5 # Escaping
---| 6 # Socialising
---| integer

---@alias EMountCombatBehaviourState
---| 0 # Invalid
---| 1 # DoNotEngage
---| 2 # NeutralEngagement
---| 3 # AggressiveEngagement
---| integer

---@alias EMountConsumptionBehaviourState
---| 0 # Invalid
---| 1 # Any
---| 2 # Assigned
---| 3 # None
---| integer

---@alias EMountGrazingBehaviourState
---| 0 # Invalid
---| 1 # Any
---| 2 # Foliage
---| 3 # Carcasses
---| 4 # None
---| integer

---@alias EMountMovementBehaviourState
---| 0 # Invalid
---| 1 # Follow
---| 2 # IdleWander
---| 3 # IdleStanding
---| 4 # IdleLying
---| integer

---@alias EMovementState
---| 0 # Undefined
---| 1 # Stationary
---| 2 # Sneak
---| 3 # Walk
---| 4 # Jog
---| 5 # Run
---| 6 # Sprint
---| 7 # Attacking
---| 8 # Following
---| integer

---@alias EMusicConditionCombatState
---| 0 # None
---| 1 # Idle
---| 2 # InCombat
---| 4 # InCombat_Boss
---| 8 # InCombat_EpicBoss
---| integer

---@alias EMusicConditionDisaster
---| 0 # None
---| 1 # Normal
---| 2 # Fire
---| integer

---@alias EMusicConditionDropState
---| 0 # None
---| 1 # DropShipDescending
---| 2 # Prospect
---| 4 # DropShipAscending
---| 8 # Hab
---| 16 # LoadingProspect
---| integer

---@alias EMusicConditionDropTime
---| 0 # None
---| 1 # Normal
---| 2 # TimeRunningOut
---| integer

---@alias EMusicConditionGameplayEvent
---| 0 # None
---| 1 # DiscoveredMetaResource
---| 2 # Revived
---| integer

---@alias EMusicConditionPlayerState
---| 0 # None
---| 1 # Alive
---| 2 # Dead
---| 4 # LowHealth
---| integer

---@alias EMusicConditionTimeOfDay
---| 0 # None
---| 1 # Dawn
---| 2 # Day
---| 4 # Dusk
---| 8 # Night
---| integer

---@alias EMusicConditionWeather
---| 0 # None
---| 1 # Normal
---| 2 # Storm_Ramp
---| 4 # Storm_Damage
---| 8 # Storm_Chaos
---| integer

---@alias ENPCNameGender
---| 0 # Male
---| 1 # Female
---| 2 # Both
---| integer

---@alias ENVIDIAReflexLowLatencySetting
---| 0 # Off
---| 1 # On
---| 2 # On_Plus_Boost
---| 3 # NumSettings
---| 255 # Custom
---| integer

---@alias ENavigationType
---| 0 # Jump
---| 1 # Teleport
---| 2 # MaxNavigationTypes
---| integer

---@alias EObjectSlotType
---| 0 # ObjectSlotInput
---| 1 # ObjectSlotOutput
---| 2 # ObjectSlotStorage
---| integer

---@alias EOcclusionShelterContextFMODParam
---| 0 # None
---| 1 # ListenerLowSourceLow
---| 2 # ListenerLowSourceMed
---| 3 # ListenerLowSourceHigh
---| 4 # ListenerMedSourceLow
---| 5 # ListenerMedSourceMed
---| 6 # ListenerMedSourceHigh
---| 7 # ListenerHighSourceLow
---| 8 # ListenerHighSourceMed
---| 9 # ListenerHighSourceHigh
---| integer

---@alias EOnProspectAvailability
---| 0 # None
---| 1 # Base
---| 2 # Upgrade1
---| 3 # Upgrade2
---| 4 # Upgrade3
---| integer

---@alias EOverallSetting
---| 0 # Low
---| 1 # Medium
---| 2 # High
---| 3 # Epic
---| 4 # Cinematic
---| 5 # NumSettings
---| 255 # Custom
---| integer

---@alias EPayloadDeploymentType
---| 0 # OnProjectileMovementComplete
---| 1 # OnLaunch
---| 2 # OnBounceImmediate
---| 3 # OnBounceWaitForHalt
---| 4 # OnTimerElapsed
---| integer

---@alias EPlantGrowthStates
---| 0 # Unseeded
---| 1 # Stage1
---| 2 # Stage2
---| 3 # Stage3
---| 4 # Stage4
---| 5 # Mature
---| 6 # Decayed
---| integer

---@alias EPlayerArmourTypeFMODParam
---| 0 # None
---| 1 # Fiber
---| 2 # Fur
---| 3 # Leather
---| 4 # Ghillie
---| 5 # Carbon
---| 6 # Composite
---| 7 # Polar
---| 8 # Scale
---| 9 # Bone
---| 10 # Obsidian
---| 11 # Metal
---| integer

---@alias EPlayerFoliageFMODParam
---| 0 # None
---| 1 # Bush
---| 2 # BushDry
---| 3 # BushLow
---| 4 # BushTwiggy
---| 5 # Flower
---| 6 # Bramble
---| integer

---@alias EPlayerGroundStateFMODParam
---| 0 # Earth
---| 1 # Air
---| 2 # Water
---| integer

---@alias EPlayerStanceFMODParam
---| 0 # Jogging
---| 1 # Sprinting
---| 2 # Crouching
---| 3 # Walking
---| integer

---@alias EPlayerTypeFMODParam
---| 0 # LocalPlayerFirstPerson
---| 1 # LocalPlayerThirdPerson
---| 2 # OtherPlayer
---| integer

---@alias EPostProcessingSetting
---| 0 # Low
---| 1 # Medium
---| 2 # High
---| 3 # Epic
---| 4 # Cinematic
---| 5 # NumSettings
---| 255 # Custom
---| integer

---@alias EPrebuiltStructureState
---| 0 # Built
---| 1 # NotBuilt
---| integer

---@alias EPrimaryItemTypes
---| 0 # Generic
---| 1 # Actionable
---| 2 # Armor
---| 3 # Ballistic
---| 4 # Buildable
---| 5 # Consumable
---| 6 # Combustible
---| 7 # Deployable
---| 8 # Energy
---| 9 # Equippable
---| 10 # Highlightable
---| 11 # Interactable
---| 12 # Itemable
---| 13 # Meshable
---| 14 # Processing
---| 15 # Useable
---| 16 # Weight
---| 17 # Tool
---| 18 # Resource
---| 19 # Rocketable
---| integer

---@alias EProcessorPurpose
---| 0 # Crafting
---| 1 # Repairing
---| integer

---@alias EProcessorStoppedReason
---| 0 # GenericFailure
---| 1 # NoEnergy
---| 2 # NoResources
---| 3 # NoRecipe
---| 4 # NoQueue
---| 5 # NoSpace
---| 6 # NotTurnedOn
---| 7 # NoResourceRemaining
---| 8 # PlayerStopped
---| integer

---@alias EProgressState
---| 0 # Prototype
---| 1 # Review
---| 2 # Complete
---| 3 # NumStates
---| integer

---@alias EProjectileBreakModifier
---| 0 # NoChange
---| 1 # Unbreakable
---| 2 # MustBreak
---| integer

---@alias EProspectRequiredTech
---| 0 # None
---| 1 # Tier1
---| 2 # Tier2
---| 3 # Tier3
---| 4 # Tier4
---| 5 # Tier5
---| integer

---@alias EQuestActorState
---| 0 # Valid
---| 1 # Invalid
---| integer

---@alias EQuestModifiersTableType
---| 0 # D_QuestWeatherModifiers
---| 1 # D_QuestEnemyModifiers
---| 2 # D_QuestVocalisationModifiers
---| 255 # None
---| integer

---@alias EQuestState
---| 0 # Complete
---| 1 # Incomplete
---| integer

---@alias ERCONCommandContext
---| 0 # Any
---| 1 # ServerLobby
---| 2 # Survival
---| integer

---@alias ERCONCommandPlatformContext
---| 0 # Any
---| 1 # DedicatedServer
---| 2 # P2P
---| integer

---@alias ERateLimitedRequests
---| 0 # None
---| 1 # GetDropships
---| 2 # GetMetaResources
---| 3 # GetMetaInventory
---| 4 # GetDropInventory
---| 5 # GetWorkshopPacks
---| 6 # GetCredits
---| 7 # GetNotifications
---| 8 # SyncTalents
---| integer

---@alias ERefundPermission
---| 0 # Inherit
---| 1 # Block
---| 2 # Allow
---| integer

---@alias ERefundTalentResponse
---| 0 # Invalid
---| 1 # Success
---| 2 # NullModel
---| 3 # NotUnlocked
---| 4 # IsDependency
---| 5 # InvalidatesRank
---| integer

---@alias ERelationshipType
---| 0 # Neutral
---| 1 # Hostile
---| 2 # Friendly
---| integer

---@alias EReloadType
---| 0 # Magazine
---| 1 # Chambered
---| integer

---@alias ERemoteUserSetting
---| 0 # DisableCameraFocusOnProcessor
---| integer

---@alias ERepairItemTier
---| 0 # RepairTierUnknown
---| 1 # RepairTier1
---| 2 # RepairTier2
---| 3 # RepairTier3
---| 4 # RepairTier4
---| 5 # RepairTier5
---| 6 # RepairTierWorkshop
---| integer

---@alias ERequestPlayerPersonaErrorCode
---| 0 # NoError
---| 1 # InvalidId
---| 2 # RequestTimedOut
---| integer

---@alias ERequestResourceComponentDataSource
---| 0 # ViewTrace
---| 1 # OpenUI
---| integer

---@alias EResourceLibraryExec
---| 0 # Valid
---| 1 # Invalid
---| integer

---@alias EResourceNetworkFlowType
---| 0 # Consume
---| 1 # Produce
---| 2 # Store
---| integer

---@alias ERocketPartConnectionType
---| 0 # Undefined
---| 1 # MK1_TOP
---| 2 # MK1_BOTTOM
---| 3 # MK2_TOP
---| 4 # MK2_BOTTOM
---| integer

---@alias ERocketState
---| 0 # Inactive
---| 1 # Descending
---| 2 # Landed
---| 3 # Ascending
---| integer

---@alias ERollResult
---| 0 # Success
---| 1 # Failure
---| integer

---@alias ESecondaryItemTypes
---| 0 # Generic
---| 1 # Helmet
---| 2 # Chest
---| 3 # Gloves
---| 4 # Pants
---| 5 # Boots
---| 6 # Envirosuit
---| 7 # FoodResource
---| 8 # WaterResource
---| 9 # OxygenResource
---| 10 # Utility
---| 11 # FuelA
---| 12 # FuelB
---| 13 # FuelC
---| integer

---@alias ESessionFilterState
---| 0 # None
---| 1 # ShowOnly
---| 2 # HideOnly
---| integer

---@alias ESessionSearchType
---| 0 # PlayerHosted
---| 1 # Dedicated
---| integer

---@alias ESessionSortDirection
---| 0 # Ascending
---| 1 # Descending
---| integer

---@alias ESessionSortType
---| 0 # None
---| 1 # LobbyName
---| 2 # ProspectName
---| 3 # Duration
---| 4 # Difficulty
---| 5 # PlayerCount
---| 6 # Ping
---| 7 # Hardcore
---| integer

---@alias ESetDataSuccess
---| 0 # Success
---| 1 # Failed
---| integer

---@alias ESettingType
---| 0 # Bool
---| 1 # Int
---| 2 # Float
---| 3 # Enum
---| 4 # String
---| integer

---@alias ESettingsCategory
---| 0 # Display
---| 1 # Audio
---| 2 # Gameplay
---| 3 # Controls
---| integer

---@alias ESettlementBoundsBuildRule
---| 0 # BuildWithinSettlement
---| 1 # BuildOutsideSettlement
---| 2 # BuildAnywhere
---| integer

---@alias ESettlementBuildState
---| 0 # NotStarted
---| 1 # Scheduled
---| 2 # InProgress
---| 3 # Complete
---| 4 # Damaged
---| 5 # Destroyed
---| integer

---@alias ESettlementNPCActivity
---| 0 # Work
---| 1 # Eat
---| 2 # Sleep
---| 3 # Idle
---| 4 # UnderAttack
---| integer

---@alias ESettlementNPCAilment
---| 0 # None
---| 1 # Sick
---| 2 # Injured
---| integer

---@alias ESettlementTaskOrigin
---| 0 # Pooled
---| 1 # ActivityDefault
---| 2 # IncapacitatedOverride
---| 3 # BehaviourOverride
---| integer

---@alias ESettlementVisitorLeaveReason
---| 0 # Rejected
---| 1 # StayExpired
---| integer

---@alias EShadingSetting
---| 0 # Low
---| 1 # Medium
---| 2 # High
---| 3 # Epic
---| 4 # Cinematic
---| 5 # NumSettings
---| 255 # Custom
---| integer

---@alias EShadowFilterMethodSetting
---| 0 # PCF
---| 1 # PCSS
---| 2 # NumSettings
---| 255 # Custom
---| integer

---@alias EShadowsSetting
---| 0 # Low
---| 1 # Medium
---| 2 # High
---| 3 # Epic
---| 4 # Cinematic
---| 5 # NumSettings
---| 255 # Custom
---| integer

---@alias ESkyboxQualitySetting
---| 0 # Low
---| 1 # Normal
---| 2 # NumSettings
---| 255 # Custom
---| integer

---@alias ESleepResult
---| 0 # Valid
---| 1 # InvalidTime
---| integer

---@alias ESplineLoopDirection
---| 0 # Undetermined
---| 1 # Anticlockwise
---| 2 # Clockwise
---| integer

---@alias EStaminaBracket
---| 0 # Empty
---| 1 # Low
---| 2 # Normal
---| 3 # Full
---| integer

---@alias EStatDisplayOperation
---| 0 # None
---| 1 # Multiply
---| 2 # Division
---| 3 # Addition
---| integer

---@alias EStatSources
---| 0 # Base
---| 1 # FromServer
---| 2 # Armour
---| 3 # Buff
---| 4 # Item
---| 5 # Durable
---| 6 # Buildable
---| 7 # DropShip
---| 8 # Attributes
---| 9 # Perks
---| 10 # Projectile
---| 11 # GOAP
---| 12 # EquippedItems
---| 13 # MapManager
---| 14 # ArmourSetBonus
---| 15 # AIManager
---| 16 # Talents
---| 17 # Biome
---| 18 # TimeOfDay
---| 19 # Weather
---| 20 # BackingStatsContainer
---| 21 # Weight
---| 22 # World
---| 23 # Ruleset
---| 24 # AISetup
---| 25 # AISpawner
---| 26 # EpicCreature
---| 27 # DamageEnabledAnimNotify
---| 28 # BTTaskPerformAction
---| 29 # Input
---| 30 # GOAPAction
---| 31 # CriticalHit
---| 32 # GenericBehaviourTree
---| 33 # Alteration
---| 34 # TamingComponent
---| 35 # Atmosphere
---| 36 # Shield
---| 37 # Mount
---| 38 # CreatureModifiers
---| 39 # BestiaryProgress
---| 40 # IcarusMountCharacter
---| 41 # Movement
---| 42 # OffHandActor
---| 43 # InstancedLevel
---| 44 # Actionable
---| 45 # Genetics
---| 46 # Settlement
---| 47 # SettlementTrait
---| 48 # SettlementSkill
---| integer

---@alias EStateRecorderOwnerResolvePolicy
---| 0 # FindOnly
---| 1 # RespawnOnly
---| 2 # FindOrRespawn
---| 3 # ManuallyResolved
---| integer

---@alias EStealthAttackType
---| 0 # NoStealth
---| 1 # PartialStealth
---| 2 # FullStealth
---| integer

---@alias ESteamSearchType
---| 0 # Internet
---| 1 # Favorites
---| 2 # History
---| 3 # Spectate
---| 4 # Lan
---| 5 # Friends
---| integer

---@alias ESuperResolutionSetting
---| 0 # Off
---| 1 # Auto
---| 2 # Quality
---| 3 # Balanced
---| 4 # Performance
---| 5 # Ultra_Performance
---| 6 # NumSettings
---| 255 # Custom
---| integer

---@alias ESurfaceFMODParam
---| 0 # Default
---| 1 # Dirt
---| 2 # Sand
---| 3 # Grass
---| 4 # Wood
---| 5 # Rock
---| 6 # Plastic
---| 7 # Metal
---| 8 # Carpet
---| 9 # Snow
---| 10 # Water
---| 11 # Gravel
---| 12 # Flesh
---| 13 # Concrete
---| 14 # Mud
---| 15 # Ice
---| 16 # Tree
---| 17 # VoxelRock
---| 18 # VoxelMetal
---| 19 # Bush
---| 20 # Glass
---| 21 # Thatch
---| 22 # Cactus
---| 23 # Bone
---| 24 # CorrugatedIron
---| 25 # Lava
---| 26 # Slime
---| integer

---@alias ESurveyLaserFMODParam
---| 0 # LaserOff
---| 1 # LaserOn
---| integer

---@alias ESurveyTransmitFMODParam
---| 0 # NotTransmitting
---| 1 # Transmitting
---| integer

---@alias ESurvivalConsumableType
---| 0 # Food
---| 1 # Water
---| 2 # Oxygen
---| integer

---@alias ESurvivalStatType
---| 0 # Food
---| 1 # Water
---| 2 # Oxygen
---| integer

---@alias ETagRequirement
---| 0 # HasAllTags
---| 1 # HasAnyTags
---| integer

---@alias ETalentNodeType
---| 0 # Talent
---| 1 # Reroute
---| 2 # MutuallyExclusive
---| integer

---@alias ETalentState
---| 0 # Locked
---| 1 # Available
---| 2 # Unlocked
---| 3 # Completed
---| integer

---@alias ETamedCreatureType
---| 0 # Juvenile
---| 1 # TamedCreature
---| 2 # Both
---| integer

---@alias ETamedState
---| 0 # NotTamed
---| 1 # Tamed
---| 2 # Domesticated
---| integer

---@alias ETamingTemperatureState
---| 0 # JustRight
---| 1 # TooHot
---| 2 # TooCold
---| integer

---@alias ETargetRangeState
---| 0 # Waiting
---| 1 # Active
---| integer

---@alias ETerrainAnchorState
---| 0 # Undefined
---| 1 # Valid
---| 2 # Invalid
---| integer

---@alias ETestRailState
---| 0 # Inactive
---| 1 # Initialising
---| 2 # Running
---| 3 # Complete
---| integer

---@alias ETexturesSetting
---| 0 # Low
---| 1 # Medium
---| 2 # High
---| 3 # Epic
---| 4 # Cinematic
---| 5 # NumSettings
---| 255 # Custom
---| integer

---@alias ETowerMinigameFMODParam
---| 0 # Finding
---| 1 # Found
---| integer

---@alias ETrackerSetType
---| 0 # Overwrite
---| 1 # KeepHighest
---| integer

---@alias ETreeDetachContextFMODParam
---| 0 # Collision
---| 1 # PlayerCollision
---| 2 # PlayerActionIndirect
---| 3 # PlayerActionDirect
---| integer

---@alias ETreePrimitiveDetachContext
---| 0 # None
---| 1 # PlayerAction_Direct
---| 2 # PlayerAction_Indirect
---| 3 # Collision
---| 4 # Fire
---| 5 # Storm
---| integer

---@alias ETreePrimitiveItemReplaceMethod
---| 0 # None
---| 1 # SpawnWorldItem
---| 2 # DirectIntoInventory
---| integer

---@alias ETreePrimitiveType
---| 0 # None
---| 1 # Root
---| 2 # Trunk
---| 3 # Branch
---| 4 # Leaf
---| 5 # Socketable
---| integer

---@alias EViewDistanceSetting
---| 0 # Low
---| 1 # Medium
---| 2 # High
---| 3 # Epic
---| 4 # Cinematic
---| 5 # NumSettings
---| 255 # Custom
---| integer

---@alias EViewTraceHitType
---| 0 # None
---| 1 # LineTrace
---| 2 # VolumeTrace
---| integer

---@alias EViewTraceResultPriority
---| 0 # Blocking
---| 1 # Ignore
---| 2 # Low
---| 3 # Normal
---| 4 # High
---| integer

---@alias EVocalisationInterruptType
---| 0 # Interrupt
---| 1 # Cancel
---| 2 # Queue
---| integer

---@alias EVocalisationPlayResult
---| 0 # Cancelled
---| 1 # Played
---| 2 # Queued
---| integer

---@alias EVocalisationPriority
---| 0 # Lowest
---| 1 # Low
---| 2 # Medium
---| 3 # High
---| 4 # Highest
---| integer

---@alias EVoxelMinedState
---| 0 # NotMined
---| 1 # PartiallyMined
---| 2 # FullyMined
---| integer

---@alias EVoxelResourceCategory
---| 0 # None
---| 1 # Stone
---| 2 # Metal
---| 3 # Oxite
---| 4 # Copper
---| 5 # Gold
---| 6 # Bauxite
---| 7 # Sulfur
---| 8 # Silica
---| 9 # Ice
---| 10 # Platinum
---| 11 # Titanium
---| 12 # Coal
---| 13 # Exotic_A
---| 14 # Salt
---| 15 # Limestone
---| 16 # Lithium
---| 17 # Ruby
---| 18 # Lead
---| integer

---@alias EWaterStoredFMODParam
---| 0 # None
---| 1 # Some
---| integer

---@alias EWeaponAimingFMODParam
---| 0 # NotAiming
---| 1 # Aiming
---| integer

---@alias EWeaponChargingFMODParam
---| 0 # NotCharging
---| 1 # Charging
---| integer

---@alias EWeaponReloadingFMODParam
---| 0 # NotReloading
---| 1 # Reloading
---| integer

---@alias EWeaponSilencedFMODParam
---| 0 # STANDARD
---| 1 # SILENCED
---| integer

---@alias EWorldPlacementType
---| 0 # GroundPlacement
---| 1 # WallPlacement
---| 2 # WaterPlacement
---| 3 # GroundOrWallPlacement
---| 4 # CeilingPlacement
---| 5 # LavaPlacement
---| integer

---@class EdInstancedLevelDetail
---@field Data InstancedMapData
---@field LogDetail string
---@field ShortenedName string
---@field bIsUpdate boolean

---@class EdgeSplineComponent : SplineComponent
---@field DefaultDistanceBetweenPoints number
---@field DefaultRadius number
---@field SplineDirection ESplineLoopDirection
---@field ForceSplinePointLocationsToComponentZValue fun(self: EdgeSplineComponent)
---@field GenerateGenericSpline fun(self: EdgeSplineComponent)
---@field GenerateSpline fun(self: EdgeSplineComponent, EdgePoints: Vector[], PointDensity: number)
---@field GetSplineInfoFromLocation fun(self: EdgeSplineComponent, Location: Vector|{}, OutClosestPointOnEdge: Vector|{}, OutIsLocationWithinSpline: boolean)
---@field GetSplinePointsBoundingSphere fun(self: EdgeSplineComponent, OutOrigin: Vector|{}, OutRadius: number)
---@field IsValidEdgeSpline fun(self: EdgeSplineComponent): boolean
---@field SimplifySpline fun(self: EdgeSplineComponent, SimplificationFactor: integer)

---@class ElectricDamage : IcarusDamageType

---@class EnergyComponent : ResourceNetworkComponent

---@class EnergyData : ResourceNetworkData

---@class EnergyEnum : RowEnum

---@class EnergyLibrary : RowLibrary
---@field AddRowToEnergyTable fun(self: EnergyLibrary, Name: string, Data: EnergyData|{}, NewRow: EnergyRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakEnergyEnum fun(self: EnergyLibrary, Enum: EnergyEnum|{}, Name: string, Index: integer)
---@field CastToEnergyRowHandle fun(self: EnergyLibrary, RowHandle: RowHandle|{}, Paths: EValid): EnergyRowHandle
---@field EqualEqual_EnumEnum fun(self: EnergyLibrary, A: EnergyEnum|{}, B: EnergyEnum|{}): boolean
---@field EqualEqual_FEnergyRowHandleFEnergyRowHandle fun(self: EnergyLibrary, RowHandleA: EnergyRowHandle|{}, RowHandleB: EnergyRowHandle|{}): boolean
---@field GetEnergyStruct fun(self: EnergyLibrary, RowHandle: EnergyRowHandle|{}, Energy: EnergyData|{}, Paths: EValid)
---@field IntToName fun(self: EnergyLibrary, IntValue: integer): string
---@field IntToStruct fun(self: EnergyLibrary, IntValue: integer): EnergyEnum
---@field IsValidName fun(self: EnergyLibrary, NameValue: string): boolean
---@field MakeEnergy fun(self: EnergyLibrary, RowName: string): EnergyRowHandle
---@field MakeEnergyEnum fun(self: EnergyLibrary, Enum: EnergyEnum|{}): EnergyEnum
---@field MakeEnergyFromIndex fun(self: EnergyLibrary, Index: integer): EnergyRowHandle
---@field MakeLiteralEnergy fun(self: EnergyLibrary, RowHandle: EnergyRowHandle|{}): EnergyRowHandle
---@field NameToInt fun(self: EnergyLibrary, NameValue: string): integer
---@field NameToStruct fun(self: EnergyLibrary, NameValue: string): EnergyEnum
---@field NotEqual_EnumEnum fun(self: EnergyLibrary, A: EnergyEnum|{}, B: EnergyEnum|{}): boolean
---@field NotEqual_EnumName fun(self: EnergyLibrary, A: EnergyEnum|{}, B: string): boolean
---@field NumRows fun(self: EnergyLibrary): integer
---@field RefreshConstants fun(self: EnergyLibrary)
---@field RemoveRowFromEnergyTable fun(self: EnergyLibrary, Name: string)
---@field RowHandleToStruct fun(self: EnergyLibrary, RowHandle: EnergyRowHandle|{}): EnergyEnum
---@field StructToInt fun(self: EnergyLibrary, EnumValue: EnergyEnum|{}): integer
---@field StructToName fun(self: EnergyLibrary, EnumValue: EnergyEnum|{}): string
---@field StructToRowHandle fun(self: EnergyLibrary, EnumValue: EnergyEnum|{}): EnergyRowHandle

---@class EnergyRowHandle : RowHandle

---@class EnergyTable : IcarusDataTable

---@class EnergyTraitRecord
---@field bActive boolean

---@class EnvQueryContext_BackOfQuerier : EnvQueryContext

---@class EnvQueryGenerator_CachedSpawns : EnvQueryGenerator
---@field Context Class
---@field MaxPointRadius AIDataProviderFloatValue

---@class EnvQueryGenerator_NearbyTargets : EnvQueryGenerator
---@field NearbyRadius AIDataProviderFloatValue
---@field RelationshipToQuerier ERelationshipType
---@field SearchCenter Class
---@field TargetClassFilter Class
---@field TargetableContext Class
---@field bFilterByRelationship boolean
---@field bIgnoreZHeight boolean
---@field bOnlyAliveActors boolean

---@class EnvQueryGenerator_PerceivedTargets : EnvQueryGenerator
---@field Context Class
---@field RelationshipToQuerier ERelationshipType
---@field SearchCenter Class
---@field SenseToUse Class
---@field bFilterByRelationship boolean
---@field bOnlyAliveActors boolean

---@class EnvQueryGenerator_RecentDamageCausers : EnvQueryGenerator
---@field DamagedActorContext Class
---@field NearbyRadius AIDataProviderFloatValue
---@field NearbyRadiusCenter Class
---@field RecentDuration AIDataProviderFloatValue
---@field RelationshipFilters ERelationshipType[]
---@field TargetClassFilter Class
---@field bFilterByRelationship boolean
---@field bFilterNearbyActors boolean
---@field bOnlyAliveActors boolean

---@class EnvQueryGenerator_TaggedComponents : EnvQueryGenerator
---@field GenerateOnlyActorsInRadius AIDataProviderBoolValue
---@field SearchCenter Class
---@field SearchRadius AIDataProviderFloatValue
---@field SearchedActorClass Class
---@field TagsToMatch string[]
---@field bMatchActorTags boolean
---@field bMatchComponentTags boolean

---@class EnvQueryTest_AITrace : EnvQueryTest
---@field Context Class
---@field ContextHeightOffset AIDataProviderFloatValue
---@field IgnoreClasses Class[]
---@field ItemHeightOffset AIDataProviderFloatValue
---@field MaxTraceDistance number
---@field MinTraceDistance number
---@field TraceFromContext AIDataProviderBoolValue
---@field UseComplex boolean
---@field bIgnoreAllAITargetable boolean

---@class EnvQueryTest_ActorOverlap : EnvQueryTest
---@field ActorClassFilters Class[]
---@field AdditionalTraceChannels ECollisionChannel[]
---@field OverlapData EnvOverlapData

---@class EnvQueryTest_BoundsMask : EnvQueryTest
---@field OverrideBoundsMask GameplayTexture
---@field TestRadius number

---@class EnvQueryTest_DownwardTrace : EnvQueryTest
---@field BlacklistActors Class[]
---@field CollisionChannels ECollisionChannel[]
---@field Context Class
---@field DownwardsTraceDistance AIDataProviderFloatValue
---@field IgnoreClasses Class[]
---@field ItemHeightOffset AIDataProviderFloatValue
---@field bShowDebug boolean
---@field bTraceComplex boolean

---@class EnvQueryTest_FlatArea : EnvQueryTest
---@field Context Class
---@field DownwardsTraceDistance AIDataProviderFloatValue
---@field ItemHeightOffset AIDataProviderFloatValue
---@field MaxHeightChange AIDataProviderFloatValue
---@field RequiredRadius number
---@field bShowDebug boolean

---@class EnvQueryTest_IsShallowWater : EnvQueryTest
---@field Context Class
---@field ItemHeightOffset AIDataProviderFloatValue
---@field PermitWaterDepthCm AIDataProviderFloatValue
---@field TraceData EnvTraceData
---@field UpwardsTraceDistance AIDataProviderFloatValue
---@field WaterChannel ECollisionChannel

---@class EnvQueryTest_IsUnderwater : EnvQueryTest
---@field Context Class
---@field ItemHeightOffset AIDataProviderFloatValue
---@field TraceData EnvTraceData
---@field UpwardsTraceDistance AIDataProviderFloatValue
---@field WaterChannel ECollisionChannel

---@class EnvQueryTest_IsValidFlyingTarget : EnvQueryTest
---@field MaximumHeightDifference AIDataProviderFloatValue
---@field bPassNonFlyingTargets boolean

---@class EnvQueryTest_ProjectBox : EnvQueryTest
---@field ProjectionData EnvTraceData

---@class EnvQueryTest_RecentDamage : EnvQueryTest
---@field RecentDuration AIDataProviderFloatValue

---@class EnvQueryTest_WithinRockIndexFOV : EnvQueryTest
---@field CurrentRockIndexKeyName string
---@field RockActorKeyName string
---@field bIncludeBuffer boolean

---@class EnvQueryTest_WithinSettlementBounds : EnvQueryTest
---@field SettlementContext Class

---@class EnvQueryTest_WithinSpawnBlocker : EnvQueryTest
---@field SpawnBlockersContext Class
---@field bCheckForSpawnAttractors boolean

---@class EnzymeGeyser : IcarusActor
---@field Completions integer
---@field HordeRowHandle HordeRowHandle

---@class EnzymeGeyserRecorderComponent : ActorStateRecorderComponent
---@field Completions integer
---@field HordeDTKey string

---@class EpicCreatures : IcarusTableRowBase
---@field AISetup AISetupRowHandle
---@field AdditionalStats table<BaseStatsEnum, integer>
---@field CreatureNames string[]

---@class EpicCreaturesEnum : RowEnum

---@class EpicCreaturesLibrary : RowLibrary
---@field AddRowToEpicCreaturesTable fun(self: EpicCreaturesLibrary, Name: string, Data: EpicCreatures|{}, NewRow: EpicCreaturesRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakEpicCreaturesEnum fun(self: EpicCreaturesLibrary, Enum: EpicCreaturesEnum|{}, Name: string, Index: integer)
---@field CastToEpicCreaturesRowHandle fun(self: EpicCreaturesLibrary, RowHandle: RowHandle|{}, Paths: EValid): EpicCreaturesRowHandle
---@field EqualEqual_EnumEnum fun(self: EpicCreaturesLibrary, A: EpicCreaturesEnum|{}, B: EpicCreaturesEnum|{}): boolean
---@field EqualEqual_FEpicCreaturesRowHandleFEpicCreaturesRowHandle fun(self: EpicCreaturesLibrary, RowHandleA: EpicCreaturesRowHandle|{}, RowHandleB: EpicCreaturesRowHandle|{}): boolean
---@field GetEpicCreaturesStruct fun(self: EpicCreaturesLibrary, RowHandle: EpicCreaturesRowHandle|{}, EpicCreatures: EpicCreatures|{}, Paths: EValid)
---@field IntToName fun(self: EpicCreaturesLibrary, IntValue: integer): string
---@field IntToStruct fun(self: EpicCreaturesLibrary, IntValue: integer): EpicCreaturesEnum
---@field IsValidName fun(self: EpicCreaturesLibrary, NameValue: string): boolean
---@field MakeEpicCreatures fun(self: EpicCreaturesLibrary, RowName: string): EpicCreaturesRowHandle
---@field MakeEpicCreaturesEnum fun(self: EpicCreaturesLibrary, Enum: EpicCreaturesEnum|{}): EpicCreaturesEnum
---@field MakeEpicCreaturesFromIndex fun(self: EpicCreaturesLibrary, Index: integer): EpicCreaturesRowHandle
---@field MakeLiteralEpicCreatures fun(self: EpicCreaturesLibrary, RowHandle: EpicCreaturesRowHandle|{}): EpicCreaturesRowHandle
---@field NameToInt fun(self: EpicCreaturesLibrary, NameValue: string): integer
---@field NameToStruct fun(self: EpicCreaturesLibrary, NameValue: string): EpicCreaturesEnum
---@field NotEqual_EnumEnum fun(self: EpicCreaturesLibrary, A: EpicCreaturesEnum|{}, B: EpicCreaturesEnum|{}): boolean
---@field NotEqual_EnumName fun(self: EpicCreaturesLibrary, A: EpicCreaturesEnum|{}, B: string): boolean
---@field NumRows fun(self: EpicCreaturesLibrary): integer
---@field RefreshConstants fun(self: EpicCreaturesLibrary)
---@field RemoveRowFromEpicCreaturesTable fun(self: EpicCreaturesLibrary, Name: string)
---@field RowHandleToStruct fun(self: EpicCreaturesLibrary, RowHandle: EpicCreaturesRowHandle|{}): EpicCreaturesEnum
---@field StructToInt fun(self: EpicCreaturesLibrary, EnumValue: EpicCreaturesEnum|{}): integer
---@field StructToName fun(self: EpicCreaturesLibrary, EnumValue: EpicCreaturesEnum|{}): string
---@field StructToRowHandle fun(self: EpicCreaturesLibrary, EnumValue: EpicCreaturesEnum|{}): EpicCreaturesRowHandle

---@class EpicCreaturesRowHandle : RowHandle

---@class EpicCreaturesTable : IcarusDataTable

---@class EquipmentRequestInventoryContainer : Actor
---@field CargoInventory Inventory
---@field InventoryComponent InventoryComponent
---@field MetaInventory Inventory
---@field OnMetaInventoryChanged fun(self: EquipmentRequestInventoryContainer)

---@class EquippableComponent : TraitComponent
---@field GetEquippableData fun(self: EquippableComponent, OutData: EquippableData|{}): boolean

---@class EquippableData : IcarusTableRowBase
---@field EquippableModifier Class
---@field GlobalStat_ActorClass Class
---@field GlobalStat_GrantedStats table<StatsEnum, integer>
---@field GrantedStats table<StatsEnum, integer>
---@field bAppliesInAllInventories boolean
---@field bBindToAllInventoryUpdates boolean
---@field bPreventReinitialisation boolean
---@field bStackedModifiersGiveDiminishingReturns boolean

---@class EquippableEnum : RowEnum

---@class EquippableLibrary : RowLibrary
---@field AddRowToEquippableTable fun(self: EquippableLibrary, Name: string, Data: EquippableData|{}, NewRow: EquippableRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakEquippableEnum fun(self: EquippableLibrary, Enum: EquippableEnum|{}, Name: string, Index: integer)
---@field CastToEquippableRowHandle fun(self: EquippableLibrary, RowHandle: RowHandle|{}, Paths: EValid): EquippableRowHandle
---@field EqualEqual_EnumEnum fun(self: EquippableLibrary, A: EquippableEnum|{}, B: EquippableEnum|{}): boolean
---@field EqualEqual_FEquippableRowHandleFEquippableRowHandle fun(self: EquippableLibrary, RowHandleA: EquippableRowHandle|{}, RowHandleB: EquippableRowHandle|{}): boolean
---@field GetEquippableStruct fun(self: EquippableLibrary, RowHandle: EquippableRowHandle|{}, Equippable: EquippableData|{}, Paths: EValid)
---@field IntToName fun(self: EquippableLibrary, IntValue: integer): string
---@field IntToStruct fun(self: EquippableLibrary, IntValue: integer): EquippableEnum
---@field IsValidName fun(self: EquippableLibrary, NameValue: string): boolean
---@field MakeEquippable fun(self: EquippableLibrary, RowName: string): EquippableRowHandle
---@field MakeEquippableEnum fun(self: EquippableLibrary, Enum: EquippableEnum|{}): EquippableEnum
---@field MakeEquippableFromIndex fun(self: EquippableLibrary, Index: integer): EquippableRowHandle
---@field MakeLiteralEquippable fun(self: EquippableLibrary, RowHandle: EquippableRowHandle|{}): EquippableRowHandle
---@field NameToInt fun(self: EquippableLibrary, NameValue: string): integer
---@field NameToStruct fun(self: EquippableLibrary, NameValue: string): EquippableEnum
---@field NotEqual_EnumEnum fun(self: EquippableLibrary, A: EquippableEnum|{}, B: EquippableEnum|{}): boolean
---@field NotEqual_EnumName fun(self: EquippableLibrary, A: EquippableEnum|{}, B: string): boolean
---@field NumRows fun(self: EquippableLibrary): integer
---@field RefreshConstants fun(self: EquippableLibrary)
---@field RemoveRowFromEquippableTable fun(self: EquippableLibrary, Name: string)
---@field RowHandleToStruct fun(self: EquippableLibrary, RowHandle: EquippableRowHandle|{}): EquippableEnum
---@field StructToInt fun(self: EquippableLibrary, EnumValue: EquippableEnum|{}): integer
---@field StructToName fun(self: EquippableLibrary, EnumValue: EquippableEnum|{}): string
---@field StructToRowHandle fun(self: EquippableLibrary, EnumValue: EquippableEnum|{}): EquippableRowHandle

---@class EquippableModifier : ActorComponent
---@field CachedUID integer
---@field EquippableRow EquippableRowHandle
---@field Inventory Inventory
---@field InventorySlot integer
---@field SelfDestruct boolean
---@field ArmourSlotUpdated fun(self: EquippableModifier, SourceInventory: Inventory?, Location: integer)
---@field CheckTickConditions fun(self: EquippableModifier): boolean
---@field EquippedTick fun(self: EquippableModifier, DeltaTime: number)
---@field GetEquippableStatsToAdd fun(self: EquippableModifier, Stats: table<StatsEnum, integer>)
---@field GetStackedModifierMultiplier fun(self: EquippableModifier): number
---@field ItemEquipped fun(self: EquippableModifier): boolean
---@field ItemUnequipped fun(self: EquippableModifier): boolean
---@field OnItemRemoved fun(self: EquippableModifier, RemovedInventory: Inventory?, RemovedSlot: integer)

---@class EquippableModifierList
---@field Modifiers EquippableModifier[]

---@class EquippableRowHandle : RowHandle

---@class EquippableTable : IcarusDataTable

---@class ErrorCode : IcarusTableRowBase
---@field Code string
---@field Description string
---@field bReportToSentry boolean

---@class ErrorCodesEnum : RowEnum

---@class ErrorCodesLibrary : RowLibrary
---@field AddRowToErrorCodesTable fun(self: ErrorCodesLibrary, Name: string, Data: ErrorCode|{}, NewRow: ErrorCodesRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakErrorCodesEnum fun(self: ErrorCodesLibrary, Enum: ErrorCodesEnum|{}, Name: string, Index: integer)
---@field CastToErrorCodesRowHandle fun(self: ErrorCodesLibrary, RowHandle: RowHandle|{}, Paths: EValid): ErrorCodesRowHandle
---@field EqualEqual_EnumEnum fun(self: ErrorCodesLibrary, A: ErrorCodesEnum|{}, B: ErrorCodesEnum|{}): boolean
---@field EqualEqual_FErrorCodesRowHandleFErrorCodesRowHandle fun(self: ErrorCodesLibrary, RowHandleA: ErrorCodesRowHandle|{}, RowHandleB: ErrorCodesRowHandle|{}): boolean
---@field GetErrorCodesStruct fun(self: ErrorCodesLibrary, RowHandle: ErrorCodesRowHandle|{}, ErrorCodes: ErrorCode|{}, Paths: EValid)
---@field IntToName fun(self: ErrorCodesLibrary, IntValue: integer): string
---@field IntToStruct fun(self: ErrorCodesLibrary, IntValue: integer): ErrorCodesEnum
---@field IsValidName fun(self: ErrorCodesLibrary, NameValue: string): boolean
---@field MakeErrorCodes fun(self: ErrorCodesLibrary, RowName: string): ErrorCodesRowHandle
---@field MakeErrorCodesEnum fun(self: ErrorCodesLibrary, Enum: ErrorCodesEnum|{}): ErrorCodesEnum
---@field MakeErrorCodesFromIndex fun(self: ErrorCodesLibrary, Index: integer): ErrorCodesRowHandle
---@field MakeLiteralErrorCodes fun(self: ErrorCodesLibrary, RowHandle: ErrorCodesRowHandle|{}): ErrorCodesRowHandle
---@field NameToInt fun(self: ErrorCodesLibrary, NameValue: string): integer
---@field NameToStruct fun(self: ErrorCodesLibrary, NameValue: string): ErrorCodesEnum
---@field NotEqual_EnumEnum fun(self: ErrorCodesLibrary, A: ErrorCodesEnum|{}, B: ErrorCodesEnum|{}): boolean
---@field NotEqual_EnumName fun(self: ErrorCodesLibrary, A: ErrorCodesEnum|{}, B: string): boolean
---@field NumRows fun(self: ErrorCodesLibrary): integer
---@field RefreshConstants fun(self: ErrorCodesLibrary)
---@field RemoveRowFromErrorCodesTable fun(self: ErrorCodesLibrary, Name: string)
---@field RowHandleToStruct fun(self: ErrorCodesLibrary, RowHandle: ErrorCodesRowHandle|{}): ErrorCodesEnum
---@field StructToInt fun(self: ErrorCodesLibrary, EnumValue: ErrorCodesEnum|{}): integer
---@field StructToName fun(self: ErrorCodesLibrary, EnumValue: ErrorCodesEnum|{}): string
---@field StructToRowHandle fun(self: ErrorCodesLibrary, EnumValue: ErrorCodesEnum|{}): ErrorCodesRowHandle

---@class ErrorCodesRowHandle : RowHandle

---@class ErrorCodesTable : IcarusDataTable

---@class EventCooldownList
---@field Cooldowns number[]

---@class ExistingOutpostData
---@field Difficulty EMissionDifficulty
---@field OutpostName string
---@field SelectedDropIndex integer

---@class ExoticSpawn : IcarusTableRowBase

---@class ExoticSpawnEnum : RowEnum

---@class ExoticSpawnLibrary : RowLibrary
---@field AddRowToExoticSpawnTable fun(self: ExoticSpawnLibrary, Name: string, Data: ExoticSpawn|{}, NewRow: ExoticSpawnRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakExoticSpawnEnum fun(self: ExoticSpawnLibrary, Enum: ExoticSpawnEnum|{}, Name: string, Index: integer)
---@field CastToExoticSpawnRowHandle fun(self: ExoticSpawnLibrary, RowHandle: RowHandle|{}, Paths: EValid): ExoticSpawnRowHandle
---@field EqualEqual_EnumEnum fun(self: ExoticSpawnLibrary, A: ExoticSpawnEnum|{}, B: ExoticSpawnEnum|{}): boolean
---@field EqualEqual_FExoticSpawnRowHandleFExoticSpawnRowHandle fun(self: ExoticSpawnLibrary, RowHandleA: ExoticSpawnRowHandle|{}, RowHandleB: ExoticSpawnRowHandle|{}): boolean
---@field GetExoticSpawnStruct fun(self: ExoticSpawnLibrary, RowHandle: ExoticSpawnRowHandle|{}, ExoticSpawn: ExoticSpawn|{}, Paths: EValid)
---@field IntToName fun(self: ExoticSpawnLibrary, IntValue: integer): string
---@field IntToStruct fun(self: ExoticSpawnLibrary, IntValue: integer): ExoticSpawnEnum
---@field IsValidName fun(self: ExoticSpawnLibrary, NameValue: string): boolean
---@field MakeExoticSpawn fun(self: ExoticSpawnLibrary, RowName: string): ExoticSpawnRowHandle
---@field MakeExoticSpawnEnum fun(self: ExoticSpawnLibrary, Enum: ExoticSpawnEnum|{}): ExoticSpawnEnum
---@field MakeExoticSpawnFromIndex fun(self: ExoticSpawnLibrary, Index: integer): ExoticSpawnRowHandle
---@field MakeLiteralExoticSpawn fun(self: ExoticSpawnLibrary, RowHandle: ExoticSpawnRowHandle|{}): ExoticSpawnRowHandle
---@field NameToInt fun(self: ExoticSpawnLibrary, NameValue: string): integer
---@field NameToStruct fun(self: ExoticSpawnLibrary, NameValue: string): ExoticSpawnEnum
---@field NotEqual_EnumEnum fun(self: ExoticSpawnLibrary, A: ExoticSpawnEnum|{}, B: ExoticSpawnEnum|{}): boolean
---@field NotEqual_EnumName fun(self: ExoticSpawnLibrary, A: ExoticSpawnEnum|{}, B: string): boolean
---@field NumRows fun(self: ExoticSpawnLibrary): integer
---@field RefreshConstants fun(self: ExoticSpawnLibrary)
---@field RemoveRowFromExoticSpawnTable fun(self: ExoticSpawnLibrary, Name: string)
---@field RowHandleToStruct fun(self: ExoticSpawnLibrary, RowHandle: ExoticSpawnRowHandle|{}): ExoticSpawnEnum
---@field StructToInt fun(self: ExoticSpawnLibrary, EnumValue: ExoticSpawnEnum|{}): integer
---@field StructToName fun(self: ExoticSpawnLibrary, EnumValue: ExoticSpawnEnum|{}): string
---@field StructToRowHandle fun(self: ExoticSpawnLibrary, EnumValue: ExoticSpawnEnum|{}): ExoticSpawnRowHandle

---@class ExoticSpawnRowHandle : RowHandle

---@class ExoticSpawnTable : IcarusDataTable

---@class ExperienceComponent : TraitComponent
---@field GetExperienceData fun(self: ExperienceComponent, OutData: ExperienceData|{}): boolean
---@field TriggerExperienceEvent fun(self: ExperienceComponent, Type: EExperienceSource, Target: Actor?): boolean

---@class ExperienceData : IcarusTableRowBase
---@field ExperienceEvents table<EExperienceSource, ExperienceInfo>

---@class ExperienceEnum : RowEnum

---@class ExperienceEvent : IcarusTableRowBase
---@field EventDescription string
---@field ExperienceGranted integer
---@field SharedExperience boolean

---@class ExperienceEventsEnum : RowEnum

---@class ExperienceEventsLibrary : RowLibrary
---@field AddRowToExperienceEventsTable fun(self: ExperienceEventsLibrary, Name: string, Data: ExperienceEvent|{}, NewRow: ExperienceEventsRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakExperienceEventsEnum fun(self: ExperienceEventsLibrary, Enum: ExperienceEventsEnum|{}, Name: string, Index: integer)
---@field CastToExperienceEventsRowHandle fun(self: ExperienceEventsLibrary, RowHandle: RowHandle|{}, Paths: EValid): ExperienceEventsRowHandle
---@field EqualEqual_EnumEnum fun(self: ExperienceEventsLibrary, A: ExperienceEventsEnum|{}, B: ExperienceEventsEnum|{}): boolean
---@field EqualEqual_FExperienceEventsRowHandleFExperienceEventsRowHandle fun(self: ExperienceEventsLibrary, RowHandleA: ExperienceEventsRowHandle|{}, RowHandleB: ExperienceEventsRowHandle|{}): boolean
---@field GetExperienceEventsStruct fun(self: ExperienceEventsLibrary, RowHandle: ExperienceEventsRowHandle|{}, ExperienceEvents: ExperienceEvent|{}, Paths: EValid)
---@field IntToName fun(self: ExperienceEventsLibrary, IntValue: integer): string
---@field IntToStruct fun(self: ExperienceEventsLibrary, IntValue: integer): ExperienceEventsEnum
---@field IsValidName fun(self: ExperienceEventsLibrary, NameValue: string): boolean
---@field MakeExperienceEvents fun(self: ExperienceEventsLibrary, RowName: string): ExperienceEventsRowHandle
---@field MakeExperienceEventsEnum fun(self: ExperienceEventsLibrary, Enum: ExperienceEventsEnum|{}): ExperienceEventsEnum
---@field MakeExperienceEventsFromIndex fun(self: ExperienceEventsLibrary, Index: integer): ExperienceEventsRowHandle
---@field MakeLiteralExperienceEvents fun(self: ExperienceEventsLibrary, RowHandle: ExperienceEventsRowHandle|{}): ExperienceEventsRowHandle
---@field NameToInt fun(self: ExperienceEventsLibrary, NameValue: string): integer
---@field NameToStruct fun(self: ExperienceEventsLibrary, NameValue: string): ExperienceEventsEnum
---@field NotEqual_EnumEnum fun(self: ExperienceEventsLibrary, A: ExperienceEventsEnum|{}, B: ExperienceEventsEnum|{}): boolean
---@field NotEqual_EnumName fun(self: ExperienceEventsLibrary, A: ExperienceEventsEnum|{}, B: string): boolean
---@field NumRows fun(self: ExperienceEventsLibrary): integer
---@field RefreshConstants fun(self: ExperienceEventsLibrary)
---@field RemoveRowFromExperienceEventsTable fun(self: ExperienceEventsLibrary, Name: string)
---@field RowHandleToStruct fun(self: ExperienceEventsLibrary, RowHandle: ExperienceEventsRowHandle|{}): ExperienceEventsEnum
---@field StructToInt fun(self: ExperienceEventsLibrary, EnumValue: ExperienceEventsEnum|{}): integer
---@field StructToName fun(self: ExperienceEventsLibrary, EnumValue: ExperienceEventsEnum|{}): string
---@field StructToRowHandle fun(self: ExperienceEventsLibrary, EnumValue: ExperienceEventsEnum|{}): ExperienceEventsRowHandle

---@class ExperienceEventsRowHandle : RowHandle

---@class ExperienceEventsTable : IcarusDataTable

---@class ExperienceInfo
---@field ExperienceEvent ExperienceEventsRowHandle
---@field GainedExperience integer

---@class ExperienceLibrary : RowLibrary
---@field AddRowToExperienceTable fun(self: ExperienceLibrary, Name: string, Data: ExperienceData|{}, NewRow: ExperienceRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakExperienceEnum fun(self: ExperienceLibrary, Enum: ExperienceEnum|{}, Name: string, Index: integer)
---@field CastToExperienceRowHandle fun(self: ExperienceLibrary, RowHandle: RowHandle|{}, Paths: EValid): ExperienceRowHandle
---@field EqualEqual_EnumEnum fun(self: ExperienceLibrary, A: ExperienceEnum|{}, B: ExperienceEnum|{}): boolean
---@field EqualEqual_FExperienceRowHandleFExperienceRowHandle fun(self: ExperienceLibrary, RowHandleA: ExperienceRowHandle|{}, RowHandleB: ExperienceRowHandle|{}): boolean
---@field GetExperienceStruct fun(self: ExperienceLibrary, RowHandle: ExperienceRowHandle|{}, Experience: ExperienceData|{}, Paths: EValid)
---@field IntToName fun(self: ExperienceLibrary, IntValue: integer): string
---@field IntToStruct fun(self: ExperienceLibrary, IntValue: integer): ExperienceEnum
---@field IsValidName fun(self: ExperienceLibrary, NameValue: string): boolean
---@field MakeExperience fun(self: ExperienceLibrary, RowName: string): ExperienceRowHandle
---@field MakeExperienceEnum fun(self: ExperienceLibrary, Enum: ExperienceEnum|{}): ExperienceEnum
---@field MakeExperienceFromIndex fun(self: ExperienceLibrary, Index: integer): ExperienceRowHandle
---@field MakeLiteralExperience fun(self: ExperienceLibrary, RowHandle: ExperienceRowHandle|{}): ExperienceRowHandle
---@field NameToInt fun(self: ExperienceLibrary, NameValue: string): integer
---@field NameToStruct fun(self: ExperienceLibrary, NameValue: string): ExperienceEnum
---@field NotEqual_EnumEnum fun(self: ExperienceLibrary, A: ExperienceEnum|{}, B: ExperienceEnum|{}): boolean
---@field NotEqual_EnumName fun(self: ExperienceLibrary, A: ExperienceEnum|{}, B: string): boolean
---@field NumRows fun(self: ExperienceLibrary): integer
---@field RefreshConstants fun(self: ExperienceLibrary)
---@field RemoveRowFromExperienceTable fun(self: ExperienceLibrary, Name: string)
---@field RowHandleToStruct fun(self: ExperienceLibrary, RowHandle: ExperienceRowHandle|{}): ExperienceEnum
---@field StructToInt fun(self: ExperienceLibrary, EnumValue: ExperienceEnum|{}): integer
---@field StructToName fun(self: ExperienceLibrary, EnumValue: ExperienceEnum|{}): string
---@field StructToRowHandle fun(self: ExperienceLibrary, EnumValue: ExperienceEnum|{}): ExperienceRowHandle

---@class ExperienceRowHandle : RowHandle

---@class ExperienceTable : IcarusDataTable

---@class ExplosiveDamage : IcarusDamageType

---@class ExportedCurrency
---@field CurrencyRewardRow string
---@field TotalCurrencyExported integer

---@class ExtractionSubsystem : WorldSubsystem
---@field OnItemExtractedNotify GameDelegate
---@field BroadcastItemExtractedDelegate fun(self: ExtractionSubsystem, Device: Actor?, Item: ItemData|{})
