---@meta _
-- Generated by scripts\gameindex.py from the index of the game's classes. Changes here are lost on the next run.

---@class LadderComponent : ActorComponent
---@field GetLadderEnd fun(self: LadderComponent): Transform
---@field GetLadderStart fun(self: LadderComponent): Transform
---@field GetOutermostLadder fun(self: LadderComponent): LadderComponent

---@class Lake : WaterBody
---@field FishManager FishManager
---@field LakeScale Vector
---@field WaterPoints WaterPoint[]
---@field bIsFishVolume boolean

---@class LakeSplineComponent : EdgeSplineComponent
---@field ConstructFromPrefabTemplate fun(self: LakeSplineComponent, PrefabLake: PrefabLake|{})
---@field ConstructFromTransformArray fun(self: LakeSplineComponent, Transforms: Transform[], LoopDirection: ESplineLoopDirection)
---@field GetEdgePointsFromLakePoints fun(self: LakeSplineComponent, LakePoints: table<IntPoint, Vector>): Vector[]
---@field GetEditorViewportCameraLocation fun(self: LakeSplineComponent): Vector
---@field GetLakePoints fun(self: LakeSplineComponent, Target: Actor?, Transform: Transform|{}, TraceLocations: Vector[], Density: number): table<IntPoint, Vector>

---@class LandingPadComponent : ActorComponent
---@field PlayerID PlayerCharacterID
---@field TimeBuilt integer
---@field AssignPlayer fun(self: LandingPadComponent, InPlayerID: PlayerCharacterID|{})
---@field ClearAssignedPlayer fun(self: LandingPadComponent)
---@field GetPlayerID fun(self: LandingPadComponent): PlayerCharacterID
---@field GetPlayerName fun(self: LandingPadComponent): string
---@field GetTimeBuilt fun(self: LandingPadComponent): integer
---@field HasPlayer fun(self: LandingPadComponent): boolean
---@field InitTimeBuilt fun(self: LandingPadComponent, InTimeBuilt: integer)
---@field IsPlayerAssigned fun(self: LandingPadComponent, InID: PlayerCharacterID|{}): boolean

---@class LandingPadRecord
---@field LeveTimeBuilt integer
---@field PlayerID PlayerCharacterID

---@class LandingPadRecorderComponent : DeployableRecorderComponent
---@field LandingPadRecord LandingPadRecord

---@class LanguagesData : IcarusTableRowBase
---@field Coverage integer
---@field bEnabled boolean

---@class LanguagesEnum : RowEnum

---@class LanguagesLibrary : RowLibrary
---@field AddRowToLanguagesTable fun(self: LanguagesLibrary, Name: string, Data: LanguagesData|{}, NewRow: LanguagesRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakLanguagesEnum fun(self: LanguagesLibrary, Enum: LanguagesEnum|{}, Name: string, Index: integer)
---@field CastToLanguagesRowHandle fun(self: LanguagesLibrary, RowHandle: RowHandle|{}, Paths: EValid): LanguagesRowHandle
---@field EqualEqual_EnumEnum fun(self: LanguagesLibrary, A: LanguagesEnum|{}, B: LanguagesEnum|{}): boolean
---@field EqualEqual_FLanguagesRowHandleFLanguagesRowHandle fun(self: LanguagesLibrary, RowHandleA: LanguagesRowHandle|{}, RowHandleB: LanguagesRowHandle|{}): boolean
---@field GetLanguagesStruct fun(self: LanguagesLibrary, RowHandle: LanguagesRowHandle|{}, Languages: LanguagesData|{}, Paths: EValid)
---@field IntToName fun(self: LanguagesLibrary, IntValue: integer): string
---@field IntToStruct fun(self: LanguagesLibrary, IntValue: integer): LanguagesEnum
---@field IsValidName fun(self: LanguagesLibrary, NameValue: string): boolean
---@field MakeLanguages fun(self: LanguagesLibrary, RowName: string): LanguagesRowHandle
---@field MakeLanguagesEnum fun(self: LanguagesLibrary, Enum: LanguagesEnum|{}): LanguagesEnum
---@field MakeLanguagesFromIndex fun(self: LanguagesLibrary, Index: integer): LanguagesRowHandle
---@field MakeLiteralLanguages fun(self: LanguagesLibrary, RowHandle: LanguagesRowHandle|{}): LanguagesRowHandle
---@field NameToInt fun(self: LanguagesLibrary, NameValue: string): integer
---@field NameToStruct fun(self: LanguagesLibrary, NameValue: string): LanguagesEnum
---@field NotEqual_EnumEnum fun(self: LanguagesLibrary, A: LanguagesEnum|{}, B: LanguagesEnum|{}): boolean
---@field NotEqual_EnumName fun(self: LanguagesLibrary, A: LanguagesEnum|{}, B: string): boolean
---@field NumRows fun(self: LanguagesLibrary): integer
---@field RefreshConstants fun(self: LanguagesLibrary)
---@field RemoveRowFromLanguagesTable fun(self: LanguagesLibrary, Name: string)
---@field RowHandleToStruct fun(self: LanguagesLibrary, RowHandle: LanguagesRowHandle|{}): LanguagesEnum
---@field StructToInt fun(self: LanguagesLibrary, EnumValue: LanguagesEnum|{}): integer
---@field StructToName fun(self: LanguagesLibrary, EnumValue: LanguagesEnum|{}): string
---@field StructToRowHandle fun(self: LanguagesLibrary, EnumValue: LanguagesEnum|{}): LanguagesRowHandle

---@class LanguagesRowHandle : RowHandle

---@class LanguagesTable : IcarusDataTable

---@class LargeScaleDestroyParams
---@field CleanupAfterDelay number
---@field DamageDurationSec number
---@field DamageRadiusCm integer
---@field DamageToDestroyRatio integer
---@field DamageType EIcarusDamageType
---@field IgnoreActors Actor[]
---@field Location Vector
---@field NPCDamageAmount integer
---@field Pattern EDestroyPattern
---@field PlayerDamageAmount integer
---@field PlayerDamageRadiusCm integer
---@field StructuresDamageAmount integer

---@class LaserDamage : IcarusDamageType

---@class LastProspectHostInfo
---@field CachedServerName string
---@field DedicatedServerIP string
---@field LastHostType ELastProspectHostType
---@field SteamP2PHostId string

---@class LaunchItemReturnInfo
---@field Items ItemData[]
---@field OwningPlayerID string

---@class LavaRiverFlowPointData
---@field BaseToFlowing number
---@field Extent Vector2D
---@field FlowSpeed number
---@field Location Vector2D

---@class LevelSequencesData : IcarusTableRowBase
---@field Level World
---@field LevelSequences table<string, LevelSequence>

---@class LevelSequencesEnum : RowEnum

---@class LevelSequencesLibrary : RowLibrary
---@field AddRowToLevelSequencesTable fun(self: LevelSequencesLibrary, Name: string, Data: LevelSequencesData|{}, NewRow: LevelSequencesRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakLevelSequencesEnum fun(self: LevelSequencesLibrary, Enum: LevelSequencesEnum|{}, Name: string, Index: integer)
---@field CastToLevelSequencesRowHandle fun(self: LevelSequencesLibrary, RowHandle: RowHandle|{}, Paths: EValid): LevelSequencesRowHandle
---@field EqualEqual_EnumEnum fun(self: LevelSequencesLibrary, A: LevelSequencesEnum|{}, B: LevelSequencesEnum|{}): boolean
---@field EqualEqual_FLevelSequencesRowHandleFLevelSequencesRowHandle fun(self: LevelSequencesLibrary, RowHandleA: LevelSequencesRowHandle|{}, RowHandleB: LevelSequencesRowHandle|{}): boolean
---@field GetLevelSequencesStruct fun(self: LevelSequencesLibrary, RowHandle: LevelSequencesRowHandle|{}, LevelSequences: LevelSequencesData|{}, Paths: EValid)
---@field IntToName fun(self: LevelSequencesLibrary, IntValue: integer): string
---@field IntToStruct fun(self: LevelSequencesLibrary, IntValue: integer): LevelSequencesEnum
---@field IsValidName fun(self: LevelSequencesLibrary, NameValue: string): boolean
---@field MakeLevelSequences fun(self: LevelSequencesLibrary, RowName: string): LevelSequencesRowHandle
---@field MakeLevelSequencesEnum fun(self: LevelSequencesLibrary, Enum: LevelSequencesEnum|{}): LevelSequencesEnum
---@field MakeLevelSequencesFromIndex fun(self: LevelSequencesLibrary, Index: integer): LevelSequencesRowHandle
---@field MakeLiteralLevelSequences fun(self: LevelSequencesLibrary, RowHandle: LevelSequencesRowHandle|{}): LevelSequencesRowHandle
---@field NameToInt fun(self: LevelSequencesLibrary, NameValue: string): integer
---@field NameToStruct fun(self: LevelSequencesLibrary, NameValue: string): LevelSequencesEnum
---@field NotEqual_EnumEnum fun(self: LevelSequencesLibrary, A: LevelSequencesEnum|{}, B: LevelSequencesEnum|{}): boolean
---@field NotEqual_EnumName fun(self: LevelSequencesLibrary, A: LevelSequencesEnum|{}, B: string): boolean
---@field NumRows fun(self: LevelSequencesLibrary): integer
---@field RefreshConstants fun(self: LevelSequencesLibrary)
---@field RemoveRowFromLevelSequencesTable fun(self: LevelSequencesLibrary, Name: string)
---@field RowHandleToStruct fun(self: LevelSequencesLibrary, RowHandle: LevelSequencesRowHandle|{}): LevelSequencesEnum
---@field StructToInt fun(self: LevelSequencesLibrary, EnumValue: LevelSequencesEnum|{}): integer
---@field StructToName fun(self: LevelSequencesLibrary, EnumValue: LevelSequencesEnum|{}): string
---@field StructToRowHandle fun(self: LevelSequencesLibrary, EnumValue: LevelSequencesEnum|{}): LevelSequencesRowHandle

---@class LevelSequencesRowHandle : RowHandle

---@class LevelSequencesTable : IcarusDataTable

---@class LevelStreamingBinding : Object
---@field LevelBounds Box2D
---@field LevelLandscapeProxy LandscapeProxy
---@field StreamingLevel LevelStreaming
---@field bIsGeneratedLevel boolean
---@field bLevelAnchorValid boolean
---@field OnStreamingLevelHidden fun(self: LevelStreamingBinding)
---@field OnStreamingLevelLoaded fun(self: LevelStreamingBinding)
---@field OnStreamingLevelShown fun(self: LevelStreamingBinding)
---@field OnStreamingLevelUnloaded fun(self: LevelStreamingBinding)

---@class LevelStreamingDelegateManager : Object
---@field OnLevelStreamingStateUpdated GameDelegate
---@field StreamingLevel LevelStreaming
---@field OnLevelHidden fun(self: LevelStreamingDelegateManager)
---@field OnLevelLoaded fun(self: LevelStreamingDelegateManager)
---@field OnLevelShown fun(self: LevelStreamingDelegateManager)
---@field OnLevelUnloaded fun(self: LevelStreamingDelegateManager)
---@field OnStreamingLevelStateUpdated fun(self: LevelStreamingDelegateManager)

---@class LinearColorVariableRecord
---@field Variable LinearColor
---@field VariableName string

---@class LivingItemBlueprintFunctionLibrary : BlueprintFunctionLibrary
---@field GetEquippedItemUpgrades fun(self: LivingItemBlueprintFunctionLibrary, Item: ItemData|{}, Upgrades: LivingItemUpgradeData[]): boolean Do not call from Lua: it needs 520 bytes and the call buffer holds 512.
---@field GetLivingItemActiveChallengeSlotState fun(self: LivingItemBlueprintFunctionLibrary, Item: ItemData|{}, ActiveQuestSlot: LivingItemSlotState|{}): boolean Do not call from Lua: it needs 624 bytes and the call buffer holds 512.
---@field GetLivingItemSlotStates fun(self: LivingItemBlueprintFunctionLibrary, Item: ItemData|{}, Slots: LivingItemSlotState[]): boolean Do not call from Lua: it needs 520 bytes and the call buffer holds 512.
---@field IsLivingItemUpgradeEquipped fun(self: LivingItemBlueprintFunctionLibrary, Item: ItemData|{}, Upgrade: LivingItemUpgradesRowHandle|{}): boolean Do not call from Lua: it needs 528 bytes and the call buffer holds 512.
---@field SetLivingItemUpgrade fun(self: LivingItemBlueprintFunctionLibrary, Item: ItemData|{}, Slot: integer, Upgrade: LivingItemUpgradesRowHandle|{}): boolean Do not call from Lua: it needs 528 bytes and the call buffer holds 512.
---@field UpdateLivingItemChallengeProgress fun(self: LivingItemBlueprintFunctionLibrary, OwningCharacter: IcarusPlayerCharacter?, Item: ItemData|{}, Challenge: ChallengesRowHandle|{}, ProgressIncrease: integer) Do not call from Lua: it needs 536 bytes and the call buffer holds 512.

---@class LivingItemComponent : TraitComponent
---@field AppliedMeshCustomisations table<StaticMeshComponent, MeshCustomisationData>
---@field AttachedStaticMeshes StaticMeshComponent[]
---@field Cheat_AddChallengeProgress fun(self: LivingItemComponent, Amount: integer)
---@field Cheat_CompleteActiveChallenge fun(self: LivingItemComponent)
---@field Cheat_CompleteAllChallenges fun(self: LivingItemComponent)
---@field Cheat_SetUpgradeInSlot fun(self: LivingItemComponent, SlotIndex: integer, Upgrade: LivingItemUpgradesRowHandle|{})
---@field FinaliseMeshCustomisations fun(self: LivingItemComponent)
---@field GetActiveChallengeData fun(self: LivingItemComponent): Challenge
---@field GetLivingItemData fun(self: LivingItemComponent, OutData: LivingItemData|{}): boolean
---@field HasActiveChallenge fun(self: LivingItemComponent): boolean
---@field IsAsyncLoadingMeshes fun(self: LivingItemComponent): boolean
---@field OnCorpseItemRemovedNotify fun(self: LivingItemComponent, Player: IcarusPlayerCharacter?, Item: ItemData|{})
---@field OnCreatureKilledNotify fun(self: LivingItemComponent, Player: IcarusPlayerCharacter?, Causer: IcarusActor?, Creature: Actor?, KillingBlowFromPlayer: Pawn?)
---@field OnCreatureSkinnedNotify fun(self: LivingItemComponent, Player: IcarusPlayerCharacter?, Corpse: IcarusCorpse?)
---@field OnItemHarvestedNotify fun(self: LivingItemComponent, Player: IcarusPlayerCharacter?, Item: ItemData|{})
---@field OnPlayerPerformedCriticalHitNotify fun(self: LivingItemComponent, Player: IcarusPlayerCharacter?, HitLocation: Vector|{}, CriticalHitArea: CriticalHitAreasEnum|{})
---@field OnPlayerPerformedStealthAttackNotify fun(self: LivingItemComponent, Player: IcarusPlayerCharacter?)
---@field OnTreeFelledNotify fun(self: LivingItemComponent, Player: IcarusPlayerCharacter?)
---@field OnTreeResourceCollectedNotify fun(self: LivingItemComponent, Player: IcarusPlayerCharacter?, Item: ItemData|{})
---@field OnVoxelCompletedNotify fun(self: LivingItemComponent, Player: IcarusPlayerCharacter?, Voxel: VoxelResource?)
---@field OnVoxelResourceMinedNotify fun(self: LivingItemComponent, Player: IcarusPlayerCharacter?, Item: ItemData|{})
---@field RebuildMesh fun(self: LivingItemComponent)

---@class LivingItemData : IcarusTableRowBase
---@field BehaviourOverride Class
---@field ItemPreviewOffset Vector
---@field ItemPreviewRotation Rotator
---@field PreviewMeshOverride SkeletalMesh
---@field UpgradeSlots LivingItemUpgradeSlotData[]

---@class LivingItemEnum : RowEnum

---@class LivingItemLibrary : RowLibrary
---@field AddRowToLivingItemTable fun(self: LivingItemLibrary, Name: string, Data: LivingItemData|{}, NewRow: LivingItemRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakLivingItemEnum fun(self: LivingItemLibrary, Enum: LivingItemEnum|{}, Name: string, Index: integer)
---@field CastToLivingItemRowHandle fun(self: LivingItemLibrary, RowHandle: RowHandle|{}, Paths: EValid): LivingItemRowHandle
---@field EqualEqual_EnumEnum fun(self: LivingItemLibrary, A: LivingItemEnum|{}, B: LivingItemEnum|{}): boolean
---@field EqualEqual_FLivingItemRowHandleFLivingItemRowHandle fun(self: LivingItemLibrary, RowHandleA: LivingItemRowHandle|{}, RowHandleB: LivingItemRowHandle|{}): boolean
---@field GetLivingItemStruct fun(self: LivingItemLibrary, RowHandle: LivingItemRowHandle|{}, LivingItem: LivingItemData|{}, Paths: EValid)
---@field IntToName fun(self: LivingItemLibrary, IntValue: integer): string
---@field IntToStruct fun(self: LivingItemLibrary, IntValue: integer): LivingItemEnum
---@field IsValidName fun(self: LivingItemLibrary, NameValue: string): boolean
---@field MakeLiteralLivingItem fun(self: LivingItemLibrary, RowHandle: LivingItemRowHandle|{}): LivingItemRowHandle
---@field MakeLivingItem fun(self: LivingItemLibrary, RowName: string): LivingItemRowHandle
---@field MakeLivingItemEnum fun(self: LivingItemLibrary, Enum: LivingItemEnum|{}): LivingItemEnum
---@field MakeLivingItemFromIndex fun(self: LivingItemLibrary, Index: integer): LivingItemRowHandle
---@field NameToInt fun(self: LivingItemLibrary, NameValue: string): integer
---@field NameToStruct fun(self: LivingItemLibrary, NameValue: string): LivingItemEnum
---@field NotEqual_EnumEnum fun(self: LivingItemLibrary, A: LivingItemEnum|{}, B: LivingItemEnum|{}): boolean
---@field NotEqual_EnumName fun(self: LivingItemLibrary, A: LivingItemEnum|{}, B: string): boolean
---@field NumRows fun(self: LivingItemLibrary): integer
---@field RefreshConstants fun(self: LivingItemLibrary)
---@field RemoveRowFromLivingItemTable fun(self: LivingItemLibrary, Name: string)
---@field RowHandleToStruct fun(self: LivingItemLibrary, RowHandle: LivingItemRowHandle|{}): LivingItemEnum
---@field StructToInt fun(self: LivingItemLibrary, EnumValue: LivingItemEnum|{}): integer
---@field StructToName fun(self: LivingItemLibrary, EnumValue: LivingItemEnum|{}): string
---@field StructToRowHandle fun(self: LivingItemLibrary, EnumValue: LivingItemEnum|{}): LivingItemRowHandle

---@class LivingItemRowHandle : RowHandle

---@class LivingItemShopItemData : IcarusTableRowBase
---@field Biomass ItemsStaticRowHandle
---@field BossIcon Texture2D
---@field Cost WorkshopCost[]
---@field ItemBackground Texture2D
---@field ItemImage Texture2D
---@field ItemTemplate ItemTemplateRowHandle
---@field RequiredAccountFlag AccountFlagsRowHandle
---@field RequiredPackageToPurchase DLCPackageDataRowHandle
---@field ShopBackground Texture2D

---@class LivingItemShopItemsEnum : RowEnum

---@class LivingItemShopItemsLibrary : RowLibrary
---@field AddRowToLivingItemShopItemsTable fun(self: LivingItemShopItemsLibrary, Name: string, Data: LivingItemShopItemData|{}, NewRow: LivingItemShopItemsRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakLivingItemShopItemsEnum fun(self: LivingItemShopItemsLibrary, Enum: LivingItemShopItemsEnum|{}, Name: string, Index: integer)
---@field CastToLivingItemShopItemsRowHandle fun(self: LivingItemShopItemsLibrary, RowHandle: RowHandle|{}, Paths: EValid): LivingItemShopItemsRowHandle
---@field EqualEqual_EnumEnum fun(self: LivingItemShopItemsLibrary, A: LivingItemShopItemsEnum|{}, B: LivingItemShopItemsEnum|{}): boolean
---@field EqualEqual_FLivingItemShopItemsRowHandleFLivingItemShopItemsRowHandle fun(self: LivingItemShopItemsLibrary, RowHandleA: LivingItemShopItemsRowHandle|{}, RowHandleB: LivingItemShopItemsRowHandle|{}): boolean
---@field GetLivingItemShopItemsStruct fun(self: LivingItemShopItemsLibrary, RowHandle: LivingItemShopItemsRowHandle|{}, LivingItemShopItems: LivingItemShopItemData|{}, Paths: EValid)
---@field IntToName fun(self: LivingItemShopItemsLibrary, IntValue: integer): string
---@field IntToStruct fun(self: LivingItemShopItemsLibrary, IntValue: integer): LivingItemShopItemsEnum
---@field IsValidName fun(self: LivingItemShopItemsLibrary, NameValue: string): boolean
---@field MakeLiteralLivingItemShopItems fun(self: LivingItemShopItemsLibrary, RowHandle: LivingItemShopItemsRowHandle|{}): LivingItemShopItemsRowHandle
---@field MakeLivingItemShopItems fun(self: LivingItemShopItemsLibrary, RowName: string): LivingItemShopItemsRowHandle
---@field MakeLivingItemShopItemsEnum fun(self: LivingItemShopItemsLibrary, Enum: LivingItemShopItemsEnum|{}): LivingItemShopItemsEnum
---@field MakeLivingItemShopItemsFromIndex fun(self: LivingItemShopItemsLibrary, Index: integer): LivingItemShopItemsRowHandle
---@field NameToInt fun(self: LivingItemShopItemsLibrary, NameValue: string): integer
---@field NameToStruct fun(self: LivingItemShopItemsLibrary, NameValue: string): LivingItemShopItemsEnum
---@field NotEqual_EnumEnum fun(self: LivingItemShopItemsLibrary, A: LivingItemShopItemsEnum|{}, B: LivingItemShopItemsEnum|{}): boolean
---@field NotEqual_EnumName fun(self: LivingItemShopItemsLibrary, A: LivingItemShopItemsEnum|{}, B: string): boolean
---@field NumRows fun(self: LivingItemShopItemsLibrary): integer
---@field RefreshConstants fun(self: LivingItemShopItemsLibrary)
---@field RemoveRowFromLivingItemShopItemsTable fun(self: LivingItemShopItemsLibrary, Name: string)
---@field RowHandleToStruct fun(self: LivingItemShopItemsLibrary, RowHandle: LivingItemShopItemsRowHandle|{}): LivingItemShopItemsEnum
---@field StructToInt fun(self: LivingItemShopItemsLibrary, EnumValue: LivingItemShopItemsEnum|{}): integer
---@field StructToName fun(self: LivingItemShopItemsLibrary, EnumValue: LivingItemShopItemsEnum|{}): string
---@field StructToRowHandle fun(self: LivingItemShopItemsLibrary, EnumValue: LivingItemShopItemsEnum|{}): LivingItemShopItemsRowHandle

---@class LivingItemShopItemsRowHandle : RowHandle

---@class LivingItemShopItemsTable : IcarusDataTable

---@class LivingItemSlotSaveData
---@field CurrentProgress integer
---@field CurrentUpgrade string

---@class LivingItemSlotState
---@field ChallengeProgress integer
---@field CurrentUpgrade LivingItemUpgradesRowHandle
---@field SlotData LivingItemUpgradeSlotData
---@field SlotIndex integer
---@field bIsActiveChallenge boolean
---@field bSlotUnlocked boolean

---@class LivingItemTable : IcarusDataTable

---@class LivingItemUpgradeData : IcarusTableRowBase
---@field AlterationToApply AlterationsRowHandle
---@field MeshCustomisations MeshCustomisationData[]
---@field UpgradeCost WorkshopCost[]

---@class LivingItemUpgradeSlot
---@field UnlockProgress integer
---@field UpgradeSelection LivingItemUpgradesEnum

---@class LivingItemUpgradeSlotData
---@field AvailableUpgrades LivingItemUpgradesRowHandle[]
---@field ChallengeToUnlock ChallengesRowHandle
---@field DefaultSlotMeshes MeshCustomisationData[]
---@field PinBendPosition2D Vector2D
---@field PinPosition2D Vector2D
---@field SlotPosition2D Vector2D

---@class LivingItemUpgradesEnum : RowEnum

---@class LivingItemUpgradesLibrary : RowLibrary
---@field AddRowToLivingItemUpgradesTable fun(self: LivingItemUpgradesLibrary, Name: string, Data: LivingItemUpgradeData|{}, NewRow: LivingItemUpgradesRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakLivingItemUpgradesEnum fun(self: LivingItemUpgradesLibrary, Enum: LivingItemUpgradesEnum|{}, Name: string, Index: integer)
---@field CastToLivingItemUpgradesRowHandle fun(self: LivingItemUpgradesLibrary, RowHandle: RowHandle|{}, Paths: EValid): LivingItemUpgradesRowHandle
---@field EqualEqual_EnumEnum fun(self: LivingItemUpgradesLibrary, A: LivingItemUpgradesEnum|{}, B: LivingItemUpgradesEnum|{}): boolean
---@field EqualEqual_FLivingItemUpgradesRowHandleFLivingItemUpgradesRowHandle fun(self: LivingItemUpgradesLibrary, RowHandleA: LivingItemUpgradesRowHandle|{}, RowHandleB: LivingItemUpgradesRowHandle|{}): boolean
---@field GetLivingItemUpgradesStruct fun(self: LivingItemUpgradesLibrary, RowHandle: LivingItemUpgradesRowHandle|{}, LivingItemUpgrades: LivingItemUpgradeData|{}, Paths: EValid)
---@field IntToName fun(self: LivingItemUpgradesLibrary, IntValue: integer): string
---@field IntToStruct fun(self: LivingItemUpgradesLibrary, IntValue: integer): LivingItemUpgradesEnum
---@field IsValidName fun(self: LivingItemUpgradesLibrary, NameValue: string): boolean
---@field MakeLiteralLivingItemUpgrades fun(self: LivingItemUpgradesLibrary, RowHandle: LivingItemUpgradesRowHandle|{}): LivingItemUpgradesRowHandle
---@field MakeLivingItemUpgrades fun(self: LivingItemUpgradesLibrary, RowName: string): LivingItemUpgradesRowHandle
---@field MakeLivingItemUpgradesEnum fun(self: LivingItemUpgradesLibrary, Enum: LivingItemUpgradesEnum|{}): LivingItemUpgradesEnum
---@field MakeLivingItemUpgradesFromIndex fun(self: LivingItemUpgradesLibrary, Index: integer): LivingItemUpgradesRowHandle
---@field NameToInt fun(self: LivingItemUpgradesLibrary, NameValue: string): integer
---@field NameToStruct fun(self: LivingItemUpgradesLibrary, NameValue: string): LivingItemUpgradesEnum
---@field NotEqual_EnumEnum fun(self: LivingItemUpgradesLibrary, A: LivingItemUpgradesEnum|{}, B: LivingItemUpgradesEnum|{}): boolean
---@field NotEqual_EnumName fun(self: LivingItemUpgradesLibrary, A: LivingItemUpgradesEnum|{}, B: string): boolean
---@field NumRows fun(self: LivingItemUpgradesLibrary): integer
---@field RefreshConstants fun(self: LivingItemUpgradesLibrary)
---@field RemoveRowFromLivingItemUpgradesTable fun(self: LivingItemUpgradesLibrary, Name: string)
---@field RowHandleToStruct fun(self: LivingItemUpgradesLibrary, RowHandle: LivingItemUpgradesRowHandle|{}): LivingItemUpgradesEnum
---@field StructToInt fun(self: LivingItemUpgradesLibrary, EnumValue: LivingItemUpgradesEnum|{}): integer
---@field StructToName fun(self: LivingItemUpgradesLibrary, EnumValue: LivingItemUpgradesEnum|{}): string
---@field StructToRowHandle fun(self: LivingItemUpgradesLibrary, EnumValue: LivingItemUpgradesEnum|{}): LivingItemUpgradesRowHandle

---@class LivingItemUpgradesRowHandle : RowHandle

---@class LivingItemUpgradesTable : IcarusDataTable

---@class LoadedLevelInfo
---@field LoadedDynamicLevel LevelStreamingDynamic
---@field LocationToLoadLevel Vector
---@field PickedSlot integer
---@field Players IcarusPlayerCharacter[]
---@field Requestor TeleportComponent

---@class LoadingScreenInterface : Interface
---@field InitLoadingScreen fun(self: LoadingScreenInterface, LevelName: string)

---@class LoadingScreenSettings : DeveloperSettings
---@field DefaultLoadingScreenWidget Class
---@field InBetweenLoadingScreenWidget Class
---@field InBetweenLoadingVideos string[]
---@field MinimumLoadingScreenDisplayTime number
---@field PerLevelLoadingScreens table<string, Class>
---@field PostLoadFadeInDuration number

---@class LocomotionAnims
---@field CrouchWalkB AnimSequence
---@field CrouchWalkF AnimSequence
---@field CrouchWalkL AnimSequence
---@field CrouchWalkR AnimSequence
---@field RunB AnimSequence
---@field RunF AnimSequence
---@field RunL AnimSequence
---@field RunR AnimSequence
---@field SprintF AnimSequence
---@field WalkB AnimSequence
---@field WalkF AnimSequence
---@field WalkL AnimSequence
---@field WalkR AnimSequence

---@class LogCategoriesEnum : RowEnum

---@class LogCategoriesLibrary : RowLibrary
---@field AddRowToLogCategoriesTable fun(self: LogCategoriesLibrary, Name: string, Data: IcarusLogCategory|{}, NewRow: LogCategoriesRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakLogCategoriesEnum fun(self: LogCategoriesLibrary, Enum: LogCategoriesEnum|{}, Name: string, Index: integer)
---@field CastToLogCategoriesRowHandle fun(self: LogCategoriesLibrary, RowHandle: RowHandle|{}, Paths: EValid): LogCategoriesRowHandle
---@field EqualEqual_EnumEnum fun(self: LogCategoriesLibrary, A: LogCategoriesEnum|{}, B: LogCategoriesEnum|{}): boolean
---@field EqualEqual_FLogCategoriesRowHandleFLogCategoriesRowHandle fun(self: LogCategoriesLibrary, RowHandleA: LogCategoriesRowHandle|{}, RowHandleB: LogCategoriesRowHandle|{}): boolean
---@field GetLogCategoriesStruct fun(self: LogCategoriesLibrary, RowHandle: LogCategoriesRowHandle|{}, LogCategories: IcarusLogCategory|{}, Paths: EValid)
---@field IntToName fun(self: LogCategoriesLibrary, IntValue: integer): string
---@field IntToStruct fun(self: LogCategoriesLibrary, IntValue: integer): LogCategoriesEnum
---@field IsValidName fun(self: LogCategoriesLibrary, NameValue: string): boolean
---@field MakeLiteralLogCategories fun(self: LogCategoriesLibrary, RowHandle: LogCategoriesRowHandle|{}): LogCategoriesRowHandle
---@field MakeLogCategories fun(self: LogCategoriesLibrary, RowName: string): LogCategoriesRowHandle
---@field MakeLogCategoriesEnum fun(self: LogCategoriesLibrary, Enum: LogCategoriesEnum|{}): LogCategoriesEnum
---@field MakeLogCategoriesFromIndex fun(self: LogCategoriesLibrary, Index: integer): LogCategoriesRowHandle
---@field NameToInt fun(self: LogCategoriesLibrary, NameValue: string): integer
---@field NameToStruct fun(self: LogCategoriesLibrary, NameValue: string): LogCategoriesEnum
---@field NotEqual_EnumEnum fun(self: LogCategoriesLibrary, A: LogCategoriesEnum|{}, B: LogCategoriesEnum|{}): boolean
---@field NotEqual_EnumName fun(self: LogCategoriesLibrary, A: LogCategoriesEnum|{}, B: string): boolean
---@field NumRows fun(self: LogCategoriesLibrary): integer
---@field RefreshConstants fun(self: LogCategoriesLibrary)
---@field RemoveRowFromLogCategoriesTable fun(self: LogCategoriesLibrary, Name: string)
---@field RowHandleToStruct fun(self: LogCategoriesLibrary, RowHandle: LogCategoriesRowHandle|{}): LogCategoriesEnum
---@field StructToInt fun(self: LogCategoriesLibrary, EnumValue: LogCategoriesEnum|{}): integer
---@field StructToName fun(self: LogCategoriesLibrary, EnumValue: LogCategoriesEnum|{}): string
---@field StructToRowHandle fun(self: LogCategoriesLibrary, EnumValue: LogCategoriesEnum|{}): LogCategoriesRowHandle

---@class LogCategoriesRowHandle : RowHandle

---@class LogCategoriesTable : IcarusDataTable

---@class LogOverlayFunctionLibrary : BlueprintFunctionLibrary
---@field IsLogValid fun(self: LogOverlayFunctionLibrary, Log: IcarusLogEntry|{}): boolean
---@field LogTimestampToString fun(self: LogOverlayFunctionLibrary, Timestamp: DateTime|{}): string
