---@meta _
-- Generated by scripts\gameindex.py from the index of the game's classes. Changes here are lost on the next run.

---@class ObjectSlot : IcarusActor
---@field AttachedActor Deployable
---@field HighlightableComponent HighlightableComponent
---@field InteractableComponent InteractableComponent
---@field LinkedSlot ObjectSlot
---@field OnLinkDestroyed GameDelegate
---@field OnLinkEstablished GameDelegate
---@field SlotType EObjectSlotType
---@field CanLink fun(self: ObjectSlot, SlotToConnect: ObjectSlot?): boolean
---@field GetSlotInventory fun(self: ObjectSlot): InventoryComponent
---@field OnInteraction fun(self: ObjectSlot, Interactor: Actor?, HitResult: HitResult|{})
---@field OnServer_Interact fun(self: ObjectSlot, Interactor: Actor?, HitResult: HitResult|{}): boolean
---@field OnServer_LinkSlots fun(self: ObjectSlot, SlotToConnect: ObjectSlot?)
---@field OnServer_UnlinkSlots fun(self: ObjectSlot)
---@field UpdateVisibility fun(self: ObjectSlot): boolean

---@class OfflineAccountMigrator : Object
---@field CurrentMigrationStep EMigrationStep
---@field DownloadedAccountData OnlineProfileUser
---@field DownloadedCharacters OnlineProfileCharacter[]
---@field DownloadedProspectInfos ProspectInfo[]
---@field GetCharacterLoadoutCallbackProxy GetCharacterLoadoutCallbackProxyGen
---@field GetCharactersCallbackProxy GetCharactersCallbackProxyGen
---@field GetLoadoutInventoryCallbackProxy GetLoadoutInventoryCallbackProxyGen
---@field GetMetaInventoryCallbackProxy GetMetaInventoryCallbackProxyGen
---@field GetPreparedLoadoutCallbackProxy GetPreparedLoadoutCallbackProxyGen
---@field GetProspectCallbackProxy GetProspectCallbackProxyGen
---@field GetProspectsCallbackProxy GetAllProspectsCallbackProxyGen
---@field GetUserProfileCallbackProxy GetUserProfileCallbackProxyGen
---@field MergedCharacters OnlineProfileCharacter[]
---@field OfflineAccountData OnlineProfileUser
---@field OfflineCharacters OnlineProfileCharacter[]
---@field OfflineProspectInfos ProspectInfo[]
---@field OnMigrationFailed GameDelegate
---@field OnMigrationSuccess GameDelegate
---@field SyncCharacterTalentsCallbackProxy SyncCharacterTalentsCallbackProxyGen
---@field BeginMigration fun(self: OfflineAccountMigrator, bForceMigration: boolean)
---@field GetAllCharactersFailed fun(self: OfflineAccountMigrator, Response: ResGetCharacters|{})
---@field GetAllCharactersSuccess fun(self: OfflineAccountMigrator, Response: ResGetCharacters|{})
---@field GetAllProspectInfosFailed fun(self: OfflineAccountMigrator, Response: ResGetAllProspects|{})
---@field GetAllProspectInfosSuccess fun(self: OfflineAccountMigrator, Response: ResGetAllProspects|{})
---@field GetCharacterLoadoutFailed fun(self: OfflineAccountMigrator, Response: ResGetCharacterLoadout|{})
---@field GetCharacterLoadoutSuccess fun(self: OfflineAccountMigrator, Response: ResGetCharacterLoadout|{})
---@field GetLoadoutInventoryFailed fun(self: OfflineAccountMigrator, Response: ResLoadoutInventory|{})
---@field GetLoadoutInventorySuccess fun(self: OfflineAccountMigrator, Response: ResLoadoutInventory|{})
---@field GetMetaInventoryFailed fun(self: OfflineAccountMigrator, Response: ResGetMetaInventory|{})
---@field GetMetaInventorySuccess fun(self: OfflineAccountMigrator, Response: ResGetMetaInventory|{})
---@field GetPreparedLoadoutFailed fun(self: OfflineAccountMigrator, Response: ResPreparedLoadout|{})
---@field GetPreparedLoadoutSuccess fun(self: OfflineAccountMigrator, Response: ResPreparedLoadout|{})
---@field GetProspectBlobFailed fun(self: OfflineAccountMigrator, Response: ResGetProspect|{})
---@field GetProspectBlobSuccess fun(self: OfflineAccountMigrator, Response: ResGetProspect|{})
---@field GetUserProfileFailed fun(self: OfflineAccountMigrator, Response: ResGetUserProfile|{})
---@field GetUserProfileSuccess fun(self: OfflineAccountMigrator, Response: ResGetUserProfile|{})
---@field GetUserProfileTimedout fun(self: OfflineAccountMigrator)
---@field HasAccountDataMigrationBeenPerformed fun(self: OfflineAccountMigrator): boolean
---@field SkipMigration fun(self: OfflineAccountMigrator)

---@class OfflinePackageFlagsSubsystem : GameInstanceSubsystem
---@field FetchAndGrantPackageFlagsForCurrentUser fun(self: OfflinePackageFlagsSubsystem, PlayerID: string, PackageFlags: integer[], FailReason: string): boolean
---@field HasPackageFlag fun(self: OfflinePackageFlagsSubsystem, PlayerID: string, PackageFlag: DLCPackageDataRowHandle|{}): boolean
---@field LoadFlagsFromFile fun(self: OfflinePackageFlagsSubsystem, PlayerID: string, AccountFlags: integer[]): boolean
---@field SaveFlagsToFile fun(self: OfflinePackageFlagsSubsystem, PlayerID: string, AccountFlags: integer[]): boolean

---@class OilGeyserRecorderComponent : ActorStateRecorderComponent

---@class OneOffAccolade : AccoladeImpl

---@class OneShotAudio : Actor
---@field AudioContext AudioContextComponent
---@field EventPath SoftObjectPath
---@field OcclusionComponent AudioOcclusionComponent
---@field bUseListenerRotation boolean
---@field bUseOcclusion boolean

---@class OptionalResourceFlowData : IcarusTableRowBase
---@field DisplayedMessage string
---@field ShortMessage string

---@class OptionalResourceFlowsEnum : RowEnum

---@class OptionalResourceFlowsLibrary : RowLibrary
---@field AddRowToOptionalResourceFlowsTable fun(self: OptionalResourceFlowsLibrary, Name: string, Data: OptionalResourceFlowData|{}, NewRow: OptionalResourceFlowsRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakOptionalResourceFlowsEnum fun(self: OptionalResourceFlowsLibrary, Enum: OptionalResourceFlowsEnum|{}, Name: string, Index: integer)
---@field CastToOptionalResourceFlowsRowHandle fun(self: OptionalResourceFlowsLibrary, RowHandle: RowHandle|{}, Paths: EValid): OptionalResourceFlowsRowHandle
---@field EqualEqual_EnumEnum fun(self: OptionalResourceFlowsLibrary, A: OptionalResourceFlowsEnum|{}, B: OptionalResourceFlowsEnum|{}): boolean
---@field EqualEqual_FOptionalResourceFlowsRowHandleFOptionalResourceFlowsRowHandle fun(self: OptionalResourceFlowsLibrary, RowHandleA: OptionalResourceFlowsRowHandle|{}, RowHandleB: OptionalResourceFlowsRowHandle|{}): boolean
---@field GetOptionalResourceFlowsStruct fun(self: OptionalResourceFlowsLibrary, RowHandle: OptionalResourceFlowsRowHandle|{}, OptionalResourceFlows: OptionalResourceFlowData|{}, Paths: EValid)
---@field IntToName fun(self: OptionalResourceFlowsLibrary, IntValue: integer): string
---@field IntToStruct fun(self: OptionalResourceFlowsLibrary, IntValue: integer): OptionalResourceFlowsEnum
---@field IsValidName fun(self: OptionalResourceFlowsLibrary, NameValue: string): boolean
---@field MakeLiteralOptionalResourceFlows fun(self: OptionalResourceFlowsLibrary, RowHandle: OptionalResourceFlowsRowHandle|{}): OptionalResourceFlowsRowHandle
---@field MakeOptionalResourceFlows fun(self: OptionalResourceFlowsLibrary, RowName: string): OptionalResourceFlowsRowHandle
---@field MakeOptionalResourceFlowsEnum fun(self: OptionalResourceFlowsLibrary, Enum: OptionalResourceFlowsEnum|{}): OptionalResourceFlowsEnum
---@field MakeOptionalResourceFlowsFromIndex fun(self: OptionalResourceFlowsLibrary, Index: integer): OptionalResourceFlowsRowHandle
---@field NameToInt fun(self: OptionalResourceFlowsLibrary, NameValue: string): integer
---@field NameToStruct fun(self: OptionalResourceFlowsLibrary, NameValue: string): OptionalResourceFlowsEnum
---@field NotEqual_EnumEnum fun(self: OptionalResourceFlowsLibrary, A: OptionalResourceFlowsEnum|{}, B: OptionalResourceFlowsEnum|{}): boolean
---@field NotEqual_EnumName fun(self: OptionalResourceFlowsLibrary, A: OptionalResourceFlowsEnum|{}, B: string): boolean
---@field NumRows fun(self: OptionalResourceFlowsLibrary): integer
---@field RefreshConstants fun(self: OptionalResourceFlowsLibrary)
---@field RemoveRowFromOptionalResourceFlowsTable fun(self: OptionalResourceFlowsLibrary, Name: string)
---@field RowHandleToStruct fun(self: OptionalResourceFlowsLibrary, RowHandle: OptionalResourceFlowsRowHandle|{}): OptionalResourceFlowsEnum
---@field StructToInt fun(self: OptionalResourceFlowsLibrary, EnumValue: OptionalResourceFlowsEnum|{}): integer
---@field StructToName fun(self: OptionalResourceFlowsLibrary, EnumValue: OptionalResourceFlowsEnum|{}): string
---@field StructToRowHandle fun(self: OptionalResourceFlowsLibrary, EnumValue: OptionalResourceFlowsEnum|{}): OptionalResourceFlowsRowHandle

---@class OptionalResourceFlowsRowHandle : RowHandle

---@class OptionalResourceFlowsTable : IcarusDataTable

---@class OrchestrationEvent : Object

---@class OrchestrationEventDescription : IcarusTableRowBase
---@field RequiredFlags OrchestrationStateFlagsRowHandle[]
---@field StateFlagToSetOnExecute OrchestrationStateFlagsRowHandle

---@class OrchestrationEventsEnum : RowEnum

---@class OrchestrationEventsLibrary : RowLibrary
---@field AddRowToOrchestrationEventsTable fun(self: OrchestrationEventsLibrary, Name: string, Data: OrchestrationEventDescription|{}, NewRow: OrchestrationEventsRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakOrchestrationEventsEnum fun(self: OrchestrationEventsLibrary, Enum: OrchestrationEventsEnum|{}, Name: string, Index: integer)
---@field CastToOrchestrationEventsRowHandle fun(self: OrchestrationEventsLibrary, RowHandle: RowHandle|{}, Paths: EValid): OrchestrationEventsRowHandle
---@field EqualEqual_EnumEnum fun(self: OrchestrationEventsLibrary, A: OrchestrationEventsEnum|{}, B: OrchestrationEventsEnum|{}): boolean
---@field EqualEqual_FOrchestrationEventsRowHandleFOrchestrationEventsRowHandle fun(self: OrchestrationEventsLibrary, RowHandleA: OrchestrationEventsRowHandle|{}, RowHandleB: OrchestrationEventsRowHandle|{}): boolean
---@field GetOrchestrationEventsStruct fun(self: OrchestrationEventsLibrary, RowHandle: OrchestrationEventsRowHandle|{}, OrchestrationEvents: OrchestrationEventDescription|{}, Paths: EValid)
---@field IntToName fun(self: OrchestrationEventsLibrary, IntValue: integer): string
---@field IntToStruct fun(self: OrchestrationEventsLibrary, IntValue: integer): OrchestrationEventsEnum
---@field IsValidName fun(self: OrchestrationEventsLibrary, NameValue: string): boolean
---@field MakeLiteralOrchestrationEvents fun(self: OrchestrationEventsLibrary, RowHandle: OrchestrationEventsRowHandle|{}): OrchestrationEventsRowHandle
---@field MakeOrchestrationEvents fun(self: OrchestrationEventsLibrary, RowName: string): OrchestrationEventsRowHandle
---@field MakeOrchestrationEventsEnum fun(self: OrchestrationEventsLibrary, Enum: OrchestrationEventsEnum|{}): OrchestrationEventsEnum
---@field MakeOrchestrationEventsFromIndex fun(self: OrchestrationEventsLibrary, Index: integer): OrchestrationEventsRowHandle
---@field NameToInt fun(self: OrchestrationEventsLibrary, NameValue: string): integer
---@field NameToStruct fun(self: OrchestrationEventsLibrary, NameValue: string): OrchestrationEventsEnum
---@field NotEqual_EnumEnum fun(self: OrchestrationEventsLibrary, A: OrchestrationEventsEnum|{}, B: OrchestrationEventsEnum|{}): boolean
---@field NotEqual_EnumName fun(self: OrchestrationEventsLibrary, A: OrchestrationEventsEnum|{}, B: string): boolean
---@field NumRows fun(self: OrchestrationEventsLibrary): integer
---@field RefreshConstants fun(self: OrchestrationEventsLibrary)
---@field RemoveRowFromOrchestrationEventsTable fun(self: OrchestrationEventsLibrary, Name: string)
---@field RowHandleToStruct fun(self: OrchestrationEventsLibrary, RowHandle: OrchestrationEventsRowHandle|{}): OrchestrationEventsEnum
---@field StructToInt fun(self: OrchestrationEventsLibrary, EnumValue: OrchestrationEventsEnum|{}): integer
---@field StructToName fun(self: OrchestrationEventsLibrary, EnumValue: OrchestrationEventsEnum|{}): string
---@field StructToRowHandle fun(self: OrchestrationEventsLibrary, EnumValue: OrchestrationEventsEnum|{}): OrchestrationEventsRowHandle

---@class OrchestrationEventsRowHandle : RowHandle

---@class OrchestrationEventsTable : IcarusDataTable

---@class OrchestrationStateFlag : IcarusTableRowBase
---@field FlagDescriptor string

---@class OrchestrationStateFlagsEnum : RowEnum

---@class OrchestrationStateFlagsLibrary : RowLibrary
---@field AddRowToOrchestrationStateFlagsTable fun(self: OrchestrationStateFlagsLibrary, Name: string, Data: OrchestrationStateFlag|{}, NewRow: OrchestrationStateFlagsRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakOrchestrationStateFlagsEnum fun(self: OrchestrationStateFlagsLibrary, Enum: OrchestrationStateFlagsEnum|{}, Name: string, Index: integer)
---@field CastToOrchestrationStateFlagsRowHandle fun(self: OrchestrationStateFlagsLibrary, RowHandle: RowHandle|{}, Paths: EValid): OrchestrationStateFlagsRowHandle
---@field EqualEqual_EnumEnum fun(self: OrchestrationStateFlagsLibrary, A: OrchestrationStateFlagsEnum|{}, B: OrchestrationStateFlagsEnum|{}): boolean
---@field EqualEqual_FOrchestrationStateFlagsRowHandleFOrchestrationStateFlagsRowHandle fun(self: OrchestrationStateFlagsLibrary, RowHandleA: OrchestrationStateFlagsRowHandle|{}, RowHandleB: OrchestrationStateFlagsRowHandle|{}): boolean
---@field GetOrchestrationStateFlagsStruct fun(self: OrchestrationStateFlagsLibrary, RowHandle: OrchestrationStateFlagsRowHandle|{}, OrchestrationStateFlags: OrchestrationStateFlag|{}, Paths: EValid)
---@field IntToName fun(self: OrchestrationStateFlagsLibrary, IntValue: integer): string
---@field IntToStruct fun(self: OrchestrationStateFlagsLibrary, IntValue: integer): OrchestrationStateFlagsEnum
---@field IsValidName fun(self: OrchestrationStateFlagsLibrary, NameValue: string): boolean
---@field MakeLiteralOrchestrationStateFlags fun(self: OrchestrationStateFlagsLibrary, RowHandle: OrchestrationStateFlagsRowHandle|{}): OrchestrationStateFlagsRowHandle
---@field MakeOrchestrationStateFlags fun(self: OrchestrationStateFlagsLibrary, RowName: string): OrchestrationStateFlagsRowHandle
---@field MakeOrchestrationStateFlagsEnum fun(self: OrchestrationStateFlagsLibrary, Enum: OrchestrationStateFlagsEnum|{}): OrchestrationStateFlagsEnum
---@field MakeOrchestrationStateFlagsFromIndex fun(self: OrchestrationStateFlagsLibrary, Index: integer): OrchestrationStateFlagsRowHandle
---@field NameToInt fun(self: OrchestrationStateFlagsLibrary, NameValue: string): integer
---@field NameToStruct fun(self: OrchestrationStateFlagsLibrary, NameValue: string): OrchestrationStateFlagsEnum
---@field NotEqual_EnumEnum fun(self: OrchestrationStateFlagsLibrary, A: OrchestrationStateFlagsEnum|{}, B: OrchestrationStateFlagsEnum|{}): boolean
---@field NotEqual_EnumName fun(self: OrchestrationStateFlagsLibrary, A: OrchestrationStateFlagsEnum|{}, B: string): boolean
---@field NumRows fun(self: OrchestrationStateFlagsLibrary): integer
---@field RefreshConstants fun(self: OrchestrationStateFlagsLibrary)
---@field RemoveRowFromOrchestrationStateFlagsTable fun(self: OrchestrationStateFlagsLibrary, Name: string)
---@field RowHandleToStruct fun(self: OrchestrationStateFlagsLibrary, RowHandle: OrchestrationStateFlagsRowHandle|{}): OrchestrationStateFlagsEnum
---@field StructToInt fun(self: OrchestrationStateFlagsLibrary, EnumValue: OrchestrationStateFlagsEnum|{}): integer
---@field StructToName fun(self: OrchestrationStateFlagsLibrary, EnumValue: OrchestrationStateFlagsEnum|{}): string
---@field StructToRowHandle fun(self: OrchestrationStateFlagsLibrary, EnumValue: OrchestrationStateFlagsEnum|{}): OrchestrationStateFlagsRowHandle

---@class OrchestrationStateFlagsRowHandle : RowHandle

---@class OrchestrationStateFlagsTable : IcarusDataTable

---@class OreDeposit : IcarusTableRowBase
---@field HighlightableRow HighlightableRowHandle
---@field MaxOreAvailable integer
---@field MinOreAvailable integer
---@field MiningTimeSeconds integer
---@field NodeMaterial_CF MaterialInterface
---@field NodeMaterial_DC MaterialInterface
---@field RVTNodeMaterial_CF MaterialInterface
---@field RVTNodeMaterial_DC MaterialInterface
---@field ResourceType ItemTemplateRowHandle
---@field RockMaterial MaterialInterface
---@field ScannerBlacklist boolean

---@class OreDepositEnum : RowEnum

---@class OreDepositLibrary : RowLibrary
---@field AddRowToOreDepositTable fun(self: OreDepositLibrary, Name: string, Data: OreDeposit|{}, NewRow: OreDepositRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakOreDepositEnum fun(self: OreDepositLibrary, Enum: OreDepositEnum|{}, Name: string, Index: integer)
---@field CastToOreDepositRowHandle fun(self: OreDepositLibrary, RowHandle: RowHandle|{}, Paths: EValid): OreDepositRowHandle
---@field EqualEqual_EnumEnum fun(self: OreDepositLibrary, A: OreDepositEnum|{}, B: OreDepositEnum|{}): boolean
---@field EqualEqual_FOreDepositRowHandleFOreDepositRowHandle fun(self: OreDepositLibrary, RowHandleA: OreDepositRowHandle|{}, RowHandleB: OreDepositRowHandle|{}): boolean
---@field GetOreDepositStruct fun(self: OreDepositLibrary, RowHandle: OreDepositRowHandle|{}, OreDeposit: OreDeposit|{}, Paths: EValid)
---@field IntToName fun(self: OreDepositLibrary, IntValue: integer): string
---@field IntToStruct fun(self: OreDepositLibrary, IntValue: integer): OreDepositEnum
---@field IsValidName fun(self: OreDepositLibrary, NameValue: string): boolean
---@field MakeLiteralOreDeposit fun(self: OreDepositLibrary, RowHandle: OreDepositRowHandle|{}): OreDepositRowHandle
---@field MakeOreDeposit fun(self: OreDepositLibrary, RowName: string): OreDepositRowHandle
---@field MakeOreDepositEnum fun(self: OreDepositLibrary, Enum: OreDepositEnum|{}): OreDepositEnum
---@field MakeOreDepositFromIndex fun(self: OreDepositLibrary, Index: integer): OreDepositRowHandle
---@field NameToInt fun(self: OreDepositLibrary, NameValue: string): integer
---@field NameToStruct fun(self: OreDepositLibrary, NameValue: string): OreDepositEnum
---@field NotEqual_EnumEnum fun(self: OreDepositLibrary, A: OreDepositEnum|{}, B: OreDepositEnum|{}): boolean
---@field NotEqual_EnumName fun(self: OreDepositLibrary, A: OreDepositEnum|{}, B: string): boolean
---@field NumRows fun(self: OreDepositLibrary): integer
---@field RefreshConstants fun(self: OreDepositLibrary)
---@field RemoveRowFromOreDepositTable fun(self: OreDepositLibrary, Name: string)
---@field RowHandleToStruct fun(self: OreDepositLibrary, RowHandle: OreDepositRowHandle|{}): OreDepositEnum
---@field StructToInt fun(self: OreDepositLibrary, EnumValue: OreDepositEnum|{}): integer
---@field StructToName fun(self: OreDepositLibrary, EnumValue: OreDepositEnum|{}): string
---@field StructToRowHandle fun(self: OreDepositLibrary, EnumValue: OreDepositEnum|{}): OreDepositRowHandle

---@class OreDepositRowHandle : RowHandle

---@class OreDepositTable : IcarusDataTable

---@class OutOfBoundsArray
---@field OverlappedVolumes Actor[]

---@class OutOfBoundsSubsystem : WorldSubsystem
---@field OnOutOfBoundsUpdate GameDelegate
---@field PlayerVolumeMap table<IcarusPlayerCharacter, OutOfBoundsArray>
---@field IsPlayerOutOfBounds fun(self: OutOfBoundsSubsystem, Player: IcarusPlayerCharacter?): boolean
---@field RegisterOutOfBoundsForPlayer fun(self: OutOfBoundsSubsystem, Player: IcarusPlayerCharacter?, Volume: Actor?)
---@field UnRegisterOutOfBoundsForPlayer fun(self: OutOfBoundsSubsystem, Player: IcarusPlayerCharacter?, Volume: Actor?)

---@class OutOfBoundsVolume : PhysicsVolume

---@class Outpost : IcarusTableRowBase
---@field Icon Texture2D
---@field ProspectListRowHandle ProspectListRowHandle
---@field RequiredMission TalentsRowHandle

---@class OutpostTalentControllerComponent : TalentControllerComponent

---@class OutpostTalentModel : TalentModelInterface

---@class OutpostsEnum : RowEnum

---@class OutpostsLibrary : RowLibrary
---@field AddRowToOutpostsTable fun(self: OutpostsLibrary, Name: string, Data: Outpost|{}, NewRow: OutpostsRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakOutpostsEnum fun(self: OutpostsLibrary, Enum: OutpostsEnum|{}, Name: string, Index: integer)
---@field CastToOutpostsRowHandle fun(self: OutpostsLibrary, RowHandle: RowHandle|{}, Paths: EValid): OutpostsRowHandle
---@field EqualEqual_EnumEnum fun(self: OutpostsLibrary, A: OutpostsEnum|{}, B: OutpostsEnum|{}): boolean
---@field EqualEqual_FOutpostsRowHandleFOutpostsRowHandle fun(self: OutpostsLibrary, RowHandleA: OutpostsRowHandle|{}, RowHandleB: OutpostsRowHandle|{}): boolean
---@field GetOutpostsStruct fun(self: OutpostsLibrary, RowHandle: OutpostsRowHandle|{}, Outposts: Outpost|{}, Paths: EValid)
---@field IntToName fun(self: OutpostsLibrary, IntValue: integer): string
---@field IntToStruct fun(self: OutpostsLibrary, IntValue: integer): OutpostsEnum
---@field IsValidName fun(self: OutpostsLibrary, NameValue: string): boolean
---@field MakeLiteralOutposts fun(self: OutpostsLibrary, RowHandle: OutpostsRowHandle|{}): OutpostsRowHandle
---@field MakeOutposts fun(self: OutpostsLibrary, RowName: string): OutpostsRowHandle
---@field MakeOutpostsEnum fun(self: OutpostsLibrary, Enum: OutpostsEnum|{}): OutpostsEnum
---@field MakeOutpostsFromIndex fun(self: OutpostsLibrary, Index: integer): OutpostsRowHandle
---@field NameToInt fun(self: OutpostsLibrary, NameValue: string): integer
---@field NameToStruct fun(self: OutpostsLibrary, NameValue: string): OutpostsEnum
---@field NotEqual_EnumEnum fun(self: OutpostsLibrary, A: OutpostsEnum|{}, B: OutpostsEnum|{}): boolean
---@field NotEqual_EnumName fun(self: OutpostsLibrary, A: OutpostsEnum|{}, B: string): boolean
---@field NumRows fun(self: OutpostsLibrary): integer
---@field RefreshConstants fun(self: OutpostsLibrary)
---@field RemoveRowFromOutpostsTable fun(self: OutpostsLibrary, Name: string)
---@field RowHandleToStruct fun(self: OutpostsLibrary, RowHandle: OutpostsRowHandle|{}): OutpostsEnum
---@field StructToInt fun(self: OutpostsLibrary, EnumValue: OutpostsEnum|{}): integer
---@field StructToName fun(self: OutpostsLibrary, EnumValue: OutpostsEnum|{}): string
---@field StructToRowHandle fun(self: OutpostsLibrary, EnumValue: OutpostsEnum|{}): OutpostsRowHandle

---@class OutpostsRowHandle : RowHandle

---@class OutpostsTable : IcarusDataTable

---@class OverlapAudioComponent : SceneComponent
---@field AudioComponent FMODAudioComponent
---@field Collider SphereComponent
---@field Event FMODEvent
---@field MaxDistance number
---@field MinDistance number
---@field bAutoPlay boolean
---@field bInitializeManually boolean
---@field bUseAttenuationOverride boolean
---@field HandleBeginOverlap fun(self: OverlapAudioComponent, OverlappedComponent: PrimitiveComponent?, OtherActor: Actor?, OtherComp: PrimitiveComponent?, OtherBodyIndex: integer, bFromSweep: boolean, SweepResult: HitResult|{})
---@field HandleEndOverlap fun(self: OverlapAudioComponent, OverlappedComponent: PrimitiveComponent?, OtherActor: Actor?, OtherComp: PrimitiveComponent?, OtherBodyIndex: integer)
---@field Initialize fun(self: OverlapAudioComponent)
---@field Play fun(self: OverlapAudioComponent)
---@field Stop fun(self: OverlapAudioComponent)

---@class OxygenComponent : ResourceNetworkComponent

---@class OxygenData : ResourceNetworkData

---@class OxygenEnum : RowEnum

---@class OxygenLibrary : RowLibrary
---@field AddRowToOxygenTable fun(self: OxygenLibrary, Name: string, Data: OxygenData|{}, NewRow: OxygenRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakOxygenEnum fun(self: OxygenLibrary, Enum: OxygenEnum|{}, Name: string, Index: integer)
---@field CastToOxygenRowHandle fun(self: OxygenLibrary, RowHandle: RowHandle|{}, Paths: EValid): OxygenRowHandle
---@field EqualEqual_EnumEnum fun(self: OxygenLibrary, A: OxygenEnum|{}, B: OxygenEnum|{}): boolean
---@field EqualEqual_FOxygenRowHandleFOxygenRowHandle fun(self: OxygenLibrary, RowHandleA: OxygenRowHandle|{}, RowHandleB: OxygenRowHandle|{}): boolean
---@field GetOxygenStruct fun(self: OxygenLibrary, RowHandle: OxygenRowHandle|{}, Oxygen: OxygenData|{}, Paths: EValid)
---@field IntToName fun(self: OxygenLibrary, IntValue: integer): string
---@field IntToStruct fun(self: OxygenLibrary, IntValue: integer): OxygenEnum
---@field IsValidName fun(self: OxygenLibrary, NameValue: string): boolean
---@field MakeLiteralOxygen fun(self: OxygenLibrary, RowHandle: OxygenRowHandle|{}): OxygenRowHandle
---@field MakeOxygen fun(self: OxygenLibrary, RowName: string): OxygenRowHandle
---@field MakeOxygenEnum fun(self: OxygenLibrary, Enum: OxygenEnum|{}): OxygenEnum
---@field MakeOxygenFromIndex fun(self: OxygenLibrary, Index: integer): OxygenRowHandle
---@field NameToInt fun(self: OxygenLibrary, NameValue: string): integer
---@field NameToStruct fun(self: OxygenLibrary, NameValue: string): OxygenEnum
---@field NotEqual_EnumEnum fun(self: OxygenLibrary, A: OxygenEnum|{}, B: OxygenEnum|{}): boolean
---@field NotEqual_EnumName fun(self: OxygenLibrary, A: OxygenEnum|{}, B: string): boolean
---@field NumRows fun(self: OxygenLibrary): integer
---@field RefreshConstants fun(self: OxygenLibrary)
---@field RemoveRowFromOxygenTable fun(self: OxygenLibrary, Name: string)
---@field RowHandleToStruct fun(self: OxygenLibrary, RowHandle: OxygenRowHandle|{}): OxygenEnum
---@field StructToInt fun(self: OxygenLibrary, EnumValue: OxygenEnum|{}): integer
---@field StructToName fun(self: OxygenLibrary, EnumValue: OxygenEnum|{}): string
---@field StructToRowHandle fun(self: OxygenLibrary, EnumValue: OxygenEnum|{}): OxygenRowHandle

---@class OxygenRowHandle : RowHandle

---@class OxygenTable : IcarusDataTable
