---@meta _
-- Generated by scripts\gameindex.py from the game's object dump. Changes here are lost on the next run.

---@class ActiveFactionMission
---@field FactionMission string
---@field Progress integer

---@class AssociatedMemberInfo
---@field AccountName string
---@field CharacterName string
---@field ChrSlot integer
---@field Experience integer
---@field IsCurrentlyPlaying boolean
---@field Settled boolean
---@field Status EProspectLocation
---@field UserID string

---@class Attachment
---@field Credits integer
---@field Exotics MetaResource[]
---@field Items MetaItem[]

---@class BackendTalent
---@field Rank integer
---@field RowName string

---@class CharacterCosmetics
---@field Customization_Age integer
---@field Customization_Body integer
---@field Customization_BodyColor integer
---@field Customization_CapLogo integer
---@field Customization_Complexion integer
---@field Customization_EyeColor integer
---@field Customization_Eyebrows integer
---@field Customization_Hair integer
---@field Customization_HairColor integer
---@field Customization_Head integer
---@field Customization_HeadFacialHair integer
---@field Customization_HeadScar integer
---@field Customization_HeadTattoo integer
---@field Customization_Helmet integer
---@field Customization_Hood integer
---@field Customization_Piercings integer
---@field Customization_Rebreather integer
---@field Customization_SkinSaturation_V2 number
---@field Customization_SkinTint_V2 number
---@field Customization_SkinTone integer
---@field Customization_SkinTone_V2 number
---@field Customization_Voice integer
---@field IsMale boolean
---@field IsReworkedCharacter boolean

---@class CharacterLoadout
---@field Dropship Dropship
---@field EnviroSuit MetaItem
---@field MetaItems MetaItem[]
---@field Valid boolean

---@class ConnectionString
---@field ExternalIP string
---@field InternalIP string
---@field P2PAddress string
---@field Port integer

---@class CustomGameSetting
---@field SettingRowName string
---@field SettingValue integer

---@class Dropship
---@field BTM_Part MetaItem
---@field DropshipID integer
---@field InUse boolean
---@field MID_Part MetaItem
---@field Name string
---@field TOP_Part MetaItem
---@field Type EDropshipType

---@class DropshipDelta
---@field Dropship Dropship

---@class DropshipModification
---@field Name string
---@field Parts DropshipPartModification[]
---@field Type EDropshipType

---@class DropshipPartModification
---@field ItemId string
---@field Type EDropshipPartType

---@class DynamicProperty
---@field Type integer
---@field Value integer

---@alias ECharacterAttribute
---| 0 # Health
---| 1 # Stamina
---| 2 # Strength
---| 3 # Agility
---| 4 # Perception
---| 5 # MaxCharacterAttribute
---| integer

---@alias EDropshipPartType
---| 0 # DropshipPartType_UndefinedID
---| 1 # DropshipType_TOP
---| 2 # DropshipType_MID
---| 3 # DropshipType_BTM
---| integer

---@alias EDropshipType
---| 0 # DropshipType_UndefinedID
---| 1 # DropshipType_Player
---| 2 # DropshipType_Equipment
---| integer

---@alias EMetaInventoryID
---| 0 # MetaInventoryID_UndefinedID
---| 1 # MetaInventoryID_Main
---| 2 # MetaInventoryID_DropLoadout
---| integer

---@alias EMissionDifficulty
---| 0 # None
---| 1 # Easy
---| 2 # Medium
---| 3 # Hard
---| 4 # Extreme
---| integer

---@alias ENotificationType
---| 0 # Server
---| 1 # General
---| 2 # MissionSummary
---| 3 # ItemRecovery
---| 4 # ProspectComplete
---| 5 # MaxNotificationTypes
---| integer

---@alias EProspectLocation
---| 0 # Unknown
---| 1 # Hab
---| 2 # Prospect_Conifer
---| 3 # Prospect_Arctic
---| 4 # Prospect_Cave
---| 5 # Prospect_Desert
---| 6 # Prospect_Grasslands
---| 7 # Prospect_Volcanic
---| 8 # Prospect_Swamp
---| 9 # Prospect_Geothermal
---| 10 # Prospect_Tundra
---| 11 # Prospect_Coastal
---| 12 # Prospect_Jungle
---| integer

---@alias EProspectState
---| 0 # Unclaimed
---| 1 # Claimed
---| 2 # Active
---| 3 # Ended
---| 4 # MaxProspectStates
---| integer

---@class InventoryDelta
---@field Delta MetaItemDelta[]
---@field ID EMetaInventoryID

---@class MaintenanceStatus
---@field EndTime integer
---@field IsMaintenance boolean
---@field Message string
---@field StartTime integer

---@class MetaItem
---@field ID string
---@field ItemStaticRow string
---@field Properties DynamicProperty[]
---@field Stats Stat[]

---@class MetaItemDelta
---@field ItemUID string
---@field MetaItem MetaItem

---@class MetaResource
---@field Count integer
---@field MetaRow string

---@class Notification
---@field Attachments Attachment
---@field Message string
---@field NotificationUID string
---@field ProspectID string
---@field Read boolean
---@field SentToPlayer boolean
---@field Title string
---@field Type ENotificationType

---@class OnlineProfileCharacter
---@field CharacterName string
---@field ChrSlot integer
---@field Cosmetic CharacterCosmetics
---@field IsAbandoned boolean
---@field IsDead boolean
---@field LastProspectId string
---@field Location EProspectLocation
---@field MetaResources MetaResource[]
---@field Talents BackendTalent[]
---@field TimeLastPlayed integer
---@field UnlockedFlags integer[]
---@field XP integer
---@field XP_Debt integer

---@class OnlineProfileUser
---@field DataVersion integer
---@field MetaResources MetaResource[]
---@field NextChrSlot integer
---@field Talents BackendTalent[]
---@field UnlockedFlags integer[]
---@field UserID string

---@class PlayerID
---@field ChrSlot integer
---@field PlayerName string
---@field Score number
---@field UserID string
---@field bHost boolean

---@class ProspectBlob
---@field BinaryBlob string
---@field DataLength integer
---@field Hash string
---@field Key string
---@field TotalLength integer
---@field UncompressedLength integer

---@class ProspectCompleteInformation
---@field Duration integer
---@field FactionMissionRewards Attachment
---@field FactionMissionSuccessful boolean
---@field ProspectInfo ProspectInfo
---@field ProspectRewards Attachment
---@field TrackedStats TrackedStat[]

---@class ProspectInfo
---@field AssociatedMembers AssociatedMemberInfo[]
---@field ClaimedAccountCharacter integer
---@field ClaimedAccountID string
---@field Cost integer
---@field CustomSettings CustomGameSetting[]
---@field Difficulty EMissionDifficulty
---@field ElapsedTime integer
---@field ExpireTime integer
---@field FactionMissionDTKey string
---@field Insurance boolean
---@field LobbyName string
---@field NoRespawns boolean
---@field ProspectDTKey string
---@field ProspectID string
---@field ProspectState EProspectState
---@field Reward integer
---@field SelectedDropPoint integer

---@class ReqBackToHab
---@field ChrSlot integer
---@field LeftWithShip boolean
---@field MetaItems MetaItem[]
---@field MetaResources MetaResource[]
---@field ProspectID string
---@field UserID string

---@class ReqCanJoinProspect
---@field ChrSlot integer
---@field ProspectID string
---@field UserID string

---@class ReqCheckProspectExpired
---@field ProspectID string

---@class ReqClaimNotificationAttachments
---@field NotificationUID string
---@field UserID string

---@class ReqClaimProspect
---@field ChrSlot integer
---@field LobbyName string
---@field Prospect ProspectInfo
---@field UserID string

---@class ReqCreateCharacter
---@field CharacterCosmeticsData CharacterCosmetics
---@field CharacterName string

---@class ReqCreateDropship
---@field Dropship DropshipModification
---@field UserID string

---@class ReqDeleteDropship
---@field DropshipID integer
---@field UserID string

---@class ReqDeleteNotification
---@field NotificationUID string
---@field UserID string

---@class ReqExchangeCurrency
---@field EndingCurrencyDelta MetaResource
---@field StartingCurrencyDelta MetaResource

---@class ReqGetAllProspects
---@field ChrSlots integer[]

---@class ReqGetCharacterLoadout
---@field ChrSlot integer
---@field UserID string

---@class ReqGetCharacterProfile
---@field ChrSlot integer
---@field UserID string

---@class ReqGetCharacters

---@class ReqGetCredits
---@field UserID string

---@class ReqGetDropships
---@field UserID string

---@class ReqGetMetaInventory
---@field MetaInventoryID EMetaInventoryID
---@field UserID string

---@class ReqGetMetaResources
---@field UserID string

---@class ReqGetNotifications
---@field CompleteList boolean
---@field UserID string

---@class ReqGetProspect
---@field ChrSlot integer
---@field HasProspectBlob boolean
---@field ProspectID string
---@field UserID string

---@class ReqGetUserProfile
---@field UserID string

---@class ReqJoinProspect
---@field ChrSlot integer
---@field ProspectID string

---@class ReqLoadoutInventory
---@field CharacterSlot integer
---@field UserID string

---@class ReqLobbyMessage
---@field AppId string
---@field AuthToken string
---@field AuthType string
---@field UserID string

---@class ReqModifyDropship
---@field Dropship DropshipModification
---@field DropshipID integer
---@field UserID string

---@class ReqMoveMetaInventoryItem
---@field CharacterSlot integer
---@field Count integer
---@field DstItemId string
---@field DstMetaInventoryID EMetaInventoryID
---@field ScrItemId string
---@field SrcMetaInventoryID EMetaInventoryID
---@field UserID string

---@class ReqPackageLoadout
---@field ChrSlot integer
---@field UserID string

---@class ReqPreparedLoadout
---@field ChrSlot integer
---@field UserID string

---@class ReqProspectExpired
---@field ChrSlot integer
---@field ProspectID string

---@class ReqReadNotification
---@field NotificationUID string
---@field UserID string

---@class ReqRemoveEnvirosuit
---@field ChrSlot integer
---@field UserID string

---@class ReqRemoveMetaInventoryItem
---@field MetaItemId string
---@field UserID string

---@class ReqRemoveSelectedDropship
---@field ChrSlot integer
---@field UserID string

---@class ReqRepairWorkshopItem
---@field MetaItemId string
---@field UserID string

---@class ReqReplicateWorkshopItem
---@field UserID string
---@field WorkshopTalent string

---@class ReqResetCharacterProspectState
---@field ChrSlot integer
---@field UserID string

---@class ReqResumeProspect
---@field AttemptHostMigration boolean
---@field ChrSlot integer
---@field ProspectID string

---@class ReqSelectDropship
---@field ChrSlot integer
---@field DropshipID integer
---@field UserID string

---@class ReqSelectEnvirosuit
---@field ChrSlot integer
---@field ItemId string
---@field UserID string

---@class ReqSettleProspect
---@field ProspectID string
---@field Settle boolean
---@field UserID string

---@class ReqSyncAccountFlags
---@field Flags integer[]
---@field UserID string

---@class ReqSyncAccountTalents
---@field Talents BackendTalent[]
---@field UserID string

---@class ReqSyncCharacterTalents
---@field CharacterSlot integer
---@field Talents BackendTalent[]
---@field UserID string

---@class ReqTalentRefund
---@field CharacterSlot integer
---@field Talent BackendTalent

---@class ReqUnlockWorkshopItem
---@field UserID string
---@field WorkshopTalent string

---@class ReqUnpackageLoadout
---@field ChrSlot integer
---@field UserID string

---@class ReqUpdateCharacterProgress
---@field ChrSlot integer
---@field IsDead boolean
---@field UnlockedFlags integer[]
---@field UserID string
---@field XP integer
---@field XP_Debt integer

---@class ReqUpdateCharacterProspectLocation
---@field ChrSlot integer
---@field Location EProspectLocation
---@field ProspectID string
---@field UserID string

---@class ReqUpdateCosmetics
---@field CharacterCosmeticsData CharacterCosmetics
---@field ChrSlot integer
---@field UserID string

---@class ReqUpdateFactionMissionProgress
---@field ChrSlot integer
---@field MissionProgress ActiveFactionMission
---@field ProspectID string
---@field UserID string

---@class ReqUpdateProspect
---@field ElapsedTime integer
---@field HasProspectBlob boolean
---@field IsLeavingGame boolean
---@field ProspectBlob ProspectBlob
---@field ProspectID string
---@field UpdateTime integer

---@class ReqUpdateTrackedStats
---@field ChrSlot integer
---@field ProspectID string
---@field TrackedStats TrackedStat[]
---@field UserID string

---@class ResAbandonProspect
---@field Success boolean

---@class ResBackToHab
---@field Success boolean

---@class ResCanJoinProspect
---@field Success boolean

---@class ResClaimNotificationAttachments
---@field Credits integer
---@field InventoryDelta InventoryDelta
---@field MetaResourceDelta MetaResource[]
---@field NotificationUID string
---@field Success boolean

---@class ResClaimProspect
---@field Prospect ProspectInfo
---@field Success boolean

---@class ResCreateCharacter
---@field CreatedCharacter OnlineProfileCharacter
---@field Success boolean

---@class ResCreateDropship
---@field DropshipDelta DropshipDelta
---@field InventoryDelta InventoryDelta
---@field Success boolean

---@class ResDeleteCharacter
---@field Success boolean

---@class ResDeleteDropship
---@field DropshipRemovedID integer
---@field InventoryDelta InventoryDelta
---@field Success boolean

---@class ResDeleteNotification
---@field NotificationUID string
---@field Success boolean

---@class ResExchangeCurrency
---@field CurrencyDeltas MetaResource[]
---@field Success boolean

---@class ResGenerateProspects
---@field Prospects ProspectInfo[]
---@field Success boolean

---@class ResGetAllProspects
---@field Prospects ProspectInfo[]
---@field Success boolean

---@class ResGetCharacterLoadout
---@field Loadout CharacterLoadout
---@field Success boolean

---@class ResGetCharacterProfile
---@field Character OnlineProfileCharacter
---@field Success boolean

---@class ResGetCharacters
---@field Characters OnlineProfileCharacter[]
---@field Success boolean

---@class ResGetCredits
---@field Amount integer
---@field Success boolean

---@class ResGetDropships
---@field Dropships Dropship[]
---@field Success boolean

---@class ResGetLastProspect
---@field FactionMissionStatus integer
---@field ProspectInformation ProspectInfo
---@field Success boolean

---@class ResGetMetaInventory
---@field InventoryDelta InventoryDelta
---@field Success boolean

---@class ResGetMetaResources
---@field MetaResources MetaResource[]
---@field Success boolean

---@class ResGetNotifications
---@field CompleteList boolean
---@field NotificationDelta Notification[]
---@field Success boolean

---@class ResGetProspect
---@field Prospect ProspectInfo
---@field ProspectBlob ProspectBlob
---@field Success boolean

---@class ResGetProspectSummary
---@field ProspectInformation ProspectCompleteInformation
---@field Success boolean

---@class ResGetUserProfile
---@field IcarusProfile OnlineProfileUser
---@field Success boolean

---@class ResGetWorkshopPacks
---@field Success boolean
---@field WorkshopPacks WorkshopPack[]

---@class ResJoinProspect
---@field Prospect ProspectInfo
---@field Success boolean

---@class ResLoadoutInventory
---@field Inventory MetaItem[]
---@field Success boolean

---@class ResLobbyMessage
---@field Reason string
---@field Success boolean

---@class ResModifyDropship
---@field DropshipDelta DropshipDelta
---@field InventoryDelta InventoryDelta
---@field Success boolean

---@class ResMoveMetaInventoryItem
---@field Delta InventoryDelta[]
---@field Success boolean

---@class ResPackageLoadout
---@field DropshipDelta DropshipDelta
---@field InventoryDelta InventoryDelta
---@field LoadoutIndex integer
---@field Locked boolean
---@field Success boolean

---@class ResPreparedLoadout
---@field DropshipID integer
---@field EnviroSuit MetaItem
---@field Locked boolean
---@field Success boolean

---@class ResReadNotification
---@field NotificationUID string
---@field Success boolean

---@class ResRemoveEnvirosuit
---@field EnviroSuit MetaItem
---@field InventoryDelta InventoryDelta
---@field Success boolean

---@class ResRemoveMetaInventoryItem
---@field Delta InventoryDelta
---@field Success boolean

---@class ResRemoveSelectedDropship
---@field DropshipID integer
---@field Success boolean

---@class ResRepairWorkshopItem
---@field CurrencyDelta MetaResource[]
---@field InventoryDelta InventoryDelta
---@field Success boolean

---@class ResReplicateWorkshopItem
---@field CurrencyDelta MetaResource[]
---@field InventoryDelta InventoryDelta
---@field Success boolean

---@class ResResetCharacter
---@field Character OnlineProfileCharacter
---@field Success boolean

---@class ResResetCharacterProspectState
---@field Success boolean

---@class ResResumeProspect
---@field HostID string
---@field Prospect ProspectInfo
---@field ProspectBlob ProspectBlob
---@field Success boolean

---@class ResSelectDropship
---@field DropshipID integer
---@field Success boolean

---@class ResSelectEnvirosuit
---@field EnviroSuit MetaItem
---@field InventoryDelta InventoryDelta
---@field Success boolean

---@class ResSettleProspect
---@field ProspectInfo ProspectInfo
---@field Success boolean

---@class ResSyncAccountFlags
---@field Flags integer[]
---@field Success boolean

---@class ResSyncAccountTalents
---@field Success boolean
---@field Talents BackendTalent[]

---@class ResSyncCharacterTalents
---@field Success boolean
---@field Talents BackendTalent[]

---@class ResTalentRefund
---@field CurrencyDelta MetaResource[]
---@field Success boolean
---@field Talent BackendTalent

---@class ResUnlockWorkshopItem
---@field CurrencyDelta MetaResource[]
---@field Success boolean
---@field UnlockedTalent string

---@class ResUnpackageLoadout
---@field Locked boolean
---@field Success boolean

---@class ResUpdateCharacterProgress
---@field Success boolean

---@class ResUpdateCharacterProspectLocation
---@field Success boolean

---@class ResUpdateCosmetics
---@field Character OnlineProfileCharacter
---@field Success boolean

---@class ResUpdateFactionMissionProgress
---@field Success boolean

---@class ResUpdateTrackedStats
---@field Success boolean

---@class Stat
---@field Type integer
---@field Value integer

---@class TrackedStat
---@field StatDTKey string
---@field Value integer

---@class WorkshopPack
---@field Categories string[]
---@field MetaCost MetaResource[]
---@field Name string
---@field Tags string[]
---@field WorkshopItemsRow string[]
