---@meta _
-- Generated by scripts\gameindex.py from the index of the game's classes. Changes here are lost on the next run.

---@class HighScoreRecord
---@field PlayerID string
---@field PlayerName string
---@field Score integer

---@class HighlightableComponent : TraitComponent
---@field OnHighlightChanged GameDelegate
---@field bAlwaysHighlight boolean
---@field CanHighlight fun(self: HighlightableComponent): boolean
---@field CanUnhighlight fun(self: HighlightableComponent): boolean
---@field GetHighlightableData fun(self: HighlightableComponent, OutData: HighlightableData|{}): boolean
---@field IsHighlighted fun(self: HighlightableComponent): boolean
---@field SetHighlight fun(self: HighlightableComponent, Component: PrimitiveComponent?, bHighlighted: boolean, StencilValue: integer)

---@class HighlightableData : IcarusTableRowBase
---@field Behaviour Class
---@field Description string
---@field DisplayName string
---@field bDisableMeshOutline boolean
---@field bDisableTooltip boolean

---@class HighlightableEnum : RowEnum

---@class HighlightableLibrary : RowLibrary
---@field AddRowToHighlightableTable fun(self: HighlightableLibrary, Name: string, Data: HighlightableData|{}, NewRow: HighlightableRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakHighlightableEnum fun(self: HighlightableLibrary, Enum: HighlightableEnum|{}, Name: string, Index: integer)
---@field CastToHighlightableRowHandle fun(self: HighlightableLibrary, RowHandle: RowHandle|{}, Paths: EValid): HighlightableRowHandle
---@field EqualEqual_EnumEnum fun(self: HighlightableLibrary, A: HighlightableEnum|{}, B: HighlightableEnum|{}): boolean
---@field EqualEqual_FHighlightableRowHandleFHighlightableRowHandle fun(self: HighlightableLibrary, RowHandleA: HighlightableRowHandle|{}, RowHandleB: HighlightableRowHandle|{}): boolean
---@field GetHighlightableStruct fun(self: HighlightableLibrary, RowHandle: HighlightableRowHandle|{}, Highlightable: HighlightableData|{}, Paths: EValid)
---@field IntToName fun(self: HighlightableLibrary, IntValue: integer): string
---@field IntToStruct fun(self: HighlightableLibrary, IntValue: integer): HighlightableEnum
---@field IsValidName fun(self: HighlightableLibrary, NameValue: string): boolean
---@field MakeHighlightable fun(self: HighlightableLibrary, RowName: string): HighlightableRowHandle
---@field MakeHighlightableEnum fun(self: HighlightableLibrary, Enum: HighlightableEnum|{}): HighlightableEnum
---@field MakeHighlightableFromIndex fun(self: HighlightableLibrary, Index: integer): HighlightableRowHandle
---@field MakeLiteralHighlightable fun(self: HighlightableLibrary, RowHandle: HighlightableRowHandle|{}): HighlightableRowHandle
---@field NameToInt fun(self: HighlightableLibrary, NameValue: string): integer
---@field NameToStruct fun(self: HighlightableLibrary, NameValue: string): HighlightableEnum
---@field NotEqual_EnumEnum fun(self: HighlightableLibrary, A: HighlightableEnum|{}, B: HighlightableEnum|{}): boolean
---@field NotEqual_EnumName fun(self: HighlightableLibrary, A: HighlightableEnum|{}, B: string): boolean
---@field NumRows fun(self: HighlightableLibrary): integer
---@field RefreshConstants fun(self: HighlightableLibrary)
---@field RemoveRowFromHighlightableTable fun(self: HighlightableLibrary, Name: string)
---@field RowHandleToStruct fun(self: HighlightableLibrary, RowHandle: HighlightableRowHandle|{}): HighlightableEnum
---@field StructToInt fun(self: HighlightableLibrary, EnumValue: HighlightableEnum|{}): integer
---@field StructToName fun(self: HighlightableLibrary, EnumValue: HighlightableEnum|{}): string
---@field StructToRowHandle fun(self: HighlightableLibrary, EnumValue: HighlightableEnum|{}): HighlightableRowHandle

---@class HighlightableRowHandle : RowHandle

---@class HighlightableTable : IcarusDataTable

---@class HintsData : IcarusTableRowBase
---@field Text string

---@class HintsEnum : RowEnum

---@class HintsLibrary : RowLibrary
---@field AddRowToHintsTable fun(self: HintsLibrary, Name: string, Data: HintsData|{}, NewRow: HintsRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakHintsEnum fun(self: HintsLibrary, Enum: HintsEnum|{}, Name: string, Index: integer)
---@field CastToHintsRowHandle fun(self: HintsLibrary, RowHandle: RowHandle|{}, Paths: EValid): HintsRowHandle
---@field EqualEqual_EnumEnum fun(self: HintsLibrary, A: HintsEnum|{}, B: HintsEnum|{}): boolean
---@field EqualEqual_FHintsRowHandleFHintsRowHandle fun(self: HintsLibrary, RowHandleA: HintsRowHandle|{}, RowHandleB: HintsRowHandle|{}): boolean
---@field GetHintsStruct fun(self: HintsLibrary, RowHandle: HintsRowHandle|{}, Hints: HintsData|{}, Paths: EValid)
---@field IntToName fun(self: HintsLibrary, IntValue: integer): string
---@field IntToStruct fun(self: HintsLibrary, IntValue: integer): HintsEnum
---@field IsValidName fun(self: HintsLibrary, NameValue: string): boolean
---@field MakeHints fun(self: HintsLibrary, RowName: string): HintsRowHandle
---@field MakeHintsEnum fun(self: HintsLibrary, Enum: HintsEnum|{}): HintsEnum
---@field MakeHintsFromIndex fun(self: HintsLibrary, Index: integer): HintsRowHandle
---@field MakeLiteralHints fun(self: HintsLibrary, RowHandle: HintsRowHandle|{}): HintsRowHandle
---@field NameToInt fun(self: HintsLibrary, NameValue: string): integer
---@field NameToStruct fun(self: HintsLibrary, NameValue: string): HintsEnum
---@field NotEqual_EnumEnum fun(self: HintsLibrary, A: HintsEnum|{}, B: HintsEnum|{}): boolean
---@field NotEqual_EnumName fun(self: HintsLibrary, A: HintsEnum|{}, B: string): boolean
---@field NumRows fun(self: HintsLibrary): integer
---@field RefreshConstants fun(self: HintsLibrary)
---@field RemoveRowFromHintsTable fun(self: HintsLibrary, Name: string)
---@field RowHandleToStruct fun(self: HintsLibrary, RowHandle: HintsRowHandle|{}): HintsEnum
---@field StructToInt fun(self: HintsLibrary, EnumValue: HintsEnum|{}): integer
---@field StructToName fun(self: HintsLibrary, EnumValue: HintsEnum|{}): string
---@field StructToRowHandle fun(self: HintsLibrary, EnumValue: HintsEnum|{}): HintsRowHandle

---@class HintsRowHandle : RowHandle

---@class HintsTable : IcarusDataTable

---@class HitableBehaviourRock : HitableComponent

---@class HitableComponent : TraitComponent
---@field CanConsumeHit fun(self: HitableComponent, ActorStateIn: ActorState?, DamagePacket: IcarusDamagePacket|{}): boolean
---@field ConsumeHit fun(self: HitableComponent, ActorStateIn: ActorState?, DamagePacket: IcarusDamagePacket|{}): boolean
---@field GetHitableData fun(self: HitableComponent, OutData: HitableData|{}): boolean
---@field Hitable fun(self: HitableComponent)
---@field OnHit fun(self: HitableComponent)

---@class HitableData : IcarusTableRowBase
---@field Behaviour Class

---@class HitableEnum : RowEnum

---@class HitableLibrary : RowLibrary
---@field AddRowToHitableTable fun(self: HitableLibrary, Name: string, Data: HitableData|{}, NewRow: HitableRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakHitableEnum fun(self: HitableLibrary, Enum: HitableEnum|{}, Name: string, Index: integer)
---@field CastToHitableRowHandle fun(self: HitableLibrary, RowHandle: RowHandle|{}, Paths: EValid): HitableRowHandle
---@field EqualEqual_EnumEnum fun(self: HitableLibrary, A: HitableEnum|{}, B: HitableEnum|{}): boolean
---@field EqualEqual_FHitableRowHandleFHitableRowHandle fun(self: HitableLibrary, RowHandleA: HitableRowHandle|{}, RowHandleB: HitableRowHandle|{}): boolean
---@field GetHitableStruct fun(self: HitableLibrary, RowHandle: HitableRowHandle|{}, Hitable: HitableData|{}, Paths: EValid)
---@field IntToName fun(self: HitableLibrary, IntValue: integer): string
---@field IntToStruct fun(self: HitableLibrary, IntValue: integer): HitableEnum
---@field IsValidName fun(self: HitableLibrary, NameValue: string): boolean
---@field MakeHitable fun(self: HitableLibrary, RowName: string): HitableRowHandle
---@field MakeHitableEnum fun(self: HitableLibrary, Enum: HitableEnum|{}): HitableEnum
---@field MakeHitableFromIndex fun(self: HitableLibrary, Index: integer): HitableRowHandle
---@field MakeLiteralHitable fun(self: HitableLibrary, RowHandle: HitableRowHandle|{}): HitableRowHandle
---@field NameToInt fun(self: HitableLibrary, NameValue: string): integer
---@field NameToStruct fun(self: HitableLibrary, NameValue: string): HitableEnum
---@field NotEqual_EnumEnum fun(self: HitableLibrary, A: HitableEnum|{}, B: HitableEnum|{}): boolean
---@field NotEqual_EnumName fun(self: HitableLibrary, A: HitableEnum|{}, B: string): boolean
---@field NumRows fun(self: HitableLibrary): integer
---@field RefreshConstants fun(self: HitableLibrary)
---@field RemoveRowFromHitableTable fun(self: HitableLibrary, Name: string)
---@field RowHandleToStruct fun(self: HitableLibrary, RowHandle: HitableRowHandle|{}): HitableEnum
---@field StructToInt fun(self: HitableLibrary, EnumValue: HitableEnum|{}): integer
---@field StructToName fun(self: HitableLibrary, EnumValue: HitableEnum|{}): string
---@field StructToRowHandle fun(self: HitableLibrary, EnumValue: HitableEnum|{}): HitableRowHandle

---@class HitableRowHandle : RowHandle

---@class HitableTable : IcarusDataTable

---@class Horde : IcarusTableRowBase
---@field CompletionsBeforeInert integer
---@field ExperienceEvent ExperienceEventsRowHandle
---@field InertItemReward ItemRewardsRowHandle[]
---@field ItemReward ItemRewardsRowHandle[]
---@field LocationQueries QuestQueriesRowHandle[]
---@field Waves HordeWaveRowHandle[]

---@class HordeCreatureSetup
---@field AdditionalStats table<BaseStatsEnum, integer>
---@field Creature AISetupRowHandle
---@field Epic EpicCreaturesRowHandle
---@field ExtraSpawnCountPerAdditionalNearbyPlayer integer
---@field InitialSpawnDelay number
---@field LevelOverride integer
---@field NumberToSpawnAtATime Vector2D
---@field TimeBetweenSpawns Vector2D
---@field TotalToSpawn integer

---@class HordeEnum : RowEnum

---@class HordeLibrary : RowLibrary
---@field AddRowToHordeTable fun(self: HordeLibrary, Name: string, Data: Horde|{}, NewRow: HordeRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakHordeEnum fun(self: HordeLibrary, Enum: HordeEnum|{}, Name: string, Index: integer)
---@field CastToHordeRowHandle fun(self: HordeLibrary, RowHandle: RowHandle|{}, Paths: EValid): HordeRowHandle
---@field EqualEqual_EnumEnum fun(self: HordeLibrary, A: HordeEnum|{}, B: HordeEnum|{}): boolean
---@field EqualEqual_FHordeRowHandleFHordeRowHandle fun(self: HordeLibrary, RowHandleA: HordeRowHandle|{}, RowHandleB: HordeRowHandle|{}): boolean
---@field GetHordeStruct fun(self: HordeLibrary, RowHandle: HordeRowHandle|{}, Horde: Horde|{}, Paths: EValid)
---@field IntToName fun(self: HordeLibrary, IntValue: integer): string
---@field IntToStruct fun(self: HordeLibrary, IntValue: integer): HordeEnum
---@field IsValidName fun(self: HordeLibrary, NameValue: string): boolean
---@field MakeHorde fun(self: HordeLibrary, RowName: string): HordeRowHandle
---@field MakeHordeEnum fun(self: HordeLibrary, Enum: HordeEnum|{}): HordeEnum
---@field MakeHordeFromIndex fun(self: HordeLibrary, Index: integer): HordeRowHandle
---@field MakeLiteralHorde fun(self: HordeLibrary, RowHandle: HordeRowHandle|{}): HordeRowHandle
---@field NameToInt fun(self: HordeLibrary, NameValue: string): integer
---@field NameToStruct fun(self: HordeLibrary, NameValue: string): HordeEnum
---@field NotEqual_EnumEnum fun(self: HordeLibrary, A: HordeEnum|{}, B: HordeEnum|{}): boolean
---@field NotEqual_EnumName fun(self: HordeLibrary, A: HordeEnum|{}, B: string): boolean
---@field NumRows fun(self: HordeLibrary): integer
---@field RefreshConstants fun(self: HordeLibrary)
---@field RemoveRowFromHordeTable fun(self: HordeLibrary, Name: string)
---@field RowHandleToStruct fun(self: HordeLibrary, RowHandle: HordeRowHandle|{}): HordeEnum
---@field StructToInt fun(self: HordeLibrary, EnumValue: HordeEnum|{}): integer
---@field StructToName fun(self: HordeLibrary, EnumValue: HordeEnum|{}): string
---@field StructToRowHandle fun(self: HordeLibrary, EnumValue: HordeEnum|{}): HordeRowHandle

---@class HordeRowHandle : RowHandle

---@class HordeTable : IcarusDataTable

---@class HordeWave : IcarusTableRowBase
---@field Creatures HordeCreatureSetup[]

---@class HordeWaveEnum : RowEnum

---@class HordeWaveLibrary : RowLibrary
---@field AddRowToHordeWaveTable fun(self: HordeWaveLibrary, Name: string, Data: HordeWave|{}, NewRow: HordeWaveRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakHordeWaveEnum fun(self: HordeWaveLibrary, Enum: HordeWaveEnum|{}, Name: string, Index: integer)
---@field CastToHordeWaveRowHandle fun(self: HordeWaveLibrary, RowHandle: RowHandle|{}, Paths: EValid): HordeWaveRowHandle
---@field EqualEqual_EnumEnum fun(self: HordeWaveLibrary, A: HordeWaveEnum|{}, B: HordeWaveEnum|{}): boolean
---@field EqualEqual_FHordeWaveRowHandleFHordeWaveRowHandle fun(self: HordeWaveLibrary, RowHandleA: HordeWaveRowHandle|{}, RowHandleB: HordeWaveRowHandle|{}): boolean
---@field GetHordeWaveStruct fun(self: HordeWaveLibrary, RowHandle: HordeWaveRowHandle|{}, HordeWave: HordeWave|{}, Paths: EValid)
---@field IntToName fun(self: HordeWaveLibrary, IntValue: integer): string
---@field IntToStruct fun(self: HordeWaveLibrary, IntValue: integer): HordeWaveEnum
---@field IsValidName fun(self: HordeWaveLibrary, NameValue: string): boolean
---@field MakeHordeWave fun(self: HordeWaveLibrary, RowName: string): HordeWaveRowHandle
---@field MakeHordeWaveEnum fun(self: HordeWaveLibrary, Enum: HordeWaveEnum|{}): HordeWaveEnum
---@field MakeHordeWaveFromIndex fun(self: HordeWaveLibrary, Index: integer): HordeWaveRowHandle
---@field MakeLiteralHordeWave fun(self: HordeWaveLibrary, RowHandle: HordeWaveRowHandle|{}): HordeWaveRowHandle
---@field NameToInt fun(self: HordeWaveLibrary, NameValue: string): integer
---@field NameToStruct fun(self: HordeWaveLibrary, NameValue: string): HordeWaveEnum
---@field NotEqual_EnumEnum fun(self: HordeWaveLibrary, A: HordeWaveEnum|{}, B: HordeWaveEnum|{}): boolean
---@field NotEqual_EnumName fun(self: HordeWaveLibrary, A: HordeWaveEnum|{}, B: string): boolean
---@field NumRows fun(self: HordeWaveLibrary): integer
---@field RefreshConstants fun(self: HordeWaveLibrary)
---@field RemoveRowFromHordeWaveTable fun(self: HordeWaveLibrary, Name: string)
---@field RowHandleToStruct fun(self: HordeWaveLibrary, RowHandle: HordeWaveRowHandle|{}): HordeWaveEnum
---@field StructToInt fun(self: HordeWaveLibrary, EnumValue: HordeWaveEnum|{}): integer
---@field StructToName fun(self: HordeWaveLibrary, EnumValue: HordeWaveEnum|{}): string
---@field StructToRowHandle fun(self: HordeWaveLibrary, EnumValue: HordeWaveEnum|{}): HordeWaveRowHandle

---@class HordeWaveRowHandle : RowHandle

---@class HordeWaveTable : IcarusDataTable

---@class HuntingClue : IcarusActor

---@class HuntingClueSetup : IcarusTableRowBase
---@field ClueLifespan number
---@field ClueType EHuntingClueType
---@field HasTrail boolean
---@field HuntingClue Class
---@field HuntingWidget Class
---@field MaxClueDistance number
---@field MaxDistanceBetweenClues number
---@field MaxTimeBetweenClues number
---@field MinDistanceBetweenClues number
---@field MinTimeBetweenClues number
---@field TrailSegmentLength number

---@class HuntingClueSetupEnum : RowEnum

---@class HuntingClueSetupLibrary : RowLibrary
---@field AddRowToHuntingClueSetupTable fun(self: HuntingClueSetupLibrary, Name: string, Data: HuntingClueSetup|{}, NewRow: HuntingClueSetupRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakHuntingClueSetupEnum fun(self: HuntingClueSetupLibrary, Enum: HuntingClueSetupEnum|{}, Name: string, Index: integer)
---@field CastToHuntingClueSetupRowHandle fun(self: HuntingClueSetupLibrary, RowHandle: RowHandle|{}, Paths: EValid): HuntingClueSetupRowHandle
---@field EqualEqual_EnumEnum fun(self: HuntingClueSetupLibrary, A: HuntingClueSetupEnum|{}, B: HuntingClueSetupEnum|{}): boolean
---@field EqualEqual_FHuntingClueSetupRowHandleFHuntingClueSetupRowHandle fun(self: HuntingClueSetupLibrary, RowHandleA: HuntingClueSetupRowHandle|{}, RowHandleB: HuntingClueSetupRowHandle|{}): boolean
---@field GetHuntingClueSetupStruct fun(self: HuntingClueSetupLibrary, RowHandle: HuntingClueSetupRowHandle|{}, HuntingClueSetup: HuntingClueSetup|{}, Paths: EValid)
---@field IntToName fun(self: HuntingClueSetupLibrary, IntValue: integer): string
---@field IntToStruct fun(self: HuntingClueSetupLibrary, IntValue: integer): HuntingClueSetupEnum
---@field IsValidName fun(self: HuntingClueSetupLibrary, NameValue: string): boolean
---@field MakeHuntingClueSetup fun(self: HuntingClueSetupLibrary, RowName: string): HuntingClueSetupRowHandle
---@field MakeHuntingClueSetupEnum fun(self: HuntingClueSetupLibrary, Enum: HuntingClueSetupEnum|{}): HuntingClueSetupEnum
---@field MakeHuntingClueSetupFromIndex fun(self: HuntingClueSetupLibrary, Index: integer): HuntingClueSetupRowHandle
---@field MakeLiteralHuntingClueSetup fun(self: HuntingClueSetupLibrary, RowHandle: HuntingClueSetupRowHandle|{}): HuntingClueSetupRowHandle
---@field NameToInt fun(self: HuntingClueSetupLibrary, NameValue: string): integer
---@field NameToStruct fun(self: HuntingClueSetupLibrary, NameValue: string): HuntingClueSetupEnum
---@field NotEqual_EnumEnum fun(self: HuntingClueSetupLibrary, A: HuntingClueSetupEnum|{}, B: HuntingClueSetupEnum|{}): boolean
---@field NotEqual_EnumName fun(self: HuntingClueSetupLibrary, A: HuntingClueSetupEnum|{}, B: string): boolean
---@field NumRows fun(self: HuntingClueSetupLibrary): integer
---@field RefreshConstants fun(self: HuntingClueSetupLibrary)
---@field RemoveRowFromHuntingClueSetupTable fun(self: HuntingClueSetupLibrary, Name: string)
---@field RowHandleToStruct fun(self: HuntingClueSetupLibrary, RowHandle: HuntingClueSetupRowHandle|{}): HuntingClueSetupEnum
---@field StructToInt fun(self: HuntingClueSetupLibrary, EnumValue: HuntingClueSetupEnum|{}): integer
---@field StructToName fun(self: HuntingClueSetupLibrary, EnumValue: HuntingClueSetupEnum|{}): string
---@field StructToRowHandle fun(self: HuntingClueSetupLibrary, EnumValue: HuntingClueSetupEnum|{}): HuntingClueSetupRowHandle

---@class HuntingClueSetupRowHandle : RowHandle

---@class HuntingClueSetupTable : IcarusDataTable

---@class HuntingSetup : IcarusTableRowBase
---@field HuntingClues HuntingClueSetupRowHandle[]

---@class HuntingSetupEnum : RowEnum

---@class HuntingSetupLibrary : RowLibrary
---@field AddRowToHuntingSetupTable fun(self: HuntingSetupLibrary, Name: string, Data: HuntingSetup|{}, NewRow: HuntingSetupRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakHuntingSetupEnum fun(self: HuntingSetupLibrary, Enum: HuntingSetupEnum|{}, Name: string, Index: integer)
---@field CastToHuntingSetupRowHandle fun(self: HuntingSetupLibrary, RowHandle: RowHandle|{}, Paths: EValid): HuntingSetupRowHandle
---@field EqualEqual_EnumEnum fun(self: HuntingSetupLibrary, A: HuntingSetupEnum|{}, B: HuntingSetupEnum|{}): boolean
---@field EqualEqual_FHuntingSetupRowHandleFHuntingSetupRowHandle fun(self: HuntingSetupLibrary, RowHandleA: HuntingSetupRowHandle|{}, RowHandleB: HuntingSetupRowHandle|{}): boolean
---@field GetHuntingSetupStruct fun(self: HuntingSetupLibrary, RowHandle: HuntingSetupRowHandle|{}, HuntingSetup: HuntingSetup|{}, Paths: EValid)
---@field IntToName fun(self: HuntingSetupLibrary, IntValue: integer): string
---@field IntToStruct fun(self: HuntingSetupLibrary, IntValue: integer): HuntingSetupEnum
---@field IsValidName fun(self: HuntingSetupLibrary, NameValue: string): boolean
---@field MakeHuntingSetup fun(self: HuntingSetupLibrary, RowName: string): HuntingSetupRowHandle
---@field MakeHuntingSetupEnum fun(self: HuntingSetupLibrary, Enum: HuntingSetupEnum|{}): HuntingSetupEnum
---@field MakeHuntingSetupFromIndex fun(self: HuntingSetupLibrary, Index: integer): HuntingSetupRowHandle
---@field MakeLiteralHuntingSetup fun(self: HuntingSetupLibrary, RowHandle: HuntingSetupRowHandle|{}): HuntingSetupRowHandle
---@field NameToInt fun(self: HuntingSetupLibrary, NameValue: string): integer
---@field NameToStruct fun(self: HuntingSetupLibrary, NameValue: string): HuntingSetupEnum
---@field NotEqual_EnumEnum fun(self: HuntingSetupLibrary, A: HuntingSetupEnum|{}, B: HuntingSetupEnum|{}): boolean
---@field NotEqual_EnumName fun(self: HuntingSetupLibrary, A: HuntingSetupEnum|{}, B: string): boolean
---@field NumRows fun(self: HuntingSetupLibrary): integer
---@field RefreshConstants fun(self: HuntingSetupLibrary)
---@field RemoveRowFromHuntingSetupTable fun(self: HuntingSetupLibrary, Name: string)
---@field RowHandleToStruct fun(self: HuntingSetupLibrary, RowHandle: HuntingSetupRowHandle|{}): HuntingSetupEnum
---@field StructToInt fun(self: HuntingSetupLibrary, EnumValue: HuntingSetupEnum|{}): integer
---@field StructToName fun(self: HuntingSetupLibrary, EnumValue: HuntingSetupEnum|{}): string
---@field StructToRowHandle fun(self: HuntingSetupLibrary, EnumValue: HuntingSetupEnum|{}): HuntingSetupRowHandle

---@class HuntingSetupRowHandle : RowHandle

---@class HuntingSetupTable : IcarusDataTable

---@class HuntingWidget : UserWidget
