---@meta _
-- Generated by scripts\gameindex.py from the index of the game's classes. Changes here are lost on the next run.

---@class ItemAnimationData : IcarusTableRowBase
---@field FPJumpEnd AnimSequence
---@field FPJumpLoop AnimSequence
---@field FPJumpStart AnimSequence
---@field FPLocoBlendSpace BlendSpace1D
---@field TPJumpEnd AnimSequence
---@field TPJumpLoop AnimSequence
---@field TPJumpStart AnimSequence
---@field TPLocomotionAnims LocomotionAnims
---@field UpToDownBlendSpace BlendSpace1D

---@class ItemAnimationsEnum : RowEnum

---@class ItemAnimationsLibrary : RowLibrary
---@field AddRowToItemAnimationsTable fun(self: ItemAnimationsLibrary, Name: string, Data: ItemAnimationData|{}, NewRow: ItemAnimationsRowHandle|{}, bOverrideExistingRow: boolean) Do not call from Lua: it needs 904 bytes and the call buffer holds 512.
---@field BreakItemAnimationsEnum fun(self: ItemAnimationsLibrary, Enum: ItemAnimationsEnum|{}, Name: string, Index: integer)
---@field CastToItemAnimationsRowHandle fun(self: ItemAnimationsLibrary, RowHandle: RowHandle|{}, Paths: EValid): ItemAnimationsRowHandle
---@field EqualEqual_EnumEnum fun(self: ItemAnimationsLibrary, A: ItemAnimationsEnum|{}, B: ItemAnimationsEnum|{}): boolean
---@field EqualEqual_FItemAnimationsRowHandleFItemAnimationsRowHandle fun(self: ItemAnimationsLibrary, RowHandleA: ItemAnimationsRowHandle|{}, RowHandleB: ItemAnimationsRowHandle|{}): boolean
---@field GetItemAnimationsStruct fun(self: ItemAnimationsLibrary, RowHandle: ItemAnimationsRowHandle|{}, ItemAnimations: ItemAnimationData|{}, Paths: EValid) Do not call from Lua: it needs 896 bytes and the call buffer holds 512.
---@field IntToName fun(self: ItemAnimationsLibrary, IntValue: integer): string
---@field IntToStruct fun(self: ItemAnimationsLibrary, IntValue: integer): ItemAnimationsEnum
---@field IsValidName fun(self: ItemAnimationsLibrary, NameValue: string): boolean
---@field MakeItemAnimations fun(self: ItemAnimationsLibrary, RowName: string): ItemAnimationsRowHandle
---@field MakeItemAnimationsEnum fun(self: ItemAnimationsLibrary, Enum: ItemAnimationsEnum|{}): ItemAnimationsEnum
---@field MakeItemAnimationsFromIndex fun(self: ItemAnimationsLibrary, Index: integer): ItemAnimationsRowHandle
---@field MakeLiteralItemAnimations fun(self: ItemAnimationsLibrary, RowHandle: ItemAnimationsRowHandle|{}): ItemAnimationsRowHandle
---@field NameToInt fun(self: ItemAnimationsLibrary, NameValue: string): integer
---@field NameToStruct fun(self: ItemAnimationsLibrary, NameValue: string): ItemAnimationsEnum
---@field NotEqual_EnumEnum fun(self: ItemAnimationsLibrary, A: ItemAnimationsEnum|{}, B: ItemAnimationsEnum|{}): boolean
---@field NotEqual_EnumName fun(self: ItemAnimationsLibrary, A: ItemAnimationsEnum|{}, B: string): boolean
---@field NumRows fun(self: ItemAnimationsLibrary): integer
---@field RefreshConstants fun(self: ItemAnimationsLibrary)
---@field RemoveRowFromItemAnimationsTable fun(self: ItemAnimationsLibrary, Name: string)
---@field RowHandleToStruct fun(self: ItemAnimationsLibrary, RowHandle: ItemAnimationsRowHandle|{}): ItemAnimationsEnum
---@field StructToInt fun(self: ItemAnimationsLibrary, EnumValue: ItemAnimationsEnum|{}): integer
---@field StructToName fun(self: ItemAnimationsLibrary, EnumValue: ItemAnimationsEnum|{}): string
---@field StructToRowHandle fun(self: ItemAnimationsLibrary, EnumValue: ItemAnimationsEnum|{}): ItemAnimationsRowHandle

---@class ItemAnimationsRowHandle : RowHandle

---@class ItemAnimationsTable : IcarusDataTable

---@class ItemAttachmentData : IcarusTableRowBase
---@field BackAttachmentSocketName string
---@field EquippableHandedness EHandedness
---@field FPAttachmentSocketName string
---@field TPAttachmentSocketName string

---@class ItemAttachmentEnum : RowEnum

---@class ItemAttachmentLibrary : RowLibrary
---@field AddRowToItemAttachmentTable fun(self: ItemAttachmentLibrary, Name: string, Data: ItemAttachmentData|{}, NewRow: ItemAttachmentRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakItemAttachmentEnum fun(self: ItemAttachmentLibrary, Enum: ItemAttachmentEnum|{}, Name: string, Index: integer)
---@field CastToItemAttachmentRowHandle fun(self: ItemAttachmentLibrary, RowHandle: RowHandle|{}, Paths: EValid): ItemAttachmentRowHandle
---@field EqualEqual_EnumEnum fun(self: ItemAttachmentLibrary, A: ItemAttachmentEnum|{}, B: ItemAttachmentEnum|{}): boolean
---@field EqualEqual_FItemAttachmentRowHandleFItemAttachmentRowHandle fun(self: ItemAttachmentLibrary, RowHandleA: ItemAttachmentRowHandle|{}, RowHandleB: ItemAttachmentRowHandle|{}): boolean
---@field GetItemAttachmentStruct fun(self: ItemAttachmentLibrary, RowHandle: ItemAttachmentRowHandle|{}, ItemAttachment: ItemAttachmentData|{}, Paths: EValid)
---@field IntToName fun(self: ItemAttachmentLibrary, IntValue: integer): string
---@field IntToStruct fun(self: ItemAttachmentLibrary, IntValue: integer): ItemAttachmentEnum
---@field IsValidName fun(self: ItemAttachmentLibrary, NameValue: string): boolean
---@field MakeItemAttachment fun(self: ItemAttachmentLibrary, RowName: string): ItemAttachmentRowHandle
---@field MakeItemAttachmentEnum fun(self: ItemAttachmentLibrary, Enum: ItemAttachmentEnum|{}): ItemAttachmentEnum
---@field MakeItemAttachmentFromIndex fun(self: ItemAttachmentLibrary, Index: integer): ItemAttachmentRowHandle
---@field MakeLiteralItemAttachment fun(self: ItemAttachmentLibrary, RowHandle: ItemAttachmentRowHandle|{}): ItemAttachmentRowHandle
---@field NameToInt fun(self: ItemAttachmentLibrary, NameValue: string): integer
---@field NameToStruct fun(self: ItemAttachmentLibrary, NameValue: string): ItemAttachmentEnum
---@field NotEqual_EnumEnum fun(self: ItemAttachmentLibrary, A: ItemAttachmentEnum|{}, B: ItemAttachmentEnum|{}): boolean
---@field NotEqual_EnumName fun(self: ItemAttachmentLibrary, A: ItemAttachmentEnum|{}, B: string): boolean
---@field NumRows fun(self: ItemAttachmentLibrary): integer
---@field RefreshConstants fun(self: ItemAttachmentLibrary)
---@field RemoveRowFromItemAttachmentTable fun(self: ItemAttachmentLibrary, Name: string)
---@field RowHandleToStruct fun(self: ItemAttachmentLibrary, RowHandle: ItemAttachmentRowHandle|{}): ItemAttachmentEnum
---@field StructToInt fun(self: ItemAttachmentLibrary, EnumValue: ItemAttachmentEnum|{}): integer
---@field StructToName fun(self: ItemAttachmentLibrary, EnumValue: ItemAttachmentEnum|{}): string
---@field StructToRowHandle fun(self: ItemAttachmentLibrary, EnumValue: ItemAttachmentEnum|{}): ItemAttachmentRowHandle

---@class ItemAttachmentRowHandle : RowHandle

---@class ItemAttachmentTable : IcarusDataTable

---@class ItemAudioAnimData
---@field FMODEvents FMODEvent[]

---@class ItemAudioData : IcarusTableRowBase
---@field AnimSounds table<string, ItemAudioAnimData>
---@field BackpackFootstepSound FMODEvent
---@field BackpackSound FMODEvent
---@field BrokenSound FMODEvent
---@field ConsumableExpiredSound FMODEvent
---@field ConsumeFailedSound FMODEvent
---@field ConsumedSound FMODEvent
---@field DamagedSound FMODEvent
---@field DestroyedSound FMODEvent
---@field DropSound FMODEvent
---@field HitSound FMODEvent
---@field PickUpSound FMODEvent
---@field RepairedSound FMODEvent
---@field SlottedSound FMODEvent
---@field UseWhenBrokenSound FMODEvent
---@field WeatherSound FMODEvent

---@class ItemAudioDataEnum : RowEnum

---@class ItemAudioDataLibrary : RowLibrary
---@field AddRowToItemAudioDataTable fun(self: ItemAudioDataLibrary, Name: string, Data: ItemAudioData|{}, NewRow: ItemAudioDataRowHandle|{}, bOverrideExistingRow: boolean) Do not call from Lua: it needs 744 bytes and the call buffer holds 512.
---@field BreakItemAudioDataEnum fun(self: ItemAudioDataLibrary, Enum: ItemAudioDataEnum|{}, Name: string, Index: integer)
---@field CastToItemAudioDataRowHandle fun(self: ItemAudioDataLibrary, RowHandle: RowHandle|{}, Paths: EValid): ItemAudioDataRowHandle
---@field EqualEqual_EnumEnum fun(self: ItemAudioDataLibrary, A: ItemAudioDataEnum|{}, B: ItemAudioDataEnum|{}): boolean
---@field EqualEqual_FItemAudioDataRowHandleFItemAudioDataRowHandle fun(self: ItemAudioDataLibrary, RowHandleA: ItemAudioDataRowHandle|{}, RowHandleB: ItemAudioDataRowHandle|{}): boolean
---@field GetItemAudioDataStruct fun(self: ItemAudioDataLibrary, RowHandle: ItemAudioDataRowHandle|{}, ItemAudioData: ItemAudioData|{}, Paths: EValid) Do not call from Lua: it needs 736 bytes and the call buffer holds 512.
---@field IntToName fun(self: ItemAudioDataLibrary, IntValue: integer): string
---@field IntToStruct fun(self: ItemAudioDataLibrary, IntValue: integer): ItemAudioDataEnum
---@field IsValidName fun(self: ItemAudioDataLibrary, NameValue: string): boolean
---@field MakeItemAudioData fun(self: ItemAudioDataLibrary, RowName: string): ItemAudioDataRowHandle
---@field MakeItemAudioDataEnum fun(self: ItemAudioDataLibrary, Enum: ItemAudioDataEnum|{}): ItemAudioDataEnum
---@field MakeItemAudioDataFromIndex fun(self: ItemAudioDataLibrary, Index: integer): ItemAudioDataRowHandle
---@field MakeLiteralItemAudioData fun(self: ItemAudioDataLibrary, RowHandle: ItemAudioDataRowHandle|{}): ItemAudioDataRowHandle
---@field NameToInt fun(self: ItemAudioDataLibrary, NameValue: string): integer
---@field NameToStruct fun(self: ItemAudioDataLibrary, NameValue: string): ItemAudioDataEnum
---@field NotEqual_EnumEnum fun(self: ItemAudioDataLibrary, A: ItemAudioDataEnum|{}, B: ItemAudioDataEnum|{}): boolean
---@field NotEqual_EnumName fun(self: ItemAudioDataLibrary, A: ItemAudioDataEnum|{}, B: string): boolean
---@field NumRows fun(self: ItemAudioDataLibrary): integer
---@field RefreshConstants fun(self: ItemAudioDataLibrary)
---@field RemoveRowFromItemAudioDataTable fun(self: ItemAudioDataLibrary, Name: string)
---@field RowHandleToStruct fun(self: ItemAudioDataLibrary, RowHandle: ItemAudioDataRowHandle|{}): ItemAudioDataEnum
---@field StructToInt fun(self: ItemAudioDataLibrary, EnumValue: ItemAudioDataEnum|{}): integer
---@field StructToName fun(self: ItemAudioDataLibrary, EnumValue: ItemAudioDataEnum|{}): string
---@field StructToRowHandle fun(self: ItemAudioDataLibrary, EnumValue: ItemAudioDataEnum|{}): ItemAudioDataRowHandle

---@class ItemAudioDataRowHandle : RowHandle

---@class ItemAudioDataTable : IcarusDataTable

---@class ItemClassificationsIconsData : IcarusTableRowBase
---@field Icon Texture2D
---@field TagQuery TagQueriesRowHandle
---@field Tooltip string

---@class ItemClassificationsIconsEnum : RowEnum

---@class ItemClassificationsIconsLibrary : RowLibrary
---@field AddRowToItemClassificationsIconsTable fun(self: ItemClassificationsIconsLibrary, Name: string, Data: ItemClassificationsIconsData|{}, NewRow: ItemClassificationsIconsRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakItemClassificationsIconsEnum fun(self: ItemClassificationsIconsLibrary, Enum: ItemClassificationsIconsEnum|{}, Name: string, Index: integer)
---@field CastToItemClassificationsIconsRowHandle fun(self: ItemClassificationsIconsLibrary, RowHandle: RowHandle|{}, Paths: EValid): ItemClassificationsIconsRowHandle
---@field EqualEqual_EnumEnum fun(self: ItemClassificationsIconsLibrary, A: ItemClassificationsIconsEnum|{}, B: ItemClassificationsIconsEnum|{}): boolean
---@field EqualEqual_FItemClassificationsIconsRowHandleFItemClassificationsIconsRowHandle fun(self: ItemClassificationsIconsLibrary, RowHandleA: ItemClassificationsIconsRowHandle|{}, RowHandleB: ItemClassificationsIconsRowHandle|{}): boolean
---@field GetItemClassificationsIconsStruct fun(self: ItemClassificationsIconsLibrary, RowHandle: ItemClassificationsIconsRowHandle|{}, ItemClassificationsIcons: ItemClassificationsIconsData|{}, Paths: EValid)
---@field IntToName fun(self: ItemClassificationsIconsLibrary, IntValue: integer): string
---@field IntToStruct fun(self: ItemClassificationsIconsLibrary, IntValue: integer): ItemClassificationsIconsEnum
---@field IsValidName fun(self: ItemClassificationsIconsLibrary, NameValue: string): boolean
---@field MakeItemClassificationsIcons fun(self: ItemClassificationsIconsLibrary, RowName: string): ItemClassificationsIconsRowHandle
---@field MakeItemClassificationsIconsEnum fun(self: ItemClassificationsIconsLibrary, Enum: ItemClassificationsIconsEnum|{}): ItemClassificationsIconsEnum
---@field MakeItemClassificationsIconsFromIndex fun(self: ItemClassificationsIconsLibrary, Index: integer): ItemClassificationsIconsRowHandle
---@field MakeLiteralItemClassificationsIcons fun(self: ItemClassificationsIconsLibrary, RowHandle: ItemClassificationsIconsRowHandle|{}): ItemClassificationsIconsRowHandle
---@field NameToInt fun(self: ItemClassificationsIconsLibrary, NameValue: string): integer
---@field NameToStruct fun(self: ItemClassificationsIconsLibrary, NameValue: string): ItemClassificationsIconsEnum
---@field NotEqual_EnumEnum fun(self: ItemClassificationsIconsLibrary, A: ItemClassificationsIconsEnum|{}, B: ItemClassificationsIconsEnum|{}): boolean
---@field NotEqual_EnumName fun(self: ItemClassificationsIconsLibrary, A: ItemClassificationsIconsEnum|{}, B: string): boolean
---@field NumRows fun(self: ItemClassificationsIconsLibrary): integer
---@field RefreshConstants fun(self: ItemClassificationsIconsLibrary)
---@field RemoveRowFromItemClassificationsIconsTable fun(self: ItemClassificationsIconsLibrary, Name: string)
---@field RowHandleToStruct fun(self: ItemClassificationsIconsLibrary, RowHandle: ItemClassificationsIconsRowHandle|{}): ItemClassificationsIconsEnum
---@field StructToInt fun(self: ItemClassificationsIconsLibrary, EnumValue: ItemClassificationsIconsEnum|{}): integer
---@field StructToName fun(self: ItemClassificationsIconsLibrary, EnumValue: ItemClassificationsIconsEnum|{}): string
---@field StructToRowHandle fun(self: ItemClassificationsIconsLibrary, EnumValue: ItemClassificationsIconsEnum|{}): ItemClassificationsIconsRowHandle

---@class ItemClassificationsIconsRowHandle : RowHandle

---@class ItemClassificationsIconsTable : IcarusDataTable

---@class ItemData : IcarusTableRowBase
---@field CachedStats CachedItemStatContainer
---@field CustomProperties CustomProperties
---@field DatabaseGUID string
---@field ItemCustomStats IcarusStatReplicated[]
---@field ItemDynamicData ItemDynamicData[]
---@field ItemOwnerLookupId integer
---@field ItemStaticData ItemsStaticRowHandle
---@field RuntimeTags GameplayTagContainer
---@field bIsItemInstance boolean

---@class ItemDynamicData
---@field PropertyType EDynamicItemProperties
---@field Value integer

---@class ItemManipulationComponent : ActorComponent
---@field CanRepairItem fun(self: ItemManipulationComponent, SourceInventory: Inventory?, SourceLocation: integer, Target: IcarusPlayerCharacter?): boolean
---@field CanUseItem fun(self: ItemManipulationComponent, SourceInventory: Inventory?, SourceLocation: integer, Use: UsesEnum|{}, UseCondition: UseCondition|{}, Target: IcarusPlayerCharacter?): ECanUseItemResult
---@field ConsumeItem fun(self: ItemManipulationComponent, Source: IcarusPlayerCharacter?, SourceInventory: Inventory?, SourceLocation: integer, Target: IcarusCharacter?, ItemConsumed: ItemData|{}): boolean Do not call from Lua: it needs 536 bytes and the call buffer holds 512.
---@field FindItemsRequiredForRepair fun(self: ItemManipulationComponent, ItemData: ItemData|{}, Inventories: Inventory[]): QueueItem[] Do not call from Lua: it needs 528 bytes and the call buffer holds 512.
---@field GetTotalFoodRecovery fun(self: ItemManipulationComponent, TargetPlayer: SurvivalCharacterState?, ItemData: ItemData|{}): integer
---@field PlaceItem fun(self: ItemManipulationComponent, SourceInventory: Inventory?, SourceLocation: integer, Target: IcarusPlayerCharacter?): boolean
---@field RepairItem fun(self: ItemManipulationComponent, SourceInventory: Inventory?, SourceLocation: integer, Target: IcarusPlayerCharacter?): boolean
---@field UseItem fun(self: ItemManipulationComponent, Source: IcarusPlayerCharacter?, SourceInventory: Inventory?, SourceLocation: integer, Use: UsesEnum|{}, Target: IcarusCharacter?, ItemConsumed: ItemData|{}): boolean Do not call from Lua: it needs 552 bytes and the call buffer holds 512.

---@class ItemPriority
---@field InventoryID InventoryIDEnum
---@field QueryRow TagQueriesRowHandle

---@class ItemRank : IcarusTableRowBase
---@field Icon Texture2D
---@field TagQuery TagQueriesRowHandle

---@class ItemRanksEnum : RowEnum

---@class ItemRanksLibrary : RowLibrary
---@field AddRowToItemRanksTable fun(self: ItemRanksLibrary, Name: string, Data: ItemRank|{}, NewRow: ItemRanksRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakItemRanksEnum fun(self: ItemRanksLibrary, Enum: ItemRanksEnum|{}, Name: string, Index: integer)
---@field CastToItemRanksRowHandle fun(self: ItemRanksLibrary, RowHandle: RowHandle|{}, Paths: EValid): ItemRanksRowHandle
---@field EqualEqual_EnumEnum fun(self: ItemRanksLibrary, A: ItemRanksEnum|{}, B: ItemRanksEnum|{}): boolean
---@field EqualEqual_FItemRanksRowHandleFItemRanksRowHandle fun(self: ItemRanksLibrary, RowHandleA: ItemRanksRowHandle|{}, RowHandleB: ItemRanksRowHandle|{}): boolean
---@field GetItemRanksStruct fun(self: ItemRanksLibrary, RowHandle: ItemRanksRowHandle|{}, ItemRanks: ItemRank|{}, Paths: EValid)
---@field IntToName fun(self: ItemRanksLibrary, IntValue: integer): string
---@field IntToStruct fun(self: ItemRanksLibrary, IntValue: integer): ItemRanksEnum
---@field IsValidName fun(self: ItemRanksLibrary, NameValue: string): boolean
---@field MakeItemRanks fun(self: ItemRanksLibrary, RowName: string): ItemRanksRowHandle
---@field MakeItemRanksEnum fun(self: ItemRanksLibrary, Enum: ItemRanksEnum|{}): ItemRanksEnum
---@field MakeItemRanksFromIndex fun(self: ItemRanksLibrary, Index: integer): ItemRanksRowHandle
---@field MakeLiteralItemRanks fun(self: ItemRanksLibrary, RowHandle: ItemRanksRowHandle|{}): ItemRanksRowHandle
---@field NameToInt fun(self: ItemRanksLibrary, NameValue: string): integer
---@field NameToStruct fun(self: ItemRanksLibrary, NameValue: string): ItemRanksEnum
---@field NotEqual_EnumEnum fun(self: ItemRanksLibrary, A: ItemRanksEnum|{}, B: ItemRanksEnum|{}): boolean
---@field NotEqual_EnumName fun(self: ItemRanksLibrary, A: ItemRanksEnum|{}, B: string): boolean
---@field NumRows fun(self: ItemRanksLibrary): integer
---@field RefreshConstants fun(self: ItemRanksLibrary)
---@field RemoveRowFromItemRanksTable fun(self: ItemRanksLibrary, Name: string)
---@field RowHandleToStruct fun(self: ItemRanksLibrary, RowHandle: ItemRanksRowHandle|{}): ItemRanksEnum
---@field StructToInt fun(self: ItemRanksLibrary, EnumValue: ItemRanksEnum|{}): integer
---@field StructToName fun(self: ItemRanksLibrary, EnumValue: ItemRanksEnum|{}): string
---@field StructToRowHandle fun(self: ItemRanksLibrary, EnumValue: ItemRanksEnum|{}): ItemRanksRowHandle

---@class ItemRanksRowHandle : RowHandle

---@class ItemRanksTable : IcarusDataTable

---@class ItemRecordAlterationData
---@field Alteration string

---@class ItemRecordDynamicData
---@field Type integer
---@field Value integer

---@class ItemRecordStatData
---@field Stat string
---@field Value integer

---@class ItemResourceGeneratedAlterationResult
---@field Item ItemData
---@field ResourceGeneratedAlterations AlterationsEnum[]

---@class ItemReward
---@field ItemTemplate ItemTemplateRowHandle
---@field MaxRandomStackCount integer
---@field MinRandomStackCount integer
---@field bUseRandomStackCount boolean

---@class ItemRewardEntry
---@field DropChance number
---@field DropChanceAdditiveStat StatsRowHandle
---@field Item ItemTemplateRowHandle
---@field MaxRandomStackCount integer
---@field MinRandomStackCount integer
---@field RequiredStatToDrop StatsRowHandle
---@field StackAdditiveStat StatsRowHandle
---@field StackMultiplicativeStat StatsRowHandle
---@field bRewardsScale boolean

---@class ItemRewardFactory : BlueprintFunctionLibrary
---@field GenerateHarvestedItemRewards fun(self: ItemRewardFactory, ItemRewards: ItemRewardEntry[], ResourceRewardModifier: number, SeedRewardMultiplier: number, HarvestingActorStats: IcarusStatContainer?, CropPlotActorStats: IcarusStatContainer?, WorldContextObject: Object?): ItemData[]
---@field GenerateItemData fun(self: ItemRewardFactory, ItemReward: ItemReward|{}, WorldContextObject: Object?): ItemData Do not call from Lua: it needs 544 bytes and the call buffer holds 512.
---@field GenerateItemFromReward fun(self: ItemRewardFactory, ItemReward: ItemRewardEntry|{}, WorldContextObject: Object?): ItemData Do not call from Lua: it needs 640 bytes and the call buffer holds 512.
---@field GenerateItemFromRewardWithPlayerStats fun(self: ItemRewardFactory, ItemReward: ItemRewardEntry|{}, Character: IcarusPlayerCharacter?, WorldContextObject: Object?): ItemData Do not call from Lua: it needs 648 bytes and the call buffer holds 512.

---@class ItemRewards : IcarusTableRowBase
---@field Rewards ItemRewardEntry[]

---@class ItemRewardsEnum : RowEnum

---@class ItemRewardsLibrary : RowLibrary
---@field AddRowToItemRewardsTable fun(self: ItemRewardsLibrary, Name: string, Data: ItemRewards|{}, NewRow: ItemRewardsRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakItemRewardsEnum fun(self: ItemRewardsLibrary, Enum: ItemRewardsEnum|{}, Name: string, Index: integer)
---@field CastToItemRewardsRowHandle fun(self: ItemRewardsLibrary, RowHandle: RowHandle|{}, Paths: EValid): ItemRewardsRowHandle
---@field EqualEqual_EnumEnum fun(self: ItemRewardsLibrary, A: ItemRewardsEnum|{}, B: ItemRewardsEnum|{}): boolean
---@field EqualEqual_FItemRewardsRowHandleFItemRewardsRowHandle fun(self: ItemRewardsLibrary, RowHandleA: ItemRewardsRowHandle|{}, RowHandleB: ItemRewardsRowHandle|{}): boolean
---@field GetItemRewardsStruct fun(self: ItemRewardsLibrary, RowHandle: ItemRewardsRowHandle|{}, ItemRewards: ItemRewards|{}, Paths: EValid)
---@field IntToName fun(self: ItemRewardsLibrary, IntValue: integer): string
---@field IntToStruct fun(self: ItemRewardsLibrary, IntValue: integer): ItemRewardsEnum
---@field IsValidName fun(self: ItemRewardsLibrary, NameValue: string): boolean
---@field MakeItemRewards fun(self: ItemRewardsLibrary, RowName: string): ItemRewardsRowHandle
---@field MakeItemRewardsEnum fun(self: ItemRewardsLibrary, Enum: ItemRewardsEnum|{}): ItemRewardsEnum
---@field MakeItemRewardsFromIndex fun(self: ItemRewardsLibrary, Index: integer): ItemRewardsRowHandle
---@field MakeLiteralItemRewards fun(self: ItemRewardsLibrary, RowHandle: ItemRewardsRowHandle|{}): ItemRewardsRowHandle
---@field NameToInt fun(self: ItemRewardsLibrary, NameValue: string): integer
---@field NameToStruct fun(self: ItemRewardsLibrary, NameValue: string): ItemRewardsEnum
---@field NotEqual_EnumEnum fun(self: ItemRewardsLibrary, A: ItemRewardsEnum|{}, B: ItemRewardsEnum|{}): boolean
---@field NotEqual_EnumName fun(self: ItemRewardsLibrary, A: ItemRewardsEnum|{}, B: string): boolean
---@field NumRows fun(self: ItemRewardsLibrary): integer
---@field RefreshConstants fun(self: ItemRewardsLibrary)
---@field RemoveRowFromItemRewardsTable fun(self: ItemRewardsLibrary, Name: string)
---@field RowHandleToStruct fun(self: ItemRewardsLibrary, RowHandle: ItemRewardsRowHandle|{}): ItemRewardsEnum
---@field StructToInt fun(self: ItemRewardsLibrary, EnumValue: ItemRewardsEnum|{}): integer
---@field StructToName fun(self: ItemRewardsLibrary, EnumValue: ItemRewardsEnum|{}): string
---@field StructToRowHandle fun(self: ItemRewardsLibrary, EnumValue: ItemRewardsEnum|{}): ItemRewardsRowHandle

---@class ItemRewardsRowHandle : RowHandle

---@class ItemRewardsTable : IcarusDataTable

---@class ItemStateRecorderComponent : ActorStateRecorderComponent
---@field Alterations ItemRecordAlterationData[]
---@field ConstructionParameters IcarusItemConstructionParameters
---@field DatabaseGUID string
---@field DynamicData ItemRecordDynamicData[]
---@field ItemOwnerLookupId integer
---@field LivingItemSlots LivingItemSlotSaveData[]
---@field SpawnedContext EIcarusItemContext
---@field StaticItemDataRowName string
---@field Stats ItemRecordStatData[]

---@class ItemStaticData : IcarusTableRowBase
---@field Actionable ActionableRowHandle
---@field AdditionalStats table<BaseStatsEnum, integer>
---@field AmmoType AmmoTypesRowHandle
---@field Armour ArmourRowHandle
---@field Attachments IcarusAttachmentsRowHandle
---@field Audio ItemAudioDataRowHandle
---@field Ballistic BallisticRowHandle
---@field Buildable BuildableRowHandle
---@field Combustible CombustibleRowHandle
---@field Consumable ConsumableRowHandle
---@field CraftingExperience integer
---@field Decayable DecayableRowHandle
---@field Deployable DeployableRowHandle
---@field Durable DurableRowHandle
---@field Equippable EquippableRowHandle
---@field Experience ExperienceRowHandle
---@field FLODData FLODDescriptionsRowHandle
---@field Farmable FarmableRowHandle
---@field Fillable FillableRowHandle
---@field FirearmData FirearmDataRowHandle
---@field Flammable FlammableRowHandle
---@field Floatable FloatableRowHandle
---@field Focusable FocusableRowHandle
---@field Generated_Tags GameplayTagContainer
---@field Generator GeneratorRowHandle
---@field Highlightable HighlightableRowHandle
---@field Hitable HitableRowHandle
---@field Interactable InteractableRowHandle
---@field Inventory InventoryRowHandle
---@field InventoryContainer InventoryContainerRowHandle
---@field Itemable ItemableRowHandle
---@field LivingItem LivingItemRowHandle
---@field Manual_Tags GameplayTagContainer
---@field Meshable MeshableRowHandle
---@field Processing ProcessingRowHandle
---@field RangedWeaponData RangedWeaponDataRowHandle
---@field Resource ResourceRowHandle
---@field Rocketable RocketableRowHandle
---@field Slotable SlotableRowHandle
---@field Thermal ThermalRowHandle
---@field ToolDamage ToolDamageRowHandle
---@field Transmutable TransmutableRowHandle
---@field TurretData TurretRowHandle
---@field Usable UsableRowHandle
---@field Weight WeightRowHandle

---@class ItemTemplateEnum : RowEnum

---@class ItemTemplateLibrary : RowLibrary
---@field AddRowToItemTemplateTable fun(self: ItemTemplateLibrary, Name: string, Data: ItemData|{}, NewRow: ItemTemplateRowHandle|{}, bOverrideExistingRow: boolean) Do not call from Lua: it needs 536 bytes and the call buffer holds 512.
---@field BreakItemTemplateEnum fun(self: ItemTemplateLibrary, Enum: ItemTemplateEnum|{}, Name: string, Index: integer)
---@field CastToItemTemplateRowHandle fun(self: ItemTemplateLibrary, RowHandle: RowHandle|{}, Paths: EValid): ItemTemplateRowHandle
---@field EqualEqual_EnumEnum fun(self: ItemTemplateLibrary, A: ItemTemplateEnum|{}, B: ItemTemplateEnum|{}): boolean
---@field EqualEqual_FItemTemplateRowHandleFItemTemplateRowHandle fun(self: ItemTemplateLibrary, RowHandleA: ItemTemplateRowHandle|{}, RowHandleB: ItemTemplateRowHandle|{}): boolean
---@field GetItemTemplateStruct fun(self: ItemTemplateLibrary, RowHandle: ItemTemplateRowHandle|{}, ItemTemplate: ItemData|{}, Paths: EValid) Do not call from Lua: it needs 528 bytes and the call buffer holds 512.
---@field IntToName fun(self: ItemTemplateLibrary, IntValue: integer): string
---@field IntToStruct fun(self: ItemTemplateLibrary, IntValue: integer): ItemTemplateEnum
---@field IsValidName fun(self: ItemTemplateLibrary, NameValue: string): boolean
---@field MakeItemTemplate fun(self: ItemTemplateLibrary, RowName: string): ItemTemplateRowHandle
---@field MakeItemTemplateEnum fun(self: ItemTemplateLibrary, Enum: ItemTemplateEnum|{}): ItemTemplateEnum
---@field MakeItemTemplateFromIndex fun(self: ItemTemplateLibrary, Index: integer): ItemTemplateRowHandle
---@field MakeLiteralItemTemplate fun(self: ItemTemplateLibrary, RowHandle: ItemTemplateRowHandle|{}): ItemTemplateRowHandle
---@field NameToInt fun(self: ItemTemplateLibrary, NameValue: string): integer
---@field NameToStruct fun(self: ItemTemplateLibrary, NameValue: string): ItemTemplateEnum
---@field NotEqual_EnumEnum fun(self: ItemTemplateLibrary, A: ItemTemplateEnum|{}, B: ItemTemplateEnum|{}): boolean
---@field NotEqual_EnumName fun(self: ItemTemplateLibrary, A: ItemTemplateEnum|{}, B: string): boolean
---@field NumRows fun(self: ItemTemplateLibrary): integer
---@field RefreshConstants fun(self: ItemTemplateLibrary)
---@field RemoveRowFromItemTemplateTable fun(self: ItemTemplateLibrary, Name: string)
---@field RowHandleToStruct fun(self: ItemTemplateLibrary, RowHandle: ItemTemplateRowHandle|{}): ItemTemplateEnum
---@field StructToInt fun(self: ItemTemplateLibrary, EnumValue: ItemTemplateEnum|{}): integer
---@field StructToName fun(self: ItemTemplateLibrary, EnumValue: ItemTemplateEnum|{}): string
---@field StructToRowHandle fun(self: ItemTemplateLibrary, EnumValue: ItemTemplateEnum|{}): ItemTemplateRowHandle

---@class ItemTemplateRowHandle : RowHandle

---@class ItemTemplateTable : IcarusDataTable

---@class ItemTooltipBase : UserWidget
---@field Inventory Inventory
---@field InventorySlot integer
---@field ItemData ItemData
---@field UpdateTooltip fun(self: ItemTooltipBase)

---@class ItemTraitMask : IcarusTableRowBase
---@field bActionable boolean
---@field bArmour boolean
---@field bBallistic boolean
---@field bBuildable boolean
---@field bCombustible boolean
---@field bConsumable boolean
---@field bDecayable boolean
---@field bDeployable boolean
---@field bDurable boolean
---@field bEquippable boolean
---@field bExperience boolean
---@field bFarmable boolean
---@field bFillable boolean
---@field bFlammable boolean
---@field bFloatable boolean
---@field bFocusable boolean
---@field bGenerator boolean
---@field bHighlightable boolean
---@field bHitable boolean
---@field bInteractable boolean
---@field bInventory boolean
---@field bInventoryContainer boolean
---@field bItemable boolean
---@field bLivingItem boolean
---@field bMeshable boolean
---@field bProcessing boolean
---@field bResource boolean
---@field bRocketable boolean
---@field bSlotable boolean
---@field bThermal boolean
---@field bTransmutable boolean
---@field bUsable boolean
---@field bWeight boolean

---@class ItemTraitMasksEnum : RowEnum

---@class ItemTraitMasksLibrary : RowLibrary
---@field AddRowToItemTraitMasksTable fun(self: ItemTraitMasksLibrary, Name: string, Data: ItemTraitMask|{}, NewRow: ItemTraitMasksRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakItemTraitMasksEnum fun(self: ItemTraitMasksLibrary, Enum: ItemTraitMasksEnum|{}, Name: string, Index: integer)
---@field CastToItemTraitMasksRowHandle fun(self: ItemTraitMasksLibrary, RowHandle: RowHandle|{}, Paths: EValid): ItemTraitMasksRowHandle
---@field EqualEqual_EnumEnum fun(self: ItemTraitMasksLibrary, A: ItemTraitMasksEnum|{}, B: ItemTraitMasksEnum|{}): boolean
---@field EqualEqual_FItemTraitMasksRowHandleFItemTraitMasksRowHandle fun(self: ItemTraitMasksLibrary, RowHandleA: ItemTraitMasksRowHandle|{}, RowHandleB: ItemTraitMasksRowHandle|{}): boolean
---@field GetItemTraitMasksStruct fun(self: ItemTraitMasksLibrary, RowHandle: ItemTraitMasksRowHandle|{}, ItemTraitMasks: ItemTraitMask|{}, Paths: EValid)
---@field IntToName fun(self: ItemTraitMasksLibrary, IntValue: integer): string
---@field IntToStruct fun(self: ItemTraitMasksLibrary, IntValue: integer): ItemTraitMasksEnum
---@field IsValidName fun(self: ItemTraitMasksLibrary, NameValue: string): boolean
---@field MakeItemTraitMasks fun(self: ItemTraitMasksLibrary, RowName: string): ItemTraitMasksRowHandle
---@field MakeItemTraitMasksEnum fun(self: ItemTraitMasksLibrary, Enum: ItemTraitMasksEnum|{}): ItemTraitMasksEnum
---@field MakeItemTraitMasksFromIndex fun(self: ItemTraitMasksLibrary, Index: integer): ItemTraitMasksRowHandle
---@field MakeLiteralItemTraitMasks fun(self: ItemTraitMasksLibrary, RowHandle: ItemTraitMasksRowHandle|{}): ItemTraitMasksRowHandle
---@field NameToInt fun(self: ItemTraitMasksLibrary, NameValue: string): integer
---@field NameToStruct fun(self: ItemTraitMasksLibrary, NameValue: string): ItemTraitMasksEnum
---@field NotEqual_EnumEnum fun(self: ItemTraitMasksLibrary, A: ItemTraitMasksEnum|{}, B: ItemTraitMasksEnum|{}): boolean
---@field NotEqual_EnumName fun(self: ItemTraitMasksLibrary, A: ItemTraitMasksEnum|{}, B: string): boolean
---@field NumRows fun(self: ItemTraitMasksLibrary): integer
---@field RefreshConstants fun(self: ItemTraitMasksLibrary)
---@field RemoveRowFromItemTraitMasksTable fun(self: ItemTraitMasksLibrary, Name: string)
---@field RowHandleToStruct fun(self: ItemTraitMasksLibrary, RowHandle: ItemTraitMasksRowHandle|{}): ItemTraitMasksEnum
---@field StructToInt fun(self: ItemTraitMasksLibrary, EnumValue: ItemTraitMasksEnum|{}): integer
---@field StructToName fun(self: ItemTraitMasksLibrary, EnumValue: ItemTraitMasksEnum|{}): string
---@field StructToRowHandle fun(self: ItemTraitMasksLibrary, EnumValue: ItemTraitMasksEnum|{}): ItemTraitMasksRowHandle

---@class ItemTraitMasksRowHandle : RowHandle

---@class ItemTraitMasksTable : IcarusDataTable

---@class ItemWeightStatQueries : IcarusTableRowBase
---@field ItemTagQuery TagQueriesRowHandle
---@field WeightStatToApply StatsEnum

---@class ItemWeightStatQueriesEnum : RowEnum

---@class ItemWeightStatQueriesLibrary : RowLibrary
---@field AddRowToItemWeightStatQueriesTable fun(self: ItemWeightStatQueriesLibrary, Name: string, Data: ItemWeightStatQueries|{}, NewRow: ItemWeightStatQueriesRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakItemWeightStatQueriesEnum fun(self: ItemWeightStatQueriesLibrary, Enum: ItemWeightStatQueriesEnum|{}, Name: string, Index: integer)
---@field CastToItemWeightStatQueriesRowHandle fun(self: ItemWeightStatQueriesLibrary, RowHandle: RowHandle|{}, Paths: EValid): ItemWeightStatQueriesRowHandle
---@field EqualEqual_EnumEnum fun(self: ItemWeightStatQueriesLibrary, A: ItemWeightStatQueriesEnum|{}, B: ItemWeightStatQueriesEnum|{}): boolean
---@field EqualEqual_FItemWeightStatQueriesRowHandleFItemWeightStatQueriesRowHandle fun(self: ItemWeightStatQueriesLibrary, RowHandleA: ItemWeightStatQueriesRowHandle|{}, RowHandleB: ItemWeightStatQueriesRowHandle|{}): boolean
---@field GetItemWeightStatQueriesStruct fun(self: ItemWeightStatQueriesLibrary, RowHandle: ItemWeightStatQueriesRowHandle|{}, ItemWeightStatQueries: ItemWeightStatQueries|{}, Paths: EValid)
---@field IntToName fun(self: ItemWeightStatQueriesLibrary, IntValue: integer): string
---@field IntToStruct fun(self: ItemWeightStatQueriesLibrary, IntValue: integer): ItemWeightStatQueriesEnum
---@field IsValidName fun(self: ItemWeightStatQueriesLibrary, NameValue: string): boolean
---@field MakeItemWeightStatQueries fun(self: ItemWeightStatQueriesLibrary, RowName: string): ItemWeightStatQueriesRowHandle
---@field MakeItemWeightStatQueriesEnum fun(self: ItemWeightStatQueriesLibrary, Enum: ItemWeightStatQueriesEnum|{}): ItemWeightStatQueriesEnum
---@field MakeItemWeightStatQueriesFromIndex fun(self: ItemWeightStatQueriesLibrary, Index: integer): ItemWeightStatQueriesRowHandle
---@field MakeLiteralItemWeightStatQueries fun(self: ItemWeightStatQueriesLibrary, RowHandle: ItemWeightStatQueriesRowHandle|{}): ItemWeightStatQueriesRowHandle
---@field NameToInt fun(self: ItemWeightStatQueriesLibrary, NameValue: string): integer
---@field NameToStruct fun(self: ItemWeightStatQueriesLibrary, NameValue: string): ItemWeightStatQueriesEnum
---@field NotEqual_EnumEnum fun(self: ItemWeightStatQueriesLibrary, A: ItemWeightStatQueriesEnum|{}, B: ItemWeightStatQueriesEnum|{}): boolean
---@field NotEqual_EnumName fun(self: ItemWeightStatQueriesLibrary, A: ItemWeightStatQueriesEnum|{}, B: string): boolean
---@field NumRows fun(self: ItemWeightStatQueriesLibrary): integer
---@field RefreshConstants fun(self: ItemWeightStatQueriesLibrary)
---@field RemoveRowFromItemWeightStatQueriesTable fun(self: ItemWeightStatQueriesLibrary, Name: string)
---@field RowHandleToStruct fun(self: ItemWeightStatQueriesLibrary, RowHandle: ItemWeightStatQueriesRowHandle|{}): ItemWeightStatQueriesEnum
---@field StructToInt fun(self: ItemWeightStatQueriesLibrary, EnumValue: ItemWeightStatQueriesEnum|{}): integer
---@field StructToName fun(self: ItemWeightStatQueriesLibrary, EnumValue: ItemWeightStatQueriesEnum|{}): string
---@field StructToRowHandle fun(self: ItemWeightStatQueriesLibrary, EnumValue: ItemWeightStatQueriesEnum|{}): ItemWeightStatQueriesRowHandle

---@class ItemWeightStatQueriesRowHandle : RowHandle

---@class ItemWeightStatQueriesTable : IcarusDataTable

---@class ItemableComponent : TraitComponent
---@field OnWorldPickup GameDelegate
---@field Stack integer
---@field GetItemableData fun(self: ItemableComponent, OutData: ItemableData|{}): boolean
---@field SetStack fun(self: ItemableComponent, NewStack: integer)

---@class ItemableData : IcarusTableRowBase
---@field Behaviour Class
---@field Description string
---@field DisplayName string
---@field FieldGuideKeywords string[]
---@field FlavorText string
---@field Icon Texture2D
---@field MaxStack integer
---@field Override_Glow_Icon Texture2D
---@field Weight integer
---@field bAllowZeroWeight boolean

---@class ItemableEnum : RowEnum

---@class ItemableLibrary : RowLibrary
---@field AddRowToItemableTable fun(self: ItemableLibrary, Name: string, Data: ItemableData|{}, NewRow: ItemableRowHandle|{}, bOverrideExistingRow: boolean)
---@field BreakItemableEnum fun(self: ItemableLibrary, Enum: ItemableEnum|{}, Name: string, Index: integer)
---@field CastToItemableRowHandle fun(self: ItemableLibrary, RowHandle: RowHandle|{}, Paths: EValid): ItemableRowHandle
---@field EqualEqual_EnumEnum fun(self: ItemableLibrary, A: ItemableEnum|{}, B: ItemableEnum|{}): boolean
---@field EqualEqual_FItemableRowHandleFItemableRowHandle fun(self: ItemableLibrary, RowHandleA: ItemableRowHandle|{}, RowHandleB: ItemableRowHandle|{}): boolean
---@field GetItemableStruct fun(self: ItemableLibrary, RowHandle: ItemableRowHandle|{}, Itemable: ItemableData|{}, Paths: EValid)
---@field IntToName fun(self: ItemableLibrary, IntValue: integer): string
---@field IntToStruct fun(self: ItemableLibrary, IntValue: integer): ItemableEnum
---@field IsValidName fun(self: ItemableLibrary, NameValue: string): boolean
---@field MakeItemable fun(self: ItemableLibrary, RowName: string): ItemableRowHandle
---@field MakeItemableEnum fun(self: ItemableLibrary, Enum: ItemableEnum|{}): ItemableEnum
---@field MakeItemableFromIndex fun(self: ItemableLibrary, Index: integer): ItemableRowHandle
---@field MakeLiteralItemable fun(self: ItemableLibrary, RowHandle: ItemableRowHandle|{}): ItemableRowHandle
---@field NameToInt fun(self: ItemableLibrary, NameValue: string): integer
---@field NameToStruct fun(self: ItemableLibrary, NameValue: string): ItemableEnum
---@field NotEqual_EnumEnum fun(self: ItemableLibrary, A: ItemableEnum|{}, B: ItemableEnum|{}): boolean
---@field NotEqual_EnumName fun(self: ItemableLibrary, A: ItemableEnum|{}, B: string): boolean
---@field NumRows fun(self: ItemableLibrary): integer
---@field RefreshConstants fun(self: ItemableLibrary)
---@field RemoveRowFromItemableTable fun(self: ItemableLibrary, Name: string)
---@field RowHandleToStruct fun(self: ItemableLibrary, RowHandle: ItemableRowHandle|{}): ItemableEnum
---@field StructToInt fun(self: ItemableLibrary, EnumValue: ItemableEnum|{}): integer
---@field StructToName fun(self: ItemableLibrary, EnumValue: ItemableEnum|{}): string
---@field StructToRowHandle fun(self: ItemableLibrary, EnumValue: ItemableEnum|{}): ItemableRowHandle

---@class ItemableRowHandle : RowHandle

---@class ItemableTable : IcarusDataTable

---@class ItemsStaticEnum : RowEnum

---@class ItemsStaticLibrary : RowLibrary
---@field AddRowToItemsStaticTable fun(self: ItemsStaticLibrary, Name: string, Data: ItemStaticData|{}, NewRow: ItemsStaticRowHandle|{}, bOverrideExistingRow: boolean) Do not call from Lua: it needs 1200 bytes and the call buffer holds 512.
---@field BreakItemsStaticEnum fun(self: ItemsStaticLibrary, Enum: ItemsStaticEnum|{}, Name: string, Index: integer)
---@field CastToItemsStaticRowHandle fun(self: ItemsStaticLibrary, RowHandle: RowHandle|{}, Paths: EValid): ItemsStaticRowHandle
---@field EqualEqual_EnumEnum fun(self: ItemsStaticLibrary, A: ItemsStaticEnum|{}, B: ItemsStaticEnum|{}): boolean
---@field EqualEqual_FItemsStaticRowHandleFItemsStaticRowHandle fun(self: ItemsStaticLibrary, RowHandleA: ItemsStaticRowHandle|{}, RowHandleB: ItemsStaticRowHandle|{}): boolean
---@field GetItemsStaticStruct fun(self: ItemsStaticLibrary, RowHandle: ItemsStaticRowHandle|{}, ItemsStatic: ItemStaticData|{}, Paths: EValid) Do not call from Lua: it needs 1192 bytes and the call buffer holds 512.
---@field IntToName fun(self: ItemsStaticLibrary, IntValue: integer): string
---@field IntToStruct fun(self: ItemsStaticLibrary, IntValue: integer): ItemsStaticEnum
---@field IsValidName fun(self: ItemsStaticLibrary, NameValue: string): boolean
---@field MakeItemsStatic fun(self: ItemsStaticLibrary, RowName: string): ItemsStaticRowHandle
---@field MakeItemsStaticEnum fun(self: ItemsStaticLibrary, Enum: ItemsStaticEnum|{}): ItemsStaticEnum
---@field MakeItemsStaticFromIndex fun(self: ItemsStaticLibrary, Index: integer): ItemsStaticRowHandle
---@field MakeLiteralItemsStatic fun(self: ItemsStaticLibrary, RowHandle: ItemsStaticRowHandle|{}): ItemsStaticRowHandle
---@field NameToInt fun(self: ItemsStaticLibrary, NameValue: string): integer
---@field NameToStruct fun(self: ItemsStaticLibrary, NameValue: string): ItemsStaticEnum
---@field NotEqual_EnumEnum fun(self: ItemsStaticLibrary, A: ItemsStaticEnum|{}, B: ItemsStaticEnum|{}): boolean
---@field NotEqual_EnumName fun(self: ItemsStaticLibrary, A: ItemsStaticEnum|{}, B: string): boolean
---@field NumRows fun(self: ItemsStaticLibrary): integer
---@field RefreshConstants fun(self: ItemsStaticLibrary)
---@field RemoveRowFromItemsStaticTable fun(self: ItemsStaticLibrary, Name: string)
---@field RowHandleToStruct fun(self: ItemsStaticLibrary, RowHandle: ItemsStaticRowHandle|{}): ItemsStaticEnum
---@field StructToInt fun(self: ItemsStaticLibrary, EnumValue: ItemsStaticEnum|{}): integer
---@field StructToName fun(self: ItemsStaticLibrary, EnumValue: ItemsStaticEnum|{}): string
---@field StructToRowHandle fun(self: ItemsStaticLibrary, EnumValue: ItemsStaticEnum|{}): ItemsStaticRowHandle

---@class ItemsStaticRowHandle : RowHandle

---@class ItemsStaticTable : IcarusDataTable
