---@meta _
-- Generated by scripts\gameindex.py from the index of the game's classes. Changes here are lost on the next run.

---@alias EDesiredImageFormat
---| 0 # PNG
---| 1 # JPG
---| 2 # BMP
---| 3 # EXR
---| integer

---@class ImageWriteBlueprintLibrary : BlueprintFunctionLibrary
---@field ExportToDisk fun(self: ImageWriteBlueprintLibrary, Texture: Texture?, Filename: string, Options: ImageWriteOptions|{})

---@class ImageWriteOptions
---@field CompressionQuality integer
---@field Format EDesiredImageFormat
---@field OnComplete GameDelegate
---@field bAsync boolean
---@field bOverwriteFile boolean
