---@meta _
-- Generated by scripts\gameindex.py from the game's object dump. Changes here are lost on the next run.

---@class LiveLinkAnimationFrameData : LiveLinkBaseFrameData
---@field Transforms Transform[]

---@class LiveLinkBaseBlueprintData

---@class LiveLinkBaseFrameData
---@field MetaData LiveLinkMetaData
---@field PropertyValues number[]
---@field WorldTime LiveLinkWorldTime

---@class LiveLinkBaseStaticData
---@field PropertyNames string[]

---@class LiveLinkBasicBlueprintData : LiveLinkBaseBlueprintData
---@field FrameData LiveLinkBaseFrameData
---@field StaticData LiveLinkBaseStaticData

---@class LiveLinkMetaData
---@field SceneTime QualifiedFrameTime
---@field StringMetadata table<string, string>

---@class LiveLinkRole : Object

---@class LiveLinkSkeletonStaticData : LiveLinkBaseStaticData
---@field BoneNames string[]
---@field BoneParents integer[]

---@class LiveLinkSourceHandle

---@class LiveLinkSubjectKey
---@field Source Guid
---@field SubjectName LiveLinkSubjectName

---@class LiveLinkSubjectName
---@field Name string

---@class LiveLinkSubjectRepresentation
---@field Role Class
---@field Subject LiveLinkSubjectName

---@class LiveLinkTransform

---@class LiveLinkWorldTime
---@field Offset number
---@field Time number

---@class SubjectFrameHandle : LiveLinkBaseBlueprintData

---@class SubjectMetadata
---@field SceneFramerate FrameRate
---@field SceneTimecode Timecode
---@field StringMetadata table<string, string>
