---@meta _
-- Generated by scripts\gameindex.py from the game's object dump. Changes here are lost on the next run.

---@class NiagaraCompileHash
---@field DataHash integer[]

---@class NiagaraDataInterfaceBase : NiagaraMergeable

---@class NiagaraMergeable : Object
