---@meta _
-- Generated by scripts\gameindex.py from the game's object dump. Changes here are lost on the next run.

---@alias ENCPoolMethod
---| 0 # None
---| 1 # AutoRelease
---| 2 # ManualRelease
---| 3 # ManualRelease_OnComplete
---| 4 # FreeInPool
---| integer

---@alias ENiagaraAgeUpdateMode
---| 0 # TickDeltaTime
---| 1 # DesiredAge
---| 2 # DesiredAgeNoSeek
---| integer

---@alias ENiagaraCullReaction
---| 0 # Deactivate
---| 1 # DeactivateImmediate
---| 2 # DeactivateResume
---| 3 # DeactivateImmediateResume
---| integer

---@alias ENiagaraDataSetType
---| 0 # ParticleData
---| 1 # Shared
---| 2 # Event
---| integer

---@alias ENiagaraRendererMotionVectorSetting
---| 0 # AutoDetect
---| 1 # Precise
---| 2 # Approximate
---| 3 # Disable
---| integer

---@alias ENiagaraScalabilityUpdateFrequency
---| 0 # SpawnOnly
---| 1 # Low
---| 2 # Medium
---| 3 # High
---| 4 # Continuous
---| integer

---@alias ENiagaraScriptCompileStatus
---| 0 # NCS_Unknown
---| 1 # NCS_Dirty
---| 2 # NCS_Error
---| 3 # NCS_UpToDate
---| 4 # NCS_BeingCreated
---| 5 # NCS_UpToDateWithWarnings
---| 6 # NCS_ComputeUpToDateWithWarnings
---| integer

---@alias ENiagaraScriptUsage
---| 0 # Function
---| 1 # Module
---| 2 # DynamicInput
---| 3 # ParticleSpawnScript
---| 4 # ParticleSpawnScriptInterpolated
---| 5 # ParticleUpdateScript
---| 6 # ParticleEventScript
---| 7 # ParticleSimulationStageScript
---| 8 # ParticleGPUComputeScript
---| 9 # EmitterSpawnScript
---| 10 # EmitterUpdateScript
---| 11 # SystemSpawnScript
---| 12 # SystemUpdateScript
---| integer

---@alias ENiagaraSimTarget
---| 0 # CPUSim
---| 1 # GPUComputeSim
---| integer

---@alias ENiagaraTickBehavior
---| 0 # UsePrereqs
---| 1 # UseComponentTickGroup
---| 2 # ForceTickFirst
---| 3 # ForceTickLast
---| integer

---@alias EParticleAllocationMode
---| 0 # AutomaticEstimate
---| 1 # ManualEstimate
---| integer

---@alias EScriptExecutionMode
---| 0 # EveryParticle
---| 1 # SpawnedParticles
---| 2 # SingleParticle
---| integer

---@class NiagaraBaselineController : Object
---@field EffectType NiagaraEffectType
---@field Owner NiagaraPerfBaselineActor
---@field System NiagaraSystem
---@field TestDuration number
---@field GetSystem fun(self: NiagaraBaselineController): NiagaraSystem
---@field OnBeginTest fun(self: NiagaraBaselineController)
---@field OnEndTest fun(self: NiagaraBaselineController, Stats: NiagaraPerfBaselineStats|{})
---@field OnOwnerTick fun(self: NiagaraBaselineController, DeltaTime: number)
---@field OnTickTest fun(self: NiagaraBaselineController): boolean

---@class NiagaraBoundParameter
---@field DestOffset integer
---@field Parameter NiagaraVariable
---@field SrcOffset integer

---@class NiagaraCompilerTag
---@field StringValue string
---@field Variable NiagaraVariable

---@class NiagaraComponent : FXSystemComponent
---@field Asset NiagaraSystem
---@field AutoAttachLocationRule EAttachmentRule
---@field AutoAttachParent SceneComponent
---@field AutoAttachRotationRule EAttachmentRule
---@field AutoAttachScaleRule EAttachmentRule
---@field AutoAttachSocketName string
---@field EmitterMaterials NiagaraMaterialOverride[]
---@field MaxTimeBeforeForceUpdateTransform number
---@field OnSystemFinished GameDelegate
---@field OverrideParameters NiagaraUserRedirectionParameterStore
---@field RandomSeedOffset integer
---@field TickBehavior ENiagaraTickBehavior
---@field bAutoAttachWeldSimulatedBodies boolean
---@field bAutoDestroy boolean
---@field bAutoManageAttachment boolean
---@field bEnableGpuComputeDebug boolean
---@field bForceSolo boolean
---@field bRenderingEnabled boolean
---@field AdvanceSimulation fun(self: NiagaraComponent, TickCount: integer, TickDeltaSeconds: number)
---@field AdvanceSimulationByTime fun(self: NiagaraComponent, SimulateTime: number, TickDeltaSeconds: number)
---@field GetAgeUpdateMode fun(self: NiagaraComponent): ENiagaraAgeUpdateMode
---@field GetAsset fun(self: NiagaraComponent): NiagaraSystem
---@field GetDataInterface fun(self: NiagaraComponent, Name: string): NiagaraDataInterface
---@field GetDesiredAge fun(self: NiagaraComponent): number
---@field GetForceSolo fun(self: NiagaraComponent): boolean
---@field GetLockDesiredAgeDeltaTimeToSeekDelta fun(self: NiagaraComponent): boolean
---@field GetMaxSimTime fun(self: NiagaraComponent): number
---@field GetNiagaraParticlePositions_DebugOnly fun(self: NiagaraComponent, InEmitterName: string): Vector[]
---@field GetNiagaraParticleValueVec3_DebugOnly fun(self: NiagaraComponent, InEmitterName: string, InValueName: string): Vector[]
---@field GetNiagaraParticleValues_DebugOnly fun(self: NiagaraComponent, InEmitterName: string, InValueName: string): number[]
---@field GetPreviewLODDistance fun(self: NiagaraComponent): number
---@field GetPreviewLODDistanceEnabled fun(self: NiagaraComponent): boolean
---@field GetRandomSeedOffset fun(self: NiagaraComponent): integer
---@field GetSeekDelta fun(self: NiagaraComponent): number
---@field GetTickBehavior fun(self: NiagaraComponent): ENiagaraTickBehavior
---@field InitForPerformanceBaseline fun(self: NiagaraComponent)
---@field IsPaused fun(self: NiagaraComponent): boolean
---@field ReinitializeSystem fun(self: NiagaraComponent)
---@field ResetSystem fun(self: NiagaraComponent)
---@field SeekToDesiredAge fun(self: NiagaraComponent, InDesiredAge: number)
---@field SetAgeUpdateMode fun(self: NiagaraComponent, InAgeUpdateMode: ENiagaraAgeUpdateMode)
---@field SetAllowScalability fun(self: NiagaraComponent, bAllow: boolean)
---@field SetAsset fun(self: NiagaraComponent, InAsset: NiagaraSystem?, bResetExistingOverrideParameters: boolean)
---@field SetAutoDestroy fun(self: NiagaraComponent, bInAutoDestroy: boolean)
---@field SetCanRenderWhileSeeking fun(self: NiagaraComponent, bInCanRenderWhileSeeking: boolean)
---@field SetDesiredAge fun(self: NiagaraComponent, InDesiredAge: number)
---@field SetForceSolo fun(self: NiagaraComponent, bInForceSolo: boolean)
---@field SetGpuComputeDebug fun(self: NiagaraComponent, bEnableDebug: boolean)
---@field SetLockDesiredAgeDeltaTimeToSeekDelta fun(self: NiagaraComponent, bLock: boolean)
---@field SetMaxSimTime fun(self: NiagaraComponent, InMaxTime: number)
---@field SetNiagaraVariableActor fun(self: NiagaraComponent, InVariableName: string, Actor: Actor?)
---@field SetNiagaraVariableBool fun(self: NiagaraComponent, InVariableName: string, InValue: boolean)
---@field SetNiagaraVariableFloat fun(self: NiagaraComponent, InVariableName: string, InValue: number)
---@field SetNiagaraVariableInt fun(self: NiagaraComponent, InVariableName: string, InValue: integer)
---@field SetNiagaraVariableLinearColor fun(self: NiagaraComponent, InVariableName: string, InValue: LinearColor|{})
---@field SetNiagaraVariableObject fun(self: NiagaraComponent, InVariableName: string, Object: Object?)
---@field SetNiagaraVariableQuat fun(self: NiagaraComponent, InVariableName: string, InValue: Quat|{})
---@field SetNiagaraVariableVec2 fun(self: NiagaraComponent, InVariableName: string, InValue: Vector2D|{})
---@field SetNiagaraVariableVec3 fun(self: NiagaraComponent, InVariableName: string, InValue: Vector|{})
---@field SetNiagaraVariableVec4 fun(self: NiagaraComponent, InVariableName: string, InValue: Vector4|{})
---@field SetPaused fun(self: NiagaraComponent, bInPaused: boolean)
---@field SetPreviewLODDistance fun(self: NiagaraComponent, bEnablePreviewLODDistance: boolean, PreviewLODDistance: number)
---@field SetRandomSeedOffset fun(self: NiagaraComponent, NewRandomSeedOffset: integer)
---@field SetRenderingEnabled fun(self: NiagaraComponent, bInRenderingEnabled: boolean)
---@field SetSeekDelta fun(self: NiagaraComponent, InSeekDelta: number)
---@field SetTickBehavior fun(self: NiagaraComponent, NewTickBehavior: ENiagaraTickBehavior)
---@field SetVariableActor fun(self: NiagaraComponent, InVariableName: string, Actor: Actor?)
---@field SetVariableBool fun(self: NiagaraComponent, InVariableName: string, InValue: boolean)
---@field SetVariableFloat fun(self: NiagaraComponent, InVariableName: string, InValue: number)
---@field SetVariableInt fun(self: NiagaraComponent, InVariableName: string, InValue: integer)
---@field SetVariableLinearColor fun(self: NiagaraComponent, InVariableName: string, InValue: LinearColor|{})
---@field SetVariableMaterial fun(self: NiagaraComponent, InVariableName: string, Object: MaterialInterface?)
---@field SetVariableObject fun(self: NiagaraComponent, InVariableName: string, Object: Object?)
---@field SetVariableQuat fun(self: NiagaraComponent, InVariableName: string, InValue: Quat|{})
---@field SetVariableTextureRenderTarget fun(self: NiagaraComponent, InVariableName: string, TextureRenderTarget: TextureRenderTarget?)
---@field SetVariableVec2 fun(self: NiagaraComponent, InVariableName: string, InValue: Vector2D|{})
---@field SetVariableVec3 fun(self: NiagaraComponent, InVariableName: string, InValue: Vector|{})
---@field SetVariableVec4 fun(self: NiagaraComponent, InVariableName: string, InValue: Vector4|{})

---@class NiagaraDataInterface : NiagaraDataInterfaceBase

---@class NiagaraDataInterfaceArrayFunctionLibrary : BlueprintFunctionLibrary
---@field GetNiagaraArrayBool fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string): boolean[]
---@field GetNiagaraArrayBoolValue fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, Index: integer): boolean
---@field GetNiagaraArrayColor fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string): LinearColor[]
---@field GetNiagaraArrayColorValue fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, Index: integer): LinearColor
---@field GetNiagaraArrayFloat fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string): number[]
---@field GetNiagaraArrayFloatValue fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, Index: integer): number
---@field GetNiagaraArrayInt32 fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string): integer[]
---@field GetNiagaraArrayInt32Value fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, Index: integer): integer
---@field GetNiagaraArrayQuat fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string): Quat[]
---@field GetNiagaraArrayQuatValue fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, Index: integer): Quat
---@field GetNiagaraArrayVector fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string): Vector[]
---@field GetNiagaraArrayVector2D fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string): Vector2D[]
---@field GetNiagaraArrayVector2DValue fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, Index: integer): Vector2D
---@field GetNiagaraArrayVector4 fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string): Vector4[]
---@field GetNiagaraArrayVector4Value fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, Index: integer): Vector4
---@field GetNiagaraArrayVectorValue fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, Index: integer): Vector
---@field SetNiagaraArrayBool fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, ArrayData: boolean[])
---@field SetNiagaraArrayBoolValue fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, Index: integer, Value: boolean, bSizeToFit: boolean)
---@field SetNiagaraArrayColor fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, ArrayData: LinearColor[])
---@field SetNiagaraArrayColorValue fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, Index: integer, Value: LinearColor|{}, bSizeToFit: boolean)
---@field SetNiagaraArrayFloat fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, ArrayData: number[])
---@field SetNiagaraArrayFloatValue fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, Index: integer, Value: number, bSizeToFit: boolean)
---@field SetNiagaraArrayInt32 fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, ArrayData: integer[])
---@field SetNiagaraArrayInt32Value fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, Index: integer, Value: integer, bSizeToFit: boolean)
---@field SetNiagaraArrayQuat fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, ArrayData: Quat[])
---@field SetNiagaraArrayQuatValue fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, Index: integer, Value: Quat|{}, bSizeToFit: boolean)
---@field SetNiagaraArrayVector fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, ArrayData: Vector[])
---@field SetNiagaraArrayVector2D fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, ArrayData: Vector2D[])
---@field SetNiagaraArrayVector2DValue fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, Index: integer, Value: Vector2D|{}, bSizeToFit: boolean)
---@field SetNiagaraArrayVector4 fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, ArrayData: Vector4[])
---@field SetNiagaraArrayVector4Value fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, Index: integer, Value: Vector4|{}, bSizeToFit: boolean)
---@field SetNiagaraArrayVectorValue fun(self: NiagaraDataInterfaceArrayFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, Index: integer, Value: Vector|{}, bSizeToFit: boolean)

---@class NiagaraDataSetCompiledData
---@field ID NiagaraDataSetID
---@field SimTarget ENiagaraSimTarget
---@field TotalFloatComponents integer
---@field TotalHalfComponents integer
---@field TotalInt32Components integer
---@field VariableLayouts NiagaraVariableLayoutInfo[]
---@field Variables NiagaraVariable[]
---@field bRequiresPersistentIDs boolean

---@class NiagaraDataSetID
---@field Name string
---@field Type ENiagaraDataSetType

---@class NiagaraDataSetProperties
---@field ID NiagaraDataSetID
---@field Variables NiagaraVariable[]

---@class NiagaraDetailsLevelScaleOverrides
---@field Cine number
---@field Epic number
---@field High number
---@field Low number
---@field Medium number

---@class NiagaraDeviceProfileStateEntry
---@field ProfileName string
---@field QualityLevelMask integer
---@field SetQualityLevelMask integer

---@class NiagaraEffectType : Object
---@field CullReaction ENiagaraCullReaction
---@field DetailLevelScalabilitySettings NiagaraSystemScalabilitySettings[]
---@field EmitterScalabilitySettings NiagaraEmitterScalabilitySettingsArray
---@field PerfBaselineStats NiagaraPerfBaselineStats
---@field PerfBaselineVersion Guid
---@field PerformanceBaselineController NiagaraBaselineController
---@field SignificanceHandler NiagaraSignificanceHandler
---@field SystemScalabilitySettings NiagaraSystemScalabilitySettingsArray
---@field UpdateFrequency ENiagaraScalabilityUpdateFrequency

---@class NiagaraEmitter : Object
---@field AllocationMode EParticleAllocationMode
---@field DefaultShaderStageIndex integer
---@field EventHandlerScriptProps NiagaraEventScriptProperties[]
---@field FixedBounds Box
---@field GPUComputeScript NiagaraScript
---@field GlobalSpawnCountScaleOverrides NiagaraDetailsLevelScaleOverrides
---@field MaxDeltaTimePerTick number
---@field MaxDetailLevel integer
---@field MaxUpdateIterations integer
---@field MinDetailLevel integer
---@field Platforms NiagaraPlatformSet
---@field PreAllocationCount integer
---@field RandomSeed integer
---@field RendererProperties NiagaraRendererProperties[]
---@field ScalabilityOverrides NiagaraEmitterScalabilityOverrides
---@field SharedEventGeneratorIds string[]
---@field SimTarget ENiagaraSimTarget
---@field SimulationStages NiagaraSimulationStageBase[]
---@field SpawnScriptProps NiagaraEmitterScriptProperties
---@field SpawnStages integer[]
---@field UniqueEmitterName string
---@field UpdateScriptProps NiagaraEmitterScriptProperties
---@field bCombineEventSpawn boolean
---@field bDeprecatedShaderStagesEnabled boolean
---@field bDeterminism boolean
---@field bFixedBounds boolean
---@field bInterpolatedSpawning boolean
---@field bLimitDeltaTime boolean
---@field bLocalSpace boolean
---@field bOverrideGlobalSpawnCountScale boolean
---@field bRequiresPersistentIDs boolean
---@field bSimulationStagesEnabled boolean
---@field bUseMaxDetailLevel boolean
---@field bUseMinDetailLevel boolean

---@class NiagaraEmitterHandle
---@field ID Guid
---@field IdName string
---@field Instance NiagaraEmitter
---@field Name string
---@field bIsEnabled boolean

---@class NiagaraEmitterScalabilityOverride : NiagaraEmitterScalabilitySettings
---@field bOverrideSpawnCountScale boolean

---@class NiagaraEmitterScalabilityOverrides
---@field Overrides NiagaraEmitterScalabilityOverride[]

---@class NiagaraEmitterScalabilitySettings
---@field Platforms NiagaraPlatformSet
---@field SpawnCountScale number
---@field bScaleSpawnCount boolean

---@class NiagaraEmitterScalabilitySettingsArray
---@field Settings NiagaraEmitterScalabilitySettings[]

---@class NiagaraEmitterScriptProperties
---@field EventGenerators NiagaraEventGeneratorProperties[]
---@field EventReceivers NiagaraEventReceiverProperties[]
---@field Script NiagaraScript

---@class NiagaraEventGeneratorProperties
---@field DataSetCompiledData NiagaraDataSetCompiledData
---@field ID string
---@field MaxEventsPerFrame integer

---@class NiagaraEventReceiverProperties
---@field Name string
---@field SourceEmitter string
---@field SourceEventGenerator string

---@class NiagaraEventScriptProperties : NiagaraEmitterScriptProperties
---@field ExecutionMode EScriptExecutionMode
---@field MaxEventsPerFrame integer
---@field MinSpawnNumber integer
---@field SourceEmitterID Guid
---@field SourceEventName string
---@field SpawnNumber integer
---@field bRandomSpawnNumber boolean

---@class NiagaraFunctionLibrary : BlueprintFunctionLibrary
---@field GetNiagaraParameterCollection fun(self: NiagaraFunctionLibrary, WorldContextObject: Object?, Collection: NiagaraParameterCollection?): NiagaraParameterCollectionInstance
---@field OverrideSystemUserVariableSkeletalMeshComponent fun(self: NiagaraFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, SkeletalMeshComponent: SkeletalMeshComponent?)
---@field OverrideSystemUserVariableStaticMesh fun(self: NiagaraFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, StaticMesh: StaticMesh?)
---@field OverrideSystemUserVariableStaticMeshComponent fun(self: NiagaraFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, StaticMeshComponent: StaticMeshComponent?)
---@field SetSkeletalMeshDataInterfaceSamplingRegions fun(self: NiagaraFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, SamplingRegions: string[])
---@field SetTexture2DArrayObject fun(self: NiagaraFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, Texture: Texture2DArray?)
---@field SetTextureObject fun(self: NiagaraFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, Texture: Texture?)
---@field SetVolumeTextureObject fun(self: NiagaraFunctionLibrary, NiagaraSystem: NiagaraComponent?, OverrideName: string, Texture: VolumeTexture?)
---@field SpawnSystemAtLocation fun(self: NiagaraFunctionLibrary, WorldContextObject: Object?, SystemTemplate: NiagaraSystem?, Location: Vector|{}, Rotation: Rotator|{}, Scale: Vector|{}, bAutoDestroy: boolean, bAutoActivate: boolean, PoolingMethod: ENCPoolMethod, bPreCullCheck: boolean): NiagaraComponent
---@field SpawnSystemAttached fun(self: NiagaraFunctionLibrary, SystemTemplate: NiagaraSystem?, AttachToComponent: SceneComponent?, AttachPointName: string, Location: Vector|{}, Rotation: Rotator|{}, LocationType: EAttachLocation, bAutoDestroy: boolean, bAutoActivate: boolean, PoolingMethod: ENCPoolMethod, bPreCullCheck: boolean): NiagaraComponent

---@class NiagaraMaterialOverride
---@field EmitterRendererProperty NiagaraRendererProperties
---@field Material MaterialInterface
---@field MaterialSubIndex integer

---@class NiagaraParameterCollection : Object
---@field CompileId Guid
---@field DefaultInstance NiagaraParameterCollectionInstance
---@field Namespace string
---@field Parameters NiagaraVariable[]
---@field SourceMaterialCollection MaterialParameterCollection

---@class NiagaraParameterCollectionInstance : Object
---@field Collection NiagaraParameterCollection
---@field OverridenParameters NiagaraVariable[]
---@field ParameterStorage NiagaraParameterStore
---@field GetBoolParameter fun(self: NiagaraParameterCollectionInstance, InVariableName: string): boolean
---@field GetColorParameter fun(self: NiagaraParameterCollectionInstance, InVariableName: string): LinearColor
---@field GetFloatParameter fun(self: NiagaraParameterCollectionInstance, InVariableName: string): number
---@field GetIntParameter fun(self: NiagaraParameterCollectionInstance, InVariableName: string): integer
---@field GetQuatParameter fun(self: NiagaraParameterCollectionInstance, InVariableName: string): Quat
---@field GetVector2DParameter fun(self: NiagaraParameterCollectionInstance, InVariableName: string): Vector2D
---@field GetVector4Parameter fun(self: NiagaraParameterCollectionInstance, InVariableName: string): Vector4
---@field GetVectorParameter fun(self: NiagaraParameterCollectionInstance, InVariableName: string): Vector
---@field SetBoolParameter fun(self: NiagaraParameterCollectionInstance, InVariableName: string, InValue: boolean)
---@field SetColorParameter fun(self: NiagaraParameterCollectionInstance, InVariableName: string, InValue: LinearColor|{})
---@field SetFloatParameter fun(self: NiagaraParameterCollectionInstance, InVariableName: string, InValue: number)
---@field SetIntParameter fun(self: NiagaraParameterCollectionInstance, InVariableName: string, InValue: integer)
---@field SetQuatParameter fun(self: NiagaraParameterCollectionInstance, InVariableName: string, InValue: Quat|{})
---@field SetVector2DParameter fun(self: NiagaraParameterCollectionInstance, InVariableName: string, InValue: Vector2D|{})
---@field SetVector4Parameter fun(self: NiagaraParameterCollectionInstance, InVariableName: string, InValue: Vector4|{})
---@field SetVectorParameter fun(self: NiagaraParameterCollectionInstance, InVariableName: string, InValue: Vector|{})

---@class NiagaraParameterDataSetBinding
---@field DataSetComponentOffset integer
---@field ParameterOffset integer

---@class NiagaraParameterDataSetBindingCollection
---@field FloatOffsets NiagaraParameterDataSetBinding[]
---@field Int32Offsets NiagaraParameterDataSetBinding[]

---@class NiagaraParameterStore
---@field DataInterfaces NiagaraDataInterface[]
---@field Owner Object
---@field ParameterData integer[]
---@field SortedParameterOffsets NiagaraVariableWithOffset[]
---@field UObjects Object[]

---@class NiagaraPerfBaselineActor : Actor
---@field Controller NiagaraBaselineController
---@field Label TextRenderComponent

---@class NiagaraPerfBaselineStats
---@field PerInstanceAvg_GT number
---@field PerInstanceAvg_RT number
---@field PerInstanceMax_GT number
---@field PerInstanceMax_RT number

---@class NiagaraPlatformSet
---@field CVarConditions NiagaraPlatformSetCVarCondition[]
---@field DeviceProfileStates NiagaraDeviceProfileStateEntry[]
---@field QualityLevelMask integer

---@class NiagaraPlatformSetCVarCondition
---@field CVarName string
---@field MaxFloat number
---@field MaxInt integer
---@field MinFloat number
---@field MinInt integer
---@field Value boolean
---@field bUseMaxFloat boolean
---@field bUseMaxInt boolean
---@field bUseMinFloat boolean
---@field bUseMinInt boolean

---@class NiagaraRendererProperties : NiagaraMergeable
---@field MotionVectorSetting ENiagaraRendererMotionVectorSetting
---@field Platforms NiagaraPlatformSet
---@field SortOrderHint integer
---@field bIsEnabled boolean
---@field bMotionBlurEnabled boolean

---@class NiagaraScript : NiagaraScriptBase
---@field CachedDefaultDataInterfaces NiagaraScriptDataInterfaceInfo[]
---@field CachedParameterCollectionReferences NiagaraParameterCollection[]
---@field CachedScriptVM NiagaraVMExecutableData
---@field CachedScriptVMId NiagaraVMExecutableDataId
---@field RapidIterationParameters NiagaraParameterStore
---@field ScriptExecutionBoundParameters NiagaraBoundParameter[]
---@field ScriptExecutionParamStore NiagaraScriptExecutionParameterStore
---@field Usage ENiagaraScriptUsage
---@field UsageId Guid
---@field RaiseOnGPUCompilationComplete fun(self: NiagaraScript)

---@class NiagaraScriptDataInterfaceCompileInfo
---@field Name string
---@field RegisteredParameterMapRead string
---@field RegisteredParameterMapWrite string
---@field Type NiagaraTypeDefinition
---@field UserPtrIdx integer
---@field bIsPlaceholder boolean

---@class NiagaraScriptDataInterfaceInfo
---@field DataInterface NiagaraDataInterface
---@field Name string
---@field RegisteredParameterMapRead string
---@field RegisteredParameterMapWrite string
---@field Type NiagaraTypeDefinition
---@field UserPtrIdx integer

---@class NiagaraScriptDataUsageInfo
---@field bReadsAttributeData boolean

---@class NiagaraScriptExecutionPaddingInfo
---@field DestOffset integer
---@field DestSize integer
---@field SrcOffset integer
---@field SrcSize integer

---@class NiagaraScriptExecutionParameterStore : NiagaraParameterStore
---@field PaddedParameterSize integer
---@field PaddingInfo NiagaraScriptExecutionPaddingInfo[]
---@field ParameterSize integer
---@field bInitialized boolean

---@class NiagaraSignificanceHandler : Object

---@class NiagaraSimulationStageBase : NiagaraMergeable
---@field Script NiagaraScript
---@field SimulationStageName string
---@field bEnabled boolean

---@class NiagaraStatScope
---@field FriendlyName string
---@field FullName string

---@class NiagaraSystem : FXSystemAsset
---@field EffectType NiagaraEffectType
---@field EmitterHandles NiagaraEmitterHandle[]
---@field ExposedParameters NiagaraUserRedirectionParameterStore
---@field FixedBounds Box
---@field ParameterCollectionOverrides NiagaraParameterCollectionInstance[]
---@field ScalabilityOverrides NiagaraSystemScalabilityOverride[]
---@field SystemCompiledData NiagaraSystemCompiledData
---@field SystemScalabilityOverrides NiagaraSystemScalabilityOverrides
---@field SystemSpawnScript NiagaraScript
---@field SystemUpdateScript NiagaraScript
---@field UserDINamesReadInSystemScripts string[]
---@field WarmupTickCount integer
---@field WarmupTickDelta number
---@field WarmupTime number
---@field bAutoDeactivate boolean
---@field bDumpDebugEmitterInfo boolean
---@field bDumpDebugSystemInfo boolean
---@field bFixedBounds boolean
---@field bHasSystemScriptDIsWithPerInstanceData boolean
---@field bNeedsGPUContextInitForDataInterfaces boolean
---@field bOverrideScalabilitySettings boolean
---@field bRequireCurrentFrameData boolean

---@class NiagaraSystemCompiledData
---@field DataSetCompiledData NiagaraDataSetCompiledData
---@field InstanceParamStore NiagaraParameterStore
---@field SpawnInstanceEmitterBindings NiagaraParameterDataSetBindingCollection[]
---@field SpawnInstanceGlobalBinding NiagaraParameterDataSetBindingCollection
---@field SpawnInstanceOwnerBinding NiagaraParameterDataSetBindingCollection
---@field SpawnInstanceParamsDataSetCompiledData NiagaraDataSetCompiledData
---@field SpawnInstanceSystemBinding NiagaraParameterDataSetBindingCollection
---@field UpdateInstanceEmitterBindings NiagaraParameterDataSetBindingCollection[]
---@field UpdateInstanceGlobalBinding NiagaraParameterDataSetBindingCollection
---@field UpdateInstanceOwnerBinding NiagaraParameterDataSetBindingCollection
---@field UpdateInstanceParamsDataSetCompiledData NiagaraDataSetCompiledData
---@field UpdateInstanceSystemBinding NiagaraParameterDataSetBindingCollection

---@class NiagaraSystemScalabilityOverride : NiagaraSystemScalabilitySettings
---@field bOverrideDistanceSettings boolean
---@field bOverrideGlobalBudgetCullingSettings boolean
---@field bOverrideInstanceCountSettings boolean
---@field bOverridePerSystemInstanceCountSettings boolean
---@field bOverrideTimeSinceRendererSettings boolean

---@class NiagaraSystemScalabilityOverrides
---@field Overrides NiagaraSystemScalabilityOverride[]

---@class NiagaraSystemScalabilitySettings
---@field MaxDistance number
---@field MaxGlobalBudgetUsage number
---@field MaxInstances integer
---@field MaxSystemInstances integer
---@field MaxTimeWithoutRender number
---@field Platforms NiagaraPlatformSet
---@field bCullByDistance boolean
---@field bCullByGlobalBudget boolean
---@field bCullByMaxTimeWithoutRender boolean
---@field bCullMaxInstanceCount boolean
---@field bCullPerSystemMaxInstanceCount boolean

---@class NiagaraSystemScalabilitySettingsArray
---@field Settings NiagaraSystemScalabilitySettings[]

---@class NiagaraTypeDefinition
---@field ClassStructOrEnum Object
---@field UnderlyingType integer

---@class NiagaraTypeDefinitionHandle
---@field RegisteredTypeIndex integer

---@class NiagaraTypeLayoutInfo
---@field FloatComponentByteOffsets integer[]
---@field FloatComponentRegisterOffsets integer[]
---@field HalfComponentByteOffsets integer[]
---@field HalfComponentRegisterOffsets integer[]
---@field Int32ComponentByteOffsets integer[]
---@field Int32ComponentRegisterOffsets integer[]

---@class NiagaraUserRedirectionParameterStore : NiagaraParameterStore
---@field UserParameterRedirects table<NiagaraVariable, NiagaraVariable>

---@class NiagaraVMExecutableData
---@field Attributes NiagaraVariable[]
---@field ByteCode integer[]
---@field CalledVMExternalFunctions VMExternalFunctionBindingInfo[]
---@field CompileTags NiagaraCompilerTag[]
---@field DIParamInfo NiagaraDataInterfaceGPUParamInfo[]
---@field DataInterfaceInfo NiagaraScriptDataInterfaceCompileInfo[]
---@field DataUsage NiagaraScriptDataUsageInfo
---@field LastCompileStatus ENiagaraScriptCompileStatus
---@field NumTempRegisters integer
---@field NumUserPtrs integer
---@field OptimizedByteCode integer[]
---@field ReadDataSets NiagaraDataSetID[]
---@field ScriptLiterals integer[]
---@field SimulationStageMetaData SimulationStageMetaData[]
---@field StatScopes NiagaraStatScope[]
---@field WriteDataSets NiagaraDataSetProperties[]
---@field bNeedsGPUContextInit boolean
---@field bReadsSignificanceIndex boolean

---@class NiagaraVMExecutableDataId
---@field BaseScriptCompileHash NiagaraCompileHash
---@field BaseScriptID Guid
---@field CompilerVersionID Guid
---@field ScriptUsageType ENiagaraScriptUsage
---@field ScriptUsageTypeID Guid
---@field ScriptVersionID Guid
---@field bInterpolatedSpawn boolean
---@field bRequiresPersistentIDs boolean
---@field bUsesRapidIterationParams boolean

---@class NiagaraVariable : NiagaraVariableBase
---@field VarData integer[]

---@class NiagaraVariableBase
---@field Name string
---@field TypeDefHandle NiagaraTypeDefinitionHandle

---@class NiagaraVariableLayoutInfo
---@field FloatComponentStart integer
---@field HalfComponentStart integer
---@field Int32ComponentStart integer
---@field LayoutInfo NiagaraTypeLayoutInfo

---@class NiagaraVariableWithOffset : NiagaraVariableBase
---@field Offset integer

---@class VMExternalFunctionBindingInfo
---@field FunctionSpecifiers VMFunctionSpecifier[]
---@field InputParamLocations boolean[]
---@field Name string
---@field NumOutputs integer
---@field OwnerName string

---@class VMFunctionSpecifier
---@field Key string
---@field Value string
