---@meta _
-- Generated by scripts\gameindex.py from the game's object dump. Changes here are lost on the next run.

---@class AccountId

---@class AchievementsDef
---@field AchievementId string
---@field FlavorText string
---@field LockedDescription string
---@field LockedDisplayName string
---@field LockedIconURL string
---@field StatInfo AchivementsStatInfo[]
---@field UnlockedDescription string
---@field UnlockedDisplayName string
---@field UnlockedIconURL string
---@field bIsHidden boolean

---@class AchivementsStatInfo
---@field StatName string
---@field ThresholdValue integer

---@class OnlineSubsystemEOSFunctionLibrary : BlueprintFunctionLibrary
---@field EpicAccountIdFromString fun(self: OnlineSubsystemEOSFunctionLibrary, AccountId: string): AccountId
---@field EpicAccountIdToString fun(self: OnlineSubsystemEOSFunctionLibrary, AccountId: AccountId|{}): string
---@field GetAccountId fun(self: OnlineSubsystemEOSFunctionLibrary): AccountId
---@field GetAchivementsDefinition fun(self: OnlineSubsystemEOSFunctionLibrary, WorldContextObject: Object?): AchievementsDef[]
---@field GetCachedEOSAchievement fun(self: OnlineSubsystemEOSFunctionLibrary, WorldContextObject: Object?, PlayerController: PlayerController?, AchievementId: string, OutAchievement: PlayerAchievementData|{}): boolean
---@field GetCachedEOSAchievements fun(self: OnlineSubsystemEOSFunctionLibrary, WorldContextObject: Object?, PlayerController: PlayerController?, OutAchievements: PlayerAchievementData[]): boolean
---@field GetProductUserId fun(self: OnlineSubsystemEOSFunctionLibrary): ProductUserId
---@field IsAuthorised fun(self: OnlineSubsystemEOSFunctionLibrary): boolean
---@field ProductUserIdFromString fun(self: OnlineSubsystemEOSFunctionLibrary, AccountId: string): ProductUserId
---@field ProductUserIdToString fun(self: OnlineSubsystemEOSFunctionLibrary, ProductUserId: ProductUserId|{}): string

---@class PlayerAchievementData
---@field AchievementId string
---@field Progress number
---@field Stats table<string, StatProgress>
---@field UnlockTime DateTime
---@field bIsUnlocked boolean

---@class ProductUserId

---@class StatProgress
---@field CurValue integer
---@field StatName string
---@field ThresholdValue integer
