---@meta _
-- Generated by scripts\gameindex.py from the game's object dump. Changes here are lost on the next run.

---@alias ESpriteCollisionMode
---| 0 # None
---| 1 # Use2DPhysics
---| 2 # Use3DPhysics
---| integer

---@alias ESpritePolygonMode
---| 0 # SourceBoundingBox
---| 1 # TightBoundingBox
---| 2 # ShrinkWrapped
---| 3 # FullyCustom
---| 4 # Diced
---| integer

---@alias ESpriteShapeType
---| 0 # Box
---| 1 # Circle
---| 2 # Polygon
---| integer

---@class IntMargin
---@field Bottom integer
---@field Left integer
---@field Right integer
---@field Top integer

---@class PaperSprite : Object
---@field AdditionalSourceTextures Texture[]
---@field AlternateMaterial MaterialInterface
---@field AlternateMaterialSplitIndex integer
---@field BakedRenderData Vector4[]
---@field BakedSourceDimension Vector2D
---@field BakedSourceTexture Texture2D
---@field BakedSourceUV Vector2D
---@field BodySetup BodySetup
---@field DefaultMaterial MaterialInterface
---@field PixelsPerUnrealUnit number
---@field Sockets PaperSpriteSocket[]
---@field SpriteCollisionDomain ESpriteCollisionMode

---@class PaperSpriteBlueprintLibrary : BlueprintFunctionLibrary
---@field MakeBrushFromSprite fun(self: PaperSpriteBlueprintLibrary, Sprite: PaperSprite?, Width: integer, Height: integer): SlateBrush

---@class PaperSpriteSocket
---@field LocalTransform Transform
---@field SocketName string

---@class PaperTileInfo
---@field PackedTileIndex integer
---@field TileSet PaperTileSet

---@class PaperTileMetadata
---@field CollisionData SpriteGeometryCollection
---@field TerrainMembership integer
---@field UserDataName string

---@class PaperTileSet : Object
---@field AdditionalSourceTextures Texture[]
---@field AllocatedHeight integer
---@field AllocatedWidth integer
---@field BorderMargin IntMargin
---@field DrawingOffset IntPoint
---@field HeightInTiles integer
---@field Margin integer
---@field PerTileData PaperTileMetadata[]
---@field PerTileSpacing IntPoint
---@field Spacing integer
---@field Terrains PaperTileSetTerrain[]
---@field TileHeight integer
---@field TileSheet Texture2D
---@field TileSize IntPoint
---@field TileWidth integer
---@field WidthInTiles integer

---@class PaperTileSetTerrain
---@field CenterTileIndex integer
---@field TerrainName string

---@class SpriteGeometryCollection
---@field AlphaThreshold number
---@field DetailAmount number
---@field GeometryType ESpritePolygonMode
---@field PixelsPerSubdivisionX integer
---@field PixelsPerSubdivisionY integer
---@field Shapes SpriteGeometryShape[]
---@field SimplifyEpsilon number
---@field bAvoidVertexMerging boolean

---@class SpriteGeometryShape
---@field BoxPosition Vector2D
---@field BoxSize Vector2D
---@field Rotation number
---@field ShapeType ESpriteShapeType
---@field Vertices Vector2D[]
---@field bNegativeWinding boolean

---@class TileMapBlueprintLibrary : BlueprintFunctionLibrary
---@field BreakTile fun(self: TileMapBlueprintLibrary, Tile: PaperTileInfo|{}, TileIndex: integer, TileSet: PaperTileSet?, bFlipH: boolean, bFlipV: boolean, bFlipD: boolean)
---@field GetTileTransform fun(self: TileMapBlueprintLibrary, Tile: PaperTileInfo|{}): Transform
---@field GetTileUserData fun(self: TileMapBlueprintLibrary, Tile: PaperTileInfo|{}): string
---@field MakeTile fun(self: TileMapBlueprintLibrary, TileIndex: integer, TileSet: PaperTileSet?, bFlipH: boolean, bFlipV: boolean, bFlipD: boolean): PaperTileInfo
