"""Imports a folder of Lucide icons (white PNGs) into the Wax GUI: python scripts/import_lucide.py <folder of .png>

Writes wax/runtime/assets/lucide/96 (as given) and /32 (for small sizes), the name list in gui/icons_list.lua, and
sheet32.png: every small icon on one image, 40 to a row in the order of the name list (the GUI draws from it).
`python scripts/import_lucide.py --sheet` rebuilds only the sheet from the files already imported.
"""
import re
import sys
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "wax" / "runtime" / "assets" / "lucide"
LIST = ROOT / "wax" / "runtime" / "Scripts" / "wax" / "gui" / "icons_list.lua"
WHITE = (255, 255, 255, 255)


def white_with_alpha(image, size):
    alpha = image.convert("RGBA").getchannel("A")
    if alpha.size != (size, size):
        alpha = alpha.resize((size, size), Image.LANCZOS)
    out = Image.new("RGBA", (size, size), WHITE)
    out.putalpha(alpha)
    return out


SHEET_COLUMNS = 40   # gui/icons.lua counts on this


def write_sheet(names):
    rows = -(-len(names) // SHEET_COLUMNS)
    side = max(SHEET_COLUMNS, rows) * 32
    sheet = Image.new("RGBA", (side, side), (255, 255, 255, 0))
    for index, name in enumerate(names):
        with Image.open(OUT / "32" / f"{name}.png") as image:
            sheet.paste(image.convert("RGBA"), ((index % SHEET_COLUMNS) * 32, (index // SHEET_COLUMNS) * 32))
    sheet.save(OUT / "sheet32.png", optimize=True)
    print(f"wrote sheet32.png ({side}x{side}) with {len(names)} icons")


def main():
    if len(sys.argv) == 2 and sys.argv[1] == "--sheet":
        listed = re.search(r"\[\[(.*?)\]\]", LIST.read_text(encoding="utf-8"), re.S).group(1)
        write_sheet(listed.split())
        return
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    source = Path(sys.argv[1])
    files = sorted(source.glob("*.png"))
    if not files:
        sys.exit(f"no .png files in {source}")
    for size in (96, 32):
        (OUT / str(size)).mkdir(parents=True, exist_ok=True)
    names = []
    for file in files:
        with Image.open(file) as image:
            white_with_alpha(image, 96).save(OUT / "96" / file.name, optimize=True)
            white_with_alpha(image, 32).save(OUT / "32" / file.name, optimize=True)
        names.append(file.stem)
    lines, line = [], ""
    for name in names:
        if len(line) + len(name) + 1 > 110:
            lines.append(line)
            line = ""
        line = f"{line} {name}" if line else name
    lines.append(line)
    LIST.write_text("-- Generated by scripts/import_lucide.py: the names of the bundled Lucide icons\nreturn [[\n"
                    + "\n".join(lines) + "\n]]\n", encoding="utf-8", newline="\n")
    print(f"imported {len(names)} icons into {OUT} and wrote {LIST.name}")
    write_sheet(names)


if __name__ == "__main__":
    main()
